### ISSUE TITLE
Canonical urls rejected

### ISSUE THREAD

**Issue by pascaldimassimo** [Norconex/collector-http#103]
Trying to crawl from "http://www.norconex.com/" does not work, because the start url is rejected with REJECTED_CANONICAL.

This is on the develop branch.

**Comment by essiembre** [comment]
Should work since the URL you access and the canonical URL defined in he page are the same and there is a check for that.  Seems to not be working in this case.  Will investigate.

**Comment by essiembre** [comment]
In the meantime anyone having similar problems can disable the canonical URL resolution feature by adding this to their crawler config:
```xml
<canonicalLinkDetector ignore="true" />
```

**Comment by essiembre** [comment]
A new [snapshot release](http://www.norconex.com/collectors/collector-http/download) was made with the fix.

**Comment by essiembre** [comment]
Norconex HTTP Collector 2.2.0 official release is out. It includes this fix. You can download it [here](http://www.norconex.com/collectors/collector-http/download).
