### ISSUE TITLE
Power outage and JOB files empty

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#107]
While the crawler was running, due to a power outage, the server has reinit. Then, I've run the crawler with ```resume``` but it has run as in ```start```mode with a lot of UNMODIFIED events.
I've realized that ```\progress\latest``` and ```progress\latest\status``` JOB files exist but are empty, so I suppose this is the reason.
If I'm right, these JOB files (or one of them) are critical for resuming the run properly, so they should be protected against the effect of a power outage.
Can I do anything to resume the run?. Can I fill the JOB files with an information the crawler admit to resume the run?.

**Comment by essiembre** [comment]
Which release were you using?

You are correct they should not be empty and there should be a way to prevent that.  The challenge is to reproduce this so it can be fixed, without having to create a power outage each time.  I'll 

In the meantime, I am not sure recovering the way you suggest has been attempted before.  I suggest you run a separate instance (in a different directory), and then compare the .job files.  That way maybe you'll know what type of info is expected by each.  Modify the original job files and try resuming again.

**Comment by csaezl** [comment]
In other issue I told you that I was confident with stop/resume but not sure with another way of interrupting the crawler. This is one case.

I was using 2.0.2 with its last snapshot. I'm still testing 2.1.0 with 2.2.0-SNAPSHOT

If the content of JOB files is only informative for the process, I could be possible to put a similar content taken from another JOB file (from a backup) for the same collector/crawler. If the process checks in some way the contents against the crawldb, there is a problem.

**Comment by csaezl** [comment]
Wouldn't killing the process have the same effect as a prower outage?

**Comment by essiembre** [comment]
If a hard kill of the process does not give the JVM time to finalize, I am assuming that yes, it should be comparable to a power outage.  I have not been able to reproduce.  Can you confirm if you still have the issue with the latest stable release. [2.2.0](http://www.norconex.com/collectors/collector-http/download) was just released.

**Comment by csaezl** [comment]
It doesn't happen anymore
