### ISSUE TITLE
Lenient is not set when using StandardSitemapResolverFactory

### ISSUE THREAD

**Issue by leonardsaers** [Norconex/collector-http#120]
I'm currently using version 2.1 but I think that this also applies to 2.2-SNAPSHOT.

The property lenient is never set in StandardSitemapResolver when using the configuration suggested by the class documentation.

```XML
        <sitemap ignore="false" lenient="true" class="com.norconex.collector.http.sitemap.impl.StandardSitemapResolverFactory">
            <location>http://example.com/generated/sitemap.xml</location>
        </sitemap>
```

Also, the property ignore which is suggested in the class documentation is never used.

**Comment by essiembre** [comment]
This one should work just fine.  When you disable the sitemap support, you should be getting this line somewhere at the beginning of your log:

```
INFO  [HttpCrawler] Your Crawler Name: Sitemap support: false
```

If you do not see that, it looks like your sitemap configuration was not picked up.

Where did you store this in your config? It needs to go under your ``<crawler ...>`` tag.  

The logic involved has not changed from 2.1 to 2.2-SNAPSHOT.

**Comment by essiembre** [comment]
@leonardsaers, can you confirm if you resolved this one?

**Comment by leonardsaers** [comment]
Sorry for late response. What I noticed was that the property lenient was read from configuration but never applied in the ISitemapResolver.

The property is read in the StandardSitemapResolverFactory.
https://github.com/Norconex/collector-http/blob/master/norconex-collector-http/src/main/java/com/norconex/collector/http/sitemap/impl/StandardSitemapResolverFactory.java
````java
    public void setLenient(boolean lenient) {
        this.lenient = lenient;
    }
````

But the parameter is never passed to the created ISitemapResolver. Or am I missing something here?

**Comment by essiembre** [comment]
Looks like you are quite right! I just made a fix you can try using the [latest snapshot](http://www.norconex.com/collectors/collector-http/download).

**Comment by essiembre** [comment]
Norconex HTTP Collector 2.2.0 official release is out. It includes this fix. You can download it [here](http://www.norconex.com/collectors/collector-http/download).
