### ISSUE TITLE
Typo in URLStatusCrawlerEventListener example

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#121]
http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/crawler/event/impl/URLStatusCrawlerEventListener.html

class="**ccom**.norconex.collector.http.crawler.event.impl.URLStatusCrawlerEventListener"

**Comment by essiembre** [comment]
Typo fixed. Thanks for reporting.
