### ISSUE TITLE
startURLs is still needed when using site map

### ISSUE THREAD

**Issue by leonardsaers** [Norconex/collector-http#128]
In most cases there will not be a need for a startURL when using site maps.

When having the following site map configuration
````xml
        <sitemap ignore="false" lenient="true" class="com.norconex.collector.http.sitemap.impl.StandardSitemapResolverFactory">
            <location>http://someurl:30025/sitemap.xml</location>
        </sitemap>
````

There is still a need to specify startURL
````xml
    <crawlers>
        <crawler id="uu-web-special">
            <startURLs>
                <url>http://someurl:30025/sitemap.xml</url>
            </startURLs>

            <referenceFilters>
                <filter class="$urlRegex" onMatch="include">^https?://someurl:30025/.*</filter>
            </referenceFilters>
        </crawler>
    </crawlers>
````

It is possible to just add the site map as a seed url but I would say that thats not necessary here.

**Comment by essiembre** [comment]
Adding ``http://someurl:30025`` as the start URL already takes care of your sitemap.xml so you do not need to specify a sitemap as a start URL.

By default, the crawler extracts the domain from your start URL(s) and append ``/sitemap.xml`` and if that does not work, it appends ``/sitemap_index.xml`` (without you having to do anything). The ``<location``> tag for sitemap is optional.  It is only there in case you have a sitemap defined in a non-standard location. 

So in your code sample, the sitemap ``<location>`` is redundant and can be removed.  In fact the whole ``<sitemap>`` tag can be removed unless you want to keep the ``lenient="true"`` flag.

This means you generally don't have to specify two URLs (unless sitemap location is not standard).  

One thing to keep in mind, if a sitemap is found, it will not prevent the crawler from crawling other URLs it finds on a site whether they are defined in the sitemap or not.  You can see it as if sitemap URLs get added to your list of start URLs.  

Tip: if you like to keep your config compact, know that you do not have to specify default attributes. So, given the above explanation, you should be able to rewrite the sitemap piece like this:

```xml
<sitemap lenient="true" />
```

**Comment by leonardsaers** [comment]
I'm trying to only crawl the sites specified in the sitemap and no other pages. To achieve this I have put maxDepth to 0.
````xml
<maxDepth>0</maxDepth>
````
This works grate since all URLs in the site map are treated as seed URLs. I can then simply crawl the site using one simple rule:
````xml
<referenceFilters>
    <filter class="$urlRegex" onMatch="include">^https?://someurl:30025/.*</filter>
</referenceFilters>
````
This setup makes my work much easier :) and the person responsible for the sitemap are happy since it's easy to control the crawler without changing any crawler settings.

The only small problem with the setup is that I have to specify at least one startURLs. This could be handled by giving the following start URL:
````xml
<startURLs>
    <url>http://someurl:30025/</url>
</startURLs>
````
This setup will crawl the sitemap and http://someurl:30025/. I would rather only crawl the sitemap and then only crawl http://someurl:30025/ if it's included in the site map.

To solve this I have added the following start URL as start URL:
````xml
<startURLs>
    <url>http://someurl:30025/sitemap.xml</url>
</startURLs>
````
This works fine, but it's not as clean as it could be. 

My first thought was that the startURLs should not be mandatory if a site map is specified such as:
````xml
<sitemap ignore="false" lenient="true" class="com.norconex.collector.http.sitemap.impl.StandardSitemapResolverFactory">
    <location>http://someurl:30025/sitemap.xml</location>
</sitemap>
````

An alternative approach could be specifying the site map location in the startULRs. That might make the configuration more easy to understand. It could look as the following example:
````xml
<startURLs>
    <url>http://some-domain/sitemap.xml</url>
    <url>http://another-domain/sitemap.xml</url>
    <sitemap>http://domain-with-sitemap/sitemap.xml</sitemap>
</startURLs>
````
How does this sound? It all works now. This is just a suggestion how to improve the configuration a bit.

**Comment by essiembre** [comment]
I am glad you got the behavior you wanted.

If you know the home page is not in the sitemap, you can exclude it using one of the Importer filters.  But I understand you may not always know whether it should be kept at first and you may want to leave that logic in the sitemaps.  

Having the sitemap as a start URL and then rejecting the sitemap URL itself is a good way to only have to define it once (but forces an extra filter).   

I like the idea of being able to rely on sitemap only and nothing else (at least in a simpler/cleaner way).  I am marking this as a feature request.

**Comment by essiembre** [comment]
A new [snapshot release](https://www.norconex.com/collectors/collector-http/download) is now available to address this feature.  It is now possible to specify any number of ``<sitemap>`` under the ``<startURLs>`` tag. Here are all the options now:
```xml
    <startURLs ...>
      <url>http://www.example.com</url>
      <urlsFile>/local/path/to/a/file/full/of/urls.txt</urlsFile>
      <sitemap>http://www.somewhere.com/sitemap.xml</sitemap>
    </startURLs>
```
As a consequence, it is no longer possible to specify ``<location>`` tags as part of sitemap resolution (the "other" ``<sitemap>`` tag).

Let me know how that works for you.

**Comment by leonardsaers** [comment]
I can verify that <sitemap> works.

I have not tried it but it's also nice to be able to use <urlsFile>.

Thanks :)

**Comment by essiembre** [comment]
By "I can verify that works", do you mean you DID verify or you WILL verify? In other words, can we close this issue?

**Comment by leonardsaers** [comment]
Sorry for my unclear answer. I have verified that <sitemap> works. I like that you also added <urlsFile>, but I have not tried that feature yet. I would say that this feature request is resolved now.

**Comment by essiembre** [comment]
Thanks for getting back.
