### ISSUE TITLE
Empty Disallow triggers REJECTED_ROBOTS_TXT

### ISSUE THREAD

**Issue by echosia** [Norconex/collector-http#129]
A robots.txt like the following

> User-agent: *
> Disallow:

seems to trigger a REJECTED_ROBOTS_TXT

> INFO  [CrawlerEventManager]       REJECTED_ROBOTS_TXT: http://www.testwebsite.com (Subject: RobotsTxt[filters={Robots.txt (Disallow:)},crawlDelay=-1.0,sitemapLocations={}])

This is using the class provided at `com.norconex.collector.http.robot.impl.StandardRobotsTxtProvider`

**Comment by essiembre** [comment]
Good catch. Thanks for reporting. Will fix.

**Comment by echosia** [comment]
I have not yet tested this, but thank you for the quick reply and fix!

**Comment by essiembre** [comment]
I just created a new [snapshot release](http://www.norconex.com/collectors/collector-http/download) with this fix.  Please let me know if it fixes it for you.

**Comment by echosia** [comment]
Looking good now! Thanks!
