### ISSUE TITLE
"SolrCommiter" version cannot be stablished

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#136]
At the beginning of the run I get the message: "SolrCommiter" version cannot be stablished. It's difficult to see because it only appears on the screen. Since it is an INFO message, I expect it not to influence the run .

**Comment by essiembre** [comment]
This message is completely harmless and can be ignores.  The version is printed when made available, for convenience (e.g. troubleshooting), but is not actually used anywhere.

**Comment by csaezl** [comment]
Thank you
