### ISSUE TITLE
External Redirect?

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#140]
Crawling ``` <url>http://fomento.gobex.es/</url>``` with:
```
<httpClientFactory>
    <ignoreExternalRedirects>true</ignoreExternalRedirects>
</httpClientFactory>	  
...
<linkExtractors>
    <extractor ignoreExternalLinks="true" />
</linkExtractors>
```
I get:
````
Ignoring external redirect: http://fomento.gobex.es/ -> http://fomento.gobex.es/fomento/live/index.html
      REJECTED_BAD_STATUS: http://fomento.gobex.es/
```
So I get no document processed. Is this redirect really external?

**Comment by essiembre** [comment]
I also noticed this oddness yesterday as well with another site I am crawling.   I am investigating.

**Comment by essiembre** [comment]
A new [snapshot release](http://www.norconex.com/collectors/collector-http/download) was just made with the fix to this.  Sometimes the default port came across as -1 instead of 80, causing it to believe the original and redirect ports were different.

**Comment by csaezl** [comment]
Now it seems to work fine. Thank you

**Comment by essiembre** [comment]
Great, thanks for testing.
