### ISSUE TITLE
The crawler doesn't extract URLs from www.feccoo-extremadura.org 

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#141]
Crawling ```www.feccoo-extremadura.org```, I get just one document, the one for the domain, but navigating with a browser, it automatically converts to ```www.feccoo-extremadura.org/ensenanzaextremadura``` and then more URLs are extracted. 
What can I do?

**Comment by essiembre** [comment]
This is a case where the home page contains a meta redirect.  This is the content:

```xml
<HTML>
  <HEAD>
    <META HTTP-EQUIV=REFRESH CONTENT="0; URL=/ensenanzaextremadura/">
    </META>
  </HEAD>
</HTML>
```

Such redirects ARE supported by the HTTP Collector and should be followed. The issue in this case is with the ``REFRESH``.  The ``GenericLinkExtractor`` expects to be in quote and it is not.  This is a simple fix.

Until the fix is done and released, I recommend you start crawling from ``www.feccoo-extremadura.org/ensenanzaextremadura``.

**Comment by essiembre** [comment]
I just pushed a new [snapshot release](http://www.norconex.com/collectors/collector-http/download) with a fix.  Please test and confirm.

**Comment by csaezl** [comment]
It doesn't work for me.
```
MC (crawler): 2015-09-18 11:36:24 INFO -           CRAWLER_STARTED
MC (crawler): 2015-09-18 11:36:24 INFO - MC (crawler): Crawling references...
MC (crawler): 2015-09-18 11:36:25 INFO -          DOCUMENT_FETCHED: http://www.feccoo-extremadura.org/
MC (crawler): 2015-09-18 11:36:25 INFO -       CREATED_ROBOTS_META: http://www.feccoo-extremadura.org/
MC (crawler): 2015-09-18 11:36:25 INFO -            URLS_EXTRACTED: http://www.feccoo-extremadura.org/
MC (crawler): 2015-09-18 11:36:25 INFO -         DOCUMENT_IMPORTED: http://www.feccoo-extremadura.org/
MC (crawler): 2015-09-18 11:36:25 INFO -    DOCUMENT_COMMITTED_ADD: http://www.feccoo-extremadura.org/
MC (crawler): 2015-09-18 11:36:25 INFO - MC (crawler): 1 reference(s) processed.
MC (crawler): 2015-09-18 11:36:25 INFO -          CRAWLER_FINISHED
```
From ```lib``` folder:
```
	norconex-collector-http-2.3.0-SNAPSHOT.jar            	‎17/‎09/‎2015 ‏‎23:51	Archivo JAR	235 KB
	fontbox-2.0.0-20150917.205852-1735.jar               	‎17/‎09/‎2015 ‏‎23:50	Archivo JAR	1.440 KB
	pdfbox-2.0.0-20150917.210012-1682.jar                	‎17/‎09/‎2015 ‏‎23:50	Archivo JAR	2.327 KB
	norconex-collector-core-1.3.0-20150914.153806-6.jar   	‎17/‎09/‎2015 ‏‎23:50	Archivo JAR	144 KB
	norconex-importer-2.4.0-20150914.151843-5.jar          	‎17/‎09/‎2015 ‏‎23:50	Archivo JAR	355 KB
	norconex-commons-lang-1.8.0-SNAPSHOT.jar              	‎17/‎09/‎2015 ‏‎23:48	Archivo JAR	163 KB

```

**Comment by essiembre** [comment]
OK, I just made a [new one](http://www.norconex.com/collectors/collector-http/download) and this time that's the good one. :-)

**Comment by csaezl** [comment]
Although the job is still running, it seems to work. Thank you.
