### ISSUE TITLE
Invalid redirect?

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#143]
I have found out some redirects with spaces in the source URL. The source URL exists but the target doesn't.

```
MC (crawler): 2015-09-19 17:26:07 INFO - URL Redirect: http://www.federacionpiraguismodeextremadura.com/Circulares/CALENDARIO REGATAS 2014-2015.pdf -> http://www.federacionpiraguismodeextremadura.com/Circulares/CALENDARIO+REGATAS+2014-2015.pdf
MC (crawler): 2015-09-19 17:26:07 INFO -         REJECTED_NOTFOUND: http://www.federacionpiraguismodeextremadura.com/Circulares/CALENDARIO+REGATAS+2014-2015.pdf
```

**Comment by essiembre** [comment]
The strict rule for encoding spaces in the "path" portion of a URL is to use %20.  Only query strings should use + (but %20 will also work).   Many web servers are relaxed about it, but it looks like the one you are crawling is not.  I fixed it so the path portion is now properly escaped, which fixes your issue.  Check [latest snapshot](http://www.norconex.com/collectors/collector-http/download).

**Comment by csaezl** [comment]
It works fine. Thank you.
