### ISSUE TITLE
http / https redirection

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#144]
Crawling ```http://adelantextremadura.wordpress.com/``` with ```<extractor ignoreExternalLinks="true" />``` when the redirection is based on http/https, the original URL is rejected. Could it be possible to manage them as the same protocol?. If not, it would be mandatory to know what to use, http/https, in advance.
```
MC (crawler): 2015-09-19 18:54:48 INFO -           CRAWLER_STARTED
MC (crawler): 2015-09-19 18:54:48 INFO - MC (crawler): Crawling references...
MC (crawler): 2015-09-19 18:54:49 INFO - Ignoring external redirect: http://adelantextremadura.wordpress.com/ -> https://adelantextremadura.wordpress.com/
MC (crawler): 2015-09-19 18:54:49 INFO -       REJECTED_BAD_STATUS: http://adelantextremadura.wordpress.com/
MC (crawler): 2015-09-19 18:54:50 INFO - MC (crawler): Crawler finishing: committing documents.
MC (crawler): 2015-09-19 18:54:50 INFO - MC (crawler): 1 reference(s) processed.
MC (crawler): 2015-09-19 18:54:50 INFO -          CRAWLER_FINISHED

```

**Comment by csaezl** [comment]
I tested ```http://adelantextremadura.wordpress.com/``` with:
```
      <startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
		         <url>http://adelantextremadura.wordpress.com/</url>
```

and got similar result:
```
           CRAWLER_STARTED
 MC (crawler): Crawling references...
       REJECTED_REDIRECTED: http://adelantextremadura.wordpress.com/
           REJECTED_FILTER: https://adelantextremadura.wordpress.com/
 MC (crawler): Crawler finishing: committing documents.
 MC (crawler): 1 reference(s) processed.
          CRAWLER_FINISHED
```

**Comment by essiembre** [comment]
This is expected because you are telling it you want to crawl pages of the same protocol.  In your case I think what you want is this:

```xml
      <startURLs stayOnDomain="true" stayOnPort="false" stayOnProtocol="false">
```

Because a change of protocol from (http vs https) also changes the port (80 vs 443), it is best to also make the "stayOnPort" false like above.

**Comment by csaezl** [comment]
Of course, you are right. Thank you, it works.

**Comment by essiembre** [comment]
No problem!

**Comment by Pittiplatsch** [comment]
Nowadays, with `stayOnDomain`, `stayOnPort`, and `stayOnProtocol` options in place, what is the intended way of handling HTTP <-> HTTPS directions without parsing URLs of **every** port?
Basically, only `http://my.domain/path` and `https://my.domain/path` urls are to be allowed, whereas `http://my.domain:8080/path` and others are to be rejected.

**Comment by essiembre** [comment]
If I understanding your question properly, you would use
```
stayOnDomain="true"
stayOnPort="true"
stayOnProtocol="false"
```

Given this ticket is closed, please create a new one if you have further questions.
