### ISSUE TITLE
Regarding the collector-http.sh command usage

### ISSUE THREAD

**Issue by mitchelljj** [Norconex/collector-http#149]
Regarding the collector-http.sh command usage listed below.  If I start a crawl (via -a start) and it does not complete because of something like losing the connection to the Linux server that it is running on can I pickup up where I left off by running the same command except using resume (via -a resume)?
Also how would I use the stop command when a process is currently running via start or resume collector-http.sh command?

usage: collector-http[.bat|.sh]
 -a,--action <arg>      Required: one of start|resume|stop
 -c,--config <arg>      Required: HTTP Collector configuration file.
 -v,--variables <arg>   Optional: variable file.

**Comment by essiembre** [comment]
If the process died before its time, running the same command with ``-a resume`` will continue where it stopped.
To manually stop it, run the exact same command again, but with ``-a stop``.  That is, pass in the same config and same variable file (if any).  In other words, to start, stop and resume:

```
collector-http.sh -a start  -c /path/to/myconfig.xml -v /optional/var/file.variables
collector-http.sh -a stop   -c /path/to/myconfig.xml -v /optional/var/file.variables
collector-http.sh -a resume -c /path/to/myconfig.xml -v /optional/var/file.variables
```

**Comment by essiembre** [comment]
Do you feel your question on ``collector-http.sh`` command usage has been answered?
