### ISSUE TITLE
How do you set the URLCrawlScopeStrategy for a crawler

### ISSUE THREAD

**Issue by yvesnyc** [Norconex/collector-http#157]
Hi. 

I know how to query the URLCrawlScopeStrategy but not how to set it.

Where and how do you do this using the API ?

Thanks.

**Comment by essiembre** [comment]
The flags it supports can be set on the ``<startURLs>`` tag, like this:

```xml
<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
    ...
</startURLs>
```

If you want to know how to do it programmatically, you obtain it on the ``HttpCrawlerConfig``, like this:
```java
HttpCrawlerConfig crawlerConfig = // your config instance here
URLCrawlScopeStrategy crawlScope = crawlerConfig.getURLCrawlScopeStrategy();
crawlScope.setStayOnDomain(true);
crawlScope.setStayOnProtocol(true);
crawlScope.setStayOnPort(true);
```
Clear enough?

**Comment by essiembre** [comment]
I must state this feature currently exists in HTTP Collector 2.3.0-SNAPSHOT only.

**Comment by yvesnyc** [comment]
Obvious now. :)

Thanks.
