### ISSUE TITLE
I want to process any deltas (adds, changes and deletes) after a certain amount of time

### ISSUE THREAD

**Issue by mitchelljj** [Norconex/collector-http#159]
Once I have completely crawled all the areas that need crawling via "norconex-collector-http-2.2.1/collector-http.sh -a start -c examples/minimum/minimum-config.xml" and I want to process any deltas (adds, changes and deletes) after a certain amount of time like once a day or once a week do I run the same "norconex-collector-http-2.2.1/collector-http.sh -a start -c examples/minimum/minimum-config.xml" command in order to update the Solr index with the deltas?

**Comment by essiembre** [comment]
Yes, that's exactly what you do.  After the first crawl, incremental crawls are performed and only changes/addition/deletions are sent to your committer.  To perform a full crawl again, delete the working directory (more precisely the crawlstore directory).

**Comment by mitchelljj** [comment]
What would be the reason to ever perform a full crawl again if the deltas are also captured with incremental crawls?

**Comment by essiembre** [comment]
There are different reasons mainly revolving around "change". For instance, wanting to have a configuration changes retroactively apply to all documents (like indexing a new field with each documents).  Also, while in development stage of a project, it happens frequently you may want to recrawl for all kinds of reason (search engine schema changed, testing features out until you get it right, etc).   A website redesign may also force your to do a full re-crawl as well in case your current configuration no longer apply.  A significant version upgrade of the HTTP Collector may also force you to do that to take advantage of new features, etc.  

I am sure they are several other reasons, but most are not inherent to the HTTP Collector but to crawling in general.  On a stable production environment, crawling stable websites, it's true there should be little need to redo full crawls unless maybe your requirements change for some reason.

Does that answer?

**Comment by mitchelljj** [comment]
Yes it does thanks!
