### ISSUE TITLE
Canonical url is not fetched from non canonical URL

### ISSUE THREAD

**Issue by leonardsaers** [Norconex/collector-http#162]
I have an issue when the crawled URL is not the same as the canonical URL. The canonical URL is not fetched when using the provided minimum-config.xml where the url is changed to http://www.skolverket.se/kompetens-och-fortbildning/lararlegitimation/legitimation-1.237043

From HttpImporterPipelineUtil, it look like the canonical URL should be fetched. But it never happens.

``` java
public static boolean resolveCanonical(
...
            HttpCrawlData newData = (HttpCrawlData) ctx.getCrawlData().clone();
            newData.setReference(canURL);
            HttpQueuePipelineContext newContext = new HttpQueuePipelineContext(
                    ctx.getCrawler(), ctx.getCrawlDataStore(), newData);
            new HttpQueuePipeline().execute(newContext);
            ctx.getCrawlData().setState(HttpCrawlState.REJECTED);
            ctx.getCrawler().fireCrawlerEvent(
                    HttpCrawlerEvent.REJECTED_CANONICAL, 
                    ctx.getCrawlData(), detector);
...
```

**Comment by essiembre** [comment]
Is it on the same domain/port/protocol?  Because the latest minimum-config.xml has the stayOn... attributes set to "true".  If it is, a copy of your config to reproduce would be helpful.

**Comment by leonardsaers** [comment]
Here is the configuration: https://github.com/leonardsaers/TextFiles/blob/master/norconex-http-collector/minimum-config.xml

**Comment by essiembre** [comment]
I found out the issue is with the site creating a circular reference between the canonical URL and a redirect.  To explain:

Your start URL...
```
http://www.skolverket.se/kompetens-och-fortbildning/lararlegitimation/legitimation-1.237043
``` 
...specifies this canonical URL:
```
http://www.skolverket.se/kompetens-och-fortbildning/lararlegitimation
```
That canonical URL has a redirect to your original start URL:
```
http://www.skolverket.se/kompetens-och-fortbildning/lararlegitimation/legitimation-1.237043
```
At that time it has already been processed and eliminated since it was non-canonical (rejecting it also avoids an infinite loop in the process).

I am afraid the site did not design this one properly and I would recommend you tell them so they can fix that.  In the meantime, your best option may be to ignore canonical URLs for that one with this:
```xml
<canonicalLinkDetector ignore="true" />
```

**Comment by leonardsaers** [comment]
Thanks for the answerer. I also took a look at https://tools.ietf.org/html/rfc6596 which strongly suggest that canonical pages should not redirect.

However, should http-collector handle this faulty set-up of canonical URLs?

**Comment by essiembre** [comment]
It kind of does by 1) avoiding the infinite loop, and 2) being able to disable canonical link support.

What would you like the behavior to be in this case?  Keep the canonical, ignoring the redirect? Or keep the redirect, ignoring the canonical?  Either way, if we support one at the detriment of the other, some people are bound to raise this as an issue (e.g. "[redirects|canonical] are not always working").  You can think of anyway to avoid that?

**Comment by leonardsaers** [comment]
I have now seen this behaviour on two totally different sites. This faulty implementation of canonical links may not be that uncommon.

Maybe the default behaviour could be as it is now, following how it is supposed to work. In addition a redirect strategy could be given where one strategy would be:


If (URL **a** has Canonical url **ca** AND (url **ca** does not have a canonical url AND url **ca** is not a redirect))
FETCH **ca**

If (URL **a** has Canonical url **ca** AND url **ca** redirects to **a**)
FETCH **a**

else
DROP **a**
DROP **ca**

**Comment by essiembre** [comment]
Now that we are storing the redirect "trail" with each document, we can use that to figure out if we are in a non-canonical/redirect circular reference and process the non-canonical page.

I tested with success the example provided earlier in this ticket with the latest snapshot.

Please confirm if you have a chance.

**Comment by essiembre** [comment]
Handling of non-canonical/redirect circular reference is now part of the official 2.8.0 release.

**Comment by leonardsaers** [comment]
Thanks :)
