### ISSUE TITLE
Crawl fails when canonical link is escaped

### ISSUE THREAD

**Issue by leonardsaers** [Norconex/collector-http#164]
The following escaped canonical URL results in an exception while parsing.

```html
<link rel="canonical" href="https&#x3a;&#x2f;&#x2f;test&#x2e;kaffe&#x2e;se&#x2f;web" />
```

**Comment by essiembre** [comment]
Your pull request was included in the latest snapshot release.  Please test.  Thanks a lot for your contribution!

**Comment by essiembre** [comment]
Where you able to validate this was added and is working properly?

**Comment by leonardsaers** [comment]
Yes, I'm using the fix now, and it works.

**Comment by essiembre** [comment]
Thanks for confirming.
