### ISSUE TITLE
Relative redirection?

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#169]
It seems that there is a relative redirection to ```web``` although it is taken as absolute, so no document is crawled.
```
 INFO -           CRAWLER_STARTED
 INFO - MC_(crawler): Crawling references...
 INFO -       REJECTED_REDIRECTED: http://juventudextremadura.gobex.es/
 INFO -           REJECTED_FILTER: web
 INFO - MC_(crawler): Crawler finishing: committing documents.
 INFO - MC_(crawler): 1 reference(s) processed.
 INFO -          CRAWLER_FINISHED
```

**Comment by essiembre** [comment]
Redirects should not be sending relative URLs, but try the new [snapshot version](https://www.norconex.com/collectors/collector-http/download) that was just released.  Relative redirects are now supported.

**Comment by csaezl** [comment]
It works fine. Thank you for your support.
