### ISSUE TITLE
maxDocuments proposition

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#172]
The parameter mentioned above means `Maximum documents to successfully process. Default is -1 (unlimited).`

Using the parameter with importer filter I find, that the parameter means `continue until review X urls`, but not `continue, until X documents are imported`.

It is possible other users find `maxDocuments` parameter variations for _imported_, and _committed_ documents useful.

**Comment by essiembre** [comment]
Good idea.  I am marking this as a feature request.

**Comment by sylvainroussy** [comment]
Hi,
To do that for Committed documents, I wrote a ```ICrawlerEventListener```, something like that:
```
@Override
public void crawlerEvent(ICrawler crawler, CrawlerEvent event) {
		if(limitReach) return;	
		if(CrawlerEvent.DOCUMENT_COMMITTED_ADD.equals(event.getEventType())){
			count++;
                        if (count >= limit){
                            // sends Stop command to collector
                        }
                 }

```
Hope this is helpful.

**Comment by essiembre** [comment]
This has been implemented in the last version 3 snapshot using the same approach suggested by @sylvainroussy.

The `maxDocuments` option remains the same, but you can optionally use instead the new [StopCrawlerOnMaxEventListener](https://opensource.norconex.com/collectors/core/v2/apidocs/com/norconex/collector/core/crawler/event/impl/StopCrawlerOnMaxEventListener.html) class. It goes under the `<eventListeners>` section of your `<crawler ...>` configuration.  It gives you control over what events and how many should be encountered before stopping.  As an example, if you want to stop the crawler after 100 documents were either added or deleted (regardless of how many were rejected), you could do it like this:

```xml
<listener class="StopCrawlerOnMaxEventListener" max="100" onMultiple="sum">
    <eventMatcher method="csv">DOCUMENT_COMMITTED_UPSERT,DOCUMENT_COMMITTED_DELETE</eventMatcher>
</listener>
```
