### ISSUE TITLE
Where can I add additional HTTP request headers

### ISSUE THREAD

**Issue by essiembre** [Norconex/collector-http#175]
From @comschmid in #168:
> Where can I add additional HTTP request headers, such as 'Accept-Language'?

**Comment by essiembre** [comment]
I am marking this as a new feature request to have a new configuration option to add custom HTTP header values to every requests.

**Comment by essiembre** [comment]
This has been implemented in the latest [snapshot release](https://www.norconex.com/collectors/collector-http/download).  You can now specify your own request headers like this:
```xml
<httpClientFactory>
    ...
    <headers>
        <header name="Header1">Value 1</header>
        <header name="Header2">Value 2</header>
    </headers>
</httpClientFactory>
```

Please give it a try and let me know.

**Comment by comschmid** [comment]
Thanks, works as intended!
