### ISSUE TITLE
Child elements of <httpClientFactory> are not nested properly when config is saved

### ISSUE THREAD

**Issue by essiembre** [Norconex/collector-http#176]
From @comschmid in #168:
> When I was looking at the generated XML above, I realized that some of the child-elements of ``<httpClientFactory>`` appear after this element, like ``<connectionTimeout>``

**Comment by essiembre** [comment]
This has been fixed in the latest [snapshot release](https://www.norconex.com/collectors/collector-http/download).  Please test it.

**Comment by comschmid** [comment]
Thanks, works as intended!
