### ISSUE TITLE
CDATA and regex

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#179]
I'd like to know is it possible to use CDATA or something similar in regex filters to shield  ```&``` and other XML language parts may met in urls?

```
<filter class="com.norconex.importer.handler.filter.impl.RegexMetadataFilter" field="document.reference" ... >someurl?param1=1&param2=2&param3=.*$</filter>
```

Replacing such symbols by HTML entities (for example ```&``` to ```&amp;```) makes XML syntax correct, but breaks regex semantics.

**Comment by essiembre** [comment]
Definitely!  CDATA is part of the SGML/XML specs and not something specific to the HTTP Collector.  You can use it in the body of just any tag in any XML.  More info: https://en.wikipedia.org/wiki/CDATA

**Comment by AntonioAmore** [comment]
Thank you, it works perfectly.

**Comment by essiembre** [comment]
No problem!
