### ISSUE TITLE
Relative links possible bugs

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#180]
Links from a page, formatted as following:
```
<ul>
...
   <li><a href="/download?param1=1&param2=2"></li>
...
```
aren't queued for download. Absolute links from the same page are processed correctly.

I believe if I'm wrong, they should appear in the log with REJECTED_FILTER comment, but they don't.

**Comment by AntonioAmore** [comment]
Seems a kind of misconfiguration. Works perfectly on SNAPSHOT 2.3.0.

**Comment by essiembre** [comment]
FYI, 2.3.0 is officially out now.
