### ISSUE TITLE
nofollow behaviour

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#185]
I have pages with following links:
```
<a rel="nofollow" title="title" href="/article?id=100500">Link</a>
```
Checking the logs I find that they're ignored by the collector. Is there a way to force it process such links?

**Comment by essiembre** [comment]
Yes there is.  You have to tell the link extractor not to ignore the "nofollow" links.  Try this:
```xml
<linkExtractors>
    <extractor ignoreNofollow="true" />
</linkExtractors>
```

**Comment by AntonioAmore** [comment]
It works perfectly, thank you!
