### ISSUE TITLE
How can I config client for elasticsearch commiter

### ISSUE THREAD

**Issue by bruce-genhot** [Norconex/collector-http#190]
Hi, I'd like to commit my data to a remote running elasticsearch, but I did not find configuration about client in the example. could you please let me know how can I do that, thanks.

**Comment by essiembre** [comment]
Sure, the Elasticsearch committer has its own site: https://www.norconex.com/collectors/committer-elasticsearch/

For configuration options, look here: https://www.norconex.com/collectors/committer-elasticsearch/configuration

If you want to report issues, have questions or else, you can use: https://github.com/Norconex/committer-elasticsearch/issues

Let me know if that answers your question.

**Comment by bruce-genhot** [comment]
Thank you, but seems that I could not config client's host in the committer. here is my committer configuration.
 <committer class="com.norconex.committer.elasticsearch.ElasticsearchCommitter">
                <indexName>opportunity</indexName>
                <typeName>test</typeName>
                <clusterName>xx.xx.xx.xx:9300/elasticsearch</clusterName>
 </committer>

Actually, I'd like to specify client's host in clusterName, but seems that above configuration does not work for me.

**Comment by bruce-genhot** [comment]
It works for me now, thank you.

The elasticsearch committer library only works with elasticsearch 1.5,  the latest version is 2.1.0. Hope the committer library can be upgrate as well.

**Comment by essiembre** [comment]
Glad it works.  I created a new ticket for upgrading the library: https://github.com/Norconex/committer-elasticsearch/issues/2.
