### ISSUE TITLE
Regex filter not working

### ISSUE THREAD

**Issue by essiembre** [Norconex/collector-http#191]
From @searchquest in #187:
> There are some urls like http://x.y.com/abc/AllArticle.aspx?PageNo=1 and I am trying to exclude them as below,
> 
> <filter
class="com.norconex.collector.core.filter.impl.RegexReferenceFilter"
onMatch="exclude">http:\/\/x.y.com\/abc\/AllArticle.aspx.*</filter>
> 
> But it does not. If you please help on this plz.

**Comment by essiembre** [comment]
@searchquest, without having tried it yet, I do not see what could be wrong. Can you please attach your config?

**Comment by searchquest** [comment]
@essiembre , sorry for late reply. I was bit engaged in some other activities. I have attached the config file. Please have a look.

Thanks.

[internal-config_infoservice.txt](https://github.com/Norconex/collector-http/files/54975/internal-config_infoservice.txt)

**Comment by essiembre** [comment]
I think I found the issue just by looking at your config.  You have regex filters defined in the ``<crawlerDefaults>`` section, but you overwrite them with a single extension filter in your ``<crawler>`` section.  

When you have only one crawler defined, I strongly recommend to put all your configuration under your ``<crawler ...>`` tag and forget about the ``<crawlerDefaults>`` section to avoid this type of situation.  There is also the possibility to create configuration fragments you can include dynamically if one day you want to share common settings and avoid possible confusion with ``<crawlerDefaults>``.

Please confirm that your filters work as expect after you made the suggested changes.

**Comment by essiembre** [comment]
Given the lack of feedback, I will assume the configuration issue I found in your attached config is what caused your problem. If fixing your config does not resolve it, feel free to re-open.

**Comment by searchquest** [comment]
Hi,

The issue indeed got resolved. It was the issue with the crawlerdefaults being overwritten. Now working fine. Thanks.
