### ISSUE TITLE
Title and content are in messy code

### ISSUE THREAD

**Issue by bruce-genhot** [Norconex/collector-http#194]
When I do fetching against http://www.spprec.com/sczw/infodetail/?infoid=5f2c3843-86ce-4f22-a99d-c88e1c838aba&categoryNum=005002005, the returned title and content is in messy code.

**Comment by bruce-genhot** [comment]
It because HTTP response returns wrong Content-type(returns 'text/html;charset=utf-8', but the real is 'text/html;charset='gb2312')

**Comment by essiembre** [comment]
Do you own that page or can you contact the owner to have it fixed?  Otherwise, I think we should a new feature to either force using a character set when reading pages, or being able to specify what to rely on for charset.  Given this is an error of the site, I will mark this ticket as a feature request to support bad charset declarations (as opposed to a bug).

**Comment by bruce-genhot** [comment]
Thanks, I am not the owner of that page, will try to contact the owner. I think it's better if we can specify a charset which will be force used.

**Comment by niels** [comment]
FWIW, wile the `Content-Type` HTTP header is incorrect, the HTML itself correctly self-reports as being gb2312 encoded:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
```

This should however [be supported by Tika](https://tika.apache.org/1.9/api/org/apache/tika/parser/html/HtmlEncodingDetector.html)?

**Comment by essiembre** [comment]
Tika uses a few encoding detection techniques and the declared charset in HTML is one.  Tika is invoked when parsing documents.  That's when it converts extracted text to UTF-8.  In your case, are you by-passing parsing of documents to keep the original document like you described in #202? If so it is very possible to have varying outcome if you expect all files to be UTF-8 (they will not all be).

**Comment by essiembre** [comment]
Let me know if we can close this ticket in favor of #202, which is about character encoding also and now provides a solution.

**Comment by bruce-genhot** [comment]
OK, will have a try with the latest snapshot

**Comment by bruce-genhot** [comment]
Thank you @essiembre , but Unfortunately, ```CharsetTransformer``` is not the solution for me, here are my configuration file.

```
<?xml version="1.0" encoding="UTF-8"?>
<httpcollector id="Minimum Config HTTP Collector">
    <progressDir>./www.spprec.com/progress</progressDir>
    <logsDir>./www.spprec.com/logs</logsDir>
    <crawlers>
        <crawler id="www.spprec.com">
            <startURLs stayOnDomain="false" stayOnPort="false" stayOnProtocol="false">
                <url>
                    <![CDATA[http://www.spprec.com/sczw/InfoDetail/Default.aspx?InfoID=38c6ad47-aabe-4cbe-a550-6ea6fea88a81&CategoryNum=005003001]]>
                </url>
            </startURLs>
            <workDir>./www.gsggzyjy.cn</workDir>
            <referenceFilters>
                <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="include"
                        caseSensitive="false">
                    <![CDATA[http://www\.spprec\.com/sczw/InfoDetail/Default\.aspx\?InfoID=38c6ad47-aabe-4cbe-a550-6ea6fea88a81&CategoryNum=005003001]]>
                </filter>
            </referenceFilters>
            <importer>
                <preParseHandlers>
                    <transformer class="com.norconex.importer.handler.transformer.impl.CharsetTransformer" targetCharset="UTF-8">
                        <restrictTo field="document.contentType">
                            text/.*
                        </restrictTo>
                    </transformer>
                </preParseHandlers>
            </importer>
            <committer class="com.norconex.committer.core.impl.FileSystemCommitter">
                <directory>./examples-output/minimum/crawledFiles</directory>
            </committer>
        </crawler>
    </crawlers>
</httpcollector>
```

**Comment by essiembre** [comment]
I was able to reproduce and the problem is exactly has described earlier by @bruce-genhot.  The HTML parser relies on the charset specified in the page when present, which is wrongfully set in your case.  The best solution is of course to contact the owner so they fix their page.  

If that's not possible, you have two options.  

The first option, make sure to use the latest snapshot and change the page encoding to match the declaration (bg2312). Then the HTML parser will be able to convert it properly to UTF-8 when parsing it. 

```xml
<importer>
  <preParseHandlers>
    <transformer class="com.norconex.importer.handler.transformer.impl.CharsetTransformer"
        targetCharset="gb2312">
      <restrictTo field="document.contentType">text/html</restrictTo>
    </transformer>
  </preParseHandlers>    
</importer>
```

The other option is to have the crawler fix your declaration by performing a search and replace on the HTML to replace the character set to UTF-8. 
```xml
<importer>
  <preParseHandlers>
    <transformer class="com.norconex.importer.handler.transformer.impl.ReplaceTransformer">
        <replace>
            <fromValue>content="text/html; charset=gb2312"</fromValue>
            <toValue>content="text/html; charset=utf-8"</toValue>
        </replace>
        <restrictTo field="document.contentType">text/html</restrictTo>
    </transformer>
  </preParseHandlers>
</importer>
```
Of course all your HTML pages have to declare the charset the same way for the above to work. Otherwise, modify accordingly.

Try either approach and please confirm this works for you (they both worked for me).

**Comment by bruce-genhot** [comment]
Thank you @essiembre , both worked for me as well. but we have a similar problem with TikaLinkExtractor, here are my config, the title is in messy code.
```
<?xml version="1.0" encoding="UTF-8"?>
<httpcollector id="Minimum Config HTTP Collector">
    <progressDir>./www.spprec.com/progress</progressDir>
    <logsDir>./www.spprec.com/logs</logsDir>
    <crawlers>
        <crawler id="www.spprec.com">
            <startURLs stayOnDomain="false" stayOnPort="false" stayOnProtocol="false">
                <url>
                    <![CDATA[http://www.spprec.com/sczw/jyfwpt/005003/005003001/MoreInfo.aspx?CategoryNum=005003001]]>
                </url>
            </startURLs>
            <workDir>./www.spprec.com</workDir>
            <referenceFilters>
                <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="include"
                        caseSensitive="false">
                    <![CDATA[(http://www\.spprec\.com/sczw/jyfwpt/005003/005003001/MoreInfo\.aspx\?CategoryNum=005003001)|(http://www\.spprec\.com/sczw/InfoDetail/Default\.aspx\?InfoID=.*)]]>
                </filter>
            </referenceFilters>
            <importer>
                <preParseHandlers>
                    <!--<transformer class="com.norconex.importer.handler.transformer.impl.CharsetTransformer" targetCharset="gb2312">-->
                        <!--<restrictTo field="document.contentType">text/html</restrictTo>-->
                    <!--</transformer>-->
                    <transformer class="com.norconex.importer.handler.transformer.impl.ReplaceTransformer">
                        <replace>
                            <fromValue>content="text/html; charset=gb2312"</fromValue>
                            <toValue>content="text/html; charset=utf-8"</toValue>
                        </replace>
                        <restrictTo field="document.contentType">text/html</restrictTo>
                    </transformer>
                </preParseHandlers>
                <postParseHandlers>
                    <tagger class="com.norconex.importer.handler.tagger.impl.ConstantTagger">
                        <constant name="Content-Encoding">UTF-8</constant>
                        <constant name="type">采购公告</constant>
                        <constant name="location">中国.四川</constant>
                        <constant name="source">四川公共资源交易网</constant>
                    </tagger>
                    <tagger class="com.norconex.importer.handler.tagger.impl.KeepOnlyTagger">
                        <fields>
                            collector.referrer-link-text,document.reference,content,type,location,source,collector.referenced-urls,collector.referrer-reference,timestamp
                        </fields>
                    </tagger>
                    <tagger class="com.norconex.importer.handler.tagger.impl.RenameTagger">
                        <rename fromField="collector.referrer-link-title" toField="title" overwrite="true"/>
                        <rename fromField="document.reference" toField="link" overwrite="true"/>
                        <rename fromField="collector.referrer-reference" toField="reference" overwrite="true"/>
                        <rename fromField="collector.referenced-urls" toField="sourceLink" overwrite="true"/>
                    </tagger>
                    <tagger class="com.norconex.importer.handler.tagger.impl.CurrentDateTagger" field="timestamp"
                            format="yyyy-MM-dd hh:mm:ss" overwrite="true"></tagger>
                </postParseHandlers>
            </importer>
            <!--<committer class="com.norconex.committer.core.impl.FileSystemCommitter">-->
            <!--<directory>./examples-output/minimum/crawledFiles</directory>-->
            <!--</committer>-->

            <linkExtractors>
                <extractor class="com.norconex.collector.http.url.impl.TikaLinkExtractor" maxURLLength="2048" ignoreNofollow="true" keepReferrerData="true">
                    <contentTypes>text/html,application/xhtml+xml,vnd.wap.xhtml+xml,x-asp</contentTypes>
                    <tags>
                        <tag name="a" attribute="href"/>
                    </tags>
                </extractor>
            </linkExtractors>
        </crawler>
    </crawlers>
    <crawlerDefaults>
        <maxDepth>1</maxDepth>
        <robotsTxt ignore="true"/>
        <robotsMeta ignore="true"/>
        <sitemap ignore="true"/>
        <sitemapResolverFactory ignore="true"/>
        <delay default="5000"/>
    </crawlerDefaults>
</httpcollector>
```

**Comment by essiembre** [comment]
@bruce-genhot, what is the problem with TikaLinkExtractor?  The returned links are bad? Or the parsed document title after importing took place is bad when you use TikaLinkExtractor?

**Comment by bruce-genhot** [comment]
@essiembre , parsed document title is bad (in messy code).

**Comment by essiembre** [comment]
I see what is happening now. The charset fix is done in the importer, but you are using the title from the referrer link which is extracted before importing takes place.  For reasons I ignore at the moment, the GenericLinkExtractor seems to store the titles properly.  Can you try?

In any case, I will look into making a CharsetTagger so fix charsets in fields.

**Comment by bruce-genhot** [comment]
@essiembre , yes, GenericLinkExtractor works for me, thank you.

**Comment by essiembre** [comment]
The [GenericLinkExtractor](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/impl/GenericLinkExtractor.html) was modified in the latest [snapshot release](https://www.norconex.com/collectors/collector-http/download).  It now tries to detect the encoding before extracting links and referrer data. In addition, there is now a new ``charset`` attribute on it allowing you to dictate which charset to use.  

Can you give it a try and see if your issue remains resolved with it?  

I also created a new [CharsetTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/CharsetTagger.html) if you ever need it.  It can convert the charset on specified field values the same way ``CharsetTransformer`` does it on content.,

**Comment by bruce-genhot** [comment]
@essiembre , OK, thanks. will have a try with the latest release.

**Comment by essiembre** [comment]
Recent changes described in https://github.com/Norconex/collector-http/issues/209#issuecomment-172744356 can be relevant to this ticket.  Let me know if we can close now.

**Comment by bruce-genhot** [comment]
Yes, confirmed, thank you.
