### ISSUE TITLE
Is it possible to save the href title as a part of document ?

### ISSUE THREAD

**Issue by bruce-genhot** [Norconex/collector-http#195]

**Comment by essiembre** [comment]
I am not sure this is what you mean, but you can set the ``keepReferrerData`` to ``true`` on your link extractor to keep information on the link that led to a document, as metadata. E.g.: 

```xml
<extractor class="com.norconex.collector.http.url.impl.TikaLinkExtractor"
    keepReferrerData="true" />
```

The target document will then have the following metadata fields added (taken from [Javadoc](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/impl/GenericLinkExtractor.html)):

* **Referrer reference**: The reference (URL) of the page where the link to a document was found. Metadata value is HttpMetadata.COLLECTOR_REFERRER_REFERENCE (collector.referrer-reference).
* **Referrer link tag**: The tag and attribute names of the link that contained the document reference (URL) in referrer's content. Metadata value is HttpMetadata.COLLECTOR_REFERRER_LINK_TAG (collector.referrer-link-tag).
* **Referrer link text**: The text between the <a href=""></a> tags of the referrer document. Can be useful to help establish better document titles. Metadata value is HttpMetadata.COLLECTOR_REFERRER_LINK_TEXT (collector.referrer-link-text).
* **Referrer link title**: The title attribute of the link that contained the document reference (URL) in referrer's content. Can also be useful to help establish better document titles. Metadata value is HttpMetadata.COLLECTOR_REFERRER_LINK_TITLE (collector.referrer-link-title).

Is this what you are after?  You can rename or copy the ``collector.referrer-link-title`` field to whatever best suits you using a [RenameTagger](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/RenameTagger.html) for instance (part of [Importer Module](http://www.norconex.com/collectors/importer/configuration)).

**Comment by bruce-genhot** [comment]
Thanks, it works for me.

**Comment by essiembre** [comment]
Thanks for confirming.
