### ISSUE TITLE
One more SSL related issue

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#196]
I got an issue, using 2.4.0 snapshot:
```
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Host name 'www.aflac.com' does not match the certificate subject provided by the peer (CN=incapsula.com, O=Incapsula Inc, L=Dover, ST=Delaware, C=US)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:465)

```
I believe it is because invalid certificate, but it is possible there are a lot of such sites, so solution may be helpful to community.

**Comment by essiembre** [comment]
Setting ``trustAllSSLCertificates`` to ``true`` does not do it for you?  Like:
```xml
<httpClientFactory>
    ...
    <trustAllSSLCertificates>true</trustAllSSLCertificates>
</httpClientFactory>
```
I thought we recently resolved the last issues with SSL certificates in #181?

**Comment by AntonioAmore** [comment]
Seems the solution doesn't plays for another site, and the exception a bit differs, on my opinion.

**Comment by essiembre** [comment]
Try the [latest snapshot release](https://www.norconex.com/collectors/collector-http/download).  When trusting all certificates, host name verification is now disabled.  This eliminates the error in my testing.  Please confirm.

**Comment by AntonioAmore** [comment]
The newest snapshot works perfectly! (tested with tika extractor)
Thank you a lot.
