### ISSUE TITLE
Log tune-ups to investigate relational links fetch

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#197]
I detected the crawler with config, mentioned at #181 (the same site) seems not fetching relational urls like ```/en/press/news/studies/news_2011-03-29.html/```

It is possible there are filters rejecting the url, but it doesn't appear at the log, even when I set REJECTED_REDIRECTED to DEBUG.

Which parameters I should set at log4j.properties to detect why relational urls aren't fetched? And how I may detect are they processing at all?

**Comment by essiembre** [comment]
This is likely the same issue as #188.  Please refer to it for a temporary solution that works.

Please confirm it is the same issue before we close this one.

**Comment by AntonioAmore** [comment]
Seems it doesn't working for that case: I don't see neither urls, normalized from relative, nor messages about redirects to others in logs.

**Comment by essiembre** [comment]
Can you please attach your config? Setting all loggers to DEBUG in the log4j.properties file will be overkill but you will for sure get all the information it is possible to get.

**Comment by AntonioAmore** [comment]
It is the same as for #181. I added tika url extractor to test, but doesn't plays neither for it, nor generic extractor.
Tested with the latest 2.4.0 snapshot

**Comment by essiembre** [comment]
I just tested with your same confirm from 181, and I have relative URLs extracted properly.

For instance, the ``collector.referenced-urls`` metadata field contains several URLs matching the pattern you mention (that are relative in the page).  Like:

* https\://www.allianz.com/en/press/extra_new/125-years-of-allianz.html/
* https\://www.allianz.com/en/press/news/company/
* https\://www.allianz.com/en/press/press_service/calendar_events.html/

I can also see from the log that they are extracted just fine.  Like this one:
```
INFO  [CrawlerEventManager]            URLS_EXTRACTED: https://www.allianz.com/en/press/news/company/appointments/140927_quotes_on_daniel_ivascyn_pimco.html/
```
When looking at your main page source, I cannot find ``/en/press/news/studies/news_2011-03-29.html/`` in it.  Can you specify which page/URL has that link in it?

If your concern is with the URL ending with a forward slash, know that it is like that in the page it self and that's not "invalid" for a URL.  You can always strip the trailing slash via URL normalization.

**Comment by AntonioAmore** [comment]
The source of page ```www.allianz.com/en/press/news/?oneweb:filter:date=2009to2014&page=1``` contains set of relative urls looking like ```"/en/press/news/company/point_of_view/news_2013-06-25.html/"```, etc. at ```div."container container-listing"```

I believe they should appear in the log, even if rejected by a filter.

**Comment by essiembre** [comment]
With your config files from #181, this URL is extracted and processed as it should: ``/en/press/news/company/point_of_view/news_2013-06-25.html/``.

If your concern is only to show in the logs all URLs that get rejected by filters, make sure you set the log level to INFO in the ``classes/log4j.properties`` file for the following:
```
log4j.logger.CrawlerEvent.REJECTED_FILTER=INFO
```
Using DEBUG sometimes prints more info (like the exact filter rules having caused the filtering):
```
log4j.logger.CrawlerEvent.REJECTED_FILTER=DEBUG
```

It will then look something like this (dummy filter I created just to show you, with INFO):
```
INFO  [CrawlerEventManager]           REJECTED_FILTER: https://www.allianz.com/en/press/news/financials/business_results/news_2013-05-15.html/
INFO  [CrawlerEventManager]           REJECTED_FILTER: https://www.allianz.com/en/products_solutions/
INFO  [CrawlerEventManager]           REJECTED_FILTER: https://www.allianz.com/en/press/extra_new/discovery.html/
INFO  [CrawlerEventManager]           REJECTED_FILTER: https://www.allianz.com/v_1370417655000/media/press/photo/archive/sonnenblumen_teaser.jpg
INFO  [CrawlerEventManager]           REJECTED_FILTER: https://www.allianz.com/en/press/news/financials/stakes_investments/news_2013-06-05.html/
INFO  [CrawlerEventManager]           REJECTED_FILTER: https://www.allianz.com/v_1362039300000/media/press/photo/archive/riess_291x187.jpg
```
Does it answer your question?

**Comment by AntonioAmore** [comment]
I used ```REJECTED_FILTER=INFO``` and ```REJECTED_FILTER=DEBUG```,  but urls looking like ```/en/press/news/company/point_of_view/news_2013-06-25.html/``` never appear in my logs, even in REJECTED list.

Let's  close the issue, thank you for your attention.

**Comment by essiembre** [comment]
I am closing, but it's not clear if you made it work for your or not.  It is showing in the logs for me but if you feel there is something wrong, feel free to re-open.
