### ISSUE TITLE
URLStatusCrawlerEventListener does not work correctly

### ISSUE THREAD

**Issue by bruce-genhot** [Norconex/collector-http#206]
I am using URLStatusCrawlerEventListener to catch errors like below.
```
URLStatusCrawlerEventListener urlStatusCrawlerEventListener = new URLStatusCrawlerEventListener();
urlStatusCrawlerEventListener.setStatusCodes("403,404,500");
urlStatusCrawlerEventListener.setOutputDir(ERROR_OUTPUT_DIR);
```
but have two issues
- all error files are named like 'null219-1451459005846.tsv'
- all error files do not include real error message or code, only column names are there
```
Referrer	URL	Status	Reason
```

**Comment by essiembre** [comment]
To get rid of the "null" prefix you can invoke this method:
```
urlStatusCrawlerEventListener.setFileNamePrefix("fileNamePrefix");
```
As far as the file being empty, do you have such errors in the logs?  I just tried to reproduce and I get some entries when there are errors.  Can you provide your config and which URL should be triggering errors so I can reproduce?

**Comment by essiembre** [comment]
With the latest [snapshot release](https://www.norconex.com/collectors/collector-http/download), you should no longer have file names prefixed by ``null``.

**Comment by bruce-genhot** [comment]
OK, thank you.

**Comment by essiembre** [comment]
You closed this, but did you manage to get your errors (if any exists) in the file created?

**Comment by bruce-genhot** [comment]
file names are not prefixed by ```null``` now, but I did not test error content yet.

**Comment by bruce-genhot** [comment]
just close this issue now, will open another issue if I can not get errors.
