### ISSUE TITLE
Delete rejected documents on clean/first run

### ISSUE THREAD

**Issue by jetnet** [Norconex/collector-http#211]
Hi Pascal,

can the collector be configured to send a deletion command for all rejected documents?
That can be very useful, for example, if the exclude filter list gets changed (for instance, adding a new path), so the collector will delete documents from the index, which have been indexed before.

BTW, how can I define multiple regular expressions?
A regex per line seems not to be working:

``` xml
<referenceFilters>
  <filter class="$filterRegexRef"  onMatch="exclude" caseSensitive="false" >
    .*/path1.*
    .*/path2.*
  </filter>
</referenceFilters>
```

is the grouping only the way to do that?

``` xml
<referenceFilters>
  <filter class="$filterRegexRef"  onMatch="exclude" caseSensitive="false" >
     .*(/path1|/path2).*
  </filter>
</referenceFilters>
```

Thank you!

**Comment by jetnet** [comment]
I apologize, it does send deletion commands for previously indexed documents, if the exclude rules have been changed.
It does not delete rejected pages on the first run only, and that is the "expected behavior" I guess :smile:

**Comment by essiembre** [comment]
You are correct about the expected behavior.  I guess there might be a use cases where a "fresh" crawl does not necessarily mean there is not already content in your index and you would like to use the crawler to clean up an existing index.  Often people would simply wipe out their index first before doing a crawl from scratch (i.e. first crawl) when they want to do a massive "clean" of their index, but we can make this a feature request if you feel a strong need for it.  Let me know.

About having multiple regexes, yes, the grouping will work, but handlers can also be repeated as often as you like. For instance, nothing prevents you from having several regexes defined this way:

```xml
 <filter class="$filterRegexRef"  onMatch="exclude">.*/path1.*</filter>
 <filter class="$filterRegexRef"  onMatch="exclude">.*/path2.*</filter>
```
It's whatever you prefer. :-)

**Comment by jetnet** [comment]
Thanks for confirming that!

We have the following case, where deletion during a "fresh" run makes sense:
upon a publishing process, the CMS creates a searchview (a simple HTML file, which gets published to the webserver along with the content) with the links to the pages, which have being modified, added or deleted  and triggers the crawler to index the searchview (`depth=1`).
The crawler does not need to keep statistics for that job (to prevent it to check all the pages it has ever crawled, the `<workDir>` gets deleted everytime). So, deleted (and modified with `robots=noindex`) pages gets removed from the index by the connector, no need to communicate with the index-server directly to remove pages.

Do you think, it makes sense to make the "deletion on a fresh run" configurable?..
Not as a matter of priority of course ;)

**Comment by essiembre** [comment]
So I understand right, your "searchview" list a bunch of URLs one day, and the next day, it may list another bunch which many links being the same, except some of them now points to 404 pages.  Then you would like a deletion command to be sent.  Correct?  I am marking as a feature request.

**Comment by jetnet** [comment]
Exactly! Thank you!

**Comment by neil-s** [comment]
@essiembre is there a plan to support this feature? It's leading to inefficient workarounds for an implementation.

**Comment by essiembre** [comment]
It is planned for the next major release (3.0, no ETA).  For now, for a custom solution, you can look at using [URLStatusCrawlerEventListener](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/crawler/event/impl/URLStatusCrawlerEventListener.html) for listing broken URLs to be deleted.  You could also create your own version of it that will automatically delete them from your target location.

**Comment by essiembre** [comment]
This feature is now part of the latest snapshot release.  To have rejected documents deleted, you can add a the new [DeleteRejectedEventListener](https://opensource.norconex.com/collectors/core/v2/apidocs/com/norconex/collector/core/crawler/event/impl/DeleteRejectedEventListener.html) class within your `<crawler>` section.  By default, it will send deletion requests to your Committer(s) for all events name starting with `REJECTED_`.   You can control which event should trigger a deletion request, regardless of whether the crawler starts from scratch or does an incremental run.  An example:

```
 <listener class="DeleteRejectedEventListener">
   <eventMatcher method="csv">REJECTED_NOTFOUND,REJECTED_FILTER</eventMatcher>
 </listener>
```
