### ISSUE TITLE
Is there a tagger for removing html code from a field

### ISSUE THREAD

**Issue by bruce-genhot** [Norconex/collector-http#217]
I am using DomTagger to extract something, like below.
```
 <tagger class="com.norconex.importer.handler.tagger.impl.DOMTagger">
                        <dom selector="#showacticle" toField="detail" overwrite="false"></dom>
                        <restrictTo caseSensitive="false" field="document.reference"><![CDATA[http://www\.nxzfcg\.gov\.cn/morelink\.aspx\?type=12&index=2]]></restrictTo>
                    </tagger>
```
the result is a piece of html code, can I use a tagger to remove html code from it ?

**Comment by essiembre** [comment]
The ``DOMTagger`` will indeed return the HTML but the underlying API it uses allows to control whether to return the HTML or just the text.  I am marking this as a feature request to add a flag to tell it what to return exactly.

In the meantime, you can use [ReplaceTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ReplaceTagger.html) to remove HTML tags using regular expression. Like this (not tested):

```xml
  <tagger class="com.norconex.importer.handler.tagger.impl.ReplaceTagger">
      <replace fromField="detail" regex="true">
          <fromValue><![CDATA[<[^>]*>]]></fromValue>
          <toValue></toValue>
      </replace>
  </tagger>
```

**Comment by bruce-genhot** [comment]
OK, thanks.

**Comment by essiembre** [comment]
The [latest snapshot](https://www.norconex.com/collectors/collector-http/download) now extracts the text by default instead of HTML.  It has a new ``extract`` attribute you can add to change what it gets. Possible values are "text" (default), "html", and "outerHtml".

**Comment by bruce-genhot** [comment]
Yes, it works for me now, thanks.
