### ISSUE TITLE
Start URLs with and without trailing slash treated differently

### ISSUE THREAD

**Issue by niels** [Norconex/collector-http#225]
This might be a WONTFIX as there is an easy workaround, but sites that respond with a relative redirect for their root domain won't be handled correctly when the startURL didn't contain a trailing slash:

When queueing a `Location` response, the queued URL will differ based on whether the `startURL` contained a trailing slash or not. Given https://norconex-redir-test.herimedia.com, which redirects to `phone.html`, the crawler will correctly recognize

> DEBUG [GenericRedirectURLProvider] URL redirect: https://norconex-redir-test.herimedia.com/ -> https://norconex-redir-test.herimedia.com/phone.html

but will incorrectly recognize

> DEBUG [GenericRedirectURLProvider] URL redirect: https://norconex-redir-test.herimedia.com -> https://phone.html

This sample config shows the differing behavior depending solely on whether or not the startURL contains a trailing slash:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<httpcollector id="test-collector">
  <crawlers>
    <crawler id="test-crawler-1">
      <startURLs stayOnDomain="true">
        <url>https://norconex-redir-test.herimedia.com</url>
      </startURLs>
    </crawler>
    <crawler id="test-crawler-2">
      <startURLs stayOnDomain="true">
        <url>https://norconex-redir-test.herimedia.com/</url>
      </startURLs>
    </crawler>
  </crawlers>
</httpcollector>
```

test-crawler-2 will work as expected (following the redirect to `https://norconex-redir-test.herimedia.com/phone.html`), whereas test-crawler-1 will interpret the redirect as leading to `https://phone.html`.

**Comment by essiembre** [comment]
Sorry for the late reply, but I just tried and the host does not exist anymore.  If you still have the issue, can you provide a URL to replicate?

**Comment by niels** [comment]
No worries & thanks for the follow-up.

The test domain should be back online (you might need to refresh you DNS cache):

```
> curl -I https://norconex-redir-test.herimedia.com
HTTP/1.1 301 Moved Permanently
Server: nginx/1.9.6
Date: Sat, 20 Feb 2016 15:36:50 GMT
Content-Type: text/html
Content-Length: 185
Connection: keep-alive
Location: index.html
```

Please note that I haven't re-tested any of the newer snapshots.

**Comment by essiembre** [comment]
Thanks, I was able to reproduce but I am getting an Unknown Host exception again, before I could fix.  I will try to recreate in a test case.

**Comment by essiembre** [comment]
Ignore my previous comment.  I had a connection problem.  I can reach the domain without issues.

**Comment by essiembre** [comment]
The latest [snapshot release](https://www.norconex.com/collectors/collector-http/download) now has this fix.  Please confirm.

**Comment by essiembre** [comment]
2.4.0 has now been officially released with this fix.
