### ISSUE TITLE
Crawler directory rename

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#226]
Let's suppose the crawler dir has such structure:
```
crawler1|
        |-config
        |-workdir
```
If I rename a dir ```./crawler1```, will it affect previously collected db at the workdir? Still it correct and actual, for example, in scope of already visited, and imported pages?

Of course I assume all necessary changes to configurations are performed.

**Comment by essiembre** [comment]
No it should have any negative impact. 

If you change the top level dir, nothing will be affected unless you use full paths in your config for your workdir, logs, etc.   In which case updating those full paths to the new one will ensure things work like before.

Does that answer? Have you experienced any different?

**Comment by AntonioAmore** [comment]
Thank you for the answer. I don't know why, but I expected the collector uses in the DB unique IDs, etc., created basing on current workdir path, and other parameters, unique for the computer.

As I have some information, which I don't want loose, already collected, it was the reason I asked that question.

And what happens, if I used full paths in configuration? As mentioned above, those paths will updated on rename.

**Comment by essiembre** [comment]
Basically, the collector does not care where everything resides, paths are used like pointers and they are not used internally to create IDs or anything like that.  The default path values are relative to your installation directory... so if you only change the top level dir, they will remain relative.  Any non-relative ones would be paths you have defined yourself in your config and you can change them at will.

The only think to watch for is not to have two or more collectors pointing to the same location for storing their files.  This could cause impacting collisions.

There is one exception to this that may or may not impact you... and it is with this file:
```
<workdir>\progress\latest\status\<collectorName>.index
```
That file has full paths to your logs and progress files in it that you can update to your new path... but they should not be impacting and will be updated to your newest path on a new run so you can probably ignore.  Those are used by third party tools, such as [JEF Monitor](https://www.norconex.com/jef/monitor/).   But if you move things to a new location... such tools may think your files reside in the old location until you run the collector again.  In any case, they are not related to the crawl URL database which has your history of what was already crawled or not.

**Comment by AntonioAmore** [comment]
- Is it a solution, to remove that ```*.index``` file, before 1st launch of the crawler from the new location?

- May we say it is harmless to change ```<crawler id="..."``` and ```<httpcollector id="..."``` parameters in addition to config/workdir paths?

**Comment by essiembre** [comment]
Sure you can delete the index file.  If you want to do a fresh crawl the recommendation is to delete all generated folders/files anyway (typically everything under your "workdir").

But if you want to keep the cache ("mapdb" folder) because you want the crawler to keep detecting modified vs unmodified docs compared to previous runs, you can do so and delete other folders and it will work fine.  

If you do not care about keeping the progress of your last job (which is likely "completed" anyway) and keeping the logs, you definitely delete the ``progress`` and ``logs`` folders.

The simplest if you just want to re-crawl "from scratch" and you do not care to process all documents again is not to bother with any previously created files and folders (delete them or do not move them to your new location).

**Comment by essiembre** [comment]
About the ``id``, yes it is harmless if you start fresh (delete workdir files).  Else, make sure the cach directory/file names matches your new ID in the event that they were matching them before.  I recommend you assume a fresh crawl if you change those (less to worry about).

**Comment by AntonioAmore** [comment]
Ok, thank you a lot. You answered all my questions.

**Comment by essiembre** [comment]
You are welcome.
