### ISSUE TITLE
treat ./ as /

### ISSUE THREAD

**Issue by nuliknol** [Norconex/collector-http#230]
I believe the path "./" in the url has to be threaded as "/" , i.e. , remove the dot "." . Because otherwise the crawler can go into infinite loop under specific conditions, just like happens when crawling musl-libc.org website. The "offending" href tag can be something like this:
``
<li><a href="./">Home</a>
``
This is the output from the logfile of the crawler after it got into the loop:

`INFO  [CrawlerEventManager]          DOCUMENT_FETCHED: http://www.musl-libc.org/./././././././././././././././././././download.html
INFO  [CrawlerEventManager]       CREATED_ROBOTS_META: http://www.musl-libc.org/./././././././././././././././././././download.html
INFO  [CrawlerEventManager]           REJECTED_FILTER: http://www.musl-libc.org/./././././././././././././././././././musl2.png
INFO  [CrawlerEventManager]           REJECTED_FILTER: http://www.musl-libc.org/./././././././././././././././././././releases/musl-1.1.13.tar.gz
INFO  [CrawlerEventManager]            URLS_EXTRACTED: http://www.musl-libc.org/./././././././././././././././././././download.html
INFO  [CrawlerEventManager]         DOCUMENT_IMPORTED: http://www.musl-libc.org/./././././././././././././././././././download.html
INFO  [CrawlerEventManager]    DOCUMENT_COMMITTED_ADD: http://www.musl-libc.org/./././././././././././././././././././download.html
INFO  [AbstractCrawler] Norconex Minimum Test Page: 94% completed (374 processed/397 total)
INFO  [CrawlerEventManager]          DOCUMENT_FETCHED: http://www.musl-libc.org/./././././././././././././././././././support.html
INFO  [CrawlerEventManager]       CREATED_ROBOTS_META: http://www.musl-libc.org/./././././././././././././././././././support.html
INFO  [CrawlerEventManager]           REJECTED_FILTER: http://www.musl-libc.org/./././././././././././././././././././musl2.png
INFO  [CrawlerEventManager]            URLS_EXTRACTED: http://www.musl-libc.org/./././././././././././././././././././support.html
INFO  [CrawlerEventManager]         DOCUMENT_IMPORTED: http://www.musl-libc.org/./././././././././././././././././././support.html
INFO  [CrawlerEventManager]    DOCUMENT_COMMITTED_ADD: http://www.musl-libc.org/./././././././././././././././././././support.html
INFO  [CrawlerEventManager]          DOCUMENT_FETCHED: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.1.8.tar.gz.asc
INFO  [CrawlerEventManager]       CREATED_ROBOTS_META: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.1.8.tar.gz.asc
INFO  [CrawlerEventManager]            URLS_EXTRACTED: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.1.8.tar.gz.asc
INFO  [CrawlerEventManager]         DOCUMENT_IMPORTED: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.1.8.tar.gz.asc
INFO  [CrawlerEventManager]    DOCUMENT_COMMITTED_ADD: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.1.8.tar.gz.asc
INFO  [AbstractCrawler] Norconex Minimum Test Page: 94% completed (376 processed/397 total)
INFO  [CrawlerEventManager]          DOCUMENT_FETCHED: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.0.5.tar.gz.asc
INFO  [CrawlerEventManager]       CREATED_ROBOTS_META: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.0.5.tar.gz.asc
INFO  [CrawlerEventManager]            URLS_EXTRACTED: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.0.5.tar.gz.asc
INFO  [CrawlerEventManager]         DOCUMENT_IMPORTED: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.0.5.tar.gz.asc
INFO  [CrawlerEventManager]    DOCUMENT_COMMITTED_ADD: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.0.5.tar.gz.asc
INFO  [AbstractCrawler] Norconex Minimum Test Page: 94% completed (377 processed/397 total)
INFO  [CrawlerEventManager]          DOCUMENT_FETCHED: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.1.10.tar.gz.asc
INFO  [CrawlerEventManager]       CREATED_ROBOTS_META: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.1.10.tar.gz.asc
INFO  [CrawlerEventManager]            URLS_EXTRACTED: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.1.10.tar.gz.asc
INFO  [CrawlerEventManager]         DOCUMENT_IMPORTED: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.1.10.tar.gz.asc
INFO  [CrawlerEventManager]    DOCUMENT_COMMITTED_ADD: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.1.10.tar.gz.asc
INFO  [AbstractCrawler] Norconex Minimum Test Page: 95% completed (378 processed/397 total)
INFO  [CrawlerEventManager]          DOCUMENT_FETCHED: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.1.7.tar.gz.asc
INFO  [CrawlerEventManager]       CREATED_ROBOTS_META: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.1.7.tar.gz.asc
INFO  [CrawlerEventManager]            URLS_EXTRACTED: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.1.7.tar.gz.asc
INFO  [CrawlerEventManager]         DOCUMENT_IMPORTED: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.1.7.tar.gz.asc
INFO  [CrawlerEventManager]    DOCUMENT_COMMITTED_ADD: http://www.musl-libc.org/./././././././././././././././././releases/musl-1.1.7.tar.gz.asc
^C
`

Steps to reproduce:
Run the Norconex with the following configuration file:
````xml
<?xml version="1.0" encoding="UTF-8"?>
<httpcollector id="Minimum Config HTTP Collector">
  <progressDir>./musl-output/progress</progressDir>
  <logsDir>./musl-output/logs</logsDir>


  <crawlers>
    <crawler id="Norconex Minimum Test Page">
      <startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
        <url>http://www.musl-libc.org</url>
      </startURLs>
      <workDir>./musl-output/work</workDir>
	  <numThreads>5</numThreads>
      <maxDepth>-1</maxDepth>
      <sitemap ignore="true" />
      <sitemapResolverFactory ignore="true" />
      <delay default="5000" />

<referenceFilters>
	<filter class="com.norconex.collector.core.filter.impl.ExtensionReferenceFilter" onMatch="exclude">jpg,gif,png,ico,css,js,gz,bz,tgz,apk,rar,asec,zab,001,002,003,z01,isz,iwa,jar,ipa,pak,zip,xap,b1,webarchive,cso,dlc,cbr,egg,arc,air,edz,xsn,7z,ace,ex_,exe,bin,hqx,nbf,djprojects,wmz,pkg,dz,soundpack,as4a,dbz,pzip,cab,xzm,srr,bar,tot,diagcab,ark,aar,saz,r00,tar,zlib,deb,rpm,</filter>
</referenceFilters>
<metadataFilters>
  <filter class="com.norconex.collector.core.filter.impl.RegexMetadataFilter" field="Content-Type">
    .*\btext/html\b.*
  </filter>
  <filter class="com.norconex.collector.core.filter.impl.RegexMetadataFilter" field="Content-Type">
    .*\btext/plain\b.*
  </filter>
</metadataFilters>

      <importer>
        <postParseHandlers>
          <tagger class="com.norconex.importer.handler.tagger.impl.KeepOnlyTagger">
            <fields>title,keywords,description,document.reference</fields>
          </tagger>
        </postParseHandlers>
      </importer> 
      
      <committer class="com.norconex.committer.core.impl.FileSystemCommitter">
        <directory>./musl-output/crawledFiles</directory>
      </committer>
    </crawler>
  </crawlers>

</httpcollector>
`

**Comment by essiembre** [comment]
This ticket is a duplicate already answered here: https://github.com/Norconex/collector-http/issues/224#issuecomment-173278765

Please re-open if you feel it is not.

**Comment by nuliknol** [comment]
definitely works! thanks.
