### ISSUE TITLE
Varying max-depth settings issue

### ISSUE THREAD

**Issue by ahaertig** [Norconex/collector-http#231]
We are using the HTTP collector 2.3.0 mainly to simulate client requets to prefill our website cache. No documents are collected, just the URLs are crawled. For different requirements we crawl with different max-depth settings, usually 0 or 4.
While checking the log files after crawling with max-depth set to 0, we discovered that more then the configured start URLs were crawled. That should not be the case. We found out that this is related to the data store, which is MapDB in our setup. After deleting the MapDB-files everythin went back to normal.
So the question is: from the performance point of view, is a bad to delete the MapDB-files before starting the crawler and loose all collected site information?
Or is there any configuration option where we should pay attention to when changing the max-depth settings frequently?

**Comment by essiembre** [comment]
The crawler will cache previously crawled links to find out if they have changed from one crawl to another. This is used mainly to control what to send to your committer or not (unmodified documents are not committed).  In your case you do not need "commit" the data so this default behavior does not bring you anything.   In which case, deleting the mapdb folder like you are doing is perfectly fine.  This forces to do a "fresh" crawl every time.  If you want to simulate requests on every page, you pretty much have to do it fresh each time (if I understand you right).

About your issue of crawling more than the depth specified... it is probably tied to the URL cache as well.  See, the default behavior is to try re-crawl an URLs remaining in the cache after a re-crawl (also called "orphans".  So if on pass 1 you have a max depth of 4 and it crawls let's say 100 documents... then you change it to 1, it will crawl less at first, but then will attempt to recrawl all the ones you have in the cache form a previous run.  This default behavior can be disable like this:

```xml
 <orphansStrategy>IGNORE</orphansStrategy>
```

The safest/cleanest for what you want is probably just to delete the cache like you are doing though.

BTW, I strongly recommend using 2.4.0-SNAPSHOT which is pretty stable by now and has a few bug fixes in it not found in 2.3.0.  We'll try to make a formal release soon enough.

**Comment by ahaertig** [comment]
Thanks for your quick reply!
We will implement the deletion of the MapDB files.
