### ISSUE TITLE
GenericLinkExtractor not extracting script-src

### ISSUE THREAD

**Issue by ahaertig** [Norconex/collector-http#232]
We are using the HTTP collector 2.3.0 mainly to simulate client requets to prefill our website cache. No documents are collected, just the URLs are crawled. One requirement is to crawl JavaScript-files that are referenced via `<script` `src="URL"></script>`. So we enhanced our configuration by adding `<tag name="script" attribute="src" />` to the configuration. But apparently none of script files of our website are crawled. After checking the configuration twice and even upgrading to HTTP collector 2.4.0, I took a look at the Java class `com.norconex.collector.http.url.impl.GenericLinkExtractor`. I stumbled upon the private method `extractLinks(...)` : the first thing done here is removing all script-tags from the content, that afterwards is parsed for tags to extract links from. If I'm right there's no chance to ever extract a link from a script-tags src-attribute.

**Comment by essiembre** [comment]
I created a new [snapshot release](https://www.norconex.com/collectors/collector-http/download) with a fix for this.  Please confirm.

**Comment by ahaertig** [comment]
Thanks for the quick fix. I could test it successfully.

**Comment by ahaertig** [comment]
Is there a schedule for the release of 2.4.0, as our client wont deploy a snapshot-release on the production systems?

**Comment by essiembre** [comment]
We are hoping to release it within a week.  Thanks for confirming the fix.
