### ISSUE TITLE
Crawl additional sitemap elements

### ISSUE THREAD

**Issue by searchquest** [Norconex/collector-http#239]
Hi,

I am using V2.4.0 currently. I have checked earlier about sitemap crawling and it crawls the urls fine. But, if I want to fetch some additional elements present there in the sitemap what specific config to be included. Here is a sample section of the sitemap below,

&lt;url&gt;
         &lt;loc&gt;http://xyz.com&lt;/loc&gt;
         &lt;lastmod&gt;2015-10-19T06:32:00Z&lt;/lastmod&gt;
         &lt;priority&gt;1.0&lt;/priority&gt;
&lt;/url&gt;

So, the requirement is if I want to fetch elements &lt;lastmod&gt; or &lt;priority&gt; along with the urls present in &lt;loc&gt;.

Please suggest.

Thanks.

**Comment by essiembre** [comment]
Are you saying you would like those supported in general, or extracted and added as metadata fields to the document?  

``<lastmod>`` support will be made available in next feature release (see #127).  Adding them as metadata fields seems a good idea and we can make this a feature request.

**Comment by searchquest** [comment]
Thanks. Yes, idea is to add them as metadata fields in the document. Please let me know once that is implemented.

**Comment by essiembre** [comment]
After looking into this, it turns out those fields are already stored as metadata fields with each documents.  The field names are:

* collector.sitemap-priority
* collector.sitemap-lastmod
* collector.sitemap-changefreq

Can you confirm you can get them with these names?

**Comment by essiembre** [comment]
@searchquest: Can you confirm you are able to get those values?  Can we close this ticket?

**Comment by searchquest** [comment]
Please close the ticket. Thanks for the help.
