### ISSUE TITLE
Norconex HTTP Collector and crawler4j

### ISSUE THREAD

**Issue by sayed2008** [Norconex/collector-http#245]
I'm working on new project to choose the best crawler but I'm looking for two types Norconex HTTP Collector and crawler4j to be use but Can someone tell me , what are the difference between Norconex HTTP Collector and crawler4j ?

**Comment by essiembre** [comment]
One key distinction is Norconex HTTP Collector is meant to be viable/robust as a full-featured standalone crawler while crawler4j is first and foremost a Java API.  In a sense, a "product" vs a "library".

While Norconex HTTP Collector can also be embedded in java applications or extended using Java, the vast majority of use cases can be handled out-of-the-box via XML-based configuration and does not require any programming experience.  It can be used as a command-line application whereas crawler4j usually requires you to code your own crawling solution with it.

Norconex HTTP Collector also has more native features, expanding beyond pure crawling by offering configurable data manipulation options, language detection, OCR, etc. You can give a look at a partial list [here](https://www.norconex.com/collectors/collector-http/) and [there](https://www.norconex.com/collectors/features).  It also has "committers" that stores crawled data already identified targets such as Solr, Elasticsearch, IDOL, etc.

For businesses, Norconex HTTP Collector uses a business-friendly license (Apache) and commercial support is available.

In the end though, it depends what needs you are trying to fulfill.  If you are hesitating, the best recommendation I can give is to try them both and chose the one that better suits your needs.
