### ISSUE TITLE
recrawlableResolver with pre-v2.5.0 crawls in MongoDB

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#247]
I'd really like to apply recrawlableResolver  with pre-v2.5.0 crawls registered in MongoDB. Is it possible to define the new 2.5.0 fields in MongoDB (and perhaps assign them some initial value to mimic the crawler), so the crawler can operate with them?.
Could you give me some guidance on that matter?
Thanks
Carlos

**Comment by essiembre** [comment]
When it comes to MongoDB, I do not think the two new fields added (``contentType`` and ``crawlDate``), need to be explicitly added beforehand.  You may want to make a backup of your MongoDB if you are uncertain, but I suspect it will just work, except that each of your document will have to be recrawled at least once before they have the new values added (you will not see the benefits right away).

You can probably add default values manually by inserting values into Mongo yourself, but I am not sure how realistic that is for you and if it is really worth it (vs waiting one extra cycle until they get populated normally).

Please share your findings.

**Comment by csaezl** [comment]
After downloding v2.5.0-SNAPSHOT, I have these files:
```
httpmime-4.2.6.jar    24/02/2016 12:20
httpmime-4.4.1.jar    01/04/2015 13:02

jempbox-1.8.11.jar                      24/02/2016 12:20
jempbox-2.0.0-20140823.120514-532.jar   15/06/2015 22:52
```
Which ones Should I keep?

**Comment by OkkeKlein** [comment]
I always keep the latest version of all jars to prevent issues.

**Comment by essiembre** [comment]
@csaezl, are things OK for you now?  Can this ticket be closed?

**Comment by csaezl** [comment]
Yes, you can close it. I'll come back to it later
