### ISSUE TITLE
Spring MVC - HttpCollector executed by scheduler

### ISSUE THREAD

**Issue by V3RITAS** [Norconex/collector-http#249]
In Spring MVC application, we want to start a configured HttpCollector from within a service:
```java
@Service
public class CrawlerService implements ICrawlerService {
  
  @Autowired
  private HttpCollector httpCollector;

  @Override
  public void crawl() {
      this.httpCollector.start(true);
      ...
```  
This service method starting the crawler will be executed periodically by a scheduler.

The first execution works fine, but every subsequent one throws the following exception, even if the previous execution finished successfully:
```  
com.norconex.collector.core.CollectorException: javax.management.InstanceAlreadyExistsException: com.norconex.collector.http.crawler:type=My crawler
```  
Is there a preferred way of executing crawling jobs periodically (in a Spring Web App)?

**Comment by essiembre** [comment]
Collectors are meant first as standalone apps that are best run in isolation.  Their instances are meant to be destroyed after they ran.  This ensure a clean state each time they startup and is a design choice to increase stability given how more aggressive crawl (or corner cases) can be taxing on a system.  If it cannot be destroyed properly from withing your app, the recommendation is to run it as an external process. This recommendation also ensure stability of your host application.  Crawling many files at once sometimes takes a lot of memory and some big/problematic crawls should definitely be best run in isolation to keep your parent application intact.  There are ways to then monitor and get the state of things and you may want to have a look at the (JEF)[https://www.norconex.com/jef/] project for this. The JEF Monitor application can report on crawl status without keeping instances alive.  It may give you good pointers.  It even allows you to run your crawls on one server and have a parent app report on them remotely without having to keep instances in your main app.  

Usually the recommendation is to use the operating system scheduler (crontabs or Windows Task Scheduler).  But if invoking the Collector as an external process is an option for you, any scheduling mechanism should then work.

**Comment by V3RITAS** [comment]
Basically, scheduling and starting the crawler is the only purpose of this web application.

If I understood this right, we need to create an instance of HttpCollector for each crawl or, in other words, an HttpCollector instance which has been started once should not be started again, no matter if finished successfully or not.

Then, the question is, how to detect a finishing state of the crawl rep. HttpCollector and further, how to 'destroy it properly' after it finished? I already tried by checking JobSuite.getCurrentJobId() resp. using HttpCollector#stop() which seemed to be doing nothing but blocking.

**Comment by essiembre** [comment]
No need to create an instance of Collector for each crawl.  You can have many crawls in one Collector instance, but every time you run the collector, it is recommended it is a new instance, yes (making sure the former one is no longer).   

Again, would recommend to launch them as an external process (new JVM).  In your app you launch it as an external process, then you can then check its progress using [JobSuiteStatusSnapshot#newSnapshot(File)](https://www.norconex.com/jef/api/latest/apidocs/com/norconex/jef4/status/JobSuiteStatusSnapshot.html)

The file you need to pass is the index file generated by each collector when they run.  Typically found under ``[...]/progress/latest/*.index``.

You will then get a snapshot in time of the status of crawlers (whether they are running or not).

FYI, it takes a few seconds for the collector detects a previous instance has finished (5 I think) so if you try to run it again right away after it finishes, it will tell you it is already running.

If you do not want to launch it as an external process, you may end up with object instances still living, including maybe some statically initialized ones by third-parties libraries being used.   The life cycle of a collector is meant to start and die with the JVM.  If your launch app does not start and die with a collector run... you are in uncharted territories for the most part.  It does not mean you can't succeed at it, but you will lack the stability benefits of running crawls in complete isolation so on the long run you "may" run into issues you normally would not get.

**Comment by V3RITAS** [comment]
After a lot of testing we withdrew the idea of executing the crawler within a Spring MVC application. Instead we will keep the crawler as a stand-alone application which is executed by crontab.

I will close this ticket. Thank you very much Pascal for your detailed explanations!
