### ISSUE TITLE
I am trying to configure its importer module to strip what's between headers, rightnavs and footers but is does not seem to be stripping what is between these known tags.

### ISSUE THREAD

**Issue by mitchelljj** [Norconex/collector-http#250]
I am trying to use Norconex HTTP Collector to configure its importer module to strip what's between  headers, rightnavs and footers but is does not seem to be stripping what is between these known tags.
 
==========================================
Below are the divs within the html documents

`<div id="header">........</div>`

`<div id="rightnav" class="col-sm-3">........</div>`

`<div id="footer">........</div>`

Below is part of the XML file
      <importer>

        <postParseHandlers>

          <transformer class="com.norconex.importer.handler.transformer.impl.StripBetweenTransformer"

            inclusive="true">

            <stripBetween>

              <start><![CDATA[<div id="header">]]></start>

              <end><![CDATA[</div>]]></end>

            </stripBetween>

            <stripBetween>

              <start><![CDATA[<div id="rightnav" class="col-sm-3">]]></start>

              <end><![CDATA[</div>]]></end>

            </stripBetween>

            <stripBetween>

              <start><![CDATA[<div id="footer">]]></start>

              <end><![CDATA[</div>]]></end>

            </stripBetween>

          </transformer>

        </postParseHandlers>

      </importer>

**Comment by OkkeKlein** [comment]
You might want to try to use this on the  <preParseHandlers> stage. Once the content is parsed it is missing these tags.

**Comment by mitchelljj** [comment]
what does "on the stage" mean?

**Comment by OkkeKlein** [comment]
Text dropped, so edited post.

You need to move the config from postParseHandlers to preParseHandlers stage.

**Comment by mitchelljj** [comment]
I just switched to preParseHandlers and reran and it still does not strip out.

**Comment by essiembre** [comment]
Which version of the HTTP Collector are you using? Please attach your full config to reproduce.

**Comment by mitchelljj** [comment]
HTTP Collector 2.2.1 and I attached the full config file via an email to pascal.essiembre@norconex.com

**Comment by essiembre** [comment]
OK I just tried with the latest HTTP Collector snapshot version and it works fine.  Text from your header/footer/sidenav could not be found in the extracted text.

If you do not want a snapshot release, there is a fix to the StripBetweenTagger that was made to the Importer module 2.5.1 which you can download [here](https://www.norconex.com/collectors/importer/download).

Replace the norconex-importer-x.x.x.jar you have under your installation "lib" directory with the newer jar of the same name you'll get form the above download.

**Comment by essiembre** [comment]
Is this working now with the latest version of the Importer?

**Comment by mitchelljj** [comment]
Using the <stripBetween> tag (see below config file section) I am able to successfully ignore sections within crawled web pages but the problem is that for other content that is also crawled like PDF's that don't contain these sections to ignore these PDF's are not even committed but if I take out the <stripBetween> tags from the config file then these PDF's are committed but as expected the other crawled web pages no longer ignore these sections.

===========================================
    <crawler id="Norconex OCR Search">
      <importer>
        <preParseHandlers>
          <transformer class="com.norconex.importer.handler.transformer.impl.StripBetweenTransformer"
            inclusive="true">
            <stripBetween>
              <start><![CDATA[<div id="header">]]></start>
              <end><![CDATA[<div id="columns" class="row">]]></end>
            </stripBetween>
            <stripBetween>
              <start><![CDATA[<div id="rightnav" class="col-sm-3">]]></start>
              <end><![CDATA[]]></end>
            </stripBetween>
            <stripBetween>
              <start><![CDATA[<div id="footer-columns" class="row">]]></start>
              <end><![CDATA[]]></end>
            </stripBetween>
          </transformer>
        </preParseHandlers>
      </importer> 

      

      
      <startURLs>
        <url>http://www2.ed.gov/about/offices/list/ocr/docs/investigations/</url>
      </startURLs>


      
      <referenceFilters>

        <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="include">http://www2\.ed\.gov/about/offices/list/ocr/docs/investigations/.*</filter>

      </referenceFilters>
    </crawler>
