### ISSUE TITLE
Bug in handling preprocessing directives

### ISSUE THREAD

**Issue by liar666** [Norconex/collector-http#255]
I just copy-pasted your code from https://github.com/Norconex/collector-http/issues/41 :+1: 

Unfortunately, the preprocessor interprets the  #set in the comment, and raises:

> com.norconex.commons.lang.config.ConfigurationException: Cannot load config file as a string: /home/gmuller/Downloads/norconex-collector-http-2.5.0/tests/test1/test.xml
>         at com.norconex.commons.lang.config.ConfigurationLoader.loadString(ConfigurationLoader.java:234)
>         at com.norconex.commons.lang.config.ConfigurationLoader.loadXML(ConfigurationLoader.java:181)
>         at com.norconex.collector.core.CollectorConfigLoader.loadCollectorConfig(CollectorConfigLoader.java:73)
>         at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:76)
>         at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:75)
> Caused by: org.apache.velocity.exception.ParseErrorException: Encountered ".." at /home/gmuller/Downloads/norconex-collector-http-2.5.0/tests/test1/test.xml[line 3, column 45]
> Was expecting one of:
>     <WHITESPACE> ...
>     <IDENTIFIER> ...
>     "{" ...
>     
>         at org.apache.velocity.runtime.RuntimeInstance.evaluate(RuntimeInstance.java:1301)
>         at org.apache.velocity.app.VelocityEngine.evaluate(VelocityEngine.java:272)
>         at com.norconex.commons.lang.config.ConfigurationLoader.loadString(ConfigurationLoader.java:230)
>         ... 4 more
>

**Comment by essiembre** [comment]
The ticket you reference has an old config and some references in it are no longer valid.   You should start with the sample configurations provided with the version you downloaded.  

Please confirm if you run into issues using current configuration samples and documentation.

**Comment by liar666** [comment]
Hi,

Thanks for the quick answer, I know the config in the referred ticket is quite old, but the "problem" is still here in the last version of the software :)

Indeed, if you add the following comment in any file, it will not run:
```
<!-- You can define variables with the #set(...) directive to simplify your 
     config maintenance (using Apache Velocity syntax) -->
```

**Comment by essiembre** [comment]
I see... this is a problem in the comment in the ticket you reference only.  I verified all XML examples shipping with the product and on site documentation and that #set() in comment does not exist.  I updated the ticket you referenced to eliminate this.
