### ISSUE TITLE
extracted files, how i can get them?

### ISSUE THREAD

**Issue by doaa-khaled** [Norconex/collector-http#257]
I am new in norconex collector http, I did some changes in configuration files to be able to extract files from website but can't get these grabbed files?
is norconex save files by extracted urls ? and if yes where these files are saved
and finally if not, is there any solution to save files from fetched url on my hard desk ?
thank you

**Comment by liar666** [comment]
Hi,

I'm no expert in Norconex, but according to the provided examples, you should find what you are looking for with the following options:
```
  <!-- Decide where to store generated files. -->
  <progressDir>./tests-output/startupnation/progress</progressDir>
  <!-- Specify a crawler default directory where to generate files. -->
  <workDir>./tests-output/startupnation</workDir>
  <!-- Decide what to do with your files by specifying a Committer. -->
  <committer class="com.norconex.committer.core.impl.FileSystemCommitter">
     <directory>./tests-output/startupnation/crawledFiles</directory>
  </committer>

```

**Comment by essiembre** [comment]
In addition to @liar666 pointers, you can also add ``<keepDownloads>true</keepDownloads>`` to your crawler config and the raw files will be found under ``<workDir>/downloads``.

Normally though, you use a Committer to control where and how you want your data to be stored. The FileSystemCommitter ships out of the box but is too generic for most cases.  You normally want to either use an [existing committer](https://www.norconex.com/collectors/#committers) or [create your own](https://www.norconex.com/collectors/committer-core/create-your-own) to do exactly what you need.  

Does that answer?

**Comment by doaa-khaled** [comment]
I tried make flag of keepDownloads to be write, but the count of fetched files by less than fetched files by setting this flag to false ?

**Comment by essiembre** [comment]
The crawler will perform incremental crawls and only pick up new/modified/deleted content on each run so it is normal to get different files each time.  To start a "fresh" new crawl, delete the generated files under your working directory before restarting the crawler.

**Comment by doaa-khaled** [comment]
I will try.. thanks
