### ISSUE TITLE
Dynamically change the UserAgent?

### ISSUE THREAD

**Issue by liar666** [Norconex/collector-http#260]
Hi (again!!!!)

I will probably need soon to change the UserAgent while crawling a site, i.e. have a dynamic UserAgent.

According to the config docs, it seems that the UserAgent is a unique and fixed String. So what I need is not possible out-of-the-box.

Am I right in saying that if I want to achieve my goal, I either have to implement a complete
http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/client/IHttpClientFactory.html
Or I can overwrite:
http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/client/impl/GenericHttpClientFactory.html
to add some changes in the UserAgentString?

**Comment by essiembre** [comment]
The user agent is set on re-usable HTTP connections on Apache HttpClient. 
You could try to override the [GenericHttpClientFactory.html#buildCustomHttpClient(...)](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/client/impl/GenericHttpClientFactory.html#buildCustomHttpClient-org.apache.http.impl.client.HttpClientBuilder-) method to have a new user agent each time an HTTP client is constructed like this:

``builder.setUserAgent(myUserAgent);``

HTTP client instances being reused I doubt you'll be able to change the user agent in mid-crawl.
