### ISSUE TITLE
What does "keep" in LastModifiedMetadataChecksummer do?

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#265]

**Comment by essiembre** [comment]
By default, checksums are stored "internally" only and not attached to documents.  The "keep" attribute indicates you want the checksum generated/used to be stored as a new field on the document.  The name of the new checksum field is "collector.checksum-metadata" unless you specify your own name with "targetField".

This is documented in the base class [AbstractMetadataChecksummer](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/checksum/AbstractMetadataChecksummer.html).  That documentation should be repeated in implementing classes.  I will keep this ticket open until the documentation is updated to reflect the above.

**Comment by essiembre** [comment]
Documentation about "keep" attribute has been added to all checksum-related classes (like [LastModifiedMetadataChecksummer](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/checksum/impl/LastModifiedMetadataChecksummer.html)).
