### ISSUE TITLE
Unable to download content - charset encoding

### ISSUE THREAD

**Issue by searchquest** [Norconex/collector-http#271]
We have one legacy site which we want to crawl. We configured and crawled. we started for a small set of URLs and were able to crawl it but there were few pages we were not able to extract the body part.
After enabling debuging, we found that this seems to be the issue with charset encoding. The parser treat this as UTF-8 but the html shows that it is ISO-8859-1. In one of the fixed issues, i have seen that handlers should detect charset encoding automatically.
We are not sure as what could be the reason. I tried looking various post but was not able to figure out as what could be the reason. Please have a look and let me know as what could be the reason.

Below is the log snippet:
Norconex pci: 2016-06-30 09:52:48 DEBUG - Creating new input stream from memory cache.
Norconex pci: 2016-06-30 09:52:48 DEBUG - Detected encoding: ISO-8859-1
Norconex pci: 2016-06-30 09:52:48 DEBUG - Creating new input stream from memory cache.
Norconex pci: 2016-06-30 09:52:48 DEBUG - OCR parsing is disabled (no path provided).
Norconex pci: 2016-06-30 09:52:48 DEBUG - Parser "com.norconex.importer.parser.impl.FallbackParser" about to parse "http://test.ss.sw.abcd.se/pci/Download?url=http%3A%2F%2Fpci.al.sw.abcd.se%2Fcgi-bin%2Fparallel%2Falexserv%3FLI%3DEN%2FLZN7010219R9A%26FN%3D7_19080-CNZ222163Uen.B.html%26IX%3DFILTER_LIBTIT".
Norconex pci: 2016-06-30 09:52:48 DEBUG - Creating new input stream from memory cache.
Norconex pci: 2016-06-30 09:52:48 DEBUG - Parser "class com.norconex.importer.parser.impl.FallbackParser" did not produce new content for: http://test.ss.sw.abcd.se/pci/Download?url=http%3A%2F%2Fpci.al.sw.abcd.se%2Fcgi-bin%2Fparallel%2Falexserv%3FLI%3DEN%2FLZN7010219R9A%26FN%3D7_19080-CNZ222163Uen.B.html%26IX%3DFILTER_LIBTIT
Norconex pci: 2016-06-30 09:52:48 DEBUG - Document already parsed, assuming UTF-8 charset: http://test.ss.sw.abcd.se/pci/Download?url=http%3A%2F%2Fpci.al.sw.abcd.se%2Fcgi-bin%2Fparallel%2Falexserv%3FLI%3DEN%2FLZN7010219R9A%26FN%3D7_19080-CNZ222163Uen.B.html%26IX%3DFILTER_LIBTIT
Norconex pci: 2016-06-30 09:52:48 DEBUG - Transformer "class com.norconex.importer.handler.transformer.impl.ReduceConsecutivesTransformer" did not return any content for: http://test.ss.sw.abcd.se/pci/Download?url=http%3A%2F%2Fpci.al.sw.abcd.se%2Fcgi-bin%2Fparallel%2Falexserv%3FLI%3DEN%2FLZN7010219R9A%26FN%3D7_19080-CNZ222163Uen.B.html%26IX%3DFILTER_LIBTIT
Norconex pci: 2016-06-30 09:52:48 INFO -         DOCUMENT_IMPORTED: http://test.ss.sw.abcd.se/pci/Download?url=http%3A%2F%2Fpci.al.sw.abcd.se%2Fcgi-bin%2Fparallel%2Falexserv%3FLI%3DEN%2FLZN7010219R9A%26FN%3D7_19080-CNZ222163Uen.B.html%26IX%3DFILTER_LIBTIT (Subject: com.norconex.importer.response.ImporterResponse@6818f224)
Norconex pci: 2016-06-30 09:52:48 DEBUG - Creating memory cache from cached stream.
Norconex pci: 2016-06-30 09:52:48 DEBUG - Creating new input stream from memory cache.
Norconex pci: 2016-06-30 09:52:48 DEBUG - Document checksum from content: d41d8cd98f00b204e9800998ecf8427e

&lt;importer&gt;
    &lt;preParseHandlers&gt;                                  
                                &lt;filter 
            class="com.norconex.importer.handler.filter.impl.RegexMetadataFilter"
            onMatch="exclude" field="document.reference"&gt;http:\/\/test\.ss\.sw\.ericsson\.se\/Cpi\/Page\?dn=.*&lt;/filter&gt;
                    &lt;filter 
            class="com.norconex.importer.handler.filter.impl.RegexMetadataFilter"
            onMatch="exclude" field="document.reference"&gt;http:\/\/test\.ss\.sw\.ericsson\.se\/Cpi\/Index\/.*&lt;/filter&gt;
    &lt;/preParseHandlers&gt;
                &lt;postParseHandlers&gt;
                                                                &lt;tagger class="com.norconex.importer.handler.tagger.impl.ConstantTagger"&gt;
                                                                                &lt;constant name="SITE"&gt;Norconex Test Site&lt;/constant&gt;
                                                                &lt;/tagger&gt;
                   &lt;transformer class="com.norconex.importer.handler.transformer.impl.ReduceConsecutivesTransformer"&gt;
                        &lt;reduce&gt;\s&lt;/reduce&gt;
                        &lt;reduce&gt;\n&lt;/reduce&gt;
                        &lt;reduce&gt;\s\n&lt;/reduce&gt;
                    &lt;/transformer&gt;
    &lt;/postParseHandlers&gt;
&lt;/importer&gt;

**Comment by essiembre** [comment]
Without a sample page, it is hard to reproduce/troubleshoot.  Short of being able to share a public URL, can you attach a page for which you cannot get the content?

**Comment by searchquest** [comment]
Hi,
Here is a sample page attached.
[SamplePage.txt](https://github.com/Norconex/collector-http/files/342955/SamplePage.txt)

This a html file, changed the ext to .txt for uploading purpose.

Please suggest.

**Comment by essiembre** [comment]
I cannot reproduce. 

I ran your file through the latest version of the importer module with your configuration as-is and I did get a body extracted just fine.  See attached.
[collector-http-issue271.html.txt](https://github.com/Norconex/collector-http/files/357996/collector-http-issue271.html.txt)

Maybe it is something else in your config?  You just pasted the importer section, maybe you should attach your full HTTP Collector config?  Can you attach your config instead of pasting it in case something did not paste properly?

**Comment by essiembre** [comment]
Closing due to lack of feedback.
