### ISSUE TITLE
Documentation clarification on using a proxy

### ISSUE THREAD

**Issue by ThePrudentNinja** [Norconex/collector-http#282]
I have looked and looked and I can't seem to find any information on how exactly to use collector-http with an http proxy. The documentation seems to lack clear enough information on this.

I guess this would technically be a documentation issue as I am a totally new user trying to figure out how to use collector-http with an http proxy.

**Comment by essiembre** [comment]
Many connection-related settings can be set on [GenericHttpClientFactory](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/client/impl/GenericHttpClientFactory.html).  To set up proxy settings, add this to your crawler configuration:

```xml
<httpClientFactory>
      <proxyHost>...</proxyHost>
      <proxyPort>...</proxyPort>
      <proxyRealm>...</proxyRealm>
      <proxyScheme>...</proxyScheme>
      <proxyUsername>...</proxyUsername>
      <proxyPassword>...</proxyPassword>
</httpClientFactory>
```
Refer to the above link for more options if you want to encrypt the password. 

Does this answer?

**Comment by ThePrudentNinja** [comment]
Yes, perfect. I didn't realize the <httpClientFactory> and </httpClientFactory> were needed or where to put it. Thank you. It's working now.
