### ISSUE TITLE
Running multiple committers at the same time not possible?

### ISSUE THREAD

**Issue by liar666** [Norconex/collector-http#283]
Hi,

I'm currently developing my own committer. In order to debug my own code, I wanted to keep the FileSystemCommitter , so that I can compare the output of both committer.

The configuration file looks like this: 

```
    <crawler>
...
      <committer class="fr.presans.crawling.norconex.FoafCommitter">
        <where>STD_OUT</where>
      </committer>

      <committer class="com.norconex.committer.core.impl.FileSystemCommitter">
        <directory>./crawlers-output/startupnation/crawledFiles</directory>
      </committer>
    </crawler>
```

Unfortunately, when both committers are active, the second one (FileSystemCommitter) does not seem to be called: I can't find any ./crawlers-output/startupnation/crawledFiles/ directory nor files in it...
However, when the first committer is commented-out, everything works fine.

Did I miss something in the configuration file or is there a bug?

PS: I'm using norconex-collector-http-2.5.1 + norconex-importer-2.6.0-SNAPSHOT.jar

**Comment by essiembre** [comment]
The configuration does not allow you to specify more than one committer, but fear not, a committer exists that just allows that: [MultiCommitter](https://www.norconex.com/collectors/committer-core/latest/apidocs/com/norconex/committer/core/impl/MultiCommitter.html).  You can use it like this:

```xml
  <committer class="com.norconex.committer.core.impl.MultiCommitter">
      <committer class="(committer class)">
          (Commmitter-specific configuration here)
      </committer>
      <committer class="(committer class)">
          (Commmitter-specific configuration here)
      </committer>
      ...
  </committer>
```

**Comment by liar666** [comment]
Oh! Yes of course! On top of that, I read about this feature recently! Sorry for the waste of time!

**Comment by essiembre** [comment]
Just to point there was an issue that sometimes committers besides the first one listed in a multi committer would not receive the content.  This has been fixed in the latest snapshot release.

**Comment by liar666** [comment]
I just noticed bug that is somewhat different but seems related: when I comment out one of the two committers I put in my MultiCommitter, then nothing happens. My bug is that when there's only one committer in a MultiCommitter, then it does not receive the content either...
I'll check and tell you if the latest snapshot corrects the bug.

**Comment by liar666** [comment]
OK. I just verified, the 2 bugs were indeed related, it's now corrected :)
