### ISSUE TITLE
Getting HTTP-Headers from the servers's response

### ISSUE THREAD

**Issue by liar666** [Norconex/collector-http#288]
Hi,

I'm trying to crawl patents@EPO (https://worldwide.espacenet.com).

In order to limit the load on their servers, they designed a RESTful API:
https://www.epo.org/searching-for-patents/technical/espacenet/ops.html#tab3  (2nd document)

I've managed to get a fresh Token (on a regular basis) and add it to any HTTP request by imitating what is done at (I ended up overriding `createUriRequest` rather than `fetchDocument`):
https://www.norconex.com/how-to-crawl-facebook/

Unfortunately, the EPO's API also requires that we get some information about our quota of usage from the HTTP-Headers of each server's *response*.

Based on what is done in the facebook tutorial, I wanted to override `fetchDocument`, call `super.fetchDocument`, and extract the info from Headers that I expected to be able to get from its `HttpFetchResponse`.
Unfortunately, I couldn't find a way to access the HTTP-Headers from the `HttpFetchResponse`.

I know they are accessible from the `HttpResponse` that the `HttpClient.execute()` method returns.

But is there a way I can get the HTTP-Headers simply with norconex's API?

Thanks

**Comment by essiembre** [comment]
Yes, ALL HTTP headers are stored as document metadata so you can grab them easily wherever you have access to that metadata.  So it all depends if you have access to the metadata object from where you are in your own code.

From what I understand, you want the HTTP headers after calling ``super.fetchDocument(...)``.  This means you are probably in an overridden ``fetchDocument`` method, right?  If so, here is how you can obtain what you want:

```java
    @Override
    public HttpFetchResponse fetchDocument(
            HttpClient httpClient, HttpDocument doc) {
        // the fetchDocument method will populate the HttpDocument, so you 
        // can get metadata from it afterwards.
        
        HttpFetchResponse response = super.fetchDocument(httpClient, doc);
        
        // replace "quota-usage" with the right HTTP header name
        String quotaUsage = doc.getMetadata().getString("quota-usage");
        
        // do what you need with quotaUsage
        
        return response;
    }
```

Does this work for you?

**Comment by liar666** [comment]
Hi,

Thanks again for your very quick and valuable response.

I still have to finish writing the crawler's code, run it and reach the quota to tell you if it actually works, but for the moment, it compiles :)
