### ISSUE TITLE
[MinFrequency] regex variable not computed in constructor

### ISSUE THREAD

**Issue by sylvainroussy** [Norconex/collector-http#289]
Hi! 
For information, I don't have time for now to send a pull request but:

I build a **MinFrequency** by its constructor but when the **GenericRecrawlableResolver** ._getMatchingMinFrequency_ () method is called then the MinFrequency throws the message "Value or pattern missing in minimum frequency" due to _regex_ property is null.

The **MinFrequency**._setPattern_ () method  correctly builds the regex property.

**Comment by essiembre** [comment]
I just made a new [snapshot release](http://www.norconex.com/collectors/collector-http/download) with a fix for this.  Please confirm.  Thanks for reporting it!

**Comment by sylvainroussy** [comment]
It's ok.
