### ISSUE TITLE
Link extraction from commented HTML code

### ISSUE THREAD

**Issue by xnerus** [Norconex/collector-http#291]
`GenericLinkExtractor` allows to fine-tune tags with which it works, that is definitely an advantage over `TikaLinkExtractor`. However `TikaLinkExtractor` is not parsing code in the HTML-comments. For example, the following code:

```html
<a href="http://bot.nerus.com/">New Link</a>
<!--
<a href="http://bot.nerus.com/some/nonexistent/">Old Link</a>
-->
```

will be presented by `GenericLinkExtractor` as two references, but `TikaLinkExtractor` will return only one reference.

As I said above, `GenericLinkExtractor` has its own advantages over the alternative solution, so it would be desirable that this class also worked well.

**Comment by essiembre** [comment]
Check out the [latest snapshot](https://www.norconex.com/collectors/collector-http/download).  It will no longer extract URLs from comments by default, but the possibility is still there for those who see value added in doing so by adding the new configurable attribute ``commentsEnabled="true"``.  See XML configuration usage for [GenericLinkExtractor](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/impl/GenericLinkExtractor.html) for more details.

Please confirm.

**Comment by xnerus** [comment]
New attribute `commentsEnabled` in `GenericLinkExtractor` works exactly as you described above. I confirm this.

**Comment by essiembre** [comment]
Thanks for confirming.
