### ISSUE TITLE
Process sitemap only if it is presented in robots.txt

### ISSUE THREAD

**Issue by xnerus** [Norconex/collector-http#292]
Using `StandardSitemapResolverFactory` is very overhead when scanning a large number of different sites. This is due to the fact that for each new hostname sending a request for `sitemap.xml` and `sitemap_index.xml`. If these files are not available, the server responds something strange in many cases (default page, error page etc).

This is not a problem, and this task perfectly controlled by this class. However, the creation of two queries, receiving responses and trying to recognize them takes some time. Sometimes it is quite slow.

Currently is taken to indicate sitemap directly in `robots.txt` file. `StandardSitemapResolverFactory` and in this situation very well behaved.

It would be nice to be able to handle the sitemap *only* if it is presented in the `robots.txt` file as `sitemap` directive.

**Comment by essiembre** [comment]
A new [snapshot release](https://www.norconex.com/collectors/collector-http/download) was just made, which enables the behavior you are after in [StandardSitemapResolverFactory](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/sitemap/impl/StandardSitemapResolverFactory.html).  You can now specify an empty ``<path>`` tag to indicate you do not want the crawler to user any path to try find sitemaps.  It will then rely only on sitemaps specified as start URLs or found in robots.txt (if support for robots.txt has not been disabled).  An example:
```xml
  <sitemapResolverFactory>
    <path/>
  </sitemapResolverFactory>  
```

Please confirm.

**Comment by xnerus** [comment]
This is a very useful feature and it works exactly as described.
I have tested this and confirm it.

**Comment by essiembre** [comment]
Thanks for confirming.
