### ISSUE TITLE
error: validStatusCodes has private access in GenericDocumentFetcher

### ISSUE THREAD

**Issue by liar666** [Norconex/collector-http#293]
Hi,

Still working on overwriting GenericDocumentFetcher to allow the transmission of an OAuth token, I wanted to use the GenericDocumentFetcher.validStatusCodes to check the response from the server.

Unfortunately, I got the following error:
error: validStatusCodes has private access in GenericDocumentFetcher

It might be good to relax the contraints on this field so that users can access it when they extend the class.

**Comment by essiembre** [comment]
You can access it via its expected accessor methods: getValidStatusCodes() and setValidStatusCodes().
