### ISSUE TITLE
How to resolve org.apache.http.conn.ConnectionPoolTimeoutException?

### ISSUE THREAD

**Issue by liar666** [Norconex/collector-http#295]
Hi,

When I run one of my crawlers, I get a lot of errors like:
ERROR [AbstractCrawler] MyCrawler: Could not process document: <url> (org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool)

Whereas <url> is perfectly accessible.

Do you have any idea how I can resolve this?

Thanks in advance

**Comment by essiembre** [comment]
I cannot reproduce.  This exception usually indicates a leak in the connection pool.  That is, connections are allocated but they are never released so the pool is running out of connections to allocate.  You indicated in another ticket you wrote your own document fetcher.  Is it possible you forget to release a connection there?  If you can reproduce without using custom code, (e.g. using GenericDocumentFetcher), please attach your config.

**Comment by liar666** [comment]
Hi

Thanks again for your prompt reply and your kind help. 

You were indeed right again: as I'm not an expert with all the Apache http tools, I copied some code from the internet:
http://www.mkyong.com/java/apache-httpclient-examples/
and didn't realized they didn't close the connection...

Thanks to your remark, I went to your own (GenericDocumentFetcher) code and realized that I was lacking the following part:
        } finally {
            if (method != null) {
                method.releaseConnection();
}

Thanks a lot!
