### ISSUE TITLE
Relative URLs Not being correctly resolved

### ISSUE THREAD

**Issue by zackderaad** [Norconex/collector-http#297]
When crawling a website that contains relative links in the form of `<a href='./dir'>example link</a>`, (empasis on the './') the crawler is showing the link (in stdout) as "http://www.example.com/./dir" rather than the correct "http://www.example.com/dir". I have tried using the GenericURLNormalizer, but it does not make any difference. Is this a bug, or am I missing something? I realize that it should resolve to the correct URI still, but I've noticed the crawler starts going into a strange infinite loop of appending additional "./" to the URLs found. For example, it will "find" "http://www.example.com/./dir" then "http://www.example.com/././dir" then "http://www.example.com/./././dir", etc.. none of which are actually links within the crawled URL.

**Comment by zackderaad** [comment]
Yes the `removeDotSegments` did fix the issue, thank you.

**Comment by essiembre** [comment]
Thanks for confirming.
