### ISSUE TITLE
crawler loop

### ISSUE THREAD

**Issue by angelo337** [Norconex/collector-http#303]
hi there 
I am trying to crawl a site and I am stuck in a loop like this

> http://www.sic.gov.co/drupal/recursos_user/boletin_juridico2016/articulo/datos/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../conceptos_juridicos.html
http://www.sic.gov.co/drupal/recursos_user/boletin_juridico2016/articulo/datos/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../Conceptos%20pdf/19954/16_0019954__0.pdf
http://www.sic.gov.co/drupal/recursos_user/boletin_juridico2016/articulo/datos/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../articulo/consumidor/../../Conceptos%20pdf/62808/16_0062808__0.pdf

I already try to filter it with no luck, with this filters:

`<filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" 
        onMatch="exclude"
        caseSensitive="false">
        /([^/](..)+/.*)/\\1/\\1/
      </filter>`

`<filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" 
        onMatch="exclude"
        caseSensitive="false">
        http://www.sic.gov.co/drupal//recursos_user/boletin_juridico2016/articulo/consumidor/../.*
      </filter>`

Would you please point me out my error?
thanks a lot
angelo

**Comment by essiembre** [comment]
This look similar to issue #297 which can be fixed by URL normalization.  Here is a repeat of the config you can try to fix this:
```xml
  <urlNormalizer>
    <normalizations>
        removeFragment, lowerCaseSchemeHost, upperCaseEscapeSequence,
        decodeUnreservedCharacters, removeDefaultPort, 
        encodeNonURICharacters, removeDotSegments
    </normalizations>
  </urlNormalizer>
```
Let me know if that works for you.

**Comment by angelo337** [comment]
It seems that Work like a perfect charm
thanks a lot
