### ISSUE TITLE
Rejected_Bad_Status for working online

### ISSUE THREAD

**Issue by khmostafa** [Norconex/collector-http#304]
i am trying to crawl over this site http://kycon.com/gz/website/Index.html, but every time the collector returns this status - Rejected_Bad_Status - for some online links, i took a sample of rejected online and found it working, ex. 
Need to know why, what is this status mean and what is the best solution for it ?
May also you suggest me the best configuration for this site, to learn from it.
Many thanks for your time.

**Comment by essiembre** [comment]
Chances are the returned HTTP response code is not valid (e.g. other than 200).  Do you have a few URLs examples that have a bad status?  

If you want to find out more about rejections, you can change the log level to DEBUG in the ``log4j.properties`` file found in the installation directory.

For instance, you can change this line:
```
log4j.logger.CrawlerEvent.REJECTED_BAD_STATUS=DEBUG
```

**Comment by khmostafa** [comment]
Done, here is what i get in log file:
Link Locator Crawler: 2016-10-07 22:24:09 INFO -       REJECTED_BAD_STATUS: http://anacapa.kycon.com/WebScript.nsf/partSearchDXLxsltNF?OpenAgent&xslF=WebPartSrchCerts3d1.xsl&Start=1&Count=10&Keyfield=part_id&Query=JSX-1035 (Subject: HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])

Why statusCode=400 although when open on browser no problem? 
Thank you for time.

**Comment by essiembre** [comment]
This is a bug within the ``norconex-commons-lang`` library.  URLs with query string having parameters with no equal sign saw those parameters removed ("OpenAgent" in your case).  That library has been fixed and you can download the latest version [here](https://www.norconex.com/product/commons-lang/download.html).  Locate the ``norconex-commons-lang-1.12.2.jar`` in the lib folder in the zip and replace the older version found under the ``lib`` folder of your HTTP collector install with this new one.

Alternatively, a new [snapshot release](https://www.norconex.com/collectors/collector-http/download) of HTTP Collector was just made, which includes that updated library dependency.

Please confirm.

**Comment by khmostafa** [comment]
Really fixed no rejected status found, 
Many thanks for your time and for your great support.

**Comment by essiembre** [comment]
You are welcome.
