### ISSUE TITLE
Stopping non-running job results in NullPointerException

### ISSUE THREAD

**Issue by liar666** [Norconex/collector-http#309]
I just (stupidly) tried to stop a crawler that is not running. This resulted in a NullPointerException:

$ ./collector-http.sh -a stop -c crawlers/mynonrunningcrawler/crawler.xml
Details of the error has been stored at: xxx
$ cat xxx
java.lang.NullPointerException
        at com.norconex.collector.core.AbstractCollector.stop(AbstractCollector.java:144)
        at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:84)
        at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:75)

**Comment by essiembre** [comment]
The latest [snapshot](https://www.norconex.com/collectors/collector-http/download) has a fix for this.  Thanks for reporting!

Please confirm.

**Comment by liar666** [comment]
Hi,

Sorry, with all the installations I have to manage, one of them got mixed up running old jars. I've updated lib/ to latest snapshot and I can confirm it is now returning an error saying the crawler is not running!

Thanks
