### ISSUE TITLE
Manually filtering of to-be-crawled URLs?

### ISSUE THREAD

**Issue by liar666** [Norconex/collector-http#310]
Hi,

If I pause a crawler, is it possible for me to manually filter the list of to-be-crawled URLs, then resume the crawler?

Indeed, I have a crawler that, after running for days, seems to be stuck in an infinite loop, because the crawled site appends & shuffles attributes in the URL.  For instance, crawling the URL:
http://xxx/plop?facet-discipline=%22Biomedical%22
would generate to-be-crawled-URLs:
http://xxx/plop?facet-discipline=%22Biomedical+Material%22
Which, in turns, will generate:
http://xxx/plop?facet-discipline=%22Material+Biomedical+Sciences%22
Attributes gets appended even if they are already there and since they are shuffled, millions of useless URLs get inserted in the to-be-crawled list.

1. I do not want to restart the whole crawling process, since a large part has already been done and I do not want to overload neither the crawled website, nor my servers.
2. I've tried to pause the crawler, add a RegexReferenceFilter in the config file and resume the crawler, but it did not work (the crawler still _extacts_ bad URLs from the bad pages, even if it does not run the taggers on them)...
3. I've tried to pause again the crawler and add also an extractor that filters the URLs extracted by the GenericLinkExtractor, but it did not work...

Is there a solution to such a problem?

**Comment by essiembre** [comment]
The crawler will queue URLs extracted from pages before they are actually crawled.  The regex reference filter takes place before queuing happens (i.e., they are not queued if they are rejected).   Unfortunately in your case, what is in your queue will need to be processed.  

On the other hand, your reference filter should make sure no more of those URLs get added to the queue for processing.  In other words, once those in the queue are processed, that should be it and you should get out of the infinite loop.  

If you want to make sure entries in the queue are not committed, you can also filter them at the importer level using a [RegexMetadataFilter](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/filter/impl/RegexMetadataFilter.html) on ``document.reference`` (make sure this is in addition to the regex reference filter).

**Comment by liar666** [comment]
OK I'll do as you suggest, but what I don't understand is that, in my step 2., I've added an Extractor which:
- accept() returns reference.matches("^((?!facet-discipline=).)*$") , that is to say only URLs that DO NOT match "facet-discipline="
- extractLinks() links using GenericLinkExtractor.extractLinks(), then removes all the links which toString().matches("^.*facet-discipline=.*$"), that is to say all the URLs that MATCH "facet-discipline="

But still, in the logs, I see many lines reading:
MYEXTRACTOR: accept=false for: http://xxx&facet-discipline=xxx
INFO  [CrawlerEventManager]            URLS_EXTRACTED: http://xxx&facet-discipline=xxx

From these logs, it seems to me:
1. that my extractor is clearly in use
2. that my extractor returns accept=false for the given reference
3. still, the crawler extracts URLs from the references

Where could I be doing a mistake?

**Comment by essiembre** [comment]
URLS_EXTRACTED only indicates it is done with URL extraction stage for that URL.  You should always get it even if no URLs were extracted.  If your extractor returns false to the accept() method, then none would have been extracted by it since its ``extracLinks`` method will not even be invoked.

So your extractor is likely working as you expect.  Do you have evidence of the contrary by what is being committed?

You can use the importer [DebugTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DebugTagger.html) as the first thing in your pre parse handlers to see if anything was extracted for a document. Look for the value of ``collector.referenced-urls``.  There should be none (unless you have more than one extractor defined?).

**Comment by liar666** [comment]
OK thanks for the information and the tip, I'll try that.
