### ISSUE TITLE
[GenericURLNormalizer] Special case of jsessionId

### ISSUE THREAD

**Issue by sylvainroussy** [Norconex/collector-http#311]
Hi!
In some pages, I found an url with the following format:
http://myurl.com;jsessionid=E460A97852FA769CD9AD387095C680A9.tpdila09v_2?p=v

If I remove the jsessionId using the GenericURLNormalizer, the Url takes the form:
http://myurl.com.tpdila09v_2?p=v

Then the document is REJECTED_NOT_FOUND, and unfotunatly that's right.

Is there a smart way to solves this issue ? and to normalize this url to:
http://myurl.com?p=v

Thanks,
Sylvain

**Comment by essiembre** [comment]
The pattern for recognizing the session ID did not account for a possible dot followed by word characters.  

A snapshot release of [norconex-commons-lang](https://oss.sonatype.org/content/repositories/snapshots/com/norconex/commons/norconex-commons-lang/1.12.3-SNAPSHOT/norconex-commons-lang-1.12.3-20161114.182417-1.jar) was just made with a fix.  Please download it, replacing the same JAR with an older version with it. 

Please confirm.

**Comment by sylvainroussy** [comment]
Perfect! Thanks, I'm closing it.

**Comment by essiembre** [comment]
A stable release of norconex-commons-lang was made and it has been included in the latest [snapshot release](https://www.norconex.com/collectors/collector-http/download) of HTTP Collector.
