### ISSUE TITLE
[GenericLinkExtractor] RSS - Links with CDATA are not extracted

### ISSUE THREAD

**Issue by sylvainroussy** [Norconex/collector-http#319]
Hi, 

I would to parse a RSS stream (https://medlineplus.gov/feeds/news_en.xml) but the Url values of `link` tags are enclosed in `CDATA` and it seems they're ignored by the *GenericLinkExtractor*.

Is there a way to catch them ?

Thanks.
Sylvain

Edit: somme corrections

**Comment by essiembre** [comment]
Right now, this would be possible by writing your own [ILinkExtractor](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/ILinkExtractor.html).

The default link extractor is [GenericLinkExtractor](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/impl/GenericLinkExtractor.html) and is geared towards HTML pages.  There is a feature request (#236) to add the ability to use regex to extract links using custom patterns but that's not there yet.

To keep the generic link extractor and add yours for RSS feeds via XML config, you can do it like this:
```xml
    <linkExtractors>
        <extractor class="com.norconex.collector.http.url.impl.GenericLinkExtractor"/>
        <extractor class="your.custom.Extractor"/>
    </linkExtractors>
```

**Comment by sylvainroussy** [comment]
Ok, thank you.

**Comment by essiembre** [comment]
FYI, the [latest snapshot](https://www.norconex.com/collectors/collector-http/download) release has a new [XMLFeedLinkExtractor](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/impl/XMLFeedLinkExtractor.html) you can use.
