### ISSUE TITLE
Crawling Dynamic Content on 2.7.0

### ISSUE THREAD

**Issue by nemojjh** [Norconex/collector-http#320]
In these days, many websites are using AJAX.

So some contents is revealed after java script executed.

I've realized that norconex of 2.7.0 can crawl some content made by javascript.

Is it possible to crawl 'some reply content' loaded by java script(AJAX)?

if possible.. is there some restriction on performance?

I'm trying to figure out it by test. But for clearly.

Thank you :)

Best Regards,

**Comment by essiembre** [comment]
You have to use [PhantomJSDocumentFetcher](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/PhantomJSDocumentFetcher.html).

If the replies you want are automatically generated when the page loads, they should be picked up.  If it takes a while for them to get loaded, make sure you give it sufficient time by setting ``<renderWaitTime>`` to a high enough value.

Performance will vary.  Just know that it launches a new instance of PhantomJS each time so it is definitely less efficient and taking more system resources.  You will have to experiment with the render wait time, the crawler "delay" setting, and the crawler's number of threads to get something that works fast enough for you.
