### ISSUE TITLE
Help! REJECTED_REDIRECTED

### ISSUE THREAD

**Issue by ryangabbbriel** [Norconex/collector-http#324]
I cant crawl the site, it always display REJECTED_REDIRECTED, i dont know why.

![1](https://cloud.githubusercontent.com/assets/10920091/24227783/c3a6f2d2-0faa-11e7-8c6b-2596c95b119c.JPG)
![2](https://cloud.githubusercontent.com/assets/10920091/24227785/c66deb7e-0faa-11e7-8ae1-eb2a026e91ca.JPG)

**Comment by ryangabbbriel** [comment]
And what is the meaning of Authentication Status, Moved Permanently.
![ssssssssssss](https://cloud.githubusercontent.com/assets/10920091/24132008/1cfcd470-0e2d-11e7-8b72-c2cdb9cae39a.JPG)

**Comment by essiembre** [comment]
``REJECT_REDIRECTED`` means the crawler encountered an HTTP redirect.  The URL is then discarded and the target URL will be crawled instead.

The same thing is happening with the authentication you are trying to perform.  The page holding the form redirects to another page.

See when you try in your browser which page it redirects to, and you can try to crawl that page instead.   If you see no redirect when trying in a browser, it may be that the server has rules in place that redirects for certain clients/IP only.   Make sure you set the user-agent properly, this sometimes makes a difference.

**Comment by ryangabbbriel** [comment]
Is there a way to crawl the site successfully?

**Comment by essiembre** [comment]
I see some ``DOCUMENT_COMMITED_ADD`` entries in your log so it appears to be crawling successfully.  Are redirected URLs being crawled with the URL they point to?  Do you have pages that are not getting crawled?   If so, please identify which ones with a config sample so we can reproduce.  Attaching your log can also help.

**Comment by ryangabbbriel** [comment]
I tried the URL in my browser and there is no redirecting happens but when i crawl the url it displays Rejected_redirected. Here's my logs.

![asdasdasddd](https://cloud.githubusercontent.com/assets/10920091/24277652/8bb1544c-1079-11e7-99a4-e21aed3864e3.JPG)

**Comment by essiembre** [comment]
Without the ability to reproduce, it is difficult to troubleshoot.  

I recommend you change the log level to DEBUG in the log4j.properties file to get more details.  Especially the line that references ``REJECTED_REDIRECTED``. That should tell you what are the target URLs of redirects.

You can also try to get a listing of HTTP requests/response including HTTP headers from your browser (there are plugins to help you do that).  Your authentication mechanism maybe too complex and use Ajax or something else to authenticate, too fancy for the generic form-based solution offered by the collector.  A custom authentication solution may be required.
