### ISSUE TITLE
crawlerDefaults.startURLs.stayOnDomain ignored

### ISSUE THREAD

**Issue by aleha84** [Norconex/collector-http#326]
Using HTTP Collector 2.6.2 + Elasticsearch Committer 3.0.0-SNAPSHOT	

if crawlerDefaults has startURLs with stayOnDomain="true" it completely ignored, and crawler begins to process all other domains founded on page (twitter, facebook and others). i've detected it in crawler logs and in Elastic indexes. 

If i remove this property from crawlerDefaults and insert it directly into crawler, then everithing is ok as expected.

**Comment by essiembre** [comment]
This is is now fixed in the latest [snapshot](http://www.norconex.com/collectors/collector-http/download) release.  Please confirm.

**Comment by aleha84** [comment]
Confirmed.
