### ISSUE TITLE
Self-Documented Configuration Reference xml delay class wrong

### ISSUE THREAD

**Issue by aleha84** [Norconex/collector-http#327]
On page Norconex HTTP Collector Configuration https://www.norconex.com/collectors/collector-http/configuration link for self-documented config https://www.norconex.com/collectors/collector-http/latest/examples/collector-http-config-reference.xml got delay section:
```xml
<delay default="1000" ignoreRobotsCrawlDelay="true"
           class="$http.delay.impl.DefaultDelayResolver">
          <schedule dayOfWeek="from Monday to Friday" 
                    time="from 8:00 to 16:30">10000</schedule>
    </delay>
```
Provided here class value is wrong - $http.delay.impl.DefaultDelayResolver and crawler totally ignores all other attributes value and procceed with default values.

**Comment by essiembre** [comment]
This was an error in the documentation.  The actual name is [GenericDelayResolver](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/delay/impl/GenericDelayResolver.html).

I have updated the ``collector-http-config-reference.xml `` file.

Thanks for reporting!
