### ISSUE TITLE
merging absolute links

### ISSUE THREAD

**Issue by aleha84** [Norconex/collector-http#332]
Found in logs entries like this: `REJECTED_FILTER: http://mysite.comhttp://forum.mysite.com/ (No "include" reference filters matched.)` and `REJECTED_FILTER: http://mysite.comhttp://www.mysite.com/s1876 (No "include" reference filters matched.)`

Checked markup of pages which were used to collect links: url given as absolute. 

`<div class="item"><a href="http://forum.mysite.com/">Forum</a></div>`
`<div class="item"><a href="http://www.mysite.com/s1876">Some entry</a></div>`

other links on page are relative. 
`<div class="item"><a href="/s1918">Some other entry</a></div>`

**Comment by essiembre** [comment]
Can you share your config to reproduce?

**Comment by aleha84** [comment]
Can i do it somekind private here? Or send it via email?

**Comment by essiembre** [comment]
You can find my email in my github profile.  I will respond here when I have a chance.  Please reference this ticket number. :-)

**Comment by essiembre** [comment]
I found the issue and it is with the site you are crawling.   You have a few pages with bad URLs in them.  For example, check the source of (replacing "----"): http://fs.----.com/files/11480

You will find:

<div class="item"><a href="http://----.comhttp://forum.----.com/">Форум</a></div>

**Comment by aleha84** [comment]
thanx  for a founded bug on my site.
