### ISSUE TITLE
crawlerDefaults.importer.preParseHandlers ignored 

### ISSUE THREAD

**Issue by aleha84** [Norconex/collector-http#333]
Same as https://github.com/Norconex/collector-http/issues/326
But at this time for importer section. I believe that this is relevant both for preParseHandlers and postParseHandlers or for importer entirely.

Putting importer section to crawler directly solwing the problem.

**Comment by essiembre** [comment]
Can you share your config?  This may be working as expected.  When you overwrite a config block for a crawler, the whole block (level tags in the crawler section) is overwritten.    If you want more flexibility in having reusable portions of configuration, I recommend you create configuration fragments that you can dynamically include wherever you need in your config, using the ``#parse`` or ``#include`` directives.  Just like the "complex-config.xml" example demonstrates in the HTTP Collector zip.

**Comment by essiembre** [comment]
Closing for lack of feedback.  Please re-open if needed.
