### ISSUE TITLE
documentFetcher PhantomJSDocumentFetcher regexp pattern for reference

### ISSUE THREAD

**Issue by aleha84** [Norconex/collector-http#334]
Part of my site pages using angularjs to render content. And PhantomJSDocumentFetcher works as expected. Great. But i don't need it to use for all pages. It's additional renderWaitTime takes time, and indexing becomes to slow.  So i need ability to pass regex pattarn to check currently processed url. If it matchs then use PhantomJSDocumentFetcher , if not then use default GenericDocumentFetcher. it will be great feature.

**Comment by essiembre** [comment]
You can already do so based on URL extension, if there is any.  I am marking this as a feature request to be able to use regular expression on the entire URL instead (more flexible).

**Comment by aleha84** [comment]
There are no url extensions for these links,  so this can't help. Will wait for more flexibility. Thx.

**Comment by essiembre** [comment]
The latest snapshot now replaces the extensions and content type comma-separated lists with reference (URL) and content type patterns.   The two new replacement configuration tags for ``PhantomJSDocumentFetcher`` are:

```xml
     <referencePattern>
          (Regular expression matching URLs for which to use the
           PhantomJS browser. Non-matching URLs will fallback
           to using GenericDocumentFetcher.)
      </referencePattern>      
      <contentTypePattern>
          (Regular expression matching content types for which to use 
           the PhantomJS browser. Non-matching content types will use 
           the GenericDocumentFetcher.)
      </contentTypePattern>   
```

The javadoc has been updated as well.

**Comment by aleha84** [comment]
documentFetcher stops worked as before. It is just returning first state of the page with angularjs placeholders. 

documentFetcher without referencePattern, to match all.
```
<documentFetcher class="com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher">
			<exePath>C:\norconex\phantomjs\bin\phantomjs.exe</exePath>
			<renderWaitTime>
				10000
			</renderWaitTime>
		</documentFetcher>  
```
in task managers i can see phantomjs.exe running. But that is all. Sadly, deleted yesterday's version and cant check for differences.

**Comment by essiembre** [comment]
So your problem is that you are not getting your content, that phantomjs.exe never returns, or both?  Do you have a URL that can be used to reproduce?

**Comment by aleha84** [comment]
Sended links to your email. I thing that the problem is that the result from phantomjs is not returned.

**Comment by essiembre** [comment]
There was a minor issue when the content type returned by PhantomJS also contained a charset.  I fixed this in a new snapshot.  I tested your page with it and it was processed properly.  Can you try again?

**Comment by aleha84** [comment]
Can do it monday only.

**Comment by aleha84** [comment]
PhantomJS works fine. Confirming fix. 
referencePattern - also woks as expected.

**Comment by essiembre** [comment]
Great, thanks for confirming.
