### ISSUE TITLE
Can i get the whole javascript code by using Norconex?

### ISSUE THREAD

**Issue by ryangabbbriel** [Norconex/collector-http#339]

**Comment by essiembre** [comment]
The answer is "probably". :-) I would need to understand better what you want to do first.  Can you give examples?

By default URLs from ``<script src="url.js">`` are now followed.  If you simply want to follow them so they are crawled, you can ask the [GenericLinkExtractor](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/impl/GenericLinkExtractor.html) to do so, like this:

```xml
<linkExtractors>
  <extractor class="com.norconex.collector.http.url.impl.GenericLinkExtractor">
      <tags>
          <tag name="a" attribute="href" />
          <tag name="frame" attribute="src" />
          <tag name="iframe" attribute="src" />
          <tag name="img" attribute="src" />
          <tag name="meta" attribute="http-equiv" />
          <tag name="script" attribute="src" />  <!-- Adding it here --->
      </tags>
  </extractor>
</linkExtractors>
```

Is this what you want?

**Comment by ryangabbbriel** [comment]
Where can i find the extracted urls? Is it in the meta file?

**Comment by essiembre** [comment]
They can be found under this metadata field: ``collector.referenced-urls``.

**Comment by ryangabbbriel** [comment]
How can i get the code inside the JS file? For example, <script src="url.js">, how can i get all the javascript codes inside the url.js? is it possible?

**Comment by ryangabbbriel** [comment]
I already get all the codes inside the url.js by using TextPatternTagger. Thanks :)

**Comment by ryangabbbriel** [comment]
I have another question, how can i remove all \r, \n, \t inside the javascript code field?

**Comment by ryangabbbriel** [comment]
Example: javascriptCode = var ProjectCreator \= (function() {\r\n\tfunction ProjectCreator(elem, options) {\r\n\t\tthis.elem \= {\r\n\t\t\tambAmount\:\t\t\t\t$(elem).find("\#amb-amount")

**Comment by essiembre** [comment]
Assuming you have the javascript as part of the body of a document (as opposed to being in a metadata), you can use [ReduceConsecutivesTransformer](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/impl/ReduceConsecutivesTransformer.html) or [ReplaceTransformer](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/impl/ReplaceTransformer.html) with proper regex.  

If you have it in a meta data field instead, you can use regex to do so with [ReplaceTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ReplaceTagger.html)

Please create new issues for new questions.
