### ISSUE TITLE
How can i get the values of html tags?

### ISSUE THREAD

**Issue by ryangabbbriel** [Norconex/collector-http#340]

**Comment by ryangabbbriel** [comment]
And How can i change the log level from info to debug? Thanks

**Comment by essiembre** [comment]
HTML ``meta`` tag values are extracted automatically.  For extracting values from other HTML tags, there are a few options, such as [TextBetweenTagger](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/TextBetweenTagger.html), [TextPatternTagger](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/TextPatternTagger.html), or [DOMTagger](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DOMTagger.html).  They should be used as pre-parse handlers, on HTML files only.

You can change the log level in the ``log4j.properties`` file found at the root of your unzipped installation.
