### ISSUE TITLE
incremental crawling and starting URLs question

### ISSUE THREAD

**Issue by danizen** [Norconex/collector-http#341]
How can I implement an incremental crawler using Norconex HTTP Collector?   I implemented a simple crawler with a max # of documents, and when I ran it again, it appeared to start exactly where it left off.  If the crawler reaches max documents when many more are queued, what is the best way to identify what to crawl next time?

I can obtain the starting URLs from a CSV, and obtain the URLs to start with (e.g. those not finished) by implementing a crawl listener that can track this information.   The question is not whether it is possible, but what is the best way?

Is there a way to obtain the URLs to crawl via a database query?

**Comment by danizen** [comment]
Beginnings of the project are present at https://github.com/danizen/trynorconex.   For more context, https://medlineplus.gov/ has a large number of "approved organizations".  We need to crawl these periodically to identify new potential articles (monitoring).  We also need to crawl links already present in MedlinePlus for review (topic review).  As architect, I am helping the team out.

**Comment by essiembre** [comment]
If you want to recrawl the same pages and pick-up changes each time, maybe max docs is not what you are after.   I recommend you do not limit the maximum documents and you restrict what you are crawling some other way, mainly using URL patterns.

For instance, to crawl your organizations, I would have this page as a start URL:
https://medlineplus.gov/organizations/all_organizations.html and use ``<maxDepth>`` to crawl X level deep in each sites you want.

I would add a mix of reference filters (taking place before download and links extraction), and document filter (taking place after document download and URL extraction).

The problem I see is if you want more than 1 level deep, then you'll have trouble sticking to each organization sites only (as those sites can have external links too).  If that is a concern, then it would be best to create a seed list instead (with ``stayOnDomain`` being true).  

You mention a database query, which suggests you can obtain the org list from its database source.  Unfortunately, there is currently no way to support dynamic seed lists from the crawler config, but you can get there some other ways.  One approach would be to create a separate process that periodically generates a seed file (one URL per line) and reference it in your crawler config like this:

```xml
<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
     <urlsFile>/path/to/generatedSeedFile</urlsFile>
</startURLs>
```

Alternatively, you can create a custom "sitemap.xml" that would be rendered dynamically somewhere on your site and replace ``<urlsFiles>`` with ``<sitemap>``.

Does one of these approaches work for you?

**Comment by danizen** [comment]
Generating a file from the database and feeding it to urlsFile via a variable is quite reasonable.  Also, the maxDocuments limit was dictated because I'm still getting started, and I didn't want it to run too long.

I see the configurable `recrawlableResolver` - does that imply that if I repeat a crawl with the same directories and have such a configuration that the crawler will skip some URLs on a subsequent recrawl?

Related question - is there documentation on the data present in the crawl data store?   I am still using the default mvdata store, but it might be useful to understand what data is present.

**Comment by essiembre** [comment]
RecrawlableResolver is to find out if a document should be recrawled or not based on whatever condition you have.  The GenericRecrawlableResolver does it based on a period of time.  Documents that have been crawled in less than X time ago will be skipped until next recrawl (if enough time has past then).

The crawl store is the crawler inner caching and not meant to be used directly in your own code. The same information is found as document fields sent to your committer (unless you toss them out) so you should be able to get what you need relying on document metadata.

Still, if you want to know, this is currently the list of possible information kept in the crawl store for each documents:
```
reference
parentRootReference
isRootParentReference
state
metaChecksum
contentChecksum
contentType
crawlDate
depth
sitemapLastMod
sitemapChangeFreq
sitemapPriority
originalReference
referrerReference
referrerLinkTag
referrerLinkText
referrerLinkTitle
referencedUrls
```

They are a serialization of [HttpCrawlData](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/data/HttpCrawlData.html)

**Comment by danizen** [comment]
Thanks, Pascal.

I think my questions are answered.   I have to give you a lot of credit for writing this.  Our crawler and index of choice at work is IBM Watson Explorer.   I am no fan.   The problem replacing this with ManifoldCF/Solr er ES or with LucidWorks Fusion is that you are still configuring the crawl through a GUI.   Even my little repository shows that with Norconex, you can configure the crawl via a project checked into git, then can then be subjected to CI/CD to some sense.   This is a big win.

**Comment by essiembre** [comment]
Thank you! We always appreciate good feedback like yours. You may be interested to know the [latest snapshot](https://www.norconex.com/collectors/collector-http/download) now offers a way to obtain URLs dynamically.  If you do not mind a bit of Java coding, you can implement your own [IStartURLsProvider](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/crawler/IStartURLsProvider.html) class and configure it like this:
```xml
<startURLs ...>
    ...
    <provider class="YourProviderClass"/>
</startURLs>
```
The site documentation will be updated soon to reflect this addition.

**Comment by danizen** [comment]
Cool.    I will use that, and if the need arises, I will not hesitate to add an HDFS or WebDav committer to get a more robust pipeline involved.   The life of an architect involves too little coding, and Norconex is shaping up to scratch that itch for the nonce.

**Comment by essiembre** [comment]
Let us know of your progress with creating HDFS/Webdav committers if you end up having time to build them.  They would be nice additions for sure!
