### ISSUE TITLE
Please provide example Camel integration

### ISSUE THREAD

**Issue by danizen** [Norconex/collector-http#342]
It would be very nice to have a Camel integration where an HTTP Collector with config can be the target of a camel route, or the camel message can be the variables for such.

**Comment by essiembre** [comment]
I have not had a change to integrate HTTP Collector with Camel before so I do not have an example to provide.  If you manage to do it and that's something that can easily be added to the project, please share your findings!

**Comment by danizen** [comment]
I'm now out of the Java world for this stuff and using Spotify luigi.   If I were to switch to anything it would probably be Apache/Airbnb Airflow.   So, I'm suggesting this be closed unless someone else also requests it.

**Comment by essiembre** [comment]
As you wish! Thanks for the update.
