### ISSUE TITLE
Question on delay and numThreads

### ISSUE THREAD

**Issue by danizen** [Norconex/collector-http#348]
If I have 5 threads, and a delay of 1 second, is it true that each thread is using a 1 second delay between URLs as suggested by the flow diagram?   

I've seen other crawlers interpreting the politeness factor as per-domain, but with Norconex it might be per-thread or overall.

How does it work with Norconex?

**Comment by essiembre** [comment]
It is configurable. By default the behavior is the more "polite", but you can have the scope to be per domain, or per threads.   See [GenericDelayResolver](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/delay/impl/GenericDelayResolver.html).

**Comment by danizen** [comment]
Wow.   How did I miss that.    BTW, I'm thinking about the differences between Spring and your configurable XML schema.   The way you do it has more strong typing built in because of the XSD validation.   You also keep the older design of interface and factory.   Interesting - I haven't made up my mind which I like more, and it hardly matters - Spring is hard to avoid these days and so must be known.
