### ISSUE TITLE
jef metrics feature request

### ISSUE THREAD

**Issue by danizen** [Norconex/collector-http#349]
Running the JEF Monitor, I can see how many references have been crawled out of all references identified, but I cannot see any metrics on the crawl.   This is completely possible with the JEF API.

Feature request:
* Add a rolling average showing rate of reference resolution over a period to the note, or as properties.
* Add a rolling average showing rate of commits over a period to the note, or as properties.

Question:
* Is it possible through the crawl listener for me to add these myself via Java to the existing job?
* Would it be better (structured) for me to use the JEF API to create a new status for the job, to avoid conflict with the status collection already done by the collector?

**Comment by danizen** [comment]
Withdrawn - it is better to do this based on metrics drawn from crawlstore.   The following gist provides enough to chart out how to do this using PyMongo to access metrics from a Mongo status store, to drive a stacked bar graph based on crawlState - https://gist.github.com/danizen/e9243c699b206a1c41107f7c8392b223

That said, this can be left open if desired by @essiembre , or closed as better done a different way.

**Comment by essiembre** [comment]
Version 3 offers a few ways to help with this request.  In addition to querying the crawl store as you suggested, it is easier to listen for (more) events and act on them. 

Most importantly, you can supply the system property ` -DenableJMX=true` to enable JMX support.  You can then tie the collector with monitoring tools such as Prometheus and you will get time series generated in real-time for you without having to do anything special to the collector.  You can track/monitor all kinds of crawling events that way.

This should address the original request.
