### ISSUE TITLE
Allow collection names to be configurable for MongoCrawlDataStoreFactory

### ISSUE THREAD

**Issue by danizen** [Norconex/collector-http#353]
This would be helpful in my corporate environment.   I have one configured Mongo database for the crawl project.   I can ask for another to preserve data, but this is not ideal.

**Comment by essiembre** [comment]
The latest HTTP snapshot now supports this.  The ``MongoCrawlDataStoreFactory`` now supports these new optional tags:

```xml
      <cachedCollectionName>(Custom "cached" collection name)</cachedCollectionName>
      <referencesCollectionName>(Custom "references" collection name)</referencesCollectionName>
```

Please confirm whether that works for you.

**Comment by danizen** [comment]
I'll try it, but am home sick today.

**Comment by danizen** [comment]
This is not working yet.   I am trying with norconex-collector-core 1.8.3-SNAPSHOT and norconex-collector-http 2.7.2-SNAPSHOT.

Using -k while having the `cachedCollectionName` and `referencesCollectionName` doesn't cause any errors, but it doesn't take either.

**Comment by essiembre** [comment]
This is now fixed.  It was missing some code "wiring".

**Comment by danizen** [comment]
Thanks, Pascal.   This works for me with norconex-collector-core 1.9.0-SNAPSHOT and norconex-collector-http 2.8.0-SNAPSHOT.   I will go back to 1.8.2 and 2.7.2 and wait for any release.

**Comment by essiembre** [comment]
Great, thanks for confirming.
