### ISSUE TITLE
Support additional indexes for the MongoCrawlDataStoreFactory

### ISSUE THREAD

**Issue by danizen** [Norconex/collector-http#354]
Here is the kind of thing I want to be able to do:

```
<addIndex collection="references">{ 'contentType': 1}</addIndex>
```

This is a helpful syntactic sugar sort of feature - adding it after the fact is quite doable.

**Comment by essiembre** [comment]
What is the relation between the extra indexes and crawling?  I mean would those indexes have any use by the crawler or it is just for convenience?

**Comment by danizen** [comment]
This is the process of establishing crawl quality.   Trying to figure out what sort of fish you've bagged.  The kind of thing no doubt your analytics products help with ;)

Another way would be to just index into Elasticsearch the crawling logs - I'm sure there are defined ways to import log4j output.

**Comment by danizen** [comment]
Ten minutes later, the Python has finished anyway:

```python
db.references.create_index([('contentType', pymongo.ASCENDING)], background=True, sparse=True)
db.references.create_index([('crawlStatus', pymongo.ASCENDING)], background=True, sparse=True)
```

**Comment by danizen** [comment]
Feel free to close this unless you think it is helpful enough.

**Comment by essiembre** [comment]
I am not sure I fully get what you are seeking to do, but if I do, maybe a custom implementation of 
[ICrawlerEventListener](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/crawler/event/ICrawlerEventListener.html) would be a better fit?

You can have a look at this implementation as a starting point: 
[URLStatusCrawlerEventListener](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/crawler/event/impl/URLStatusCrawlerEventListener.html).

**Comment by danizen** [comment]
Yes, I was thinking about that in my other comment.   The problem is that architecturally, writing Java to do that sort of thing just doesn't pay.   Things like logstash are just too good at taking files and pumping them to elasticsearch.   So, maybe I'll go that way.

For whatever its worth - if I'm replying at this time on a Friday, I'm pretty stoked on Norconex Collectors.

**Comment by danizen** [comment]
The proof is in the pudding.   This `logstash.conf` is many, many fewer lines of code than doing it as a ICrawlEventListener.  All it needs is the tweek to send it to elastic search.

```ruby
input {
  file {
    path => "${CRAWLER_WORKDIR}/logs/latest/logs/*.log"
    sincedb_path => "${CRAWLER_WORKDIR}/sincedb"
    start_position => "beginning"
    type => "log4j"
  }
}

filter {
  grok {
    match => { "message" => "[^:]+: %{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:loglevel}\s+-\s+%{JAVALOGMESSAGE:content}" }
    remove_field => [ "message" ]
  }
  date {
    match => [ "timestamp", "yyyy-MM-dd HH:mm:ss", "ISO8601" ]
    remove_field => [ "timestamp" ]
  }
}

output {
  stdout { codec => rubydebug }
}
```

**Comment by essiembre** [comment]
Nice! Thanks for sharing.
