### ISSUE TITLE
Question - auto stop on elasticsearch/mongodb health check error

### ISSUE THREAD

**Issue by danizen** [Norconex/collector-http#355]
What would you recommend as far as automatically stopping a crawler based on persistent errors for MongoDB (CrawlDataStoreFactory) or Elasticsearch?

I know I can just write a script that checks these periodically and then runs collector-http ... -a stop, but I'm wondering whether there any knobs/buttons within the framework for this sort of thing.

**Comment by essiembre** [comment]
Good question.  There is not out-of-the-box option to make it stop prematurely given efforts are made to keep it running despite errors (with a focus on document-related errors).   That being said, there are specific areas where exceptions are considered more critical to the stability of the crawling process and will trigger a stop.   If you want to force it yourself, right now one way would be to subclass the MongoCrawlDataSerializer (and factory) and throw runtime exceptions after whatever failing checks you want to make.  This should issue a stop().

**Comment by danizen** [comment]
Good answers/suggestions.  It is unfortunately salient - the ops folks at work updated the wrong elasticsearch cluster at work, and they only touched 2 out of 3 nodes.   With 2 nodes running 5.1 and one running 2.4, it would not come up.

This also reveals another difference between our structured data indices and this crawl's data - the index in elasticsearch has to be treated as ground truth because there is no deterministic method to recreate that index data.   With structured data from RDBMS or XML, it may still take a long time, but the index can be recrated in a deterministic fashion.  So, I have to look at backup strategies for Elasticsearch.

**Comment by essiembre** [comment]
Yeah, backups are always a good idea.  You can use the ``MultiCommitter`` to backup the content to a DB at the same time as elasticsearch, or you can use elasticsearch own cluster snapshot options.
