### ISSUE TITLE
Can I crawl a page w/ a list of dynamically-generated javascript links?

### ISSUE THREAD

**Issue by dkh7m** [Norconex/collector-http#357]
I have a page that uses javascript to generate a long list of links to procedure pages that I want to index and add to Solr. When I run the collector on it, it only finds the four or five "real" links in the header of the page. How would I go about setting up a crawler to get just the list of js-generated links (if possible)?

**Comment by essiembre** [comment]
To crawl javascript-generated pages/links, your best bet is a Javascript interpreter that supports the browser DOM.  Luckily, the HTTP Collector integrates with [PhantomJS](http://phantomjs.org/).   Install PhantomJS and replace the HTTP Collector default document fetcher with the [PhantomJSDocumentFetcher](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/PhantomJSDocumentFetcher.html).

**Comment by dkh7m** [comment]
Thanks! Looks like this will work. But I need a bit of guidance on the setup. Here's what I have so far:

`		  <documentFetcher  
			  class="com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher"
			  detectContentType="true" detectCharset="true">
			  <exePath>C:\phantomjs-2.1.1-windows\bin\phantomjs.exe</exePath>
			  <renderWaitTime>
				  3000
			  </renderWaitTime>     
			  <referencePattern></referencePattern>  
<contentTypePattern></contentTypePattern>
			  <validStatusCodes>200</validStatusCodes>
			  <notFoundStatusCodes>404</notFoundStatusCodes>
		  </documentFetcher>`

Not clear on what to do with the referencePattern. The links on the page I'm trying to crawl all refer to "javascript:;". The actual pages they link to, however, are formatted as "http://procedures.lww.com/lnp/view.do?pId=152197" (with different pId values, of course). Which pattern should I use for the reference.

Also not sure what to do with contentTypePattern. The pages I'm trying to crawl are all rendered as HTML.

**Comment by essiembre** [comment]
Using PhantomJS to fetch non-HTML pages may be overkill and/or may not always give expected results.  The ``referencePattern`` and ``contentTypePattern`` options are there to tell ``PhantomJSDocumentFetcher`` when to use PhantomJS, and fall back to the ``GenericDocumentFetcher`` for non matching URLs/content types.  If you are only crawling HTML pages (rejecting everything else) and you want them all to be processed by PhantomJS, you can ignore these tags.

You should not have to do anything special for link extraction.  Phantom JS will load and execute Javascript and links will be extracted from the resulting DOM.   If URLs are constructed only with certain user action (e.g. click) then it will likely won't work unless you get yourself deep into mimicking user actions using PhantomJS scripting.  Test it first with the minimum settings to see how it behaves.

FYI, when you paste XML or other code, I recommend you use GitHub Markdown syntax for it so what you paste is easier to read (I modified your post so it formats better).

**Comment by dkh7m** [comment]
I will give that a try. Also, I usually use the "Insert Code" button, but it doesn't always behave the way I expect it to. I see you're using a different method for marking down the code in my comment above, so I will try that next time. Thanks!

**Comment by akshaybijawe** [comment]
[config.txt](https://github.com/Norconex/collector-http/files/1229003/config.txt)
Hi Pascal, I'm trying to crawl a [webpage ](https://clinicaltrials.gov/ct2/results?cond=Rheumatoid+Arthritis#wrapper) that has links in it which are generated dynamically using JavaScript. I've followed the above instructions but still the crawler wouldn't extract the links from that page. I have attached my config.xml file. Thanks a lot.

**Comment by essiembre** [comment]
@akshaybijawe, did you check the logs?  Trying it I get:
```
INFO  [CrawlerEventManager] REJECTED_ROBOTS_META_NOINDEX: https://clinicaltrials.gov/ct2/results?cond=Rheumatoid+Arthritis
```

If you check the page source, you will find this:
```html
 <meta name="robots" content="noindex,nofollow"/>
```

So the author of that page added robot rules to prevent you from indexing it or following its links.

If the site owner gave you permission to bypass robot rules for what you are doing, you can do so by adding the following to your crawler config:
```xml
      <robotsTxt ignore="true" />
      <robotsMeta ignore="true" />
      <sitemapResolverFactory ignore="true" />
```
The third one is to disable looking for a sitemap (since none appear to be present for that site).

Also, looking at the page source, it seems links are not generated using JavaScript so maybe you do not have to use PhantomJS.

**Comment by akshaybijawe** [comment]
That makes sense. Thanks a lot, Pascal.

**Comment by essiembre** [comment]
You are welcome.
