### ISSUE TITLE
Velocity setting entirely from command-line

### ISSUE THREAD

**Issue by danizen** [Norconex/collector-http#359]
I think it would be good in the collectors to support a velocity setting entirely at the command-line, so that someone starting it up can override what's in the variables files.

**Comment by essiembre** [comment]
This feature is now supported in version 3.  You can pass JVM system properties when launching the application, like this:

```
-Dsome.variable=Example
```

You can rely on environment variables as well.  

Variable naming resolution is quite flexible.  As an example, a variable `${hostName}` can be defined in any of the following ways when using system property/environment variables:

```
    hostName
    hostname
    HOST_NAME
    Host-Name
    host.name
```
