### ISSUE TITLE
norconex connector issue

### ISSUE THREAD

**Issue by Navaminavu** [Norconex/collector-http#365]
I am trying to set up a norconex connector for a site
and my issue is that the URLs under the div portion is not getting crawled.

Attaching the configuration code here:-

```xml
<httpcollector id="HTTPCollectorLmr">

	#set($http = "com.norconex.collector.http")
	#set($core = "com.norconex.collector.core")
	#set($urlNormalizer   = "${http}.url.impl.GenericURLNormalizer")
	#set($filterExtension = "${core}.filter.impl.ExtensionReferenceFilter")
	#set($filterRegexRef  = "${core}.filter.impl.RegexReferenceFilter")
	#set($http
	= "com.norconex.collector.http")
	#set($committer =
	"com.norconex.committer")
	#set($urlNormalizer   = "${http}.url.impl.GenericURLNormalizer")
	#set($filterExtension = "${core}.filter.impl.ExtensionReferenceFilter")
	<!--#set($sitemapFactory    = "${http}.sitemap.impl.StandardSitemapResolverFactory")-->
	
    <crawlerDefaults>
        <numThreads>2</numThreads>
        <orphansStrategy>DELETE</orphansStrategy>
        <delay default="500" />
        <robotsTxt ignore="true"
				class="com.norconex.collector.http.robot.impl.StandardRobotsTxtProvider" />
        <referenceFilters>
           <filter class="$filterExtension" onMatch="exclude">jpg,gif,png,ico,css,js
			</filter> 
			<filter
					class="com.norconex.collector.core.filter.impl.RegexReferenceFilter"
					onMatch="include">
                https://lmr-doxygen.rnd.ki.sw.ericsson.se/l2tm/.*
             </filter>
        </referenceFilters>
    </crawlerDefaults>
    <crawlers>
		<crawler id="lmrdoxygen">
			<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
				<url>
					https://lmr-doxygen.rnd.ki.sw.ericsson.se/l2tm/.*
				</url>
			</startURLs>
			<canonicalLinkDetector class="com.norconex.collector.http.url.impl.GenericCanonicalLinkDetector" ignore="true"></canonicalLinkDetector>
			<workDir>./output/lmr</workDir>
			<maxDepth>2</maxDepth>
			<maxDocuments>-1</maxDocuments>
			<progressDir>./output/lmr/progress</progressDir>
			<logsDir>./output/lmr/logs</logsDir>
			<importer>
			       <preParseHandlers>
                                  <!--<filter class="com.norconex.importer.handler.filter.impl.RegexMetadataFilter"
                                                onMatch="include" field="document.reference" >
                                                         https://lmr-doxygen.rnd.ki.sw.ericsson.se/l2tm/.*
                                   </filter>-->

			       	  <transformer
			       		class="com.norconex.importer.handler.transformer.impl.StripBetweenTransformer"
			       		inclusive="true" sourceCharset="ISO-8859-1" caseSensitive="false" maxReadSize="1000000">
			       		<stripBetween>
			       			<start>&lt;div id="header"&gt;</start>
			       			<end>&lt;div&gt;</end>
			       		</stripBetween>
			       		 <stripBetween>
			       			<start>&lt;divid="subcontent"&gt;</start>		       														
							<end>&lt;div&gt;</end>
			       		</stripBetween>
				    </transformer>
				</preParseHandlers>
			<!--	<postParseHandlers>
					<tagger class="com.norconex.importer.handler.tagger.impl.KeepOnlyTagger">
						<fields>title,document.reference
						</fields>
					</tagger>
					<transformer
						class="com.norconex.importer.handler.transformer.impl.ReduceConsecutivesTransformer">
						<reduce>\s</reduce>
						<reduce>\n</reduce>
						<reduce>\s\n</reduce>
					</transformer>				  
				</postParseHandlers>-->
			</importer>
			<committer class="com.norconex.committer.i3.I3Committer">
				<i3Params>
					<param name="indexURL">http://esesslx0790.ss.sw.ericsson.se:8080/rest/xtendedintranet/documents.json
					</param>
					<param name="Content-type">application/json;charset=utf-8</param>
					<param name="custom_id">false</param>
					<param name="id_prefix">dummy</param>
					<param name="id_field_name">dummy</param>
				</i3Params>
				<commitBatchSize>10</commitBatchSize>
				<queueDir>./queue/lmr/</queueDir>
				<queueSize>100</queueSize>
				<maxRetries>2</maxRetries>
				<maxRetryWait>100</maxRetryWait>
			</committer>
		</crawler>
    </crawlers>
</httpcollector>
```
Sorry that I cant find the code of the HTML page.
Attaching the screenshot of the page and highlighted portion is the part where I should crawl document.
![image](https://user-images.githubusercontent.com/29800957/28102781-2dadf810-66ef-11e7-98a2-b714d482c23c.png)
Please find below the HTML part which Iam trying to crawl.Here you can find a range of .html files which Iam trying to crawl but not ableto crawl it
[div.txt](https://github.com/Norconex/collector-http/files/1140949/div.txt)

**Comment by essiembre** [comment]
On first look of your snippet, I find nothing wrong.  Do you have any indications in the logs whether those URLs are rejected?

Looking at your picture, it suggests the portion you are interested in is a frame.  If so, it is considered a separate page and it should normally be crawled if the frame has a valid ``src`` value.  Does it?   If the frame is loaded via JavaScript you will need the ability to interpret JavaScript and you can try using [PhantomJSDocumentFetcher](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/PhantomJSDocumentFetcher.html).

**Comment by Navaminavu** [comment]
Hi pascal, the frame I gave above is loaded via Javascript..
So we have managed to crawl the data under jJavascript..but what we need is that there are some html pages under <a href>   tags inside the java script which we need to crawl.so how can e do that can you help me on this?
Please find below the current config:- 
<?xml version="1.0" encoding="UTF-8"?>
<httpcollector id="HTTPCollectorlmr">

	#set($http = "com.norconex.collector.http")
	#set($core = "com.norconex.collector.core")
	#set($urlNormalizer   = "${http}.url.impl.GenericURLNormalizer")
	#set($filterExtension = "${core}.filter.impl.ExtensionReferenceFilter")
	#set($filterRegexRef  = "${core}.filter.impl.RegexReferenceFilter")
	#set($http
	= "com.norconex.collector.http")
	#set($committer =
	"com.norconex.committer")
	#set($urlNormalizer   = "${http}.url.impl.GenericURLNormalizer")
	#set($filterExtension = "${core}.filter.impl.ExtensionReferenceFilter")
	#set($sitemapFactory    = "${http}.sitemap.impl.StandardSitemapResolverFactory")

    <crawlerDefaults>
        <numThreads>2</numThreads>
        <orphansStrategy>DELETE</orphansStrategy>
        <delay default="500" />
        <robotsTxt ignore="false"
				class="com.norconex.collector.http.robot.impl.StandardRobotsTxtProvider" />
         <referenceFilters>
            <filter class="$filterExtension" onMatch="exclude">jpg,gif,png,ico,css
			</filter>
        </referenceFilters>
    </crawlerDefaults>
    <crawlers>
        <crawler id="lmr">
         <sitemapResolverFactory ignore="true" lenient="true" class="com.norconex.collector.http.sitemap.impl.StandardSitemapResolverFactory"/>
			<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
			<url>https://lmr-doxygen.rnd.ki.sw.ericsson.se/l2tm/index.html</url>		
			</startURLs>			
            <canonicalLinkDetector class="com.norconex.collector.http.url.impl.GenericCanonicalLinkDetector" ignore="true"></canonicalLinkDetector>
            
            <workDir>./output/lmr</workDir>
            <maxDepth>2</maxDepth>
            <maxDocuments>-1</maxDocuments>
            
            <progressDir>./output/lmr/progress</progressDir>
            <logsDir>./output/lmr/logs</logsDir>
			
	
			
			 <linkExtractors>	
				<extractor class="com.norconex.collector.http.url.impl.GenericLinkExtractor">
							
					<tags>
						<tag name="a" attribute="href" />
						<tag name="script" attribute="src" />
					</tags>
				</extractor>				
			</linkExtractors>
			
			 <importer>
				<postParseHandlers>
					<transformer
						class="com.norconex.importer.handler.transformer.impl.ReduceConsecutivesTransformer">
						<reduce>\s</reduce>
						<reduce>\n</reduce>
						<reduce>\s\n</reduce>
					</transformer>
				</postParseHandlers>
			</importer>
           
            
			<committer class="com.norconex.committer.core.impl.FileSystemCommitter">
			<directory>./output/lmr/crawledFiles</directory>
			</committer>
			
        </crawler>
    </crawlers>
</httpcollector>

**Comment by Navaminavu** [comment]
Pascal, can you look at the above comment?

**Comment by essiembre** [comment]
Have you tried the ``PhantomJSDocumentFetcher`` suggestion mentioned earlier?  Do you get further?

Otherwise, you can create your own link extractor or have a look at existing ones that may help you, like [RegexLinkExtractor](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/impl/RegexLinkExtractor.html)

**Comment by Navaminavu** [comment]
[lmr.zip](https://github.com/Norconex/collector-http/files/1158958/lmr.zip)
Hi Pascal,
I did try the Phantom JS thing but along with one/2 HTML files out of 10/12 we requires,lot of JS content is also coming.

The config has been modified me as below:- 
<?xml version="1.0" encoding="UTF-8"?>
<httpcollector id="HTTPCollectorlmr">

	#set($http = "com.norconex.collector.http")
	#set($core = "com.norconex.collector.core")
	#set($urlNormalizer   = "${http}.url.impl.GenericURLNormalizer")
	#set($filterExtension = "${core}.filter.impl.ExtensionReferenceFilter")
	#set($filterRegexRef  = "${core}.filter.impl.RegexReferenceFilter")
	#set($http
	= "com.norconex.collector.http")
	#set($committer =
	"com.norconex.committer")
	#set($urlNormalizer   = "${http}.url.impl.GenericURLNormalizer")
	#set($filterExtension = "${core}.filter.impl.ExtensionReferenceFilter")
	#set($sitemapFactory    = "${http}.sitemap.impl.StandardSitemapResolverFactory")

    <crawlerDefaults>
        <numThreads>2</numThreads>
        <orphansStrategy>DELETE</orphansStrategy>
        <delay default="500" />
        <robotsTxt ignore="false"
				class="com.norconex.collector.http.robot.impl.StandardRobotsTxtProvider" />
         <referenceFilters>
            <filter class="$filterExtension" onMatch="exclude">jpg,gif,png,ico,css,js
			</filter>
        </referenceFilters>
    </crawlerDefaults>
    <crawlers>
        <crawler id="lmr">
         <sitemapResolverFactory ignore="true" lenient="true" class="com.norconex.collector.http.sitemap.impl.StandardSitemapResolverFactory"/>
			<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
			<url>https://lmr-doxygen.rnd.ki.sw.ericsson.se/l2tm/</url>		
			</startURLs>			
            <canonicalLinkDetector class="com.norconex.collector.http.url.impl.GenericCanonicalLinkDetector" ignore="true"></canonicalLinkDetector>
            
            <workDir>./output/lmr</workDir>
            <maxDepth>2</maxDepth>
            <maxDocuments>-1</maxDocuments>
            
            <progressDir>./output/lmr/progress</progressDir>
            <logsDir>./output/lmr/logs</logsDir>
			 <linkExtractors>	
				<extractor class="com.norconex.collector.http.url.impl.GenericLinkExtractor">		
					<tags>
						<tag name="a" attribute="href" />
						<tag name="script" attribute="src" />
					</tags>
				</extractor>				
			</linkExtractors>
			<documentFetcher class="com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher">
				<exePath>C:\Users\enavami\Documents\norconex-collector-http-2.6.2\phantomjs-2.1.1-windows\bin\phantomjs.exe</exePath>
				<renderWaitTime>5000</renderWaitTime>
				<referencePattern>^.*\.html$</referencePattern>
			</documentFetcher>
			
			
			 <importer>
				<postParseHandlers>
					<transformer
						class="com.norconex.importer.handler.transformer.impl.ReduceConsecutivesTransformer">
						<reduce>\s</reduce>
						<reduce>\n</reduce>
						<reduce>\s\n</reduce>
					</transformer>
				</postParseHandlers>
			</importer>
           
            
			<committer class="com.norconex.committer.core.impl.FileSystemCommitter">
			<directory>./output/lmr/crawledFiles</directory>
			</committer>
			
        </crawler>
    </crawlers>
</httpcollector>
 and attaching the output generated also after crawling
[lmr.zip](https://github.com/Norconex/collector-http/files/1158957/lmr.zip)

**Comment by essiembre** [comment]
I do not understand what is your last issue.  Is it that you are getting JavaScript content extracted with regular content?  You may want to look at [StripBetweenTransformer](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/impl/StripBetweenTransformer.html) or [ReplaceTransformer](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/impl/ReplaceTransformer.html) to eliminate content you do not want.

**Comment by Navaminavu** [comment]
hi Pascal, we have some how managed to crawl the documents..
I have one more query...
That instead of com.norconex.committer.i3.I3Committer used in the previous version which version should we use in the 2.7.1 version to get the same results?

**Comment by essiembre** [comment]
I3Committer is your own creation?  As do not know anything about it I can't really answer your question.  Can you elaborate?

**Comment by essiembre** [comment]
Now working. Confirmed by email.
