### ISSUE TITLE
Using http proxy that requires Windows authentication

### ISSUE THREAD

**Issue by jpcoder2** [Norconex/collector-http#367]
Can someone give me an example of how to setup Norconex so that it will function behind an http proxy (in this case a TMG proxy server) and pass Windows authentication to the proxy?  I have tried every combination I can think of for the httpClientFactory <proxy*> params with no luck.  Also, if there is a way to not have to put the username/password in the config file and to instead use the authentication of the currently logged on user that would be preferable.

Thanks...

**Comment by essiembre** [comment]
What is your authentication mechanism?  With the log level to DEBUG what errors are you getting?  Is it that's it's not going through the proxy or that authentication fails?  What authentication method have you tried?  Did you try different ones (e.g. "ntlm" vs "kerberos")?

As for using the user credentials, I am not sure, but Apache HttpClient (the library used) has some info on this you may want to try: https://hc.apache.org/httpcomponents-client-ga/tutorial/html/authentication.html (look under "4.8.5. Windows Specific configuration").

**Comment by jpcoder2** [comment]
How do you set the log level to DEBUG?  I was looking for that yesterday.

Also, where do you set the authentication method?  I didn't see an XML
element for that.

Thanks...

**Comment by essiembre** [comment]
Look in the log4j.properties file and you'll see several elements where you can change the log level.

As for the authentication method, look for ``<authMethod>`` in the [GenericHttpClientFactory](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/client/impl/GenericHttpClientFactory.html) documentation.

**Comment by jpcoder2** [comment]
I'm not seeing anything in the debug or info output about it attempting to use a proxy at all.  Do I maybe have the <httpClientFactory> in the wrong place?  Does it go under the top level <httpcollector> or somewhere else?

**Comment by essiembre** [comment]
You can share your config and it may help.  What tells you it is not working?  You can also attach the log.

**Comment by jpcoder2** [comment]
Here is the modified part of the config including the proxy settings:

`<httpcollector id="Minimum Config HTTP Collector">

  <httpClientFactory class="com.norconex.collector.http.client.impl.GenericHttpClientFactory">
      <proxyHost>myproxyserver.net</proxyHost>
      <proxyPort>8080</proxyPort>
      <proxyScheme>http</proxyScheme>
      <proxyRealm>mydomain</proxyRealm> 
      <proxyUsername>username</proxyUsername>
      <proxyPassword>mypassword</proxyPassword>
      <authMethod>ntlm</authMethod>
  </httpClientFactory>  
`
And here is a snippet from the logs showing the connection error:

`Norconex Minimum Test Page: 2017-07-14 14:24:38 INFO - Norconex Minimum Test Page: Done initializing sitemap store.
Norconex Minimum Test Page: 2017-07-14 14:24:59 WARN - Not able to obtain robots.txt at: http://www.healthadvantage-hmo.com/robots.txt
org.apache.http.conn.HttpHostConnectException: Connect to www.healthadvantage-hmo.com:80 [www.healthadvantage-hmo.com/209.184.52.132] failed: Connection timed out: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
`
Looks to me it is not attempting to connect to the proxy server which makes me think the proxy settings are either wrong or in the wrong place.

**Comment by essiembre** [comment]
From your config fragment, the tag is indeed at the wrong place.   It needs to be under ``httpcollector->crawlers->crawler`` (or under ``crawlerDefaults``).  Have a look at the [XML configuration documentation](https://www.norconex.com/collectors/collector-http/configuration).  

If you are using a recent version, you can also add the ``-k`` flag on startup and it will validate your config and won't start if there are syntax errors.

**Comment by jpcoder2** [comment]
Great!  That worked.  Thanks.
