### ISSUE TITLE
How to get proxy to work ?

### ISSUE THREAD

**Issue by etaygudai** [Norconex/collector-http#368]
Hello,

1. would like to start simple example : ``collector-http.bat -a start -c examples/minimum/minimum-config.xml``
2. Tried latest stable and snapshot versions : 2.7.1  2.7.2.

3. checked ( including documentation )
```
https://github.com/Norconex/collector-http/issues/367
https://github.com/Norconex/collector-http/issues/167
```

4. placed in both httpcollector->crawlers->crawler and / or under crawlerDefaults 
```xml
  <httpClientFactory class="com.norconex.collector.http.client.impl.GenericHttpClientFactory">
     <proxyHost>myproxyhost</proxyHost>
      <proxyPort>80</proxyPort>
      <proxyScheme>http</proxyScheme>
  </httpClientFactory>
```
see error attached ( if not seen then use this : [https://www.dropbox.com/s/zget8u3va87mzpu/error_for_nor.jpg?dl=1](url)
Can you send a code example ( copy & paste ) 
Any assistance would be appreciated ?

Regards
Etay G

![image](https://user-images.githubusercontent.com/18305794/28326041-45e22c14-6be8-11e7-97fc-7f6e7b18e1b5.png)

**Comment by essiembre** [comment]
Can you confirm it also fails without the proxy?   Also, is it possible you are not using an HTTP proxy but rather a SOCKS proxy?

I do not think SOCKS proxies are currently supported out-of-the-box.  You can get around this easily by modifying the ``collector-http.bat`` file to add socks proxy information directly to the JVM (with your own values):

```
java -DsocksProxyHost=socks.yourdomain.com -DsocksProxyPort=1080 ...
```

**Comment by etaygudai** [comment]
Hello,

Thank you for the prompt reply.
It failed without a proxy.
Using http surely.

The best would be of you have any working example ( I am a coder myself and
used proxy implementations many times using different languages in code
successfully in same network), so I might be missing something (installed
twice the stable and spot versions and configured separately).

Regards
Etay g
On Jul 18, 2017 23:07, "Pascal Essiembre" <notifications@github.com> wrote:

Can you confirm it also fails without the proxy? Also, is it possible you
are not using an HTTP proxy but rather a SOCKS proxy?

I do not think SOCKS proxies are currently supported out-of-the-box. You
can get around this easily by modifying the collector-http.bat file to add
socks proxy information directly to the JVM (with your own values):

java -DsocksProxyHost=socks.yourdomain.com -DsocksProxyPort=1080 ...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Norconex/collector-http/issues/368#issuecomment-316182128>,
or mute the thread

**Comment by essiembre** [comment]
The code for it is in this repo.  You can find [here](https://github.com/Norconex/collector-http/blob/master/norconex-collector-http/src/main/java/com/norconex/collector/http/client/impl/GenericHttpClientFactory.java#L465) where the proxy configuration gets used.

I'd be curious to see what happens if you try to set it up on the JVM (same suggestion but for HTTP):
```
java -DhttpProxyHost=socks.yourdomain.com -DhttpProxyPort=80 ...
```

**Comment by etaygudai** [comment]
Hello again,

Still, no good, after a new vanilla installation and setting my settings with : java -DhttpProxyHost=socks.yourdomain.com -DhttpProxyPort=80

will might check it further in the coming few days and will inform.

Regards
Etay G

**Comment by essiembre** [comment]
Just to make sure, you replaced ``socks.yourdomain.com`` and ``80`` with your own proxy information?

**Comment by etaygudai** [comment]
Of course.
I will maybe try some stunneling as well.

**Comment by essiembre** [comment]
Do you set the proxyRealm?  I realised this configuration option is not taken into account.  It will be fixed in next release.

**Comment by essiembre** [comment]
Is your proxy using NTLM authentication?  The latest version of Apache HttpClient 4.5.3 now supports NTLM proxies and 4.5.4 (not released yet) fixes NTLM issues as well.  You may want to try upgrading that library just in case.  You can get 4.5.3 [here](https://hc.apache.org/downloads.cgi).

**Comment by etaygudai** [comment]
Hello,


Thank you for the prompt reply and quick support ( I am at EMEA timezone )

Anyhow :

Didn't set proxyRealm.

I am not using NTLM authentication.


Might be doing some network sniffing in the coming days to tell.


Regards

Etay G.

**Comment by sveba** [comment]
IMO the right JVM sysprops are -Dhttp**.**proxyHost and -Dhttp**.**proxyPort

**Comment by essiembre** [comment]
@sveba, you are absolutely right. Thanks for pointing this out!  

([Oracle docs](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html))

**Comment by etaygudai** [comment]
It seems **it still doesn't** work with the following settings : 

in **collector-http.bat** I have place :

java -Dlog4j.configuration="file:///%ROOT_DIR%log4j.properties" -Dhttp.proxyHost=hostname  -Dhttp.proxyPort=port -Dfile.encoding=UTF8 -cp "./lib/*;./classes" com.norconex.collector.http.HttpCollector %*

Run the following command : **collector-http.bat -a start -c examples/minimum/minimum-config.xml**

still getting ( This works perfectly - when no proxy is involved ) : 
Connect to www.norconex.com:443 [www.norconex.com/70.32.74.48] failed: Connection timed out: connect)
INFO  [CrawlerEventManager]            REJECTED_ERROR: https://www.norconex.com/product/collector-http-test/minimum.php (com.norconex.collector.core.CollectorException: org.apache.http.conn.HttpHostConnectException: Connect to www.norconex.com:443 [www.norconex.com/70.32.74.48] failed: Connection timed out: connect)
ERROR [AbstractCrawler] Norconex Minimum Test Page: Could not process document: https://www.norconex.com/product/collector-http-test/minimum.php (org.apache.http.conn.HttpHostConnectException: Connect to www.norconex.com:443 [www.norconex.com/70.32.74.48] failed: Connection timed out: connect)
com.norconex.collector.core.CollectorException: org.apache.http.conn.HttpHostConnectException: Connect to www.norconex.com:443 [www.norconex.com/70.32.74.48] failed: Connection timed out: connect


**Please note that I am behind of Company proxy and use this proxy in 3rd party applications or in my personal coding and it works well.**

**Comment by sveba** [comment]
@etaygudai I'm using the same config like yours from the first post and it works for me. Without java props. Maybe try from the cli with curl of the proxy is OK?

**Comment by etaygudai** [comment]
Thanks @sveba . 
Can you please send me your config file ( without hostnames ), so I can see what I miss here ?

**Comment by sveba** [comment]
Sure, but tomorrow. I don't have access from home. But I'm sure it is completely the same like yours, with different values. I put it in the "crawler" section because I'm using only one crawler. And I don't need authentication also.

**Comment by etaygudai** [comment]
Thank you. It sounds I am using pretty much the same sort of Env. so I will
wait for tomorrow. appreciated.

**Comment by sveba** [comment]
This is my proxy config part
```
<httpClientFactory class="com.norconex.collector.http.client.impl.GenericHttpClientFactory">
                <proxyHost>serverproxy.domain.com</proxyHost>
                <proxyPort>8080</proxyPort>
                <proxyScheme>http</proxyScheme>
            </httpClientFactory>
```

**Comment by etaygudai** [comment]
Thanks a lot @sveba  - indeed it **solved my problem** - working behind a proxy is now working fine.
## How : 
1. Go to ...\norconex-collector-http-2.7.1\examples\minimum\ **minimum-config.xml**

2. Under the `<crawler id="Norconex Minimum Test Page">` added the following : 
```
	<httpClientFactory class="com.norconex.collector.http.client.impl.GenericHttpClientFactory">
                <proxyHost>serverproxy.domain.com</proxyHost>
                <proxyPort>80</proxyPort>
                <proxyScheme>http</proxyScheme>
    </httpClientFactory>
```

## Where it did NOT work ( for me ) : 
 When placed above in `<httpClientFactory class="$httpClientFactory">`  in **collector-http-config-reference.xml** file.

**[Print screen](https://www.dropbox.com/s/lqnbk3bauxkpqj3/code_from_notepad_plus_plus.jpg?dl=1)**

**Comment by etaygudai** [comment]
Thanks a lot !

solved - see in GitHUB :-)

https://github.com/Norconex/collector-http/issues/368#issuecomment-318889327

**Comment by essiembre** [comment]
FYI, ``$httpClientFactory`` is an example how you can define variables.  Have a look at the ``#set`` directives at the top of the reference file for where it is defined.

Also, all configuration entries with a default implementation do not need to have their ``class`` specified.  The defaults have a blue background in this [configuration page](https://www.norconex.com/collectors/collector-http/configuration#tbl-httpClientFactory).  

So for the HTTP client factory, you could do this and it would work:
```xml
<httpClientFactory>
    <proxyHost>serverproxy.domain.com</proxyHost>
    <proxyPort>80</proxyPort>
    <proxyScheme>http</proxyScheme>
</httpClientFactory>
```

**Comment by raskolnikov7** [comment]
> FYI, `$httpClientFactory` is an example how you can define variables. Have a look at the `#set` directives at the top of the reference file for where it is defined.
> 
> Also, all configuration entries with a default implementation do not need to have their `class` specified. The defaults have a blue background in this [configuration page](https://www.norconex.com/collectors/collector-http/configuration#tbl-httpClientFactory).
> 
> So for the HTTP client factory, you could do this and it would work:
> 
> ```
> <httpClientFactory>
>     <proxyHost>serverproxy.domain.com</proxyHost>
>     <proxyPort>80</proxyPort>
>     <proxyScheme>http</proxyScheme>
> </httpClientFactory>
> ```

This worked for me thanks!
