### ISSUE TITLE
phantomJS screenshoot names

### ISSUE THREAD

**Issue by angelo337** [Norconex/collector-http#369]
hi there
I just finish to test your phantomJS and work perfect as state on the [documentation](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/PhantomJSDocumentFetcher.html), however I have no clue how to rename the files after the URL that is coming from, would you please point me out some information?
thanks
angelo

**Comment by essiembre** [comment]
There is no built-in way to automate the renaming of files.  To reference the screenshots, a field is added to your document called ``phantomjs.screenshotfile``.  That field holds the full path to the image file.  This is how your application can know which image belongs to each document.

If you really want to rename files or introduce some other logic of your own, one way to do so would be to write your own [IHttpDocumentProcessor](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/doc/IHttpDocumentProcessor.html) that you configure with ``<preImportProcessors>`` or ``<postImportProcessors>`` in your crawler config.
