### ISSUE TITLE
Eliminate header and footer data  form crawled data.

### ISSUE THREAD

**Issue by Navaminavu** [Norconex/collector-http#370]
Hi Pascal,
Can you help me to avoid the header and footer data from a page  being crawled

Please find below the
[htmlfile _l2tm.txt](https://github.com/Norconex/collector-http/files/1208703/htmlfile._l2tm.txt)
 config file
<?xml version="1.0" encoding="UTF-8"?>
<httpcollector id="HTTPCollectorlmr">

	#set($http = "com.norconex.collector.http")
	#set($core = "com.norconex.collector.core")
	#set($urlNormalizer   = "${http}.url.impl.GenericURLNormalizer")
	#set($filterExtension = "${core}.filter.impl.ExtensionReferenceFilter")
	#set($filterRegexRef  = "${core}.filter.impl.RegexReferenceFilter")
	#set($http
	= "com.norconex.collector.http")
	#set($committer =
	"com.norconex.committer")
	#set($urlNormalizer   = "${http}.url.impl.GenericURLNormalizer")
	#set($filterExtension = "${core}.filter.impl.ExtensionReferenceFilter")
	#set($sitemapFactory    = "${http}.sitemap.impl.StandardSitemapResolverFactory")

    <crawlerDefaults>
        <numThreads>2</numThreads>
        <orphansStrategy>DELETE</orphansStrategy>
        <delay default="500" />
        <robotsTxt ignore="false"
				class="com.norconex.collector.http.robot.impl.StandardRobotsTxtProvider" />
         <referenceFilters>
            <filter class="$filterExtension" onMatch="exclude">jpg,gif,png,ico,css,js
			</filter>
        </referenceFilters>
    </crawlerDefaults>
    <crawlers>
        <crawler id="lmr">
         <sitemapResolverFactory ignore="true" lenient="true" class="com.norconex.collector.http.sitemap.impl.StandardSitemapResolverFactory"/>
			<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
			<url>https://lmr-doxygen.rnd.ki.sw.ericsson.se/l2tm/</url>		
			</startURLs>			
            <canonicalLinkDetector class="com.norconex.collector.http.url.impl.GenericCanonicalLinkDetector" ignore="true"></canonicalLinkDetector>
            
            <workDir>./output/lmr</workDir>
            <maxDepth>2</maxDepth>
            <maxDocuments>-1</maxDocuments>
            
            <progressDir>./output/lmr/progress</progressDir>
            <logsDir>./output/lmr/logs</logsDir>
			 
			<documentFetcher class="com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher">
				<exePath>C:\Users\enavami\Documents\norconex-collector-http-2.6.2\phantomjs-2.1.1-windows\bin\phantomjs.exe</exePath>
				<renderWaitTime>5000</renderWaitTime>
				<referencePattern>^.*\.html$</referencePattern>
			</documentFetcher>
			
				<preParseHandlers>
					
					<transformer				
						class="com.norconex.importer.handler.transformer.impl.StripBetweenTransformer"
						inclusive="true" caseSensitive="false" maxReadSize="1000000">
						<stripBetween>
							<start>&lt;div class="title"&gt;</start>
							<end>&lt;/div&gt;</end>
						</stripBetween>
						<stripBetween>
							<start>&lt;div class="contents"&gt;</start>
							<end>&lt;/div&gt;</end>
						</stripBetween>
						
					</transformer>
				</preParseHandlers>
				<postParsehandlers>
				<transformer
						class="com.norconex.importer.handler.transformer.impl.ReduceConsecutivesTransformer">
						<reduce>\s</reduce>
						<reduce>\n</reduce>
						<reduce>\s\n</reduce>
					</transformer>
				</postParsehandlers>
			</importer>
           
            
			<committer class="com.norconex.committer.core.impl.FileSystemCommitter">
			<directory>./output/lmr/crawledFiles</directory>
			</committer>
			
        </crawler>
    </crawlers>
</httpcollector>
 attaching the html file of the page and screen shot where in the area to be removed from crawl is highlighted

![screenshot](https://user-images.githubusercontent.com/29800957/29081049-1e61213e-7c7f-11e7-98d9-63d8069899be.png)
[htmlfile _l2tm.txt](https://github.com/Norconex/collector-http/files/1208710/htmlfile._l2tm.txt)

**Comment by essiembre** [comment]
This is somewhat related to #365 where your content is dynamically loaded/generated by JavaScript.  So in order to know what to strip, you need to look a the generated HTML DOM. Since the file you share does not have the dynamically loaded content.

Still, I am guessing your side navigation will be loaded before ``<div class="contents">``.  If that's the case, you can try stripping everything before that tag.  If you want to keep the HTML ``<head>`` section so metadata are extracted, you can start at ``<body>``. Somewhat like this:

```xml
<transformer class="com.norconex.importer.handler.transformer.impl.StripBetweenTransformer">
  <stripBetween>
    <start><![CDATA[<body>]]></start>
    <end><![CDATA[<div class="contents">]]></end>
  </stripBetween>
</transformer>
```

I use CDATA to make it easier since you do not have to worry about encoding your XML.

**Comment by Navaminavu** [comment]
Hi Pascal,w eare not able to avoid the heade and footer unless we strip between <head> and <div class="contents"> but the problem is that it will make the Page title also striped and we dont have a title for the content which is weird.
Can you help me to strip between <head> and <div class="contents">  and still have the  title
the current config goes as below:-
<?xml version="1.0" encoding="UTF-8"?>
<httpcollector id="HTTPCollectorlmr">

	#set($http = "com.norconex.collector.http")
	#set($core = "com.norconex.collector.core")
	#set($urlNormalizer   = "${http}.url.impl.GenericURLNormalizer")
	#set($filterExtension = "${core}.filter.impl.ExtensionReferenceFilter")
	#set($filterRegexRef  = "${core}.filter.impl.RegexReferenceFilter")
	#set($http
	= "com.norconex.collector.http")
	#set($committer =
	"com.norconex.committer")
	#set($urlNormalizer   = "${http}.url.impl.GenericURLNormalizer")
	#set($filterExtension = "${core}.filter.impl.ExtensionReferenceFilter")
	#set($sitemapFactory    = "${http}.sitemap.impl.StandardSitemapResolverFactory")

    <crawlerDefaults>
        <numThreads>2</numThreads>
        <orphansStrategy>DELETE</orphansStrategy>
        <delay default="500" />
        <robotsTxt ignore="false"
				class="com.norconex.collector.http.robot.impl.StandardRobotsTxtProvider" />
         <referenceFilters>
            <filter class="$filterExtension" onMatch="exclude">jpg,gif,png,ico,css,js
			</filter>
        </referenceFilters>
    </crawlerDefaults>
    <crawlers>
        <crawler id="lmr">
         <sitemapResolverFactory ignore="true" lenient="true" class="com.norconex.collector.http.sitemap.impl.StandardSitemapResolverFactory"/>
			<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
			<url>https://lmr-doxygen.rnd.ki.sw.ericsson.se/l2tm/</url>		
			</startURLs>			
            <canonicalLinkDetector class="com.norconex.collector.http.url.impl.GenericCanonicalLinkDetector" ignore="true"></canonicalLinkDetector>
            
            <workDir>./output/lmr</workDir>
            <maxDepth>2</maxDepth>
            <maxDocuments>-1</maxDocuments>
            
            <progressDir>./output/lmr/progress</progressDir>
            <logsDir>./output/lmr/logs</logsDir>
			 <linkExtractors>	
				<extractor class="com.norconex.collector.http.url.impl.GenericLinkExtractor">		
					<tags>
						<tag name="a" attribute="href" />
						<tag name="script" attribute="src" />
					</tags>
				</extractor>				
			</linkExtractors>
			<documentFetcher class="com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher">
				<exePath>C:\Users\enavami\Documents\norconex-collector-http-2.6.2\phantomjs-2.1.1-windows\bin\phantomjs.exe</exePath>
				<renderWaitTime>5000</renderWaitTime>
				<referencePattern>^.*\.html$</referencePattern>
			</documentFetcher>
				<importer>
					<preParseHandlers>
					<tagger class="com.norconex.importer.handler.tagger.impl.DOMTagger">
						<dom selector="div#projectname" toField="title" extract="text" overwrite="true"/>
					</tagger>
					<transformer class="com.norconex.importer.handler.transformer.impl.StripBetweenTransformer">
						<stripBetween>
						<start><![CDATA[<head>]]></start>
						<end><![CDATA[<div class="contents">]]></end>
						</stripBetween>
					</transformer>
					
					</preParseHandlers>
				<postParsehandlers>
					
					<transformer
						class="com.norconex.importer.handler.transformer.impl.ReduceConsecutivesTransformer">
						<reduce>\s</reduce>
						<reduce>\n</reduce>
						<reduce>\s\n</reduce>
					</transformer>
				</postParsehandlers>
  			</importer>
           
            
			<committer class="com.norconex.committer.core.impl.FileSystemCommitter">
			<directory>./output/lmr/crawledFiles</directory>
			</committer>
			
        </crawler>
    </crawlers>
</httpcollector>

**Comment by Navaminavu** [comment]
can you suggest a way?

**Comment by essiembre** [comment]
The page HTML header (design visible to users) and the ``<head>`` tags are two separate things.  Have you tried the example I provided?   If you want to skip the page header "content" you should start at ``<body>``, not ``<head>``.

**Comment by essiembre** [comment]
@Navaminavu, can we close this issue?

**Comment by Navaminavu** [comment]
yes you can close this.

**Comment by essiembre** [comment]
Thanks for confirming.
