### ISSUE TITLE
How to configure the Norconex HTTP Collector in java?

### ISSUE THREAD

**Issue by akshaybijawe** [Norconex/collector-http#371]
Hi, I checked this link of Java integration but I couldn't configure it properly.
The code on the page is as follows:
`HttpCollectorConfig config = new HttpCollectorConfig();
config.setId("myid");
config.setLogsDir("/tmp/logs/");
...

HttpCollector collector = new HttpCollector(config);
collector.start(true);`

I've imported the Norconex dependencies using Maven. My question is now where do I provide the StartURLs in this case? I think I can use the XML configuration here but is there any other way to specify the configuration in Java? Also, can someone please point me to an example if possible? Thank you for your time.
Sorry, if I'm missing something obvious here.

**Comment by akshaybijawe** [comment]
Hi, I checked this [link](https://www.norconex.com/collectors/collector-http/getting-started) of Java integration but I couldn't configure it properly. 
The code on the page is as follows: 
`HttpCollectorConfig config = new HttpCollectorConfig();
config.setId("myid");
config.setLogsDir("/tmp/logs/");
...
 
HttpCollector collector = new HttpCollector(config);
collector.start(true);`

I've imported the Norconex dependencies using Maven. My question is now where do I provide the StartURLs in this case? I think I can use the XML configuration here but is there any other way to specify the configuration in Java? Thank you for your time. 
Sorry, if I'm missing something obvious here.

**Comment by essiembre** [comment]
A "collector" holds one or more "crawlers".  This means you need to add one or more crawler configuration to the collector configuration.  The start URLs are set on the crawler config.

I recommend you have a look at the Javadoc.  For start URLs, have a look at [HttpCrawlerConfig](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/crawler/HttpCrawlerConfig.html) for a few options starting with ``setStart*``.   The simplest is the ``setStartURLs`` method.  I have updated the [Getting Started](https://www.norconex.com/collectors/collector-http/getting-started) page to make it more obvious.  Here is a copy of the relevant part:

```java
HttpCollectorConfig collectorConfig = new HttpCollectorConfig();
collectorConfig.setId("myid");
collectorConfig.setLogsDir("/tmp/logs/");
...
HttpCrawlerConfig crawlerConfig = new HttpCrawlerConfig();
crawlerConfig.setStartURLs("http://example1.com", "http://example2.com");
...
collectorConfig.setCrawlerConfigs(crawlerConfig);
 
HttpCollector collector = new HttpCollector(collectorConfig);
collector.start(true);
```

**Comment by akshaybijawe** [comment]
Thanks a lot, Pascal for your immediate response.

**Comment by essiembre** [comment]
No problem!
