### ISSUE TITLE
Question about RegexReferenceFilter

### ISSUE THREAD

**Issue by akshaybijawe** [Norconex/collector-http#373]
Hi Pascal, so I want to crawl this url: "https://clinicaltrials.gov/ct2/results?cond=Rheumatoid+Arthritis" with the following RegexReferenceFilter in Java
```
RegexReferenceFilter filter = new RegexReferenceFilter(".*/show/.*");
RegexReferenceFilter filter2 = new RegexReferenceFilter("https://clinicaltrials.gov/ct2/results?cond=Rheumatoid+Arthritis");
crawlerConfig.setReferenceFilters(filter,filter2);
```
But it doesn't get past the start url and I get REJECTED_FILTER as follows:
```
INFO  - REJECTED_FILTER            -           REJECTED_FILTER: https://clinicaltrials.gov/ct2/results?cond=Rheumatoid+Arthritis
```
Also, it doesn't work if I put the filter2 like this ["https://clinicaltrials.gov/ct2/results?cond=Rheumatoid+Arthritis"]. My aim is to get all the links from the [startURL ](https://clinicaltrials.gov/ct2/results?cond=Rheumatoid+Arthritis) that have "/show" pattern in them. May I know what am I missing here? By the way, it works fine if I change the filter2 to "https://clinicaltrials.gov/ct2/results.*". 
Thank you.

**Comment by essiembre** [comment]
Your regular expression is the problem.  You need to escape special regex characters.  For instance, this regex should work:
```
https://clinicaltrials.gov/ct2/results\?cond=Rheumatoid\+Arthritis
```

**Comment by akshaybijawe** [comment]
Thank you, Pascal. This allowed the crawled to add the "https://clinicaltrials.gov/ct2/results?cond=Rheumatoid+Arthritis" link but it did not add any of the other */show/* links from the page.

**Comment by essiembre** [comment]
If you view your page source, you will see these URLs do not exist.  So they are likely pulled or created dynamically using Javascript.   You may need the PhantomJS document fetcher for that one.

**Comment by akshaybijawe** [comment]
That's what I originally thought but if I remove filter2 then the crawler adds the */show/* urls.

**Comment by essiembre** [comment]
Does that mean you are using ``PhantomJSDocumentFetcher`` already?  If so, it may be that the results are not yet rendered when you obtain the page.  Increase the ``renderWaitTime`` to a large enough number for testing and see if you get them.  If not, please share your latest config to reproduce.

**Comment by akshaybijawe** [comment]
I think you are right. I have not used PhatomJSDocumentFetcher. It seems like that the "/show/" urls that I got earlier in my result must be from some other link. I just ran the crawler with the default config and just 1 maxDepth and it did not extract any "/show" url from this [page](https://clinicaltrials.gov/ct2/results?cond=Rheumatoid+Arthritis).  I have attached my config file. Thanks. 
[config.txt](https://github.com/Norconex/collector-http/files/1232736/config.txt)

**Comment by essiembre** [comment]
What happens when you try with ``PhatomJSDocumentFetcher``?  On my end, it is working just fine, including with your reference filters (once escaped properly).

**Comment by essiembre** [comment]
@akshaybijawe, can this issue be closed?

**Comment by akshaybijawe** [comment]
Hi Pascal, it worked as expected. Thank you.
