### ISSUE TITLE
zip file crawling

### ISSUE THREAD

**Issue by angelo337** [Norconex/collector-http#375]
hi there
Could be possible for collector HTTP to index Zip files?, could you please share with us some configuration in order to figure it out?
thanks

**Comment by essiembre** [comment]
Zip files should be crawled by default unless you are excluding them.  Do you have evidence to the contrary? If so, please share your config with a URL to the page containing a link to a zip file.

If you want to crawl each files in the zip separately, have a look at [GenericDocumentParserFactory](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/parser/GenericDocumentParserFactory.html).  You can add something like this to your importer config:

```xml
  <documentParserFactory>
      <embedded>
          <splitContentTypes>application/zip</splitContentTypes>
      </embedded>
  </documentParserFactory>
```

**Comment by angelo337** [comment]
Hi there
Thanks for your fast answer, although is crawling zip files, is not getting any file name, or content at all, and I would like to get both of this in here, is it possible? 
Please

**Comment by essiembre** [comment]
Have you tried the approach suggested?  Please share your config with a URL to the page containing a link to a zip file to reproduce.

**Comment by angelo337** [comment]
hi there,
sorry for the delay I just finish to test the configuration that you provide me, I am now getting just content as the name of the file, is ti possible to get the full content of every file? and the files names inside there?
thanks a lot for your help

link to the file: 
http://www.supersociedades.gov.co/delegatura_aec/estudios_financieros/sirem/Gastos%20de%20intereses%202009.zip
http://www.supersociedades.gov.co/delegatura_aec/tramites_servicios/Documentos_sirem/Gastos%20de%20intereses%202009%20-11032014.zip

**Comment by essiembre** [comment]
I am not sure I understand you.   In the end, do you want the zip file converted to ONE text document that includes the content of all embedded files plus their file name?   Or do you want to extract embedded documents from the zip file and treat them as MANY individual documents, each with their own content?

If the first, you should get it with the default behavior.  If the second, you should get it with the example I provided.   

Please confirm.

**Comment by angelo337** [comment]
I have a bunch of ZIP files, some with several files, other with a single huge file, I need to crawl the content of the files and make searchable this files for my user, if is several files return a link to the zip and giving the name of the file that include that string

thanks and Regards

**Comment by essiembre** [comment]
OK, then splitting by content type like I suggested before should do it.   It will create separate documents so a match in a document will return that document.  When clicking on that document, you can link to the zip.   

Each embedded docs extracted will have the zip URL stored in the  ``document.embedded.parent.root.reference`` field, while the field while the document name should be in ``document.embedded.reference`` (make sure you keep/index those fields).

**Comment by essiembre** [comment]
@angelo337 are you OK with this now? Can we close?

**Comment by angelo337** [comment]
Pascal:
sorry but still not working, at this moment I am working on the PDF files and tomorrow i will work on ZIP and let you know.
thanks a lot

**Comment by angelo337** [comment]
Pascal:

I just start to index the zip File, I am getting this result:

    <arr name="embeddedRelationshipId">
      <str>2015/BalanceGeneral2015SIREMV2.xls</str>
      <str>2015/EstadoResultados2015SIREMV2.xls</str>
      <str>2015/FlujoEfectivo2015SIREMV2.xls</str>
    </arr>

    <arr name="title">
      <str>Balance General 2015 SIREMV2</str>
      <str>Estado Resultados 2015 SIREM</str>
      <str>Flujo Efectivo 2015 SIREMV2</str>
    </arr>

is there a a possibility to crawl this file in a different record set? i Mean generate an  ID's for the each file an another for the ZIP file.
thanks a lot

**Comment by essiembre** [comment]
Have you tried my previous suggestion?  This will treat each file in the zip as if they are individual records:
```xml
  <documentParserFactory>
      <embedded>
          <splitContentTypes>application/zip</splitContentTypes>
      </embedded>
  </documentParserFactory>
```
Is it what you want?  One record per file?  Let me know if the above works for you.

**Comment by angelo337** [comment]
Pascal:
I test it, and in my config do not split in individuals files, I place it in between preparser and post.
any way to check it or debug besides console? please
thanks a lot

**Comment by essiembre** [comment]
Can you share your config?

**Comment by angelo337** [comment]
Pascal:
for sure, is the same as before just add the importer config
[test-congig_zip.xml.zip](https://github.com/Norconex/collector-http/files/1300809/test-congig_zip.xml.zip)
Regards

**Comment by essiembre** [comment]
Thanks to your config and its test URL, I was able to reproduce. 

The detected content-type for your Zip file is not ''application/zip'' like specified in your config, but rather ``application/x-zip-compressed``.  If you change that in your config, it will work.  If you want to support a few variations, you can try this:

```xml
<documentParserFactory>
    <embedded>
        <splitContentTypes>application/(x-)?zip(-compressed)?</splitContentTypes>
    </embedded>
</documentParserFactory>
```

Please confirm that change works for you.

**Comment by angelo337** [comment]
Pascal:
I just finish testing and I am amaze, is working so find.
thanks a lot

**Comment by essiembre** [comment]
Glad to hear!  Thanks for confirming.
