### ISSUE TITLE
Question: How to create random values in config

### ISSUE THREAD

**Issue by ebbesson** [Norconex/collector-http#378]
I have crawling situation, where we have a parameterized sitemap.xml (thesite.com/sitemap/sitemap.xml?content=somecontent) that is is cached for some reason.. 
To get around this I'd like to be able to call it with a random parameter. 
```
#set($random=$math.Random())
#set($rnd=$integer.toString($random.nextInt(32000)))
<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">		
	<sitemap>${sitemapUrl}${lang}&amp;lang=${lang}&amp;cache-trick=${rnd}</sitemap>
</startURLs>
```

But it doesn't seem to be able to evaluate ${rnd} properly. 

`ERROR [StandardSitemapResolver] Cannot fetch sitemap: http://internalsite.com/sitemapxml/sitemap?lang=no&cache-trick=${rnd} (Illegal character in query at index 64: http://internalsite.com/sitemapxml/sitemap?lang=no&cache-trick=${rnd})
`

Any ideas on how to proceed? 
I could create a shell script that adds the random values to my variable file (before the run) that mapps to $rnd, but I'd really like to be able to have this in the config.

**Comment by essiembre** [comment]
Is the server caching it, or the collector?  To rule out the collector first, can delete the sitemap cache before re-running the collector.  Look for a "sitemaps" folder in your workdir.  If that directory is not there or if it does not change anything, then caching is not happening in the collector.

**Comment by essiembre** [comment]
Just to add, if it is really the server caching it somehow and you must pass a dynamic argument, there is no way currently to do what you are trying to do via configuration alone (AFAIK).   

One way to come up with URLs dynamically, you can implement a ``IStartURLsProvider``.   

The simplest though is probably wrapping the execution in a shell that creates the dynamic value as you suggested.

**Comment by ebbesson** [comment]
Thanks for the swift reply

The server (or the Varninsh cache I have to go through) does the caching of the sitemap and it is this that needs to be called upon with a dynamic url to be able to renew the sitemap.

I think I'll go with the dynamic value solution then
