### ISSUE TITLE
Configuration example of Kerberos Authentication

### ISSUE THREAD

**Issue by akshaybijawe** [Norconex/collector-http#379]
Hi Pascal,  can you please give an example configuration for Kerberos? Thank you.

**Comment by essiembre** [comment]
Have you tried the following in your crawler config?

  ```
<httpClientFactory class="com.norconex.collector.http.client.impl.GenericHttpClientFactory">
      <authMethod>kerberos</authMethod>
      <authUsername>...</authUsername>
      <authPassword>...</authPassword>

      <!-- These apply to NTLM authentication but may help with Kerberos? -->
      <authHostname>...</authHostname>
      <authPort>...</authPort>
      <authWorkstation>...</authWorkstation>
      <authDomain>...</authDomain>
  </httpClientFactory>
```

More information [here](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/client/impl/GenericHttpClientFactory.html).

**Comment by akshaybijawe** [comment]
Hi Pascal, 
Yes, I have tried this configuration but I get the following message with DEBUG mode on.
 (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=401, reasonPhrase=Unauthorized]). The url in this message contains some parameters like CHALLENGE, SMAGENTNAME, TARGET. Also,  I can login on the url with the same username and password. I tried setting the authMethod to ntlm but still no success. Thanks.

**Comment by essiembre** [comment]
Can you try adding:
``` 
<authRealm>...</authRealm>
```
If it still fails, can you grant temporary access for testing?  At a minimum, can you send your log file?  If too sensitive, you can email it to me, referencing this ticket.

**Comment by akshaybijawe** [comment]
Hi Pascal, 
I tried adding the authRealm as well but to no success. I'm sorry I cannot share the log file or grant access. But here is the header information that I captured on Firefox browser.
```
HTTP/1.1 401 Unauthorized
Content-Type: text/html
Server: Microsoft-IIS/7.5
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
X-Powered-By: ASP.NET
X-UA-Compatible: IE=edge
```
Also, how do I get the authRealm of an url? Is there a way to get it programmatically perhaps or Is it something that the site administrator can provide me? I think I may have entered the incorrect information.  Thanks.

**Comment by essiembre** [comment]
You seem to authenticate then.  Maybe your server logs could confirm.  The error you are getting seems to indicate it redirects to himself somehow.   Can you wipe out the workdir and try again?  

It is also possible the page before the authentication is the same that you are being redirected to after authentication (so already processed)?  If so, maybe you can try a different start URL than the home page? (or add fake parameters to it as a test).

Or maybe the error comes from another thread and it is not the reason you are getting only a few docs.  Try with just one thread for testing.

**Comment by akshaybijawe** [comment]
Hi Pascal, thanks for your reply. I have tried your above suggestions but no matter which url (login page or home page), it gives the same "Already processed" message.

**Comment by essiembre** [comment]
Can you run with 1 thread and attach the resulting log?

**Comment by akshaybijawe** [comment]
Hi Pascal, I have sent you the email with the log file. Thanks.

**Comment by essiembre** [comment]
Seems the problem is when the initial page gets processed, it redirects to an auth-related URL, then when authenticated, it redirects back to the initial page (already processed).   The crawler does not process twice the same URL.  

Is the SMAGENTNAME a constant value?  If so, can you try to make the following the start URL?
```
http://www.example.com/siteminderagent/ntlm/creds.ntc?CHALLENGE=&SMAGENTNAME=[ALPHANUMERIC VALUE]&TARGET=-SM-http%3A%2F%2Fwww.example.com%2Fsmauth%2Fdefault.aspx
```

**Comment by akshaybijawe** [comment]
Hi Pascal, 
It worked when I added the configuration for PhantomJSDocumentFetcher as follows:
```
<documentFetcher class="com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher">
    <exePath>/path/to/phantomjs.exe</exePath>
    <renderWaitTime>10000</renderWaitTime>
    <validStatusCodes>302,200</validStatusCodes>
    <!--	<referencePattern>.*</referencePattern> -->          
</documentFetcher>
```
Also, I have commented out referencePattern. Does it extract all the javascript generated links if the referencePattern is commented? Thanks a lot.

**Comment by essiembre** [comment]
Yes, the ``referencePattern`` is telling it to only use ``PhantomJSDocumentFetcher`` for matching URLs.  Other ones will use the ``GenericDocumentFetcher``.   But you may not be able to get all non-HTML file types properly through ``PhantomJSDocumentFetcher``... so I am not sure it will resolve all your issues.

I am also not sure why it works for you with ``PhantomJSDocumentFetcher`` and not ``PhantomJSDocumentFetcher``.  Are you passing authentication info somehow?  If not, it is likely grabbing it from the OS account and there must be ways to do the same with ``GenericDocumentFetcher``.

**Comment by akshaybijawe** [comment]
Hi Pascal, 
I am passing the auth info using ntlm as you said above. I think the real issue was with the redirection. Thanks.

**Comment by essiembre** [comment]
Can we close then or you still experience auth-related issues?

**Comment by akshaybijawe** [comment]
Yes, I was able to crawl the authenticated websites. So, I will close this issue. Thanks for your time and assistance, Pascal.

**Comment by akshaybijawe** [comment]
Hi Pascal, I crawled one of the authenticated website and I did not configure the authentication protocol,  and I only configured the PhantomJSDocumentFetcher as the website uses JavaScript to generate the links. The crawler was able to crawl the homepage even when I did not configure any authentication protocol in the xml config file. Do you know how maybe the crawler is able to extract the authenticated home page? Thank you for your time.

**Comment by essiembre** [comment]
The only thing I can think off without being able to test it myself is that the PhantomJS version you use may be picking up the NTLM information from the account running the process.  

Is it otherwise working for you?

**Comment by akshaybijawe** [comment]
Hi Pascal, I think you are right that the PhantomJS is picking up the NTLM information from the account. I also tried without the PhantomJS but with the auth method NTLM, it seems to authenticate but not extract any urls as the urls are generated using JavaScript. This makes sense to me. Thank you for your reply.

**Comment by essiembre** [comment]
No problem.

**Comment by gwque** [comment]
Any updates for the crawler version 3? I've a IIS hosted site using Windows auth - works fine to pick up html via the WebDriverHttpFetcher (using the chrome browser which handles such authentication), but html is all it extracts. PDF content is not being extracted. It sounds like the GenericHttpFetcher is required but kerberos auth method is not working: INFO  REJECTED_BAD_STATUS - [myUrl here] - 401 Unauthorized - GenericHttpFetcher. [akshaybijawe] seemed to make it work adding a PhantomJS documentFetcher, but I'm not seeing that in the config docs for V3.

Thanks

**Comment by gwque** [comment]
Thanks for the quick reply. That documentation link you sent is exactly what I've been referring to along with other config documentation.

I've tried this config but getting 401 as described previously:

	<fetcher class="com.norconex.collector.http.fetch.impl.GenericHttpFetcher">
	  <authentication>
	    <method>kerberos</method>
	    <credentials>
      		<username>myDomainLogin</username>
	        <password>myPassword</password>
	    </credentials>
	  </authentication>
	</fetcher>

Again, I didn't spot the config setting <documentFetcher class="com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher"> as mentioned as possibly helping (in 2017).

I was so close to finalizing this Norconex crawler with Solr as a search engine, but just can't get the darn PDFs (and likely docx, etc.) to extract into searchable content. Might have to punt and find something else.

**Comment by essiembre** [comment]
This ticket has been closed over 5 years ago. I moved your last post to a new ticket. #807
