### ISSUE TITLE
SPNEGO Authentication Protocol example

### ISSUE THREAD

**Issue by akshaybijawe** [Norconex/collector-http#380]
Hi Pascal, 

I'm trying to crawl a website that has a "WWW-Authenticate: Negotiate" protocol. Below are the response headers of the website: 
```
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: text/html;charset=ISO-8859-1
Date: Some date
Expires: 0
Pragma: no-cache
Server: Apache-Coyote/1.1
WWW-Authenticate: Negotiate
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Content-Length: Some Number
Connection: keep-alive
X-RBT-Optimized-By: Some Value
```

I tried to configure this as follows:
```
<httpClientFactory class="com.norconex.collector.http.client.impl.GenericHttpClientFactory">
	<authMethod>spnego</authMethod>
	<authUsername>USERNAME</authUsername>
	<authPassword>ENCRYPTED PASSWORD</authPassword>
	<authPasswordKey>path/to/key.txt</authPasswordKey>
	<authPasswordKeySource>file</authPasswordKeySource>
	<authRealm>REALM</authRealm>
	<authHostname>HOST NAME</authHostname>
	<authWorkstation>MY IP</authWorkstation>
	<authPort>PORT NUMBER</authPort>
	<authDomain>DOMAIN</authDomain> 
	<cookiesDisabled>false</cookiesDisabled>
</httpClientFactory>
```

I get the following error:
```
INFO  [CrawlerEventManager]       REJECTED_BAD_STATUS: [LOGIN URL] (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=401, reasonPhrase=Un
authorized])
```
Which authentication protocol should be used in the config for "WWW-Authenticate: Negotiate"? Also, are there any other properties required for SPNEGO auth method. I tried using Kerberos auth method but still it gives the same error. Thank you for your time and assistance, Pascal.

**Comment by essiembre** [comment]
It seems to vary.  You may want to ask the site owner.    If you can't, there are ways to find out by yourself, which I did not try.  See [here](https://stackoverflow.com/questions/5597573/how-to-find-if-ntlm-or-kerberos-is-used-from-www-authenticate-negotiate-header) and [here](https://stackoverflow.com/questions/4265975/authentication-issues-with-www-authenticate-negotiate).

**Comment by akshaybijawe** [comment]
Thanks for your reply, Pascal. I have not been able to make the SPNEGO protocol work. I will update this thread if I have any success.

**Comment by akshaybijawe** [comment]
Hi Pascal, I believe Kerberos, and SPNEGO authentication protocol requires KDC (Key Distribution Center) field to authenticate. Is there any way to add this field in the XML configuration? Thank you.

**Comment by essiembre** [comment]
I do not have an environment to test so it is hard to help.  Doesn't the KDC contain the domain/realm information that you can already provide via XML configuration? I am not sure if you require anything extra.

I have seen a few places where Kerberos security info is passed as system properties.  You may be able to modify the launch script to add those properties.  More info:
https://docs.oracle.com/javase/8/docs/technotes/guides/security/jgss/tutorials/KerberosReq.html
