### ISSUE TITLE
Javascript links

### ISSUE THREAD

**Issue by angelo337** [Norconex/collector-http#386]
hi there:
could you please help me with an issue trying to parse Javascript on the event of the link?

 I am trying to crawl a page:

http://www.supersociedades.gov.co/nuestra_entidad/normatividad/SitesPages/Conceptos-Juridicos.aspx

and at the botton of the list on this page there is a link to see more content with this link:

```html
<a onclick="RefreshPageTo(event, &quot;?Paged=TRUE&amp;p_SortBehavior=0&amp;p_FechaPagina=20170707%2005%3a00%3a00&amp;p_ID=8376&amp;PageFirstRow=61&amp;View=bb752a08-03df-4bd9-bf8f-82202e1c8022&quot;);return false;" href="javascript:" class="ms-commandLink ms-promlink-button ms-promlink-button-enabled"><span class="ms-promlink-button-image"><img src="/_layouts/15/images/spcommon.png?rev=23" class="ms-promlink-button-right" alt="Siguiente" border="0"></span></a>
```

I am trying to follow that link with this configuration:

```xml
<linkExtractors>
    <extractor class="com.norconex.collector.http.url.impl.GenericLinkExtractor">
       <schemes>
         http,https,ftp,javascript
      </schemes>
      <tags>
          <tag name="a" attribute="href" />
          <tag name="a" attribute="onclick" />
          <tag name="frame" attribute="src" />
          <tag name="iframe" attribute="src" />
          <tag name="img" attribute="src" />
          <tag name="meta" attribute="http-equiv" />
          <tag name="script" attribute="src" />
      </tags>
```
however I am unable to retrieve that URL, after click on that page the URL suppose to be somthing similar to:

http://www.supersociedades.gov.co/nuestra_entidad/normatividad/SitesPages/Conceptos-Juridicos.aspx?Paged=TRUE&p_SortBehavior=0&p_FechaPagina=20170707%2005%3a00%3a00&p_ID=8376&FolderCTID=0x012001&PageFirstRow=61&View=bb752a08-03df-4bd9-bf8f-82202e1c8022

as you can see all information is inside the parameter of the Javascript and I am tryning to parse it with no Luck.
could you please take a look for me and point me in the right direction in order to crawl web sites with javascript as links but on th event ps the object?

thanks a lot

Angelo

**Comment by essiembre** [comment]
You should be able to extract those using the [RegexLinkExtractor](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/impl/RegexLinkExtractor.html) instead.

**Comment by angelo337** [comment]
hi there
thanks for your fast answer, I alredy try that with this code:

`     <extractor class="com.norconex.collector.http.url.impl.RegexLinkExtractor">
      <linkExtractionPatterns>
          <pattern>
             <match>(\?[A-Za-z0-9&amp;=_%-]*)</match>
              <replace>http://www.supersociedades.gov.co/nuestra_entidad/normatividad/SitesPages/Conceptos-Juridicos.aspx$1</replace>
          </pattern>
      </linkExtractionPatterns>
  </extractor>`

But still not working

**Comment by essiembre** [comment]
You mean the link is not extracted?  The ``...RefreshPageTo...`` string is only found on the page you gave after Javascript has been rendered.  Are you using the ``PhantomJSDocumentFetcher``?   I tried it and it worked fine for me.

I also suggest you surround your regular expressions with ``<![CDATA[ ... ]]>`` to avoid XML escaping issues.

**Comment by angelo337** [comment]
Pascal:
I just change the config as you told me, however still not crawling the webpage, 
could you please take a look of my config, i might be another mistake.
thanks a lot


[test-congig_new.xml.zip](https://github.com/Norconex/collector-http/files/1281778/test-congig_new.xml.zip)

**Comment by essiembre** [comment]
Not sure why it is not working for you, I tried with your config and the paging URL was extracted and committed, as you can see here:

```
INFO  [CrawlerEventManager]    DOCUMENT_COMMITTED_ADD: http://www.supersociedades.gov.co/nuestra_entidad/normatividad/SitesPages/Conceptos-Juridicos.aspx?Paged=TRUE&p_SortBehavior=0&p_FechaPagina=20170804+05%3A00%3A00&p_ID=8404&PageFirstRow=31&View=bb752a08-03df-4bd9-bf8f-82202e1c8022
```

**Comment by angelo337** [comment]
Pascal:
the only issue I see is that at the beginning of crawling i am getting this errors:

> ERROR [XMLConfigurationUtil$LogErrorHandler] (XML Validation) HttpCrawlerConfig: cvc-complex-type.2.3: Element 'crawler' cannot have character [children], because the type's content type is element-only.
ERROR [XMLConfigurationUtil$LogErrorHandler] (XML Validation) RegexLinkExtractor: cvc-complex-type.2.2: Element 'pattern' must have no element [children], and the value must be valid.
ERROR [XMLConfigurationUtil$LogErrorHandler] (XML Validation) RegexLinkExtractor: cvc-minLength-valid: Value '' with length = '0' is not facet-valid with respect to minLength '1' for type 'nonEmptyString'.
ERROR [XMLConfigurationUtil$LogErrorHandler] (XML Validation) RegexLinkExtractor: cvc-complex-type.2.2: Element 'pattern' must have no element [children], and the value must be valid. 


could be related? please, how could be solve it?

thanks

**Comment by essiembre** [comment]
Well, I did notice you had a superfluous hyphen character ( - ) on line 79:

```
-     <sitemapResolverFactory ignore="true" />
```
I took it out as I assume it was a typo. 

For the ``RegexLinkExtractor`` errors, I think that explains it.  The syntax in your config (and what I tried) matches the 2.8.0 shapsnot release.  Is that what you are using?  I suggest you downloadd the latest HTTP Collector snapshot release and try again.

**Comment by angelo337** [comment]
Pascal:
as you said it was a Typo on line 79, thanks.
In fact I was using version 2.7.1, and with that configuration is not working, however with your advice i just change to version 2.8.0 and is is working like a charm, I don't get why but it's now.
would you please explain to me how to avoid double encoding? because now i am getting to many url's on the list that is repeating it self 3 to five times.
thanks

**Comment by essiembre** [comment]
Maybe the ``GenericURLNormalizer`` can help you eliminate double encoding with some custom regex, or maybe reject some versions you do not want with a reference filter?  If that does not work for you, can you provide an example or two?

**Comment by angelo337** [comment]
Pascal:
I try to catch the same URL, however I am not sure, more or less this is what is happening to me, is encoding the same URL several times I am guessing 5 times, could you please take a look for me and provide me some advise? 
thanks a lot

> http://www.supersociedades.gov.co/nuestra_entidad/normatividad/SitesPages/Conceptos-Juridicos.aspx?Paged=TRUE&p_SortBehavior=0&p_FechaPagina=20040527+06%3A00%3A00&p_ID=426&PageFirstRow=6091&View=bb752a08-03df-4bd9-bf8f-82202e1c8022
http://www.supersociedades.gov.co/nuestra_entidad/normatividad/SitesPages/Conceptos-Juridicos.aspx?Source=%2Fnuestra_entidad%2Fnormatividad%2FSitesPages%2FConceptos-Juridicos.aspx%3FSource%3D%252Fnuestra_entidad%252Fnormatividad%252FSitesPages%252FConceptos-Juridicos.aspx%253FPaged%253DTRUE%2526PagedPrev%253DTRUE%2526p_SortBehavior%253D0%2526p_FechaPagina%253D20040721%252B06%25253A00%25253A00%2526p_ID%253D552%2526PageFirstRow%253D5971%2526View%253Dbb752a08-03df-4bd9-bf8f-82202e1c8022
http://www.supersociedades.gov.co/nuestra_entidad/normatividad/SitesPages/Conceptos-Juridicos.aspx?Source=%2Fnuestra_entidad%2Fnormatividad%2FSitesPages%2FConceptos-Juridicos.aspx%3FSource%3D%252Fnuestra_entidad%252Fnormatividad%252FSitesPages%252FConceptos-Juridicos.aspx%253FSource%253D%25252Fnuestra_entidad%25252Fnormatividad%25252FSitesPages%25252FConceptos-Juridicos.aspx%25253FSource%25253D%2525252Fnuestra_entidad%2525252Fnormatividad%2525252FSitesPages%2525252FConceptos-Juridicos.aspx%2525253FPaged%2525253DTRUE%25252526p_SortBehavior%2525253D0%25252526p_FechaPagina%2525253D20041006%2525252B06%252525253A00%252525253A00%25252526p_ID%2525253D705%25252526PageFirstRow%2525253D5881%25252526View%2525253Dbb752a08-03df-4bd9-bf8f-82202e1c8022
http://www.supersociedades.gov.co/nuestra_entidad/normatividad/SitesPages/Conceptos-Juridicos.aspx?Source=%2Fnuestra_entidad%2Fnormatividad%2FSitesPages%2FConceptos-Juridicos.aspx%3FSource%3D%252Fnuestra_entidad%252Fnormatividad%252FSitesPages%252FConceptos-Juridicos.aspx%253FSource%253D%25252Fnuestra_entidad%25252Fnormatividad%25252FSitesPages%25252FConceptos-Juridicos.aspx%25253FPaged%25253DTRUE%252526p_SortBehavior%25253D0%252526p_FechaPagina%25253D20040709%25252B06%2525253A00%2525253A00%252526p_ID%25253D528%252526PageFirstRow%25253D6031%252526View%25253Dbb752a08-03df-4bd9-bf8f-82202e1c8022
http://www.supersociedades.gov.co/nuestra_entidad/normatividad/SitesPages/Conceptos-Juridicos.aspx?Source=%2Fnuestra_entidad%2Fnormatividad%2FSitesPages%2FConceptos-Juridicos.aspx%3FSource%3D%252Fnuestra_entidad%252Fnormatividad%252FSitesPages%252FConceptos-Juridicos.aspx%253FSource%253D%25252Fnuestra_entidad%25252Fnormatividad%25252FSitesPages%25252FConceptos-Juridicos.aspx%25253FPaged%25253DTRUE%252526PagedPrev%25253DTRUE%252526p_SortBehavior%25253D0%252526p_FechaPagina%25253D20040721%25252B06%2525253A00%2525253A00%252526p_ID%25253D552%252526PageFirstRow%25253D5971%252526View%25253Dbb752a08-03df-4bd9-bf8f-82202e1c8022

**Comment by essiembre** [comment]
Not sure why the duplicates on first look, but if you are only interested in the first one, maybe you can create a reference filter to exclude ``.*\.aspx\?Source.*`` ?

**Comment by angelo337** [comment]
I just create the filter, however is not working still sending this documents

`                <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter"
                          onMatch="exclude">
                  .*\.aspx\?Source=%2Fnuestra_entida.*
                </filter>`

do you see any error on my expression please?

**Comment by essiembre** [comment]
No I don't.  Have you started fresh (deleting workdir)?   Because it may be cached URLs that are reprocessed.   Maybe try with DEBUG in the log4j.properties file and see what the log says.

**Comment by angelo337** [comment]
Pascal:
I just delete every file on the workdir, and still the same, at the same time i find out why is not crawling this content, I am getting this kind of URL's:

http://www.supersociedades.gov.co/nuestra_entidad/normatividad/SitesPages/Conceptos-Juridicos.aspx?Paged=TRUE&amp;p_SortBehavior=0&amp;p_FechaPagina=20170119+05%3A00%3A00&amp;p_ID=7295&amp;PageFirstRow=211&amp;View=bb752a08-03df-4bd9-bf8f-82202e1c8022

as you can see the file is replacing & with &amp; and no content is crawl, if i chage it to this:

http://www.supersociedades.gov.co/nuestra_entidad/normatividad/SitesPages/Conceptos-Juridicos.aspx?Paged=TRUE&p_SortBehavior=0&p_FechaPagina=20170119+05%3A00%3A00&p_ID=7295&PageFirstRow=211&View=bb752a08-03df-4bd9-bf8f-82202e1c8022

I find out that if I change that encoding i can grab all content, is that any way to chage that in the configuration? please

thanks a lot

**Comment by essiembre** [comment]
I suggest you try using a custom pattern using the ``GenericURLNormalizer`` to replace ``&amp;`` to ``&``.

**Comment by angelo337** [comment]
despite every effort i am not able to crawl this sharepoint site content in list, O don't know why but still giving me the same page over and over. 
thanks a lot for your help

**Comment by essiembre** [comment]
Don't give up when you are so close! :-)  I noticed sometimes the ``&`` is escaped and sometimes not.  So I added the following to the crawler config and I got no duplicates:
```xml
      <referenceFilters>
          <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter"
                  onMatch="exclude"><![CDATA[
              .*\.aspx\?Source=(/|%2F)nuestra(_|%5F)entida.*
          ]]></filter> 
      </referenceFilters>
```

I suggest you give it a try.

**Comment by angelo337** [comment]
Pascal:
thanks for the encouragement, I am test it, and I see that is not giving me as much repeat URL however is not visiting the following URLs either. meaning that I am trying to crawl more or less 8.000 government documents regarding societies, and this is just giving me the very first 30 results. how can I make sure that the crawling is able to crawl content on the group of PDF?
thanks a lot for your time

**Comment by essiembre** [comment]
Is it just the PDFs you are not getting?  Can you give me a sample page with PDFs in it that you are not getting?

**Comment by angelo337** [comment]
none of this PDFs are coming is very particular, before i get the first 30 pdfs files, now none of them are coming to the index.
[http://www.supersociedades.gov.co/nuestra_entidad/normatividad/normatividad_conceptos_juridicos/OFICIO%20220-029843.pdf](url)
at the same time I figure it out another mistake i have in the phantom config, however now i am  getting all info inside the page but none of the PDFs
thanks a lot

**Comment by essiembre** [comment]
Can you share your new phantom config?

**Comment by angelo337** [comment]
<documentFetcher
        class="com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher"
        detectCharset="true">
        <exePath>/usr/local/bin/phantomjs</exePath>
        <renderWaitTime>4000</renderWaitTime>
        <screenshotDir>./</screenshotDir>
        <referencePattern>^.*\.aspx.*$</referencePattern>
        <screenshotZoomFactor>0.25</screenshotZoomFactor>
      </documentFetcher>

**Comment by essiembre** [comment]
When you configured the ``RegexLinkExtractor`` that overwrote the default.  So you just have to add it back:

```xml
<linkExtractors>
    <extractor class="com.norconex.collector.http.url.impl.RegexLinkExtractor">
        ... 
    </extractor>
    <extractor class="com.norconex.collector.http.url.impl.GenericLinkExtractor"/>
</linkExtractors>
```

You should get many more links now.  Please confirm.

On an unrelated note, since you only have one crawler defined, I recommend you move what you have in ``<crawlerDefaults>`` under your ``<crawler>`` to avoid confusion.

**Comment by angelo337** [comment]
Pascal:
still grabbing at this momment, I see more Urls, but i am waiting to see if i get  any pdf indexed, i let you know in more or less 4 hours.
Thanks a lot

**Comment by angelo337** [comment]
Pascal:
officially I can say that with the code and the advise you provide me is working with the Sharepoint 2013 list. I just finish testing and is working with all URL. 
Thanks a lot

**Comment by essiembre** [comment]
Awesome! Glad to hear.
