### ISSUE TITLE
Passing url to GenericFetcher from PhantomJSFetcher

### ISSUE THREAD

**Issue by nemojjh** [Norconex/collector-http#387]
Some url return 'text/html' type through HEAD Request.

But  its response is 'application/pdf'.

So PhantomJSFetcher gets errors by these urls. (Return 'fail')

Is there way to pass these urls to GenericFetcher? If PhantomJSFetcher gets error.

Thank you.

**Comment by essiembre** [comment]
``PhantomJSDocumentFetcher`` will not work with non-HTML pages.  PhantomJS does not return a relevant DOM tree for non-HTML pages.   

So you should exclude them from the get-go.  If you rely on the ``<contentTypePattern>`` (default or your own), then an invalid content-type can indeed be problematic.

Can you try to rely on ``<referencePattern>`` instead?

If that is not possible, you can ask your crawler to make the HEAD request as a separate call (without using PhantomJS) in case the HTTP response returns the right type (if it is PhantomJS returning it wrong).  You can do so by configuring the [GenericMetadataFetcher](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/GenericMetadataFetcher.html).

**Comment by nemojjh** [comment]
```
protected HttpRequestBase createUriRequest(String url) {
        URI uri = HttpURL.toURI(url);
        if (LOG.isDebugEnabled()) {
            LOG.debug("Encoded URI: " + uri);
        }
        return new HttpGet(uri);
    }
```
I modified the code to send Get Request for getting actual content-type.

Now PhantomJSFetcher pass non-html to generic.

Thank you.
