### ISSUE TITLE
Content length of inputstream is 0 at CommitStage

### ISSUE THREAD

**Issue by nemojjh** [Norconex/collector-http#389]
```
Config 
 - PhantomJSFetcher : Only HTML(Default)
 - keepDownload : false
```

I can't handle contents of url(ex. images) in queueAddition() method.

I tried to read it but Its length is 0 so returns nothing.

I confirmed PhantomJSFetcher pass the url(mime type : image) to GenericDocumentFetcher.

Is there any option to pass content inputstream to queueAddtion method?

Thank you.

**Comment by essiembre** [comment]
The Importer module parses every file and extracts any text it can.  By default, the Committer should not receive binary streams (e.g., images).  So it may just be that no text content could be extracted from the image (just metadata) and this is why you have a zero-length stream.  You may want to investigate enabling OCR.  Have a look at [GenericDocumentParserFactory](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/parser/GenericDocumentParserFactory.html).  

If you want to get the raw image stream, you have to make sure images are not parsed.  You can try the following:
```xml
  <documentParserFactory>
      <!-- if you want OCR -->
      <ocr path="/app/tesseract/">
          <languages>en, fr</languages>
          <contentTypes>application/pdf</contentTypes>
      </ocr>

      <!-- Do not parse images: -->
      <ignoredContentTypes>
          image/.*
      </ignoredContentTypes>
  </documentParserFactory>
```
If you do so, make sure you have no import handlers that expect text.  Use the "restrictTo" on your handlers.

**Comment by nemojjh** [comment]
Thank you. It is helpful.

I'll close this.

Thank you.
