### ISSUE TITLE
Metadata from another page

### ISSUE THREAD

**Issue by angelo337** [Norconex/collector-http#393]
Hi there Pascal:
I am having a page with a list of Files (PDF) and metadata, and the documents are been crawled just fine, however I would like to include the metatada information in the crawling process, like the info on each column of this page in order to enhance the accuracy of this search. please check the page on:

http://www.supersociedades.gov.co/nuestra_entidad/normatividad/SitesPages/Conceptos-Juridicos.aspx 
could you please help me with this?
thanks a lot
angelo

**Comment by essiembre** [comment]
Right now, only a link metadata is carried through to the child page.  There is no built-in way to merge two documents AFAIK.  One thing you can do is create a custom implementation of [IHttpDocumentProcessor](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/doc/IHttpDocumentProcessor.html) and make it a ``<processor ...>`` under ``<preImportProcessors>`` or ``<postImportProcessors>``.  When creating your custom processor, you will have access to the ``HttpClient`` so you can make a call yourself to the associated document and store its content with your current document.  Not sure how easy it will be to do in your case.

Another option is to mark this as a feature request to have a built-in ability to merge documents.

**Comment by angelo337** [comment]
thanks a lot for your fast answer,
for my the solution is to crawl the website and create a manual update on each document to feed information of metadata.
could be a nice feature to feed meta information from other sources.
Best regards
angelo
