### ISSUE TITLE
How to configure subdomain crawling?

### ISSUE THREAD

**Issue by dgomesbr** [Norconex/collector-http#400]
Let's say I have a site to crawl - mywebsite.com - and I wanted to define the collector to stay on the main domain (mywebsite) while visiting news.mywebsite.com, base.mywebsite.com and even others that I don't have mapped xyz.mywebsite.com.

Is that configurable or should I code and extend something?

**Comment by essiembre** [comment]
You can set ``stayOnDomain`` to ``false`` on your ``<startURLs>`` and rely on ``<referenceFilters>`` instead, which gives you more control.  Have a look here for more details: https://github.com/Norconex/collector-http/issues/394#issuecomment-331370309

**Comment by dgomesbr** [comment]
Perfect explanation over there!
