### ISSUE TITLE
request: Migrate to SLF4J 

### ISSUE THREAD

**Issue by dgomesbr** [Norconex/collector-http#401]
Give the users control over the implementation they want use when embedding Collector in their projects and also offers a easier and friendly configuration of logging through a XML file in case of logback adoption.

details:

> from: https://softwareengineering.stackexchange.com/questions/108683/slf4j-vs-log4j-which-one-to-prefer
> 
> SLF4J is basically an abstraction layer. It is not a logging implementation. It means that if you're writing a library and you use SLF4J, you can give that library to someone else to use and they can choose which logging implementation to use with SLF4J.
> 
>  e.g. log4j or the Java logging API. It helps prevent projects from being dependent on lots of logging APIs just because they use libraries that are dependent on them.So, to summarise: SLF4J does not replace log4j, they work together. It removes the dependency on log4j from your library/app.
> 

--

> from: https://www.slf4j.org/faq.html#when
> 
> When should SLF4J be used?
> In short, libraries and other embedded components should consider SLF4J for their logging needs because libraries cannot afford to impose their choice of logging framework on the end-user. On the other hand, it does not necessarily make sense for stand-alone applications to use SLF4J. Stand-alone applications can invoke the logging framework of their choice directly. In the case of logback, the question is moot because logback exposes its logger API via SLF4J.
> SLF4J is only a facade, meaning that it does not provide a complete logging solution. Operations such as configuring appenders or setting logging levels cannot be performed with SLF4J. Thus, at some point in time, any non-trivial application will need to directly invoke the underlying logging system. In other words, complete independence from the API underlying logging system is not possible for a stand-alone application. Nevertheless, SLF4J reduces the impact of this dependence to near-painless levels.
> Suppose that your CRM application uses log4j for its logging. However, one of your important clients request that logging be performed through JDK 1.4 logging. If your application is riddled with thousands of direct log4j calls, migration to JDK 1.4 would be a relatively lengthy and error-prone process. Even worse, you would potentially need to maintain two versions of your CRM software. Had you been invoking SLF4J API instead of log4j, the migration could be completed in a matter of minutes by replacing one jar file with another.
> SLF4J lets component developers to defer the choice of the logging system to the end-user but eventually a choice needs to be made.
>

**Comment by essiembre** [comment]
This request was already made as part of the JEF dependency: https://github.com/Norconex/jef/issues/6

I agree this would be ideal, but JEF is the reason why log4j was adopted and there are unanswered challenges in changing that.   Have a look a the JEF issue and please provide feedback there if you have any.
