### ISSUE TITLE
clean up option on the script

### ISSUE THREAD

**Issue by dgomesbr** [Norconex/collector-http#402]
Nowadays we have to options to start/stop/restart, but a new run is helpful when we're debugging and starting repeatedly the project.

The option would delete:

- work
- logs
- committer-queue
- progress

and start a fully new collect session.

**Comment by essiembre** [comment]
This is already on our TODO list so I'll mark it as a feature request.  One thing about logs... we can do it right now, but it may become difficult if we switch to SLF4J: https://github.com/Norconex/jef/issues/6

**Comment by dgomesbr** [comment]
@essiembre commented out the issues that you thought that you may have with SLF4J. Meanwhile will watch over there if you need a hand with it and then migrate it to here.

Do we have a tree or a mind map diagram on how all the norconex project relate to each other?

Best

**Comment by essiembre** [comment]
Here is a quick way to show relationships:

![resized_project-relationships](https://user-images.githubusercontent.com/2326274/31159094-8a7dad10-a894-11e7-946c-071e33b3b7fe.png)

There is also Norconex Commons Lang shared by all of these (utility classes).

You could also find the following flow diagram useful: https://www.norconex.com/collectors/collector-http/flow.

**Comment by essiembre** [comment]
Implemented in dev branch of v3.0.0.   There will now be a optional ``-clean`` flag when launching and a ``clean`` standalone command.
