### ISSUE TITLE
Question: Pooling on the HttpClient

### ISSUE THREAD

**Issue by dgomesbr** [Norconex/collector-http#403]
I don't really see where and if it's being used in anyhow the pooling for the HTTP connections opened by the GenericHttpClientFactory. Any tips on how to configure one for not incurring in costs creating those connections?

Thanks in advance

**Comment by essiembre** [comment]
The default one for Apache HttpClient is being used (PoolingHttpClientConnectionManager).

You can adjust its max number of connections on GenericHttpClientFactory with the following:

```xml
     <maxConnections>...</maxConnections>
      <maxConnectionsPerRoute>...</maxConnectionsPerRoute>
```

If you are concerned about performance, changing the "delay" setting from another issue you created may have more impact.

**Comment by dgomesbr** [comment]
@essiembre is somewhat related, just was curious about it.

Thanks!

**Comment by essiembre** [comment]
Does that mean your question has been answered? (can we close?)

**Comment by dgomesbr** [comment]
Totally, good to close!
