### ISSUE TITLE
Solr committer not working.

### ISSUE THREAD

**Issue by dhock194** [Norconex/collector-http#404]
I am trying to setup the Norconex collector to push to Solr. I have it connected to and populating Elasticsearch correctly, but I really need Solr working. The crawl will complete,but then error out on one of several issues when trying to commit to Solr. I have tried several example configs from your Github issues pages,but still not working. 

Last I tried was the following:

            
            <delay default="1500" />

            
            <httpURLFilters>
                <filter class="$urlFilter"
                    onMatch="include">http://www.aerospike.com/docs/.*</filter>
                <filter class="$urlFilter"
                    onMatch="exclude">.+\.(png|jpg|jpeg|gif|ico|css|js)$</filter>
                <filter class="$urlFilter"
                    onMatch="exclude">.+\?.*</filter>
            </httpURLFilters>
            <importer>
                <postParseHandlers>
                    
                    <tagger class="com.norconex.importer.tagger.impl.KeepOnlyTagger"
                        fields="document.reference,title" />
                    
                </postParseHandlers>
            </importer>
            
            <committer class="com.norconex.committer.solr.SolrCommitter">
                <solrURL>http://localhost:8983/solr/stage_posts</solrURL>
            </committer>

            
            

        </crawler>
    </crawlers>
</httpcollector>

Error this one is generating is:
aused by: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr/stage_posts: [doc=http://www.aerospike.com/docs/client/perl/install/] missing required field: PI

Is there a known working committer config for Solr I can use? So far all of the example commit configs I have found generate errors and do not complete the commit.

**Comment by dgomesbr** [comment]
You've probably declared PI as unique (so it's mandatory). Make sure it's always filled otherwise it'll fail. Looks like a Solr usage related instead of Norconex.

Can you log the output with ```<tagger class="com.norconex.importer.handler.tagger.impl.DebugTagger" logContent="true"/>``` so you see if's something is missing? 

You could also output to a folder and analyze the data there to see why it's failing.

**Comment by essiembre** [comment]
Due to lack of feedback and because, as @dgomesbr pointed out, this is rather a Solr configuration issue, I am closing.  Please open a new ticket under the [Solr Committer](https://github.com/norconex/committer-solr/issues) project if you suspect a problem with it.
