### ISSUE TITLE
Can we use TextPatternTagger to get a section within html body as field value?

### ISSUE THREAD

**Issue by inpsolr** [Norconex/collector-http#406]
Hi there,

I am trying to add a lower weight to a certain section of my webpage. To that, I have created a Field in the Collection and want to add to the Field the text from that section in the webpage. I could then add relevancy boost to the new Field. 

My problem is that I am not being able to get the text into the new Field using the TextPatternTagger. Here is how I have modified my crawler's config.xml. The text I need is between the DIVs with class value set to referencesdiv and Footer:

```
      <importer>
        <postParseHandlers>
            ...
            <tagger class="com.norconex.importer.handler.tagger.impl.TextPatternTagger" >
              <pattern field="fooref">
                  referencesdiv*Footer
              </pattern>
           </tagger>
        </postParseHandlers>
      </importer>

```

Note: I cleared my existing index and cleaned up the working directories before recrawling. I can also see the new field in the Schema Browser in Solr admin. 

What am I missing or doing wrong?

**Comment by essiembre** [comment]
There are a few things:  

1. You are using it as a post-parse handler.  At that point, you'll only have the extracted text (no HTML tags).  If you want to match HTML tags/attributes, you should define it as a pre-parse handler.
2. The pattern must be a regular expression.
3. Since you are dealing with HTML, you may want to restrict this tag to HTML files only (``<restrictTo ...>``.
3. If you are using the snapshot version (more flexible), you can have match groups in your regular expression and use ``valueGroup`` to extract just the value you want from your pattern.
4. If you are dealing with HTML, it may be worth having a look at ``DOMTagger`` instead.

**Comment by inpsolr** [comment]
@essiembre Thank you very much for your answer. 

> 1. You are using it as a post-parse handler. At that point, you'll only have the extracted text (no HTML tags). If you want to match HTML tags/attributes, you should define it as a pre-parse handler.  

I will take this suggestion.

> 2. The pattern must be a regular expression.  

My target content is between two div tags as follows: 
```
<div id="referencesdiv">
    My Content
</div>
<div class="Footer">
...
```
That is why I am matching any and all text between the terms "referencesdiv" and "Footer" with this regular expression: `referencesdiv*Footer`

> 3. Since you are dealing with HTML, you may want to restrict this tag to HTML files only (<restrictTo ...>.  

I will take this suggestion.

> 4. If you are using the snapshot version (more flexible), you can have match groups in your regular expression and use valueGroup to extract just the value you want from your pattern.  

I will have to look into this. How do I find out if I am using the snapshot version? What is a snapshot version?

> 5. If you are dealing with HTML, it may be worth having a look at DOMTagger instead.

I considered it, but looks like DOMTagger will be more memory intensive and slower as per DOMTagger documentation. Unless I understood it wrong.

**Comment by essiembre** [comment]
2. Regex: even with the dot (.*), you will get some unwanted tags/text, you may want to refine it a bit.

4. A snapshot version is a version currently in development and it can still evolve before being made a formal release.  You can get the latest snapshot version from the [download page](https://www.norconex.com/collectors/collector-http/download).

If the field name is not dynamic, you can keep using the ``field`` attribute.  Assuming the "Footer" div is important to keep to isolate the "referencesdiv" you want, you can try something like this (untested):

```xml
<pattern field="fooref" valueGroup="1"><![CDATA[
    <div id="referencesdiv">(.*?)</div>\s+<div class="Footer">
]]></pattern>
```

5. DOMTagger: for average HTML documents (a few KB as opposed to several MB), you should not notice any difference.

**Comment by essiembre** [comment]
Are you good with this now?  Can we close?

**Comment by inpsolr** [comment]
Yes. You replies were very helpful. We can close this thread. Thank you so much for your near-real-time replies, solutions, and suggestions!
