### ISSUE TITLE
Opinions on Using Norconex and Solr as Replacement to Discontinued Google Site Search

### ISSUE THREAD

**Issue by dhildreth** [Norconex/collector-http#409]
All,

I'm wondering what your thoughts are using Norconex and Solr as a replacement for the now discontinued Google Site Search (Google Custom Search Engine).  We've been using GSS on our eCommerce website for a while, and we enjoy the ease of use.  There are times where we wish we had a little more control over the results, but overall, been happy with it and the user-friendly results it returns.

I've been able to get Norconex and Solr to play nicely together on our sever, but before I get too far, I'm wondering if this is the right direction to take.  I can see some potential difficulties along the way:

- Faceted results
  - For example, breaking results into different categories or tabs like Web, Images, Forum, etc.
- Clean descriptions
  - Google results are very smart about displaying a short description of the page with search term highlighting.
  - Google uses truncated meta description or truncated body text depending on which is more relevant to users search terms.
- Indexing PDFs
- Ability to promote or weigh particular pages over others
  - For example, a product page should always rank higher than a support page for that product
- Maintenance
  - We don't want to be search engine or crawler experts to have a search on our webpage.
  - I'm not sure how Solr 'fields' plays into all this, but they sure seem like a PITA.
- Scheduled crawling
  - I imagine there's an easy solution for this one.
- Synonyms
  - Keywords that are similar

I'd love to know what your thoughts are on the subject.  What are other people using for their websites?  Is a Solr + Norconex solution too heavy or overkill for this use case?

**Comment by essiembre** [comment]
This "combo" is used with success by several organizations already and your identified challenges are usually easily addressed.  

How big is your site? A hosted site search solution and a self-hosted search infrastructure solution are two totally different beasts. From your comments, the question I think you ask yourself first is how much control and flexibility do you want/need from your search solution vs adopting a no effort but "canned" solution.  IT capacity, infrastructure, budget, etc. will help you decide.

To take advantage of the flexibility offered by both Norconex HTTP Collector and Solr and have a tailored solution, you have to be ready to learn their basics and spend some time and effort to install and configure them properly. 

If playing with Solr fields is a pain for you and you were rather satisfied with Google Site Search features, I would suggest you investigate going with a hosted site search solution alternative (you can contact Norconex for help).  

If you decide on getting hands-on, not only can you build a comparable solution for your end-users with Norconex HTTP Collector and Solr, but you can offer something better, unique to your site.

**Comment by dhildreth** [comment]
Well, I suppose I've gotten this far.  Our site isn't very large, probably less than 2000 pages to index.    I'm just struggling with some of the finer points I wouldn't have expected to struggle with.

I just tried out two other third party search tools (addsearch.com and sitesearch360.com), and neither had very good description text.  They seem to really like grabbing header and footer text that shows up on all pages.

I'll continue to review the Norconex documentation to see where I can get in the next couple days.  I always have the others to fall back on if needed.
