### ISSUE TITLE
Cleanup Whitespace and Newline Characters in Content

### ISSUE THREAD

**Issue by dhildreth** [Norconex/collector-http#416]
Is there anyway to clean up the content a little in `postParseHandlers` or otherwise?  I'm currently getting all sorts of '\n' newline characters and lots of whitespace.  I'd love to clean that up before committing to the index.  Maybe there's a function I'm missing?

**Comment by essiembre** [comment]
You can first try [ReduceConsecutivesTransformer](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/impl/ReduceConsecutivesTransformer.html).

If you need more flexibility, you can use regular expression to perform search and replace with [ReplaceTransformer](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/impl/ReplaceTransformer.html)

Let me know how that goes for you.

**Comment by dhildreth** [comment]
While ReduceConsecutivesTransformer seemed to help, I ultimately preferred to use ReplaceTransformer.  This is what I ended up with:

          <transformer class="com.norconex.importer.handler.transformer.impl.ReplaceTransformer" caseSensitive="false">
              <replace>
                  <fromValue>\n</fromValue>
                  <toValue xml:space="preserve"> </toValue>
              </replace>
              <replace>
                  <fromValue>\r</fromValue>
                  <toValue xml:space="preserve"> </toValue>
              </replace>
              <replace>
                  <fromValue>\t</fromValue>
                  <toValue xml:space="preserve"> </toValue>
              </replace>
              <replace>
                  <fromValue>[ ]{2,}</fromValue>
                  <toValue xml:space="preserve"> </toValue>
              </replace>
          </transformer>

One more further question about this...  I'd like to also clean up the text in a field created using `TextBetweenTagger`.  The ReplaceTransformer only works on the content field.  Is there a way to cleanup this 'breadcrumb' field as well?

         <tagger class="com.norconex.importer.handler.tagger.impl.TextBetweenTagger" >
            <textBetween name="breadcrumb">
               <start>BEGINBREADCRUMB</start>
               <end>ENDBREADCRUMB</end>
            </textBetween>
          </tagger>

**Comment by essiembre** [comment]
Transformers target content while taggers target fields.   For fields, you can use: [ReplaceTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ReplaceTagger.html).

**Comment by dhildreth** [comment]
Most excellent!  Thank you.  I went with:

          <tagger class="com.norconex.importer.handler.tagger.impl.ReplaceTagger">
              <replace fromField="breadcrumb" replaceAll="true" regex="true" caseSensitive="false">
                  <fromValue>[ \t\r\n]{2,}</fromValue>
                  <toValue xml:space="preserve"> </toValue>
              </replace>
              <replace fromField="breadcrumb" replaceAll="true" regex="true" caseSensitive="false">
                  <fromValue>[\t\r\n]{1,}</fromValue>
                  <toValue xml:space="preserve"> </toValue>
              </replace>
          </tagger>

This seems to work perfectly, thank you.  We can close this if you'd like, but I have one final question for you if I may.  There appears to be an initial space in the content field.  Normally, I'd use the regex `^ {1,}` and replace with nothing, but that doesn't seem to be working in this case.

              <replace>
                  <fromValue>^ {1,}</fromValue>
                  <toValue></toValue>
              </replace>

Interestingly enough, the exact same regex for ReplaceTagger works perfectly.

              <replace fromField="breadcrumb" replaceAll="true" regex="true" caseSensitive="false">
                  <fromValue>^ {1,}</fromValue>
                  <toValue></toValue>
              </replace>

Any words of wisdom?

**Comment by dhildreth** [comment]
How would one replace with nothing?  For example, I'd like to replace "delete me" with "" (null).  When attempting to use `<toValue></toValue>` or even `<toValue> </toValue>` (with space) I'm met with an error:

```
ERROR (XML Validation) ReplaceTagger: cvc-minLength-valid: Value '' with length = '0' is not facet-valid with respect to minLength '1' for type '#AnonType_toValuereplace'.
ERROR [XMLConfigurationUtil$LogErrorHandler] (XML Validation) ReplaceTagger: cvc-minLength-valid: Value '' with length = '0' is not facet-valid with respect to minLength '1' for type '#AnonType_toValuereplace'.
```
Is there a special character or something I could use to say replace with nothing?

**Comment by essiembre** [comment]
Despite the error, my testing shows that the replacement works by leaving the ``<toValue>`` empty.  This is an XML validation error which should not be triggered.  You can safely ignore until fixed in the next release.

**Comment by dhildreth** [comment]
Sounds good to me!  I'll ignore the error then and close this for now.

Also, just to mention, the error is thrown for `ReplaceTransformer` as well:

```
<transformer class="com.norconex.importer.handler.transformer.impl.ReplaceTransformer" caseSensitive="false">
              <replace>                                                                               
                  <fromValue>^\s*[\r\n]</fromValue>
                  <toValue></toValue>
              </replace>
</transformer>
```

**Comment by essiembre** [comment]
Thanks for letting me know about the transformer one.  This one will be fixed too.

**Comment by essiembre** [comment]
FYI, the latest snapshot release now eliminates the validation error and you can safely omit the "toValue" tag to replace with nothing.   This applies to both the ReplaceTagger and ReplaceTransformer.
