### ISSUE TITLE
Create a Field from Another Field?

### ISSUE THREAD

**Issue by dhildreth** [Norconex/collector-http#417]
I'd like to create what some might call content groups.  In third-party search providers, like addsearch.com, they provide a method for adding a group based on the URL.  For example, you might want to create a "Products" content group if the URL contains "/products/" (i.e. https://mydomain.com/products/foo-bar) and a "Documentation" content group if the URL contains "/wiki/".  A further example might be to create a content group based on the domain/subdomain.  So, I'd like to be able to separate results found on "www.mydomain.com" and "support.mydomain.com" into "Storefront" and "Support" content groups.  This would ultimately allow me to organize my search results in Solr to present to users.  I believe I'd be using Solr faceting to show these content groups.

So, my question is about extracting strings from an existing field into a new field.  In the example of the categories content group, I'd need to be able to do a regex search on _document.reference_ and extract to a new field called "category".  I could see using it like this:

```
<!-- Extract category name from URL -->
<tagger class="com.norconex.importer.handler.tagger.impl.FieldPatternTagger" >
  <pattern
    fromField="document.reference"
    toField="category"
    valueGroup="1"
    caseSensitive="false">
    <![CDATA["./(.*?)/.*"]]>
  </pattern>
</tagger> 

<!-- Extract domain name from URL -->
<tagger class="com.norconex.importer.handler.tagger.impl.FieldPatternTagger" >
   <!--https://stackoverflow.com/questions/29061521/regular-expression-to-match-only-domain-from-url-->
  <pattern
    fromField="document.reference"
    toField="domain"
    valueGroup="1"
    caseSensitive="false">
    <![CDATA["(?:^https?:\/\/([^\/]+)(?:[\/,]|$)|^(.*)$)"]]>
  </pattern>
</tagger> 
```

Is there currently a method for doing something like this?  Any tips or tricks you can offer me?  Thanks in advance.

**Comment by essiembre** [comment]
What you are describing is best provided by the [ReplaceTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ReplaceTagger.html).  You configure it in a way similar to your example. Here is a usage example assuming you just want the first segment to create your categories (not tested):

```xml
  <!-- Extract category name from URL -->
  <tagger class="com.norconex.importer.handler.tagger.impl.ReplaceTagger">
      <replace fromField="document.reference" toField="category" regex="true" wholeMatch="true">
          <fromValue><![CDATA[http://yourdomain.com/(.*?)/.*]]></fromValue>
          <toValue>$1</toValue>
      </replace>
      <!-- You can have many replace tags here. -->
  </tagger>
```

Does that work for you?

**Comment by dhildreth** [comment]
That's great!  Thank you.  I knew it probably already existed. :-)

**Comment by dhildreth** [comment]
This can be considered closed still, but if you don't mind, I have another question for you.  I feel like the regex used in the crawler follows a different set of rules I'm not familiar with.  How would you implement a "domain" tagger given document.reference URL?

The expression `^(?:https?:)?(?:\/\/)?(?:[^@\n]+@)?(?:www\.)?([^:\/\n]+)` works on regex101, but doesn't appear to work for the crawler.
[https://regex101.com/r/MOIFTy/3
](https://regex101.com/r/MOIFTy/3
)

I wonder if there'd be a simpler way of doing this.  Norconex collector http is written in Java, right?  What about a solution that would involve relying on [java.net.URI](http://docs.oracle.com/javase/7/docs/api/java/net/URI.html) instead of some complex regex?  Maybe though a plugin or something?

```
public static String getDomainName(String url) throws URISyntaxException {
    URI uri = new URI(url);
    String domain = uri.getHost();
    return domain.startsWith("www.") ? domain.substring(4) : domain;
}
```

**Comment by essiembre** [comment]
The vast majority of regex options commonly used are supported in Java. You can find full details here: https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html

Your regex is indeed complex, but it does not need to be.  URLs will always be converted to absolute ones.  So the following would work to extract the domain (take group 1):  ``^.*?//(.*?)(/.*|$)``.  If you want the domain without "www", try this (pick group 2): ``^.*?//(www\.)?(.*?)(/.*|$)``

Of course, nothing prevents you from writing your own tagger that does it how you want.  If you would like that to be a feature request, please create a new ticket for this.

**Comment by dhildreth** [comment]
As per usual, I made things more complicated than they needed to be!  That regex worked perfectly. Thanks for the reference as well.
