### ISSUE TITLE
How to exclude common headers and footers available on all pages?

### ISSUE THREAD

**Issue by essiembre** [Norconex/collector-http#418]
Copied from https://github.com/Norconex/collector-http/issues/412#issuecomment-340241616, by @krishnateja-ravipati :

> I have a question regarding extracting content from a document.
>
> I would like to pick up only the content available in the body of the page and exclude common headers and footers available on all pages. The body is separated from rest of the page by <main> HTML tag. <main> HTML tag may also contain class and id in few pages.
> 
> Can you suggest which tagger would be suitable to implement my requirement?

**Comment by essiembre** [comment]
@krishnateja-ravipati, you have a few options.   I suggest you keep the ``<head>`` section if you want metadata fields extracted by the Importer parser.  So I would remove everything from ``<body...`` to ``<main...`` and strip everything after ``</main>`` up to ``</body>``.  Example using the [StripBetweenTransformer](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/impl/StripBetweenTransformer.html) pre-parse handler (not tested):

```xml
  <transformer class="com.norconex.importer.handler.transformer.impl.StripBetweenTransformer">
      <stripBetween>
          <start><![CDATA[<body.*?>]]></start>
          <end><![CDATA[<main.*?>]]></end>
      </stripBetween>
      <stripBetween>
          <start><![CDATA[</main>]]></start>
          <end><![CDATA[</body>]]></end>
      </stripBetween>
      <restrictTo field="document.contentType">text/html</restrictTo>
  </transformer>

```
I suggest you make sure to restrict this to HTML documents only to avoid issues with non-html documents (like done in above example).

If you want more flexibility you can also have a look at [ReplaceTransformer](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/impl/ReplaceTransformer.html).

Please confirm this works for you.

**Comment by krishnateja-ravipati** [comment]
@essiembre 

Thanks for the solution. It works according to my expectations. 

I use ReplaceTransformmer to replace special characters to text format, for example, & is replaced by and. Will also explore the functionality of this transformer to strip header and footer from my pages.

Thank You
Krishna Teja

**Comment by krishnateja-ravipati** [comment]
@essiembre ,

In continuation of above scenario, I would like to understand the default implementation if the document parser doesn't find a match to the expression given in **StripBetweenTransformer**.

Thank You
Krishna Teja

**Comment by essiembre** [comment]
If it does match anything, it should leave the content as is.  Are you witnessing something different?

One possible exception is if you try to read a binary file as text, then it may mess it up.  That's where the ``<restrictTo ...>`` comes in to play.

**Comment by krishnateja-ravipati** [comment]
No, I haven't yet encountered such a situation. I just wanted to understand default functionality if a page doesn't carry the regex matching tag.

I am sure we don't have any binary files on our websites. It's all HTML pages.

Thank you
Krishna Teja
