### ISSUE TITLE
What is format of <urlsFile>

### ISSUE THREAD

**Issue by flochman** [Norconex/collector-http#419]
Hi,

What is format of text file what is needed in` <urlsFile>` option?

I created plain text file and simple inserted rows of URLs but it seems it does not works.

Text file like:

http://www.web1.com
http://www.web2.com
http://www.web3.com

It gives me error:

ERROR: Execution failed for job : URL argument cannot be null

Thanks.

**Comment by flochman** [comment]
Ups, I found the problem.

My text file has a empty rows which are not allowed.

OK.

You can close this issue.

Thanks.

**Comment by essiembre** [comment]
Thanks for the update.  Know that the 2.8.0 snapshot version fixes the "blank lines" issue and will also ignore lines starting with ``#`` (comments).
