### ISSUE TITLE
Reject the URLs with 404 status in the sitemap

### ISSUE THREAD

**Issue by Navaminavu** [Norconex/collector-http#430]
Hi,
We have a sitemap to be crawled and we are having some URLs in the sitemap which gives 404 error as in the snapshot. 
![image](https://user-images.githubusercontent.com/29800957/33125772-d6ce75b6-cfa7-11e7-93f5-ef9cc38424aa.png)
Attaching config file Iam using for the crawler as well as Source of the HTML file in the  snap
[new 16.txt](https://github.com/Norconex/collector-http/files/1495796/new.16.txt)
[new 17.txt](https://github.com/Norconex/collector-http/files/1495802/new.17.txt)

Can you help us to reject these URLs or rather prevent them from being crawled

**Comment by essiembre** [comment]
URLs returning a 404 status code are always rejected by default.  Do you see some being indexed?  If so, they are probably not returning 404 even if they are "not found".  Not sure which browser you are using, but here is an example how to get the HTTP status code with Chrome: https://www.mkyong.com/computer-tips/how-to-view-http-headers-in-google-chrome/

If it is 200, you may want to let the website owner know so they could fix it.

In any case, you can filter those out based on a common pattern in the "404" pages.  You can use the ``RegexMetadataFilter`` as a post-parse handler in the Importer section.  The title seems to be a good candidate (not tested):
```xml
<filter class="com.norconex.importer.handler.filter.impl.RegexMetadataFilter"
          onMatch="exclude" field="title" >
      <regex>^404 Error.*</regex>
  </filter>
```
Let me know if that works for you.

**Comment by Navaminavu** [comment]
yes it worked for me. You can close this isue
Thank you
