### ISSUE TITLE
What is the best strategy for multiple sites

### ISSUE THREAD

**Issue by jacksonp2008** [Norconex/collector-http#431]
What is the best way to deploy with multiple sites?

For an individual config, I am thinking of launching from crontab:
```
0 4 * * * /home/xxx/norconex-collector-http-2.8.0-SNAPSHOT/collector-http.sh -a start -c zzzzzz/updates.xml 
```
pls let me know if there is a better way.  

I see that it's possible to have multiple crawlers in the config, but not sure if they execute in parallel or serially.  I want them to run when I specify, not serially.

So Is it better to have a single config.xml per site, or to have a separate config.xml per site and put each into crontab separately.

**Comment by essiembre** [comment]
There is no single answer to this. Please refer to this [FAQ](https://www.norconex.com/collectors/collector-http/faq#toc6) for pros and cons of the different approaches.

**Comment by jacksonp2008** [comment]
Got it, thanks!
