### ISSUE TITLE
Job suite execution failed: null

### ISSUE THREAD

**Issue by krithivasanchandran** [Norconex/collector-http#432]
Trying norconex http collector for the first time. Imported the jars in the lib folder into my classpath and created the below code in Scraper.java :

> 
>  import com.norconex.collector.http.HttpCollector;
> import com.norconex.collector.http.HttpCollectorConfig;
> import com.norconex.collector.http.crawler.HttpCrawlerConfig;
> import com.norconex.jef4.suite.JobSuite;
> 
> public class Scraper {
> 
>     public static void main(String[] args) {
>         HttpCollectorConfig collectorConfig = new HttpCollectorConfig();
>         collectorConfig.setId("youtube crawler");
>         collectorConfig.setLogsDir("C:/Users/Krithivasan.Chandran/Desktop/prolese");
> 
>         HttpCrawlerConfig crawlerConfig = new HttpCrawlerConfig();
>         crawlerConfig.setStartURLs("http://www.youtube.com");
>         collectorConfig.setCrawlerConfigs(crawlerConfig);
> 
>         HttpCollector collector = new HttpCollector(collectorConfig);
>         JobSuite jobsuite = collector.createJobSuite();
>         
>         collector.start(true);
>     }
> }
>

On running the code I am getting : 

FATAL - JobSuite                   - Job suite execution failed: null
java.lang.NullPointerException

Can you please help me on this .

**Comment by essiembre** [comment]
Crawlers must have a unique id.  You are missing this:
```java
crawlerConfig.setId("MyCrawler");
```
I realize this line was also missing from the sample code on the "Getting Started" page.  I have updated it.

Please confirm.

**Comment by krithivasanchandran** [comment]
![crawlererror1](https://user-images.githubusercontent.com/8763778/33228040-ec99e18c-d1d7-11e7-9035-1c2e316736dd.png)
![crawlererror2](https://user-images.githubusercontent.com/8763778/33228035-e36eb72c-d1d7-11e7-861a-cfd9880f69fa.png)

Thanks for getting back to me. I have made the required changes but still, it looks like there seems to be a null pointer exception. I have attached the screenshots. Does it go to do with Log Directory that I have mentioned. 

DEBUG - FileLogManager             - Log directory: C:\Users\Krithivasan.Chandran\Documents\p1.log
FATAL - JobSuite                           - Job suite execution failed: null

Thanks in advance
Krithivasan

**Comment by krithivasanchandran** [comment]
Its working fine now. The url: https://www.norconex.com/collectors/collector-http/getting-started reflects the changes as mentioned above. Looks like it is one of the great crawlers that you guys have now . I have used crawler4j but this one seems to be pretty advanced. 

Do you have ebook on this - Just would like to spread the word :) 👍

**Comment by essiembre** [comment]
No ebook yet!  We are focusing on online docs now, but we may consider if enough demand.  Thanks for the feedback!

**Comment by ciroppina** [comment]
Sorry, maybe this issue should be re-opened

Code provided (see _below_) makes no-use of the created JobSuite, then starts the connector:
```
HttpCollector collector = new HttpCollector(collectorConfig);
JobSuite jobsuite = collector.createJobSuite();    
collector.start(true);

```
I have the same error: 

> FATAL - JobSuite - Job suite execution failed: null
> java.lang.NullPointerException
> 	at java.lang.Thread.setName(Thread.java:1122)

and my configuration has the crawlerConfig.id sat; my Java class is a bit huge, so I attach it as file


[NorconexCollectorService.zip](https://github.com/Norconex/collector-http/files/3060464/NorconexCollectorService.zip)

**Comment by ciroppina** [comment]
Dear Sirs, I beleive the error reported in the prev comment happens when in a Java-programatically configured **HttpCollectorConfig** proper Listeners are missing or undefined
The same is true when Listeners are lacking in configuration of **HttpCrawlerConfig** 

I solved the this error by loading configuration (of both Config objetcs) from XML; then programmatically adding to them only some features, as:
- list of startUrls
- list of config variables
- orphans strategy
- some Authentication headers

The error does not appear anymore; now all work fine
