### ISSUE TITLE
ERROR [AbstractCrawler]  Invalid language code 

### ISSUE THREAD

**Issue by angelo337** [Norconex/collector-http#433]
Hi there:
I am trying to crawl a site, and I am getting this error:

> ERROR [AbstractCrawler] SIC_website: Could not process document: http://www.sic.gov.co/node/13544 (Invalid language code)
ERROR [AbstractCrawler] SIC_website: Could not process document: http://www.sic.gov.co/node/13543 (Invalid language code)
ERROR [AbstractCrawler] SIC_website: Could not process document: http://www.sic.gov.co/node/13549 (Invalid language code)
ERROR [AbstractCrawler] SIC_website: Could not process document: http://www.sic.gov.co/node/13550 (Invalid language code)
ERROR [AbstractCrawler] SIC_website: Could not process document: http://www.sic.gov.co/node/13551 (Invalid language code)
ERROR [AbstractCrawler] SIC_website: Could not process document: http://www.sic.gov.co/node/13552 (Invalid language code)

could you please help me with some information regarding how to solve this? please

thanks a lot
angelo

**Comment by essiembre** [comment]
Which version of HTTP Collector are you using?  Can you share your config (at least the minimum to reproduce)?  It crawls without issues when I try it.

**Comment by angelo337** [comment]
Hi there Pascal:
 I am using 2.8, and that happens, when I enable this config:

`                  <ocr path="/usr/bin/tesseract/">
                    
                    <contentTypes>application/pdf</contentTypes>
                  </ocr>`

if I comment out like in there, there is no issue at all

**Comment by essiembre** [comment]
Do you have "es" and "en" language packs installed for Tesseract? If so, chances are you have to use the 3-letter codes for them.  To find out the languages supported by your current Tesseract install, you can launch:

```
tesseract.exe --list-langs
```

If a language you use is not listed, you can probably find a language pack for it here: https://github.com/tesseract-ocr/tesseract/blob/master/doc/tesseract.1.asc#languages

**Comment by angelo337** [comment]
Pascal:
thanks for your answer, I am testing it, is there any way to configure the conversion of resolution? as with all the configuration that i tested i am getting just a bunch of \n characters.

**Comment by essiembre** [comment]
What do you mean by "conversion of resolution".  You want to do OCR with Tesseract, right?  If so, Tesseract is configured externally.  Can you elaborate?

**Comment by angelo337** [comment]
Pascal:
when you try to convert a PDF file to TXT you would need to do at least a little bit more than just pass the PDF, as Tesseract don't understand PDF format because PDF is just a format that emmbeded images we need to extract all images to an image format, that can be achieve it by passing you PDF file to the convert tool as in the following code: 

> `convert -density 300 target.pdf -depth 8 -strip -background white -alpha off out.tiff`

after that you need to pass this new TIFF file to Tesseract.
however when you try to include that first command I get an error like "Permission Denied"

> `tesseract out.tiff output`

Output is you file in TXT format 
thanks

**Comment by essiembre** [comment]
With the Importer module, Tesseract can work with PDFs.  The images should be extracted and passed to Tesseract without you doing anything special (other than pointing to your Tesseract installation).  So you should not need an external transformer.  This is done in the importer module by the [GenericDocumentParserFactory](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/parser/GenericDocumentParserFactory.html).  Here is the relevant configuration snippet you need to adapt:
```xml
<importer>
  ...
  <documentParserFactory>
      <ocr path="(path to Tesseract OCR software install)">
          <languages>
              (optional coma-separated list of Tesseract languages)
          </languages>
          <contentTypes>
              (optional regex matching content types to limit OCR on)
          </contentTypes>
      </ocr>
  </documentParserFactory>
  ...
</importer>
```

**Comment by angelo337** [comment]
Pascal:
thanks for your answer, I try several config's and there is no way to extract text from PDF's files with just that configuration, all time the crawling return to me just an empty content field. that might be my mistake, but my only way to use that OCR is an external transformer.

**Comment by essiembre** [comment]
Can you share one of those PDFs?

**Comment by angelo337** [comment]
Sure:
http://www.sic.gov.co/recursos_user/clasificacion-de-niza/clasificacion-internacional-de-niza-v11-notas-explicativas.pdf
http://www.sic.gov.co/recursos_user/documentos/Guia_de_aplicacion_NIIF.pdf
http://www.sic.gov.co/sites/default/files/files/Contratos/ejecucion_contratual_2017.pdf
http://www.sic.gov.co/sites/default/files/files/Estadisticas_Mensuales_Marcas_2015_Actualizacion_2016-03-27.pdf
http://www.sic.gov.co/sites/default/files/files/Estadisticas_Patentes_2014.pdf
http://www.sic.gov.co/sites/default/files/files/Cuadro_Leyes_Definitivo.pdf
http://www.sic.gov.co/sites/default/files/files/Guia-de-Colombia-PPH-EPO-2.pdf
http://www.sic.gov.co/sites/default/files/files/Estadisticas_Mensuales_Patentes_Disenos_2015(1).pdf
http://www.sic.gov.co/sites/default/files/files/Denominacion%20de%20Origen/Agro%20-%20Alimenticios/arroz-meseta-ibague/resolucion-76532-de-2016.pdf
http://www.sic.gov.co/sites/default/files/files/Ejemplo%20busqueda%20Tecnologica%20Internacional.pdf
http://www.sic.gov.co/sites/default/files/files/Nuestra_Entidad/Carta-Trato-Digno-2017-06-23.pdf
http://www.sic.gov.co/sites/default/files/files/Manual-de-Usuario-5-RNBD-01032017.pdf
http://www.sic.gov.co/sites/default/files/files/PC01-F02.pdf
http://www.sic.gov.co/sites/default/files/files/Propiedad%20Industrial/Estadisticas/Estadisticas_Mensuales_Marcas_2017_06-21.pdf
http://www.sic.gov.co/sites/default/files/files/Procedimiento-SIC-OEPM-pph-2013-10-17.pdf
http://www.sic.gov.co/sites/default/files/files/Procedimientos-SIC-PPH-Corea-2016-02-24.pdf
http://www.sic.gov.co/sites/default/files/files/Informe%20de%20a%C3%B1o%202013%20integraciones.pdf
http://www.sic.gov.co/sites/default/files/files/Presentacion.pdf
http://www.sic.gov.co/sites/default/files/files/PI03-F01%20Vr2.pdf
http://www.sic.gov.co/sites/default/files/files/PI02-F05%20Vr_8.pdf
http://www.sic.gov.co/sites/default/files/programacion-gaceta-2017.pdf
http://www.sic.gov.co/sites/default/files/normatividad/062017/DECRETO-1115-DEL-29-DE-JUNIO-DE-2017.pdf
http://www.sic.gov.co/sites/default/files/files/procedimientocolombia-USPTO.pdf
http://www.sic.gov.co/sites/default/files/files/Propiedad%20Industrial/Estadisticas/PATENTES-2016-Ver-2017-01-14.pdf
http://www.sic.gov.co/sites/default/files/files/RTA%20DISE%C3%91O(1).pdf
http://www.sic.gov.co/sites/default/files/files/Propiedad%20Industrial/Estadisticas/MARCAS-2016-Ver-2017-01-15.pdf
http://www.sic.gov.co/sites/default/files/files/guia_de_colombia_pph2016(1).pdf
http://www.sic.gov.co/sites/default/files/files/instructivo_modelo_ach_protegido.pdf
http://www.sic.gov.co/sites/default/files/files/directoriocamaras2014.pdf
http://www.sic.gov.co/sites/default/files/files/Ranking_Patentes_y_Disenos_2015.pdf

**Comment by essiembre** [comment]
I just tried the following and it worked for me: http://www.sic.gov.co/sites/default/files/files/instructivo_modelo_ach_protegido.pdf

That is all I had in my importer config section for testing this file:
```xml
<importer>
  <documentParserFactory>
      <ocr path="C:\Apps\Tesseract-OCR"/>
  </documentParserFactory>
</importer> 
```
You can see from the following two files that the text was extracted properly, and there is more text when I enable OCR.  I used Tesseract default languages (I did not specify any language for this test... so not all characters may be good):
[OCR-http-443_instructivo_modelo_ach_protegido.pdf.txt](https://github.com/Norconex/collector-http/files/1537202/OCR-http-443_instructivo_modelo_ach_protegido.pdf.txt)
[NO-OCR-http-443_instructivo_modelo_ach_protegido.pdf.txt](https://github.com/Norconex/collector-http/files/1537203/NO-OCR-http-443_instructivo_modelo_ach_protegido.pdf.txt)

**Comment by angelo337** [comment]
Pascal:
I have to figure out, why do not work for me then.
thanks a lot for you patience and time
