### ISSUE TITLE
Sessions + PhantomJS

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#437]
Hello!

I highly appreciate authentication mechanism implemented in collector-http, and PhantomJS making screenshots added at version 2.8.0.

Trying collect screenshots of HTTPS site's pages with form authorization. Using the approach mentioned at https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/PhantomJSDocumentFetcher.html

```xml
     <collectorListeners>
          <listener class="com.norconex.collector.http.fetch.impl.HttpClientProxyCollectorListener" port="9090"/>
     </collectorListeners>
     ...
      <documentFetcher
         class="com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher" 
         screenshotEnabled="true"
      >
      ...
```
The log contain following lines:
```
    INFO  [HttpClientProxy] HTTPClient proxy started on port 9090.
    ...
    INFO  [CrawlerEventManager] DOCUMENT_METADATA_FETCHED: https://admin.somehost.com
    INFO  [PhantomJSDocumentFetcher] PhantomJS screenshot enabled: true
    ERROR [PhantomJSDocumentFetcher] PhantomJS:
       http://admin.somehost.com/: Host http://localhost not found
       Unsuccessful loading of: http://admin.somehost.com (status=fail).
       Content: <html><head></head><body></body></html>
    ERROR [PhantomJSDocumentFetcher] Screenshot file not created for https://admin.somehost.com
    INFO  [CrawlerEventManager]  REJECTED_BAD_STATUS: https://admin.somehost.com     (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=-1, reasonPhrase=null])
```
The site redirects to HTTPS anyways.

Why PhantomJS can't find http://localhost? Assuming it is connecting to the proxy, what is the problem?
Which setup is required to continue crawling via HTTPS, not HTTP?

**Comment by essiembre** [comment]
I just tested and the proxy is being used properly in my case.  On the other hand, I notice an issue when using the proxy with ``https`` sites.  The redirect to https should not occur if your URL start with https to begin with. 
 This was just fixed in the latest snapshot release.  Please give it a try and confirm.

**Comment by AntonioAmore** [comment]
I confirm that GenericDocumentFetcher + Proxy works and worked perfect from 2.8.0.

But using PhantomJSDocumentFetcher even with the lastest snapshot brings me the following:

    ERROR [PhantomJSDocumentFetcher] PhantomJS:
    http://admin.somesite.com/: Host http://localhost not found
    Unsuccessful loading of: http://admin.somesite.com (status=fail).
    Content: <html><head></head><body></body></html>

Hope the PhantomJS command line used by the collector helps:

`usr/bin/phantomjs --ssl-protocol=any --ignore-ssl-errors=true --web-security=false --cookies-file=/tmp/cookies.txt --load-images=true --proxy=http://localhost:9090 --proxy-auth=bindId:1 --ignore-ssl-errors=true /norconex-collector-http-2.8.1-SNAPSHOT/scripts/phantom.js http://admin.somesite.com/home/index /tmp/1512735467025000001 3000 1 https /tmp/1512735467025000000.png 1920.0x1080.0 1.0 -1`

**Comment by essiembre** [comment]
Does the page you are trying to crawl contains any "localhost" reference?  Because your log does not indicate it is tied to the proxy (it likely is, but just to make sure).

Does it work if you do not use the proxy (removing your listener)?

It is also possible the proxy is not accessible for security reasons on your system.  One thing you can try is to add a ridiculously high delay in your crawler (or put a debug breakpoint if you are using an IDE).  Then while the crawler is running and the proxy started, try the phantomjs command directly on the command prompt and see what you get.  Like this:

```xml
<delay class="com.norconex.collector.http.delay.impl.ReferenceDelayResolver"
          ignoreRobotsCrawlDelay="true">
      <pattern delay="1 day">.*</pattern>
</delay>
```

**Comment by AntonioAmore** [comment]
The page doesn't contains "localhost" word at all.

When removing the listener, it works perfectly, of course, for "open" links which doesn't require authorization + session.

Added the delay proposed in the message above I get the following:

Setting `--proxy=https://127.0.0.1:9090` to PhantomJS command received
    
    ERROR [PhantomJSDocumentFetcher] PhantomJS:
    http://admin.somesite.com/: Host http://127.0.0.1 not found
    Unsuccessful loading of: http://admin.somesite.com (status=fail).
    Content: <html><head></head><body></body></html>

I can provide some information about my system which may be helpful for investigation:

    sudo netstat -nlp|grep 9090
    tcp6       0      0 :::9090                 :::*                    LISTEN      9018/java

    sudo ss -lptn 'sport = :9090'
    State       Recv-Q Send-Q                                                   Local Address:Port                                                     Peer Address:Port 
    LISTEN      0      50                                                                  :::9090                                                               :::* 

As you can see above, `localhost` means the proxy, added by the listener, not a link from a page for being crawled. Actually, I don't know, why it has no IP address assigned, maybe it is the problem' reason.

**Comment by essiembre** [comment]
The proxy is http, not https.  It will take care of loading https sites properly.  

Can you "ping 127.0.0.1", or get the IP with "nslookup localhost" ?

Assuming your run it on Linux, do you have ``localhost`` defined in ``/etc/hosts`` ?

If not I would add it and try again.  E.g.:
```
127.0.0.1		localhost.localdomain localhost
```

If you are using only IPV6 for some reason, I would map localhost to the IPV6 loopback (``::1``)

**Comment by essiembre** [comment]
Which version of phantom JS are you using?  I researched your error, and older versions were generating that exact error with localhost when the scheme (http/https) was passed to the --proxy parameter.  The latest version should not have that issue.  I just tried on Linux (Fedora) with the latest phantomjs version and it worked just fine for me.

**Comment by AntonioAmore** [comment]
I'm using phantomJS 1.9.0. Which version is on your side?

**Comment by essiembre** [comment]
I am using the latest: 2.1.1.   That's probably the issue.  The [PhantomJSDocuumentFetcher](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/PhantomJSDocumentFetcher.html) supports 2.1+.   Can you try with the latest version of PhantomJS?

**Comment by AntonioAmore** [comment]
I have downloaded 2.1.1, and got the following:


    INFO  [PhantomJSDocumentFetcher] PhantomJS screenshot enabled: true
    Exception in thread "StreamConsumer-STDOUT" com.norconex.commons.lang.io.StreamException: Problem consuming input stream.
     at com.norconex.commons.lang.io.InputStreamConsumer.run(InputStreamConsumer.java:102)
    Caused by: java.io.IOException: Stream closed
	    at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
	    at java.io.BufferedInputStream.read(BufferedInputStream.java:336)
	    at java.io.FilterInputStream.read(FilterInputStream.java:107)
	    at com.norconex.commons.lang.io.InputStreamConsumer.run(InputStreamConsumer.java:97)
    ERROR [SystemCommand] Command returned with exit value 143 (command properly escaped?)...

and a lot of 'Host not found'

PhantomJS command is similar to one I already provided above. It delivers 'Connection refused' when I'm trying it from command line. I can open the url from my browser, and one doesn't require authorization.

**Comment by essiembre** [comment]
Can you share the URL of a page causing you trouble with a copy of your config?  Without it, I cannot replicate and makes it hard to help.

**Comment by essiembre** [comment]
Closing for not having the information to replicate.  If you still have the issue and can share the necessary information, feel free to re-open or create a new ticket.
