### ISSUE TITLE
parsed document thumbnail

### ISSUE THREAD

**Issue by douglas-andrew-harley** [Norconex/collector-http#439]
Hello,

Is it possible to generate a thumbnail screenshot for parsed documents that are being crawled and committed to Solr? I see that phantomjs can take screenshots of HTML pages, but I need for things like PDFs, Word docs/ppt, etc.

Thanks,
Doug

**Comment by essiembre** [comment]
This is not available out-of-the-box.  It would be tricky to implement given you would need a "viewer" (app or library) for each type.  There are open-source projects that attempt to do this, but only support a limited set of files.  A quick search revealed the following: 

* https://github.com/btimby/thumbnailer (Python)
* https://github.com/kig/thumbnailer (Ruby)
* https://github.com/benjaminpick/java-thumbnailer/ (Java)

Not sure how well they work and in some cases, you may have to run them as an external application.

Your best integration option is probably to implement your own [IDocumentTransformer](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/IDocumentTransformer.html) and configure it as a pre-parse handler in the Importer module.  If using an external process to do so, you can look at using the [ExternalTransformer](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/impl/ExternalTransformer.html).

**Comment by douglas-andrew-harley** [comment]
Aha, ok...yes, this seems like a risky bit of integration, and definitely not within the client's budget/timelines.

As always, thanks!
