### ISSUE TITLE
[URLCrawlScopeStrategy] HttpCrawlerConfig needs setter

### ISSUE THREAD

**Issue by sylvainroussy** [Norconex/collector-http#443]
Hi!

The HttpCrawlerConfig does not provide setter for URLCrawlScopeStrategy and I need it to personalize my scope.

**Comment by essiembre** [comment]
A setter method has been added to ``HttpCrawlerConfig`` and the member variable is no longer ``final``.  You cannot set that class via XML configuration though. Also, the method should really accept an interface instead, but doing so would require a bit of refactoring that will take more time to do.  That task has been added to the project internal TODO.  

In the meantime, I hope the new setter method and being able to subclass ``URLCrawlScopeStrategy`` can work for you.  That change is included in the latest snapshot. Please confirm.
