### ISSUE TITLE
loadCollectorConfigFromXML()  cannot be found

### ISSUE THREAD

**Issue by obxpete** [Norconex/collector-http#451]
I am getting this error when trying to call it from a fresh collectorconfig object.  

**Quick Background:**  I’m trying to run the java commands from within another java application.  I think i’ve got the dependency conflict problems worked out, but I’m having one more problem (so far) which may or may not be a holdover.

In short, if I dump a com.norconex.collector.http.HttpCollectorConfig object, I only get these 2 fields (see full dump image below for details).
java.lang.String DEFAULT_LOGS_DIR	./logs
java.lang.String DEFAULT_PROGRESS_DIR	./progress

 But, the parent class com.norconex.collector.core.AbstractCollectorConfig exposes all its methods.  

The end result is that loadCollectorConfigFromXML() , of course,  cannot be found.    Hope this question/answer will help others as well.  Thanks in advance,
 - Pete

![image](https://user-images.githubusercontent.com/2229671/34677146-2ad1c8d2-f45d-11e7-8133-7b6460817b30.png)

**Comment by essiembre** [comment]
The ``loadCollectorConfigFromXML`` method you are referring to is a protected method defined on ``AbstractCollectorConfig``.  If you are trying to access it as a public method, it may be why you are getting this error.

Another possible cause is when you "run the java commands from within another java application", the application runs without all its dependencies in its classpath.  In this specific case, it could be that ``norconex-collector-core-x.x.x.jar`` is likely not loaded.

Can you give more context info?  Maybe share your launch command (or code snippet doing the launch).

**Comment by obxpete** [comment]
Thank you @essiembre .  That is interesting about the protected method.  Here's the code I use.  It's a coldfusion application, so the syntax is a bit different, but if you can get past that, then it is most notable that the crawlerconfig, crawler, collector

`
//////////////////////
// 1. crawler config


	crawlerConfig = createObject("java", "com.norconex.collector.http.crawler.HttpCrawlerConfig");
	

	// straight test.  does the default crawlerconfig have its appropriate methods. ?
	//writeDump(crawlerConfig);  //YES

	urlsJavaArray = javaCast("string[]", [
			javaCast("string", "http://example1.com"),
			javaCast("string", "http://example2.com")
		]
	);

	crawlerConfig.setStartURLs(urlsJavaArray);

	writeDump(crawlerConfig); /// yes, this has its methods

//////////////////////
// 2. crawler obj

   crawlerObj = createObject("java", "com.norconex.collector.http.crawler.HttpCrawler").init(crawlerConfig);
	writeDump(crawlerObj);  /// yes, this has its methods


//////////////////////
// 3. collectorConfig

	collectorConfig = createObject("java", "com.norconex.collector.http.HttpCollectorConfig");

	// this has no methods of its own.  it shohave the 2.  all it has are some fields.
	writeDump(collectorConfig);abort;

	collectorConfig.setCrawlerConfigs(crawlerConfig);

//////////////////////
//4 . collector

	collector = createObject("java", "com.norconex.collector.http.HttpCollector").init(collectorConfig);`

As a last note, it is loading these jar files (among many others):
`"/Applications/ColdFusion11/cfusion/norconex_lib/norconex-collector-core-1.9.0.jar",
"/Applications/ColdFusion11/cfusion/norconex_lib/norconex-collector-http-2.8.1-SNAPSHOT.jar",`

**Comment by essiembre** [comment]
Looks like your ``writeDump`` function only writes declared methods on the concrete class, and does not handle its parents.

That being said, if you comment the ``writeDump`` calls, do you still get the ``loadCollectorConfigFromXML() cannot be found`` error?  Do you have more log entries you can share?

Does the collector run fine when launched manually from the command prompt? If so, the problem likely needs to be resolved within the ColdFusion app. You may want to seek guidance from the ColdFusion community.

**Comment by obxpete** [comment]
Just following up on this.  I was able to get it to compile (at runtime).  Basically I worked on both of your first 2 points made at the top of this thread to solve the problem.  Yay!  Thanks @pascaldimassimo !!

Sharing compiling code here.  To whom it may concern: this is written in CFScript (coldFusion).  But the lessons might be good for others who are trying to run norconex httpCollector from within another java application without having to extend norconex objects.  fwiw.


		/////////////
		// 0. javaLoader Config - use to load ALL norconex-specific jar files

		sourcePathsArr = ArrayNew(1);
		sourcePathsArr=
		[expandPath("[file path]/norconex_lib/annotations-12.0.jar"),... ;

		javaLoader = createObject("component", "javaloader.JavaLoader.Javaloader").init(sourcePathsArr); 

		//////////////////////
		// 1. crawler config

		crawlerConfig = createObject("java", "com.norconex.collector.http.crawler.HttpCrawlerConfig");

		// note: this javaCast is very much coldFusion-specific
		urlsJavaArr = javaCast("string[]", [
					javaCast("string", "http://mytestdomain.com/temptest.cfm")
				]
			);

			crawlerConfig.setStartURLs(urlsJavaArr);

		//////////////////////
		// 2. crawler obj

		crawlerObj = createObject("java", "com.norconex.collector.http.crawler.HttpCrawler").init(crawlerConfig);


		//////////////////////
		// 3. collectorConfig
		collectorConfig = javaLoader.create("com.norconex.collector.http.HttpCollectorConfig");
		collectorConfig.setId("myid");
		collectorConfig.setLogsDir("/library/webserver/documents/work/tmp/logs/");
		collectorConfig.setProgressDir("/library/webserver/documents/work/eggs");

		crawlerConfigsArr = [];
		crawlerConfigsArr[1] = crawlerConfig; 

		////  THIS really threw me off. Collector config takes crawler configs, not crawlers.  ?? ok..
		collectorConfig.setCrawlerConfigs(crawlerConfigsArr);

		//////////////////////
		//4 . collector
		collector = javaLoader.create("com.norconex.collector.http.HttpCollector").init(collectorConfig);
		
		crawlerObjArr = [];
		crawlerObjArr[1] = crawlerObj; 
		collector.setcrawlers(crawlerObjArr);
		collector.start(true);
