### ISSUE TITLE
Restricting the url extraction on limited date

### ISSUE THREAD

**Issue by AnwaarAshour** [Norconex/collector-http#454]
First I want to thank you for this great collector
Second I want to know is there is a filtering criteria to filter extracted urls on date or stop extraction when reach to date?
what I see now is that I can set the depth to limit number of extracted links but I want to always extract new   (not old puplished data) links only
Also is there a way to save only article documents?
Many thanks again

**Comment by essiembre** [comment]
Thanks for sharing your appreciation.  

There are a few options.  One can be to create different collectors with different URL filtering and running them at different times.  Within the same Collector, one way is to use the [GenericRecrawlableResolver](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/recrawl/impl/GenericRecrawlableResolver.html). Here is a reprint of the usage sample from the documentation:

```xml
  <recrawlableResolver 
         class="com.norconex.collector.http.recrawl.impl.GenericRecrawlableResolver"
         sitemapSupport="last" >
     <minFrequency applyTo="contentType" value="monthly">application/pdf</minFrequency>
     <minFrequency applyTo="reference" value="1800000">.*latest-news.*\.html</minFrequency>
  </recrawlableResolver>
```

To save only article documents, you need to know what pattern identifies them.  You can filter pages using URL patterns with something like [RegexReferenceFilter](http://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/filter/impl/RegexReferenceFilter.html).

You can also filter documents after they have been downloaded by using Importer filters (after their links were extracted).  It is useful if you want to filter out on specific fields that were extracted.  Have a look [here](http://www.norconex.com/collectors/importer/configuration#tbl-filter) for different filtering options in the Importer module.

Let me know if these answers work for you.

**Comment by AnwaarAshour** [comment]
Sorry but I think this does not solve the problem
I need to crawl websites to get today's articles only and make it stop extracting URLs if it reaches old one (not for today).
Is that applicable bu configuring the collector?
Thanks in advance.

**Comment by AnwaarAshour** [comment]
Also I have a question on SQLCommitter 
1. can you please provide me with a sample config file example for a local connection using xampp as example.
2. what is the table structure for the saved data
Many thanks

**Comment by essiembre** [comment]
By default, the crawler will only pick up new and modified pages on subsequent runs.  Could this meet your requirement?

If you need more control and assuming you are already extracting a date with your documents, you can use the [DateMetadataFilter](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/filter/impl/DateMetadataFilter.html) from the Importer module to perform date-based filtering.

Does that work for you?

For your SQL Committer question, please file it under the SQL Committer project.  There is an answer to a similar question already on that project: https://github.com/Norconex/committer-sql/issues/1.

**Comment by AnwaarAshour** [comment]
Many thanks for help.
I want to ask another question about the extracted URL 
for URLs that have Arabic characters, can it be saved in arabic
the same for importer contents.
Many thanks in advance

**Comment by essiembre** [comment]
Ultimately the extracted values finding their way to your Committer should all be UTF-8.  As such, Arabic should be supported.  Do you witness something else? If so please create a new ticket for this.
