### ISSUE TITLE
Duplicated entries on domain root

### ISSUE THREAD

**Issue by mauromi76** [Norconex/collector-http#455]
Hi
I searched the web for a solution but couldn't find it so I hope you can help me with this issue.

Basically we have a duplicated entry on the home page and that happens because in the HTML of website we are crawling there are some links that points to "http://doimain.com" and some that points to "http://domain.com/"; of course norconex indexes both and then submit them to Elastic Search and when we run the search we get both as result.

I'm aware that the fix could be done in the HTML and set all the links in a proper way, but we are running Norconex on 160 websites and this problem can occur in many of those websites so to fix the HTML may require a lot of time.

So I'm wondering if there's a way to make norconex detect that he's double indexing the same page.

My idea was to discard the second entry by matching the "page title" but couldn't find any solution on the web.

I also tried to use the "urlNormalizer" adding the parameter "removeTrailingSlash," which works fine, but then we have the opposite problem which means that if we try to crawl the url "http://domain2.com/subfolder/" this get discarded.

any idea?

thanks
Mauro

**Comment by essiembre** [comment]
Is ``http://domain2.com/subfolder/`` returning the same page as ``http://domain2.com/subfolder`` (without the slash)? If so, using ``removeTrailingSlash`` should work just fine. It will not reject the ``subfolder/`` URLs, it will convert them to ``subfolder``.    Are you experiencing a different behavior?  If so, please give an example URL or two.   

Keep in mind with the URL normalizer, you can also use regular expressions if something is not offered out-of-the-box.

**Comment by mauromi76** [comment]
Hi
no, http://domain2.com/subfolder return an error so it must be http://domain2.com/subfolder.

Regular Expression may work, but what can be the way to make the domain name dynamic?

I have an xml with 160 "<crawler>"; how can I make it work for all of them at once?

thanks
Mauro

**Comment by essiembre** [comment]
You have twice the same URL in your last example.

For the domain, maybe you can use the ``GenericURLNormalizer`` to always add a slash with ``addDomainTrailingSlash`` and for subdirectories, you have it without it?

Maybe I am getting it wrong.  Is this what you are after?

```
http://www.domain.com   ->  http://www.domain.com/
http://www.domain.com/  ->  http://www.domain.com/

http://www.domain.com/subfolder   ->  http://www.domain.com/subfolder
http://www.domain.com/subfolder/  ->  http://www.domain.com/subfolder
```
Or is it the opposite?

**Comment by wolverline** [comment]
It is interesting that I have same issue in Elasticsearch. For that reason, I use domain name with a slash (ex. http://sub.domain.com/) as starting point.
