### ISSUE TITLE
Can crawlDataStoreFactory and committer coexist?

### ISSUE THREAD

**Issue by wolverline** [Norconex/collector-http#459]
I've faced a strange issue. I am trying to add crawled urls to MongoDB and commit the data to Elasticsearch at the same time. When I run without `crawlDataStoreFactory` config setup, it works fine. 
<pre>
INFO  [AbstractCrawler] single: Reprocessing any cached/orphan references...
INFO  [AbstractCrawler] single: Crawler finishing: committing documents.
INFO  [AbstractFileQueueCommitter] Committing 16 files
INFO  [ElasticsearchCommitter] Sending 16 commit operations to Elasticsearch.
INFO  [ElasticsearchCommitter] Done sending commit operations to Elasticsearch.
INFO  [ElasticsearchCommitter] Elasticsearch RestClient closed.
INFO  [AbstractCrawler] single: 26 reference(s) processed.
INFO  [CrawlerEventManager]          CRAWLER_FINISHED
INFO  [AbstractCrawler] single: Crawler completed.
INFO  [AbstractCrawler] single: Crawler executed in 1 minute 16 seconds.
INFO  [SitemapStore] single: Closing sitemap store...
INFO  [JobSuite] Running single: END (Mon Jan 22 17:45:19 WST 2018)
</pre>

But with this config, there is only one record committed to Elasticsearch. 
<pre>
INFO  [AbstractCrawler] single: Reprocessing any cached/orphan references...
INFO  [AbstractCrawler] single: Crawler finishing: committing documents.
INFO  [AbstractFileQueueCommitter] Committing 1 files
INFO  [ElasticsearchCommitter] Sending 1 commit operations to Elasticsearch.
INFO  [ElasticsearchCommitter] Done sending commit operations to Elasticsearch.
INFO  [ElasticsearchCommitter] Elasticsearch RestClient closed.
INFO  [AbstractCrawler] single: 25 reference(s) processed.
INFO  [CrawlerEventManager]          CRAWLER_FINISHED
INFO  [AbstractCrawler] single: Crawler completed.
INFO  [AbstractCrawler] single: Crawler executed in 1 minute 14 seconds.
INFO  [SitemapStore] single: Closing sitemap store...
INFO  [SLF4JLogger] Closed connection [connectionId{localValue:6, serverValue:111}] to localhost:27017 because the pool has been closed.
INFO  [SLF4JLogger] Closed connection [connectionId{localValue:2, serverValue:109}] to localhost:27017 because the pool has been closed.
INFO  [SLF4JLogger] Closed connection [connectionId{localValue:4, serverValue:116}] to localhost:27017 because the pool has been closed.
INFO  [SLF4JLogger] Closed connection [connectionId{localValue:3, serverValue:110}] to localhost:27017 because the pool has been closed.
INFO  [SLF4JLogger] Closed connection [connectionId{localValue:7, serverValue:118}] to localhost:27017 because the pool has been closed.
INFO  [SLF4JLogger] Closed connection [connectionId{localValue:10, serverValue:115}] to localhost:27017 because the pool has been closed.
INFO  [SLF4JLogger] Closed connection [connectionId{localValue:11, serverValue:114}] to localhost:27017 because the pool has been closed.
INFO  [SLF4JLogger] Closed connection [connectionId{localValue:9, serverValue:112}] to localhost:27017 because the pool has been closed.
INFO  [SLF4JLogger] Closed connection [connectionId{localValue:5, serverValue:117}] to localhost:27017 because the pool has been closed.
INFO  [SLF4JLogger] Closed connection [connectionId{localValue:8, serverValue:113}] to localhost:27017 because the pool has been closed.
INFO  [JobSuite] Running single: END (Mon Jan 22 17:25:04 WST 2018)
</pre>

Is there any mistake in my config file? Or any tags is misconfigured? The following is the basic setup:

```xml
<crawlerDefaults>
  <crawlDataStoreFactory class="com.norconex.collector.http.data.store.impl.mongo.MongoCrawlDataStoreFactory">
    <host>localhost</host>
    <port>27017</port>
    <dbname>test</dbname>
  </crawlDataStoreFactory>
.....
  <committer class="com.norconex.committer.elasticsearch.ElasticsearchCommitter">
    <nodes>http://localhost:9200</nodes>
    <indexName>test1</indexName>
    <queueDir>./output/commit</queueDir>
    <connectionTimeout>5 minutes</connectionTimeout>
    <socketTimeout>5 minutes</socketTimeout>
    <typeName>Documents</typeName>
    <commitBatchSize>50</commitBatchSize>
    <maxRetries>1</maxRetries>
  </committer>
</crawlerDefaults>
```

**Comment by wolverline** [comment]
I realized that I deleted elasticsearch indexed records but didn't remove MongoDB collection that were marked as not modified. After removing both, it works fine. Although it runs better; however, the indexed record numbers are not consistent at each crawling (I'm crawling only one site). What cause this?

In real-life crawling, how can I avoid above mistake? Do I need to blow up all records each time I need to recrawl? This isn't a good solution in my case due to the sheer number of documents.

**Comment by essiembre** [comment]
The "CrawlDataStore" acts as a cache of URLs for subsequent crawls to figure out what has already been crawled or not.  If you want to recrawl everything from scratch (without consideration for previously modified or deleted), then yes, you have to clear that cache (Mongo in your case).  An alternative is to disable the ``documentChecksummer`` and ``metadataChecksummer`` and you will get everything every time.  You can also modify how checksums are built so you have more control as to what makes some documents to be resent or not.

About getting different document count each time, do you mean when you clean elasticsearch and perform a fresh recrawl?  If so, and you know the site has not changed between crawls, it is likely related to your config.  For instance, do you have a ``maxDocuments`` configured?  Please share your config if the issue persists.

**Comment by wolverline** [comment]
Thanks, Pascal. I was hoping the crawler can skip "recrawling" by reading HTTP header (`Last-Modified` field) first; instead of crawling/downloading the whole page. I haven't checked how GSA works but don't think it does. The reason is that, I think, it would be a time/performance saver although I don't know how reliable it is for the cralwer to tell whether a page is updated/modified. Do you think this is possible?

Clearing cache/mongo collection makes sense in crawling a site from scratch. I haven't configured `maxDocuments`. Is this going to have an effect in this scenario?

**Comment by essiembre** [comment]
You can certainly do this.  Add this to you crawler config:
```xml
 <metadataFetcher class="com.norconex.collector.http.fetch.impl.GenericMetadataFetcher" />
```

This will have the crawler first make a HEAD request for a URL.  If the ``Last-Modified`` date has not changed, the document will not be downloaded.  This is done by the default metadata checksummer: ``LastModifiedMetadataChecksummer``.

Keep in mind this is only possible if the website you crawl makes proper use of ``Last-Modified``.  This being said, there is also a document checksummer configured by default (``MD5DocumentChecksummer``).  It will use a MD5 checksum of the document content to find if a document was modified.  So for cases where the HEAD request cannot be relied upon, it will fallback to using the downloaded document.

Can this work for you?

**Comment by wolverline** [comment]
@essiembre I changed the source fields to check three fields instead of Last-Modified. It works and I think this makes more sense.
````xml
<documentChecksummer class="$MD5Checksummer">
  <!-- <sourceFields>Last-Modified</sourceFields> -->
  <sourceFields>content, title, description</sourceFields>
</documentChecksummer>
````
Regarding the recrawler config, I realized the config is already set as the following:
````xml
<metadataFetcher class="$metaFetcher">
  <validStatusCodes>200</validStatusCodes>
</metadataFetcher>
````
After I've tested it out, however it seems there is no performance gains when recrawling. The reason I am concerned about this is that I have several big sites to crawl. For one, Norconex brings over 10000 references from the initial run; it took about 28 hours. I think GSA runs quicker but I can't confirm. Is there any way it can cut down the time? I wonder if you have any Norconex performance comparison against GSA.

**Comment by essiembre** [comment]
No performance comparison was done.  Performance is very dependant on configuration and how aggressive you want it to be.  You can reduce or eliminate the "delay" between requests (3 seconds by default), you can increase the number of threads, you can recrawl some pages more frequently than others, etc.  Without a copy of your full config, it is hard to see where you could improve.  

I am sure 28 hours for 10,000 references can be improved significantly. That being said, it is nice to be fast, but in the end, you usually want to be nice to sites you crawl to not affect their performance and avoid being blocked.  

About ``keepDownload``, if you do not plan to do anything with those files, I see no value in keeping them.  The collector has no use for them.

**Comment by wolverline** [comment]
Thanks, Pascal.
