### ISSUE TITLE
Custom Committers and version 2.*

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#46]
I just checked documentation and can't find any link/text which may help me with refactoring of the existent committer. It is possible to use Importer also (I agree - a dirty hack), I guess, but the link at FAQ page (http://www.norconex.com/product/importer/) leads nowhere.

**Comment by essiembre** [comment]
The importer, collectors, committers, can all be accessed form a central page now: http://www.norconex.com/collectors/

All the sites were redone and the new Importer URL is:
http://www.norconex.com/collectors/importer/

In the release notes you will find what changed, but it may not be the easiest... so feel free to paste whatever you need to convert and I will convert it for you.   Importer release notes:
http://www.norconex.com/collectors/importer/releases

**Comment by AntonioAmore** [comment]
Thank you! It helps a lot, so now I'm rebuilding my committer with new libraries from collector/lib folder. 

May you note, am I right to suppose that ver. 1.* method ```setIdTargetField(string);``` is now called ```setTargetReferenceField(string)```?

**Comment by essiembre** [comment]
Yes you are correct.  The "id" was sometimes "id", sometimes "URL", sometimes "reference".   Version 2 cleans that up and "reference" is used everywhere now.

**Comment by AntonioAmore** [comment]
Should I close issues myself? You answered my question, thank you very much.

Actually committer designed for v.1.3.* were refactored from kick: changed 2 imports (added .core.) and replaced 2 renamed methods.

**Comment by essiembre** [comment]
Thanks confirming.  Closing.
