### ISSUE TITLE
Logical combination of filters

### ISSUE THREAD

**Issue by FuePi** [Norconex/collector-http#460]
We need to filter documents without the header Content-Length **and** with the header Transfer-Encoding set to chunked. This is the importer configuration I came up with:

```
<importer>
	<preParseHandlers>
		<!-- 	Exclude pages with header Transfer-Encoding: chunked 
			and header Content-Length missing from being saved to the cache -->
		<filter class="com.norconex.importer.handler.filter.impl.RegexMetadataFilter"
			onMatch="exclude" field="transfer-encoding">
		  .*chunked$
		</filter>
		<filter class="com.norconex.importer.handler.filter.impl.EmptyMetadataFilter"
			  onMatch="exclude" fields="content-length" />
	</preParseHandlers>
</importer>
```
But this seems to exclude documents matching either one of the filters.
Is there a way to logically combine these filters?

**Comment by essiembre** [comment]
Good question.  Not sure you can do it the way you have it, but here is a workaround I suggest you try (untested):
```xml
<filter class="com.norconex.importer.handler.filter.impl.EmptyMetadataFilter"
        onMatch="exclude" fields="content-length">
    <restrictTo field="transfer-encoding">.*chunked$</restrictTo>
</filter>
```
The ``restrictTo`` makes sure ``EmptyMetadataFilter`` is only applicable to documents with "chunked" transfer encoding.

For more control, you can also have a look at the [ScriptFilter](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/filter/impl/ScriptFilter.html).

Does that work for you?

**Comment by FuePi** [comment]
That works perfectly! Thank you very much for the fast response.
