### ISSUE TITLE
Does Norconex Http Collector(any version) support integration with Selenium for crawling dynamic web pages

### ISSUE THREAD

**Issue by jigneshshukla** [Norconex/collector-http#461]
Does Norconex Http Collector(any version) support integration with Selenium for crawling dynamic web pages (similar to Apache Nutch)? 

We have dynamically generated web pages in our application where actual content of the page is loaded by javascript ajax calls after the webpage is loaded in browser. Default Norconex Http Collector is not able to crawl them since it doesn't really execute the javascript ajax calls (similar to the browser would do).

**Comment by essiembre** [comment]
No, it does not integrate with Selenium.  It integrates with PhantomJS instead, which provides better support for Javascript-driven pages.  Have a look at [PhantomJSDocumentFetcher](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/PhantomJSDocumentFetcher.html).

**Comment by butchersoft1** [comment]
Hello,

I crawling pages with Dynamic content and looking to use the PhantomJS option, but the open source project has been closed for many years and not sure if some of the modern JavaScript extensions such as map would be supported.

Can I raise this as a feature request for support of a headless browser such as chrome or selenium

**Comment by essiembre** [comment]
The integration of headless browser with Selenium is currently under development for the next major release (v 3.0). No release date can be estimated yet.

**Comment by essiembre** [comment]
Implemented major browsers support in version 3 (headless).  It is also possible to configure when to use the browser vs. regular HTTP client based on URL patterns, and also have fallbacks if one fails.

**Comment by butchersoft1** [comment]
Awesome
