### ISSUE TITLE
Error in document processing during recrawls

### ISSUE THREAD

**Issue by krishnateja-ravipati** [Norconex/collector-http#462]
Hello @essiembre ,

I had an issue earlier while committing the documents to cloud search which looks like below,

> ERROR - CloudSearch error: { ["Field "description" must have array type to have multiple values (near operation with index 66; document_id https://www.example.com/media)"] } (Service: AmazonCloudSearchDomain; Status Code: 400; Error Code: DocumentServiceException; Request ID: 7d53f879-0ce1-11e8-b2f6-9d7cf13d27f5)

The above-mentioned URL(URL changed) had an issue containing 2 meta tags i.e. **description**.

The index field **description** in Cloudsearch is of type **text**.

After the page is fixed to one meta tag, cloud search committer is again throwing up same error as shown below after recrawling.

> ERROR - CloudSearch error: { ["Field "description" must have array type to have multiple values (near operation with index 66; document_id https://www.example.com/media)"] } (Service: AmazonCloudSearchDomain; Status Code: 400; Error Code: DocumentServiceException; Request ID: 7d53f879-0ce1-11e8-b2f6-9d7cf13d27f5)

How can I configure my collector to delete the above specific document from my crawler DB?

**Comment by essiembre** [comment]
Have a look at the [ForceSingleValueTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ForceSingleValueTagger.html).

Using that tagger will make sure "description" is a single value.

**Comment by krishnateja-ravipati** [comment]
Hello @essiembre ,

I have modified my config file according to your suggestion and part of it looks like this
![image](https://user-images.githubusercontent.com/24971712/36093884-0e5f315a-1012-11e8-9c75-5b2928ff8877.png)

But still, cloudsearch committer is returning same error.

> ERROR [CloudSearchCommitter] CloudSearch error: { ["Field "description" must have array type to have multiple values (near operation with index 66; document_id https://www.example.com/media)"] } (Service: AmazonCloudSearchDomain; Status Code: 400; Error Code: DocumentServiceException; Request ID: ca5808c6-0fe3-11e8-b2f6-9d7cf13d27f5)

Thank you

**Comment by essiembre** [comment]
Is it possible the document is still in your committer queue from the previous run?  You should clear your "workdir", or at a minimum the CloudSearch Committer queue directory (default being ``./committer-queue``) and try again.

**Comment by krishnateja-ravipati** [comment]
Hello @essiembre ,

Yup, deleting the workDir and committer queue directories fixed the issue. 
Thankyou for your quick response and help.
