### ISSUE TITLE
Feature Request: Mark Urls for Deletion

### ISSUE THREAD

**Issue by jerrywithaz** [Norconex/collector-http#463]
Hi Pascal,

I  am wondering if there is a feature where I can mark URLs for deletion.

I know you have the orphansStrategy option which you can set to IGNORE (or DELETE) but my config will possible have up to 20 or 30 URLs for large websites. 

But, sometimes I don't want to crawl all of the websites I just want to remove 1 or crawl 4 and then remove 2 without affecting the other websites I've crawled.

Currently, if I want to delete a non-referenced URL I remove it from the config and change the orphans strategy to DELETE. But, that requires that I have all of the URLs  that I want to keep in the startURLs.

I'd prefer to be able to have a deleteURL option and leave my orphans strategy to IGNORE so that I don't have to crawl every site when I need to delete 1 or 2 websites. 

Would is be possible to add a <deleteURLs></deleteURLs> parameter? 

Or if the feature already exist let me know.

Thanks!

**Comment by essiembre** [comment]
I am not sure I understand. If you want to delete specific URLs outside of a crawl, why can't you delete them directly from your target repository?  Am I missing something?

**Comment by jerrywithaz** [comment]
I have about 20 individual websites (start URLS) that I am crawling and then committing to a search domain.

I have split the 20 websites into 4 configs (5 websites per config) and they're all using the same collector.

I run each config in a staggered manner about 1.5 hours apart late a night. Everything works great so far. 

I have my orphansStrategy set to IGNORE. So that, when I run each config, it does not DELETE or PROCESS the other 15 websites that aren't in that specific config file. 

Now let's say I want to delete 1 startURL (and all of it's data) from my search domain and replace it with another. Typically I would set the orphansStrategy to DELETE, and rerun the collector with the new startURL. 

But, in my scenario I can't do that because I have separate config files. If I set the orphansStrategy  to DELETE in any of my config files, it will delete all of the data for the other 15 websites that aren't in that config.

I would instead like to always leave my orphansStrategy  set to IGNORE. And then, If I wanted to delete the data for a specific URL I could mark that URL for deletion.

Does that make sense?

**Comment by essiembre** [comment]
It looks like you have configured your 4 configs to point to the same paths (workdir, committer queue-dir, etc).  Is that the case?  If so, that is something to change.  Each config should have distinct directory locations for the files the collector will generate. That way they will run in isolation from each other (as intended) and you can put back the orphan strategy to its default (PROCESS).   Deletion/changes will be captured automatically on subsequent crawls and won't impact what you may have defined in your other configs.

**Comment by essiembre** [comment]
Correction: PROCESS will catch real deletion (page no longer exists).  Put it to DELETE if you want pages no longer referenced by your collector due to a change in your config to be deleted.

**Comment by jerrywithaz** [comment]
That is brilliant! Thanks Pascal, exactly what I needed.

**Comment by jerrywithaz** [comment]
I do have one more follow up question if  you don't mind:

Lets say I took the results folder, committer-queue folder, and the config for one of my websites and decided to move it to another crawler/committer. Would all of the data automatically be uploaded to the new crawler once I ran the collector?

Basically what I am asking is: Is it possible to move the crawler data from one collector to another without having to re-crawl?

**Comment by essiembre** [comment]
I am afraid it is not possible out-of-the-box.  The reason is simple: the data in the committer-queue is not kept once sent (trying to keep required storage to run the Collector to a minimum).  

You could write your own committer so it also stores a local copy of all data in a suitable format, taking into account modifications, deletions, etc.

You can also look at using the ``MultiCommitter`` to use more than one committer.  The extra one could be your backup.

If you have follow-up questions on this, please create a new issue, since it does not relate to the topic of this one (which is now closed).
