### ISSUE TITLE
Liferay crawling website

### ISSUE THREAD

**Issue by angelo337** [Norconex/collector-http#466]
hi there
I am trying to figure out how to crawl a website with somo 3.000 historic pages and articles in a single section : 
http://www.minminas.gov.co/en/historico-de-noticias
however when try try to use generic crawler  I am not able to. even using PhantomJS I still having issues with this crawling as just bring me the first 30 pages or so.
Could you please point me out some alternative configuration?
Regards
angelo

**Comment by essiembre** [comment]
Is there a problem with the site?  The side navigation on the URL you shared, as well as results navigation links, do not work for me when I click on them (tried both Chrome and Firefox).   Maybe that's your issue?

Please share your config and specific URLs you know are not being crawled.

I see that site has a sitemap file (http://www.minminas.gov.co/sitemap.xml).  Sitemaps are processed by default unless you disable support for it.   So you should be able to specify the ``<sitemap>`` as a start URL with a maxDepth of 0 or 1 and filter out anything you do not want from the list. Could that work for you?

**Comment by angelo337** [comment]
Pascal:
thanks a lot for your answer, I'm trying to crawl historic news sections, and I'm unable to do it.
you can see my config attach here

thanks in advance

[crawler_minminas.txt](https://github.com/Norconex/collector-http/files/1763752/crawler_minminas.txt)

**Comment by essiembre** [comment]
The HttpCollector Proxy used by PhantomJS does not always work well with secure sites ("https").  Luckily, your page can be accessed via "http".  I was able to extract the URLs you are interested in by changing the start URL to use the "http" version: 

http://www.minminas.gov.co/en/historico-de-noticias

Give it a try and let me know.

**Comment by essiembre** [comment]
I did try with your config and I was getting historic URLs. Whether I got them all or not, I would not know as I have not analyzed your site to confirm. If you know of URLs that are missing, please share some with me, and the page(s) where they are referenced from.

There is one change I made when testing, and it is increasing the delays you had before timeout in the PhantomJSDocumentFetcher config.  I have used 15 seconds:
```xml
          <renderWaitTime>15 seconds</renderWaitTime>
          <resourceTimeout>15 seconds</resourceTimeout>
```

Not sure that will make a difference, but if some pages are slow to render via javascript, giving it enough time to load everything is best.

Also, make sure you clean your "workdir" so you start clean with your config changes.

**Comment by angelo337** [comment]
Pascal:
I just change my config on phantomjs, and still the same issue just 1 thousand pages or so, and i have already check and there are more than 3 thousand pages on the site on historic news.

here are some examples of news that are not index:

https://www.minminas.gov.co/web/10180/historico-de-noticias?idNoticia=23744101
https://www.minminas.gov.co/web/10180/historico-de-noticias?idNoticia=23744409
https://www.minminas.gov.co/web/10180/historico-de-noticias?idNoticia=23743432

could you please check that for me and let me know a course of action?
thanks a lot

**Comment by essiembre** [comment]
Do you know where these pages are linked from?  If they can only be reached from the search page, that may be the problem.  I noticed the results pagination and side menu do no use regular URLs.  Even if PhantomJS can render the page properly, there are no URLs to extract for these.  The changing of a page is triggered by a user click action with javascript.

I can think of a few approaches.  If you know there is a range of Ids, you can use a ``<urlsFile>`` as a start URL, which would be a file you dynamically generate, containing tons of URLs with a range of IDs.

Another approach would be to simulate the user clicking on every link.  For this, you will need to analyze what element triggers the page change and create you own PhantomJS script (or modify existing one).  That may be a more complex task.  Have a look here for related information: http://phantomjs.org/api/webpage/method/send-event.html

The easiest would be to ask the site owner to make their site crawler-friendly, with real URLs.  It would help also if they have a REST API or if they can easily create an index page with all historical pages for crawling.

**Comment by angelo337** [comment]
Thanks a lot for your help and time Pascal, I am going to try both approaches and let you know 
Best regards
