### ISSUE TITLE
Tagger - documentation is very incomplete

### ISSUE THREAD

**Issue by tdrobcsak** [Norconex/collector-http#469]
Hi I tried to figure out what would be right using the replace Tagger works, but documentation is very incomplete and examples are not helping..

Here is my issue I have extracted metadata and with Split tagger it created multiple metadata with same field name.

      <meta name="description">Carol Dune swimmer</meta>
      <meta name="description">Washington , Hello street 221.</meta>
      <meta name="description">Tel.: +180030/54-34-741</meta>
      <meta name="description">coach</meta>

Now I would like to change "description" Field name based on values using regex, 

Instead of above metadata to (I had to put those ... otherwise this viewer doesn't shows meta tags)
     <meta...name="Name">Carol Dune swimmer<.../meta>
     <meta...name="Address">Washington , Hello street 221.<../meta>
     <meta...name="mobile">Tel.: +180030/54-34-741<.../meta>
      <meta..name="Profession">coach<.../meta>

however from any of the examples found in the site not possible to figure-out how it is possible? 

Reneme Tagger doesn't offers any Regex matching function. While in Examples for Replace there is no example where Regex is could be used!

**Comment by essiembre** [comment]
Have you read the Javadoc for the [ReplaceTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ReplaceTagger.html)?  The documentation mentions the ``regex="true"`` attribute to use regular expression.  If you feel something else is missing let us know.

There are different ways to achieve what you want.  One example could be to use 4 ReplaceTagger to match each occurrence separately.  You can also use the MergeTagger to combine them with a special character (e.g. ``|``) and then the ReplaceTagger 4 times for each section.

In the end though, if you feel what you want to do is too complex for simple configuration, you can consider using the [ScriptTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ScriptTagger.html) to have more control.

Does that help?

**Comment by essiembre** [comment]
Glad you figured it out.  What do you mean by "more **reacher** examples"?  Do you mean richer?  That is definitely a good candidate for a FAQ entry.  Sharing your solution would be a good start! :-)  Otherwise, I'll come up with examples myself when I have the chance.  Thanks for your feedback.
