### ISSUE TITLE
Update field on different crawls

### ISSUE THREAD

**Issue by jotacor** [Norconex/collector-http#471]
Hi!
I have started using this crawl and I'm trying to do something that I don't know if it is feasible.

I have several roles on the site, so I want to crawl the site with every role and commit the pages to solr.
I put a constant field "role" with "ConstantTagger" on every crawl with different roles values, but the tag "role" becomes overwritten with every role crawl.

Is there a way to update only this field to add the roles, or some way to store same page with different roles?
Thanks.

**Comment by essiembre** [comment]
I am not sure I understand.  Do you mean you want to crawl the same site with the same crawler multiple times with the only difference being your constant value, but append that value to existing ones in Solr, for the same document?

If you crawl using different roles, wouldn't the content change as well?  If not, why crawl again?  Can you just store all roles using constants, in a single crawl?

Can you provide more details?

**Comment by jotacor** [comment]
Hi, you understood well :)
I can put the constant in a crawl with a role, or roles, but there is content (pages on site) that may be available for a role, or not, so if I configure the constant and make the crawl with one logged user, I will only know if this logged user has permissions to access to the content, but not for the rest of users with different roles.
That is the reason that I would like to update one field (Solr atomic update) for the content already in Solr.

**Comment by essiembre** [comment]
The Solr Committer does not support atomic updates.  You can extend the Solr committer to suit your needs, or we can turn this ticket into a feature request if you want.

As an alternative, you can store each document separately, creating unique ids by appending the role to the URL and storing the URL to a non-unique field.   Then you could use Solr field-grouping feature to retrieve them as one.

**Comment by jotacor** [comment]
That is what I'm doing right now, appending the role to the end if the id. But I'm duplicating by the number of roles all the documents.
I will try the grouping.
Thanks!
