### ISSUE TITLE
HTTP Request

### ISSUE THREAD

**Issue by rvega1204** [Norconex/collector-http#472]
Hi, I'm trying to get all the data from HTTP headers(especially: GET, POST, mimetype, etc) but I can't get the data. Also, I have an error on the selects when I try to save the data into the DB. Please check the attached files.

aused by: java.sql.SQLException: Error de Sintaxis en sentencia SQL "INSERT INTO TEST_TABLE(COLLECTOR.[*]CONTENT-TYPE,DOCUMENT.CONTENTFAMILY,SERVER,KEYWORDS,X-RUNTIME,CONTENT-LOCATION,COLLECTOR.REFERRER-LINK-TAG,DESCRIPTION,TITLE,COLLECTOR.REFERRER-LINK-TEXT,CONTENT,DOCUMENT.REFERENCE,X-FRAME-OPTIONS,DC:TITLE,COLLECTOR.IS-CRAWL-NEW,CSRF-TOKEN,CONTENT-ENCODING,CONTENT-TYPE-HINT,SET-COOKIE,COLLECTOR.DEPTH,ID,X-XSS-PROTECTION,CONTENT-LENGTH,CONTENT-TYPE,KEEP-ALIVE,SITE,X-PARSED-BY,X-REQUEST-ID,COLLECTOR.CONTENT-ENCODING,X-CONTENT-TYPE-OPTIONS,CONNECTION,DOCUMENT.CONTENTENCODING,CSRF-PARAM,DATE,COLLECTOR.REFERRER-REFERENCE,CACHE-CONTROL,ETAG,VIEWPORT,DOCUMENT.CONTENTTYPE,VARY,COLLECTOR.REFERENCED-URLS) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) "; se esperaba ",, )"
Syntax error in SQL statement "INSERT INTO TEST_TABLE(COLLECTOR.[*]CONTENT-TYPE,DOCUMENT.CONTENTFAMILY,SERVER,KEYWORDS,X-RUNTIME,CONTENT-LOCATION,COLLECTOR.REFERRER-LINK-TAG,DESCRIPTION,TITLE,COLLECTOR.REFERRER-LINK-TEXT,CONTENT,DOCUMENT.REFERENCE,X-FRAME-OPTIONS,DC:TITLE,COLLECTOR.IS-CRAWL-NEW,CSRF-TOKEN,CONTENT-ENCODING,CONTENT-TYPE-HINT,SET-COOKIE,COLLECTOR.DEPTH,ID,X-XSS-PROTECTION,CONTENT-LENGTH,CONTENT-TYPE,KEEP-ALIVE,SITE,X-PARSED-BY,X-REQUEST-ID,COLLECTOR.CONTENT-ENCODING,X-CONTENT-TYPE-OPTIONS,CONNECTION,DOCUMENT.CONTENTENCODING,CSRF-PARAM,DATE,COLLECTOR.REFERRER-REFERENCE,CACHE-CONTROL,ETAG,VIEWPORT,DOCUMENT.CONTENTTYPE,VARY,COLLECTOR.REFERENCED-URLS) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) "; expected ",, )"; SQL statement:
INSERT INTO test_table(collector.content-type,document.contentFamily,Server,keywords,X-Runtime,Content-Location,collector.referrer-link-tag,description,title,collector.referrer-link-text,content,document.reference,X-Frame-Options,dc:title,collector.is-crawl-new,csrf-token,Content-Encoding,Content-Type-Hint,Set-Cookie,collector.depth,id,X-XSS-Protection,Content-Length,Content-Type,Keep-Alive,SITE,X-Parsed-By,X-Request-Id,collector.content-encoding,X-Content-Type-Options,Connection,document.contentEncoding,csrf-param,Date,collector.referrer-reference,Cache-Control,ETag,viewport,document.contentType,Vary,collector.referenced-urls) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [42001-196] Query: INSERT INTO test_table(collector.content-type,document.contentFamily,Server,keywords,X-Runtime,Content-Location,collector.referrer-link-tag,description,title,collector.referrer-link-text,content,document.reference,X-Frame-Options,dc:title,collector.is-crawl-new,csrf-token,Content-Encoding,Content-Type-Hint,Set-Cookie,collector.depth,id,X-XSS-Protection,Content-Length,Content-Type,Keep-Alive,SITE,X-Parsed-By,X-Request-Id,collector.content-encoding,X-Content-Type-Options,Connection,document.contentEncoding,csrf-param,Date,collector.referrer-reference,Cache-Control,ETag,viewport,document.contentType,Vary,collector.referenced-urls) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) Parameters: [text/html, html, thin 1.6.2 codename Doc Brown, , 0.094165, https://demosite.appvance.com/t/brands?page=2, a.href, , Brands - Appvance Demo Site, 2, 
    
[complex-config.txt](https://github.com/Norconex/collector-http/files/1815700/complex-config.txt)

[complex-config-var.txt](https://github.com/Norconex/collector-http/files/1815701/complex-config-var.txt)
[db.zip](https://github.com/Norconex/collector-http/files/1815702/db.zip)

Thanks.

**Comment by essiembre** [comment]
Your config suggests you are using the SQL Committer version 1.   Can you please give a try to the [snapshot for version 2](https://www.norconex.com/collectors/committer-sql/download)?

Version 2 lets you define your table/field creation. Giving you that control resolves several issues.

Make sure you update your [SQL Committer configuration](https://www.norconex.com/collectors/committer-sql/configuration) for it, it has quite a few changes.

Let me know if you have issues with that new version.

**Comment by rvega1204** [comment]
Hi I will check the Sql. What about the data from http headers? I still can't find all the information, specifically the GET, POST, mime type, etc.

**Comment by essiembre** [comment]
The data from HTTP header is being sent according to the error you posted.  The error message shows it is trying to save fields such as Content-Encoding,Content-Type-Hint,Set-Cookie,X-XSS-Protection,Content-Length,Content-Type, etc.  Those are coming from the HTTP headers.

**Comment by rvega1204** [comment]
Hi, I using committer 2.0 but I'm not sure how to configure the DB. The data I need from header is something like this:

"httpVersion": "HTTP/1.1",
                        "method": "GET",
                        "url": "http://sahitest.com/demo/"
                    },
                    "response": {
                        "headers": [
                            {
                                "name": "Date",
                                "value": "Sat, 25 Nov 2017 22:36:39 GMT"
                            },
                            {
                                "name": "Server",
                                "value": "Apache/2.4.6 (CentOS) PHP/5.4.16"
                            },
                            {
                                "name": "Last-Modified",
                                "value": "Fri, 21 Apr 2017 21:07:00 GMT"
                            },
                            {
                                "name": "ETag",
                                "value": "\"d39-54db3a36f0500\""
                            },
                            {
                                "name": "Accept-Ranges",
                                "value": "bytes"
                            },
                            {
                                "name": "Content-Type",
                                "value": "text/html; charset=UTF-8"
                            },
                            {
                                "name": "File",
                                "value": "history/data629314697413801741.html"
                            }
                        ],
                        "httpVersion": "HTTP/1.1",
                        "statusText": "OK",
                        "status": 200
                    },
                    "time": 501
                },
                {
                    "startedDateTime": "1969-12-31T18:00:00.000-06:00",
                    "request": {
                        "headers": [
                            {
                                "name": "Host",
                                "value": "sahitest.com"
                            },
                            {
                                "name": "Proxy-Connection",
                                "value": "keep-alive"
                            },
                            {
                                "name": "User-Agent",
                                "value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
                            },
                            {
                                "name": "Accept",
                                "value": "image/webp,image/apng,image/*,*/*;q=0.8"
                            },
                            {
                                "name": "Referer",
                                "value": "http://sahitest.com/demo/"
                            },
                            {
                                "name": "Accept-Encoding",
                                "value": "identity"
                            },
                            {
                                "name": "Accept-Language",
                                "value": "es-ES,es;q=0.9"
                            },
                            {
                                "name": "cookie",
                                "value": ""
                            }
                        ]

and I'm getting this:
 
collector.content-type = text/html
document.contentFamily = html
Server = thin 1.6.2 codename Doc Brown
keywords = 
X-Runtime = 0.043982
Content-Location = https://demosite.appvance.com/
description = 
title = Appvance Demo Site
document.reference = https://demosite.appvance.com/
X-Frame-Options = SAMEORIGIN
dc\:title = Appvance Demo Site
collector.is-crawl-new = true
csrf-token = lOK0NF5Rw1bGQQiaGDhZGFTWicwn/8sX+CWOFmzNT0P+Vl9ZEaDTrV5z9rUTfqe9ucCHRbd4I1JDDRmMWzUpMw==
Content-Encoding = UTF-8
Content-Type-Hint = text/html; charset=UTF-8
Set-Cookie = guest_token=ImJlRl8tZnhPaTBfZVEzaGhfNzZFRWcxNTIxMjE2MDc0MDE4Ig%3D%3D--c3fc7855b1ee1e234199e210a445d8daa2d6664c; path=/; expires=Tue, 16 Mar 2038 16:01:14 -0000
collector.depth = 0
X-XSS-Protection = 1; mode=block
Content-Length = 15736
Content-Type = text/html; charset=utf-8
Content-Type = text/html; charset=UTF-8
Keep-Alive = timeout=5, max=100
SITE = Demosite
X-Parsed-By = org.apache.tika.parser.DefaultParser
X-Parsed-By = org.apache.tika.parser.html.HtmlParser
X-Request-Id = 829cfc4f-6e9d-4b10-b6f0-d02d0d64bd11
collector.content-encoding = ISO-8859-1
X-Content-Type-Options = nosniff
Connection = Keep-Alive
document.contentEncoding = ISO-8859-1
csrf-param = authenticity_token
Date = Fri, 16 Mar 2018 16:01:14 GMT
collector.referrer-reference = http://demosite.appvance.com/
Cache-Control = max-age=0, private, must-revalidate
ETag = W/\"168b112868af2e1bbc83a0af82d883b6-gzip\"
viewport = width=device-width, initial-scale=1.0, maximum-scale=1
document.contentType = text/html
Vary = Accept-Encoding
collector.referenced-urls = https://demosite.appvance.com/products/ruby-on-rails-baseball-jersey
collector.referenced-urls = https://demosite.appvance.com/products/spree-baseball-jersey
collector.referenced-urls = https://demosite.appvance.com/spree/products/33/small/apache_baseball.png?1499978146=
collector.referenced-urls = https://demosite.appvance.com/products/spree-jr-spaghetti
collector.referenced-urls = https://demosite.appvance.com/spree/products/23/small/ror_bag.jpeg?1499978140=
collector.referenced-urls = https://demosite.appvance.com/t/brands/mugs
collector.referenced-urls = https://demosite.appvance.com/products/spree-tote
collector.referenced-urls = https://demosite.appvance.com/products/spree-ringer-t-shirt
collector.referenced-urls = https://demosite.appvance.com/t/brands/ruby
collector.referenced-urls = https://demosite.appvance.com/spree/products/38/small/spree_ringer_t.jpeg?1499978150=
collector.referenced-urls = https://demosite.appvance.com/products/apache-baseball-jersey
collector.referenced-urls = https://demosite.appvance.com/t/brands/clothing
collector.referenced-urls = https://demosite.appvance.com/t/brands/spree
collector.referenced-urls = https://demosite.appvance.com/spree/products/40/small/spree_spaghetti.jpeg?1499978152=
collector.referenced-urls = https://demosite.appvance.com/products/ruby-on-rails-tote
collector.referenced-urls = https://demosite.appvance.com/spree/products/21/small/ror_tote.jpeg?1499978138=
collector.referenced-urls = https://demosite.appvance.com/products/spree-bag
collector.referenced-urls = https://demosite.appvance.com/spree/products/36/small/spree_tote_front.jpeg?1499978149=
collector.referenced-urls = https://demosite.appvance.com/
collector.referenced-urls = https://demosite.appvance.com/cart
collector.referenced-urls = https://demosite.appvance.com/spree/products/26/small/ror_jr_spaghetti.jpeg?1499978142=
collector.referenced-urls = https://demosite.appvance.com/assets/logo/spree_50-0ae687ccd486b63b01687b1df9e5394430f6fce3ab40c28250b179be4363ddc1.png
collector.referenced-urls = https://demosite.appvance.com/t/brands/apache
collector.referenced-urls = https://demosite.appvance.com/?page=2
collector.referenced-urls = https://demosite.appvance.com/products/ruby-baseball-jersey
collector.referenced-urls = https://demosite.appvance.com/products/ruby-on-rails-ringer-t-shirt
collector.referenced-urls = https://demosite.appvance.com/spree/products/29/small/ror_ringer.jpeg?1499978144=
collector.referenced-urls = https://demosite.appvance.com/spree/products/35/small/spree_bag.jpeg?1499978148=
collector.referenced-urls = https://demosite.appvance.com/spree/products/34/small/ruby_baseball.png?1499978147=
collector.referenced-urls = https://demosite.appvance.com/t/brands/rails
collector.referenced-urls = https://demosite.appvance.com/spree/products/24/small/ror_baseball.jpeg?1499978140=
collector.referenced-urls = https://demosite.appvance.com/products/ruby-on-rails-bag
collector.referenced-urls = https://demosite.appvance.com/t/brands/bags
collector.referenced-urls = https://demosite.appvance.com/spree/products/41/small/spree_jersey.jpeg?1499978152=
collector.referenced-urls = https://demosite.appvance.com/products/ruby-on-rails-jr-spaghetti

**Comment by essiembre** [comment]
I am not sure what you are asking. From what you are saying you are getting the HTTP headers just fine. The example you gave includes the HTTP headers.  Unless you are filtering them, that's all of them for your request. 

The mime type is ``Content-Type``, or the clean version: ``document.contentType``.  Unless you added your own code that does differently, the HTTP request method is always GET.

Are you looking to export in a JSON format instead of SQL?  Are you looking to limit the fields to a specific list?  If so, have a look at the Importer handler called ``KeepOnlyTagger``.

Please elaborate.
