### ISSUE TITLE
PhantomJSDocumentFetcher config error

### ISSUE THREAD

**Issue by wolverline** [Norconex/collector-http#473]
I can't seem to resolve the issue from PhantomJSDocumentFetcher config. I am running this on my local machine with PhantomJS 2.1 + Norconex collector 2.8.0.

The following is the config
````xml
 <documentFetcher class="${http}.fetch.impl.PhantomJSDocumentFetcher"
        detectContentType="false" detectCharset="false" screenshotEnabled="false">
    <exePath>bin/phantomjs</exePath>
    <scriptPath>scripts/phantom.js</scriptPath>
    <renderWaitTime>3000</renderWaitTime>
    <referencePattern>^http://www.ivvg.org/links#.*</referencePattern>
    <validStatusCodes>200</validStatusCodes>
    <notFoundStatusCodes>404</notFoundStatusCodes>
</documentFetcher>
````

I get the error at an initial crawling state. Is the version support issue?

``
ERROR [XMLConfigurationUtil$LogErrorHandler] (XML Validation) PhantomJSDocumentFetcher: cvc-complex-type.2.4.b: The content of element 'documentFetcher' is not complete. One of '{resourceTimeout, options, referencePattern, contentTypePattern, validStatusCodes, notFoundStatusCodes, headersPrefix, screenshotDimensions, screenshotZoomFactor, screenshotScaleDimensions, screenshotScaleStretch, screenshotScaleQuality, screenshotImageFormat, screenshotStorage, screenshotStorageDiskDir, screenshotStorageDiskField, screenshotStorageInlineField}' is expected.
``

**Comment by essiembre** [comment]
This is a harmless XML validation error that is wrongfully reported in your case.  The error is displayed when ``screenshotStorageDiskDir`` is not set.  The latest HTTP Collector snapshot fixes that error.  

Please confirm.

**Comment by wolverline** [comment]
I can't replicate the issue. Thanks, @essiembre!
