### ISSUE TITLE
casperjs instead of Phantomjs

### ISSUE THREAD

**Issue by angelo337** [Norconex/collector-http#474]
hi there
could you please help me I am trying to crawl a not very well constructed site and i need to click in a particular element the trigger a JS that change pages content, the mos simple way i found is ussing casperJS (http://casperjs.org/). 
i manage to do that by  call that page after click and return html resource, however i'm not figure out the way to pass that HTML to COLLECTOR.
is it possible? please, if so cloud you please point me out some resource? 
thanks a lot
regards
angelo

**Comment by essiembre** [comment]
I can't see why not. 

You can create your own ``IHttpDocumentFetcher`` or have your own version of ``PhantomJSDocumentFetcher`` but I suggest trying a simpler road.  

Without having to write Java code, I would look at modifying the current PhantomJS script used by the HTTP Collector (``phantom.js``) to integrate Casper into it.  I think you'll find a way to do it [here](http://docs.casperjs.org/en/latest/faq.html#can-i-use-casperjs-without-using-the-casperjs-executable).

You may want to replace the ``page.open(...)`` section of the script with your Casper-specific code.  Once you have obtained the page you want (after your clicking), obtain the ``page`` from Casper.  That page will be a PhantomJS page and can be used as the page on [line 92](https://github.com/Norconex/collector-http/blob/e7f7e239588adc6223c470d9219cb7bcaa25f475/norconex-collector-http/src/main/assembly/scripts/phantom.js#L92) of the phantom.js script.  This is the line that writes the page to the filesystem for later consumption by the HTTP Collector.

Let me know how that goes.
