### ISSUE TITLE
Wrongly formatted URLs throw ERROR

### ISSUE THREAD

**Issue by jsteggink** [Norconex/collector-http#475]
Hi,

I was wondering if we could come up with something else than throwing ERRORs when an extracted URL is wrongly formatted. 

In URLCrawlScopeStrategy an HttpURL object is created. However, when the URL is not valid, an ERROR is thrown in AbstractCrawler. 

When monitoring the crawler log it gives me false positives for ERRORS. It looks like a severe error, while in reality it's an issue with the data, something we have no control over. For me it would suffice to log this as INFO and let me know with a specific crawler error, like REJECTED_ERROR. This means there should be a check for the validity of a URL before sending it to HttpURL, or implementing the check in HttpURL.

What's your view on this?

Best regards,
Jeroen Steggink

**Comment by essiembre** [comment]
Can you share an example URL causing this (or steps to reproduce)?

**Comment by jsteggink** [comment]
Something like http://c:/Documents/document.pdf
(In this case http was used instead of file).
But any URL with an incorrect syntax would give an error. So for example an incorrect scheme, like htp instead of http, or in the previous example where the domain is incorrect.

**Comment by essiembre** [comment]
I changed it to INFO in the [latest snapshot](http://www.norconex.com/collectors/collector-http/download) release.  I think you are right that ERROR should be reserved for abnormal crawler problems and not website design mistakes (e.g. bad URLs).   

Setting the log level to DEBUG in log4j (more precisely on ``AbstractCrawler``, ``REJECTED_ERROR``, or ``GenericDocumentFetcher``) will log out more information about the rejection (e.g. stacktrace).

This change of logging approach probably will need to be extended to a few other places over time.

Please confirm the new snapshot does it for you.

**Comment by essiembre** [comment]
[Version 2.8.1](https://www.norconex.com/collectors/collector-http/download) was released with that change.
