### ISSUE TITLE
proxy settings under httpClientFactory not working

### ISSUE THREAD

**Issue by SolSearch** [Norconex/collector-http#481]
Hello, when I try to crawl my site, the traffic seem to bypass the proxy server.  Do I need to specify any additional parameters:

<httpClientFactory class="com.norconex.collector.http.client.impl.GenericHttpClientFactory">
<proxyHost>192.168.205.124</proxyHost>
<proxyPort>8080</proxyPort>
<proxyScheme>http</proxyScheme>
</httpClientFactory>

Thanks

**Comment by SolSearch** [comment]
sorry it seems all my configuration code got truncated,,,will try again

**Comment by SolSearch** [comment]
[gcp.txt](https://github.com/Norconex/collector-http/files/1881532/gcp.txt)

**Comment by SolSearch** [comment]
I have attached my config file.

**Comment by essiembre** [comment]
Move this configuration block under your ``<crawler ...>`` section (as opposed to under ``<httpcollector ...>``):

```xml
<robotsTxt ignore="true" />
<robotsMeta ignore="true" />

<httpClientFactory class="com.norconex.collector.http.client.impl.GenericHttpClientFactory">
  <proxyHost>192.168.205.124</proxyHost>
  <proxyPort>8080</proxyPort>
  <proxyScheme>http</proxyScheme>
</httpClientFactory>
```

Have a look here: https://www.norconex.com/collectors/collector-http/configuration

Let me know if that makes a difference.

**Comment by SolSearch** [comment]
It may be a networking issue at our end.  I will let you know if it gets resolved,  Thanks,

**Comment by SolSearch** [comment]
Moving the configuratin block under crawler and applying the right firewall rules at our end has resolved the issue.  Thank you very much.  Can I also ask you if there are any configuration settings that will allow to authenticate windows domain users.  I have a web site that is open to only the domain users and I am using a solr service account which is a domain account but I keep getting the message authentication required.  Is enabling the anonymous access the answer?

**Comment by essiembre** [comment]
The HTTP Collector supports NTML. You should be able to do so by configuring [GenericHttpClientFactory](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/client/impl/GenericHttpClientFactory.html) appropriately.   Look at all the auth* options available.

**Comment by SolSearch** [comment]
Issue resolved
