### ISSUE TITLE
how to crawl blog reader comment 

### ISSUE THREAD

**Issue by carrud** [Norconex/collector-http#482]
i succesfully crawl blog content using norconex http collector, but after i looked in crawledfiles it seems not all content got crawled, especially reader comment section that dynamically generated by javascript in iframe, could you give me some configuration example to do this?

**Comment by essiembre** [comment]
The HTTP Collector does not interpret JavaScript.  For this, you'll have to either write your own ``ILinkExtractor`` to extract dynamically invoked URLs, or use the [PhantomJSDocumentFetcher](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/PhantomJSDocumentFetcher.html) which relies on PhantomJS to crawl JavaScript-driven websites.

**Comment by carrud** [comment]
I tried phantomJSDocumentFetcher within norconex http collector but only html content and screenshoot of the page was get by the crawler not the actual user comment in text format like i want, any help ? Or do i need additional configuration on phantom js?

**Comment by essiembre** [comment]
Are you giving it enough time to render? Maybe try increasing the  ``renderWaitTime`` and ``resourceTimeout``.

Are the comments always showing or you need to scroll down to have them show up?  If you normally need to scroll down, you will likely have to modify the PhantomJS script that comes with the HTTP Collector to simulate scrolling (example [here](https://stackoverflow.com/questions/16561582/how-to-scroll-down-with-phantomjs-to-load-dynamic-content#17758165)). 

Maybe increasing your screenshot size could help as well.

If you can't resolve the issue, please consider sharing your URL.

**Comment by carrud** [comment]
thanks for your response sir,

i gave much time in renderWaitTime but i saw no impact,
the comment load by itself after main page loaded and no need to scrooldown, actually i only need the article content and user comment in text format.. so i can omit screenshoot feature

here is my crawled content url [https://www.washingtonpost.com/lifestyle/style/the-white-house-correspondents-dinner-doesnt-draw-stars-anymore-so-kathy-griffin-had-it-to-herself/2018/04/29/200356fa-4bba-11e8-af46-b1d6dc0d9bfe_story.html?utm_term=.53e6392b815a](url)

and this is my norconex config :
`<httpcollector id="Minimum Config HTTP Collector">

  
  <progressDir>./examples-output/minimum/progress</progressDir>
  <logsDir>./examples-output/minimum/logs</logsDir>

  <crawlers>
    <crawler id="Norconex Minimum Test Page">

      
      <startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
        <url>https://www.washingtonpost.com/lifestyle/style/the-white-house-correspondents-dinner-doesnt-draw-stars-anymore-so-kathy-griffin-had-it-to-herself/2018/04/29/200356fa-4bba-11e8-af46-b1d6dc0d9bfe_story.html?utm_term=.53e6392b815a</url>
      </startURLs>

      

      
      <workDir>./examples-output/minimum</workDir>

      
      <maxDepth>0</maxDepth>

      
      <sitemapResolverFactory ignore="true" />

      
      <delay default="8000" />
      
	  <documentFetcher class="com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher">
		  <exePath>C:\Users\phiec\Desktop\phantomjs-2.1.1-windows\bin\phantomjs.exe</exePath>
          <renderWaitTime>12000</renderWaitTime>
          <referencePattern>^.*\$</referencePattern>    

        </documentFetcher>
	  
	  
      
      <importer>
        <postParseHandlers>
          
          <tagger class="com.norconex.importer.handler.tagger.impl.KeepOnlyTagger">
            <fields>title,keywords,description,document.reference</fields>
          </tagger>
        </postParseHandlers>
      </importer> 
      
      
      <committer class="com.norconex.committer.core.impl.FileSystemCommitter">
        <directory>./examples-output/minimum/crawledFiles</directory>
      </committer>

    </crawler>
  </crawlers>`

**Comment by essiembre** [comment]
After looking into it, it turns out the comments are loaded only when displayed (so on scrolling to them).  This is why you do not get them with PhantomJS unless you simulate scrolling like previously mentioned.

The site also makes it difficult to crawl by forcing redirects to happen.  PhantomJS can sometimes have difficulties with redirects. 

If you can live without the comments, I was able to get the content with the default document fetcher, which is also much faster.  

You may also want to disable ``<canonicalLinkDetector ignore="true" />`` if that causes you trouble.

You could also extend the GenericDocumentFetcher to also fetch comments for a page by invoking the REST API the site uses via AJAX to pull them out if you can figure out how to do so.  That's likely no trivial task though.

**Comment by wolverline** [comment]
I tried to crawl pages with infinite scroll and/or pagination (_thanks to mobile, this is a growing trend_) with PhantomJS but it doesn't seem to be working very well. Writing PhantomJS script itself is a big pain (no wonder why the project has been suspended). If you look at the the following url, it comes from the separate content server through WS API and I am sure a JS framework renders it. If you're able to access the API, I'd recommend it.

https://comments-api.ext.nile.works/v1/search?q=((childrenof%3A+https%3A%2F%2Fwww.washingtonpost.com%2Flifestyle%2Fstyle%2Fthe-white-house-correspondents-dinner-doesnt-draw-stars-anymore-so-kathy-griffin-had-it-to-herself%2F2018%2F04%2F29%2F200356fa-4bba-11e8-af46-b1d6dc0d9bfe_story.html+source%3Awashpost.com+(((state%3AUntouched++AND+user.state%3AModeratorApproved)+OR+(state%3AModeratorApproved++AND+user.state%3AModeratorApproved%2CUntouched)+OR+(state%3ACommunityFlagged%2CModeratorDeleted+AND+user.state%3AModeratorApproved)+)+)+++))+itemsPerPage%3A+15+sortOrder%3AreverseChronological+safeHTML%3Aaggressive+children%3A+2+childrenSortOrder%3Achronological+childrenItemsPerPage%3A3++(((state%3AUntouched++AND+user.state%3AModeratorApproved)+OR+(state%3AModeratorApproved++AND+user.state%3AModeratorApproved%2CUntouched)+OR+(state%3ACommunityFlagged%2CModeratorDeleted+AND+user.state%3AModeratorApproved)+)+)++pageAfter%3A%221525044545.417%22&appkey=prod.washpost.com
