### ISSUE TITLE
Norconex support for async sites

### ISSUE THREAD

**Issue by pravinkenator** [Norconex/collector-http#486]
Does Norconex web crawler support async sites? I'm not able to find the details in the documentation.

**Comment by essiembre** [comment]
What do you mean by "async"?  Do you mean JavaScript-driven?  If so, have a look at replacing the default document fetcher with [PhantomJSDocumentFetcher](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/PhantomJSDocumentFetcher.html).

**Comment by pravinkenator** [comment]
Thanks for your reply Pascal. I mean sites with angular code angular code (asynchronous sites)

**Comment by essiembre** [comment]
My answer is what you are looking for then.

**Comment by pravinkenator** [comment]
Perfect, Thanks.
