### ISSUE TITLE
[XMLFeedLinkExtractor] Urls splitted

### ISSUE THREAD

**Issue by sylvainroussy** [Norconex/collector-http#487]
The _characters()_ method of the **FeedHandler** is called several times (due to the behaviour of the Sax Parser, see https://stackoverflow.com/questions/13336140/sax-parsing-and-special-characters?noredirect=1&lq=1 and https://stackoverflow.com/questions/4567636/java-sax-parser-split-calls-to-characters?noredirect=1&lq=1), causes splitting of the extracted Url.

We're working on a pull request.

**Comment by essiembre** [comment]
[Version 2.8.1](https://www.norconex.com/collectors/collector-http/download) was released with that fix.
