### ISSUE TITLE
Stopping of the collector isn't working

### ISSUE THREAD

**Issue by AntonioAmore** [Norconex/collector-http#49]
I run collector such way:  ```./collector-http.sh -a start /a/config/path/config.xml```

Then trying to stop it: ```./collector-http.sh -a stop /a/config/path/config.xml```

It returns following:
```
INFO  [AbstractCrawlerConfig] Reference filter loaded: com.norconex.collector.core.filter.impl.ExtensionReferenceFilter@7fa98a66[onMatch=EXCLUDE,extensions=jpg,gif,png,ico,swf,css,js,pdf,doc,xls,ppt,txt,odt,zip,rar,gz,swf,xlsx,docx,pptx,mp3,wav,mid,caseSensitive=false]
INFO  [AbstractCollectorConfig] Configuration loaded: id=somename; logsDir=/somwdir/workdir/logs; progressDir=/somedir/workdir/progress


An ERROR occured:

This collector cannot be stopped since it is NOT running.


Details of the error has been stored at: ...
```

The file with details contains
```
com.norconex.collector.core.CollectorException: This collector cannot be stopped since it is NOT running.
	at com.norconex.collector.core.AbstractCollector.stop(AbstractCollector.java:126)
	at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:73)
	at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:75)
```

I'm highly appreciate for your help and hope my experience is useful for making this nice software better.

**Comment by essiembre** [comment]
I was able to reproduce.  A fix in progress.

**Comment by AntonioAmore** [comment]
Thank you. May I have a development snapshot when it will fixed?

**Comment by essiembre** [comment]
Of course. :-)  I am hoping today.

**Comment by essiembre** [comment]
A snapshot release is now available [here](https://oss.sonatype.org/content/repositories/snapshots/com/norconex/collectors/norconex-collector-http/2.0.2-SNAPSHOT/norconex-collector-http-2.0.2-20150127.060813-2.zip).

If you overwrite your current install, make sure to remove duplicate JARs in the lib folder (a few have their version upgraded).

Let me know if you can stop now.

**Comment by AntonioAmore** [comment]
Just checked it - works perfectly. It stops much faster than 1.3.* branch. Excellent software!

**Comment by essiembre** [comment]
Thank you! I'll leave this issue open until 2.0.2 is officially released.

**Comment by essiembre** [comment]
2.0.2 released: http://www.norconex.com/collectors/collector-http/download
