### ISSUE TITLE
How to use TextPatternTagger to extract domain.subdomain into new field

### ISSUE THREAD

**Issue by kodo651** [Norconex/collector-http#493]
Hi!

I've been struggling to use the TextPatternTagger to extract the domain+subdomain (x.y.z -> y.z). I have a field, uri, which essentially is equivalent to "document.reference". I would like to apply a regex in order to extract y.z from the uri-field and then put it into a new meta-data field, "domain". Is there an easy way to accomplish this?

Many, many thanks in advance!

Ps
  No need to provide a regex as I have it already - it's the settings I'm looking for :)
Ds

**Comment by ronjakoi** [comment]
My solution with `ScriptTagger` in JavaScript:

```xml
<tagger class="com.norconex.importer.handler.tagger.impl.ScriptTagger" >
    <script><![CDATA[
        var URI = Java.type("java.net.URI");
        var host = (new URI(reference)).getHost();

        var parts = host.split(".");
        /* If the last portion of the host begins with a number,
		it's an IPv4 address and there is no domain to be found. */
        if(!parts[parts.length-2].match(/^[0-9]/)) {
            var domain = parts[parts.length-2] + "." + parts[parts.length-1];
            metadata.addString("domain", domain);
        }
    ]]></script>
</tagger>
```

**Comment by essiembre** [comment]
@kodo651, its name does not give it away, but TextPatternTagger is applied on the "body" of a document.  Besides the useful scripting suggestion by @ronjakoi, you can have a look at [ReplaceTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ReplaceTagger.html). Something like this should work:

```xml
  <tagger class="com.norconex.importer.handler.tagger.impl.ReplaceTagger">
      <replace fromField="uri" toField="domain" regex="true">
          <fromValue>your (regex)</fromValue>
          <toValue>$1</toValue>
      </replace>
  </tagger>
```
Please confirm.

**Comment by kodo651** [comment]
A big thank you to both of you. Right now I'm leaning towards the "ReplaceTagger" however I fail to get it working. This is what I'm trying to apply:

          <tagger class="com.norconex.importer.handler.tagger.impl.ReplaceTagger">
            <replace fromField="uri" toField="domain" regex="true">
              <fromValue>^(?:https?:\/\/)?(?:[^@\n]+@)?(?:www\.)?([^:\/\n]+)</fromValue>
              <toValue>$1</toValue>
            </replace>
          </tagger>

Although I have a valid uri in the uri-field, the tagger fails to apply the regex to the content - it simply performs a copy operation. What am I doing wrong here?

**Comment by essiembre** [comment]
Not sure if it should be considered an issue, but try adding ``.*`` at the end of your regex.  Works for me when I do so.

**Comment by kodo651** [comment]
Hello!

I really appreciate your effort here in helping me out :)
I tried your suggestion but it didn't help... Would you mind posting your working code fragment here as it looks in your config-file?
Many thanks!

**Comment by essiembre** [comment]
The following works for me:

```xml
<importer>
  <postParseHandlers>
    <tagger class="com.norconex.importer.handler.tagger.impl.ReplaceTagger">
      <replace fromField="uri" toField="domain" regex="true">
        <fromValue>^(?:https?:\/\/)?(?:[^@\n]+@)?(?:www\.)?([^:\/\n]+).*</fromValue>
        <toValue>$1</toValue>
      </replace>
    </tagger>    
  </postParseHandlers>
</importer>
```

**Comment by kodo651** [comment]
I'm so sorry! The configuration worked as expected - I had forgotten to do some "housekeeping" (emptying intermediate results before re-crawling) but now when I've done that it looks perfect!

Many, many thanks for your help!

Cheers

**Comment by essiembre** [comment]
No problem. Glad it works for you now.
