### ISSUE TITLE
Filtering punctuation

### ISSUE THREAD

**Issue by murdock71** [Norconex/collector-http#494]
I have a use case where punctuation is causing incomplete results. For example I.C.C. International in the document does not show up if the user searches for ICC International. There are other examples with colon, apostrophe, etc so this isn't just a period issue.

What would be the best way to handle this?

Thank You

**Comment by essiembre** [comment]
You likely can tweak your search engine to handle such scenario.  With Solr for example, you would use Solr Analysers for this.

If you are looking at performing some kind of normalization/cleaning at indexing time using the HTTP Collector instead, you can have a look at the [ReplaceTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ReplaceTagger.html) to eliminate punctuation characters from fields, or [ReplaceTransformer](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/impl/ReplaceTransformer.html) if you want to modify the document content.
