### ISSUE TITLE
Log consolidation for multiple sites

### ISSUE THREAD

**Issue by wolverline** [Norconex/collector-http#496]
This is a question regarding log consolidation. I am trying to create a consolidated log file from multiple site crawlers. By default, Norconex creates log files according to each of the site id (& folder name). In my case, there are several crawlers running at the same time. It isn't easy to check up all the processes in real time (or at the same time). Is there any way I can modify the log file name? At this point, I am not sure how log4j can handle file lock, tough. Any insight would be appreciated.

**Comment by essiembre** [comment]
This is not something currently supported by the HTTP Collector, but you may want to investigate if log4j supports log consolidation. This being said, I am not sure how recommended it is to log from different processes into the same file.  

You can also look at log analyzing tools out there (e.g. Logstash).  

If what you want is to keep an eye on running processes, you can also use [Norconex JEF Monitor](https://www.norconex.com/jef/monitor/).

**Comment by wolverline** [comment]
I think using tools is the way to go. I'll keep looking into it. Thanks!
