### ISSUE TITLE
How can I crawl two sites with stayOnDomain=true

### ISSUE THREAD

**Issue by joettt** [Norconex/collector-http#497]
Hi, 

On our web site, users are authenticated on a domain different than where the site contents are.  With stayOnDomain=true, the Norconex crawler stays on the first domain and ignores the second domain even if it is listed under the startURLs.  How do I get around this limitation?  I do not want to set stayOnDomain=false

Thanks.

**Comment by essiembre** [comment]
For more control, I am afraid you will have to set ``stayOnDomain`` to ``false``.  Don't worry, you can achieve what you want some other ways.  One way to do this is to rely on reference filters instead.

```xml
    <referenceFilters>
        <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="include">
            https://www.my-main-site.com/.*
        </filter> 
        <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="include">
            https://www.my-login-site.com/login/.*
        </filter> 
    </referenceFilters>
```

**Comment by joettt** [comment]
"rely on reference filters" trick worked.  Thanks a lot!!

**Comment by essiembre** [comment]
Perfect. Thanks for confirming.
