### ISSUE TITLE
Stay On URL

### ISSUE THREAD

**Issue by HappyCustomers** [Norconex/collector-http#501]
I have the following requirement:

1. To Crawl all the pages in a given URL , not the entire domain
Example : http://www.paihotels.com/the-president-hotel-jayanagar-bangalore/ 
The crawler should not crawl the other urls in the domain. 

2. I want to extract the following data into Solr
  URL, Title, Meta Keywords, Meta Description and the HTML content

I am able to crawl and store the data in Solr
I have the following problem

it is storing unwanted fields
It is crawling beyond the start URL

I have configured the XML as attached

----------------------

	  #set($urlFilter = "com.norconex.collector.http.filter.impl.RegexURLFilter")
	  #set($http = "com.norconex.collector.http")
	  #set($core = "com.norconex.collector.core")
	  #set($urlNormalizer   = "${http}.url.impl.GenericURLNormalizer")
	  #set($filterExtension = "${core}.filter.impl.ExtensionReferenceFilter")
	  #set($filterRegexRef  = "${core}.filter.impl.RegexReferenceFilter")

<httpcollector id="Sample Test Collector">

	<progressDir>./slr/progress</progressDir>
	 <logsDir>./slr/logs</logsDir>
	  
	<crawlerDefaults>

		<urlNormalizer class="$urlNormalizer" />
		<numThreads>2</numThreads>
		<maxDepth>3</maxDepth>
		<workDir>./slr/workdir</workDir>
		<orphansStrategy>DELETE</orphansStrategy>
		<delay default="1500" />
		<userAgent>Test Web Crawler</userAgent>

		
		
		

		<referenceFilters>
		  <filter class="$filterExtension" onMatch="exclude">jpg,gif,png,ico,css,js</filter>
		</referenceFilters>

	 </crawlerDefaults>
  
	  
	  
    <crawlers>
	
        <crawler id="sample Test Example">
            
            
                
            

			<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
					<url>http://www.paihotels.com/the-president-hotel-jayanagar-bangalore/</url>
			</startURLs>

			
			 <canonicalLinkDetector ignore="false" />
            
            <maxDepth>5</maxDepth>
		
			<sitemapResolverFactory ignore="true" />
			
            
            <delay default="1500" />

            
            <httpURLFilters>
                <filter class="$urlFilter"
                    onMatch="include">http://www.paihotels.com/the-president-hotel-jayanagar-bangalore/.*</filter>
                <filter class="$urlFilter"
                    onMatch="exclude">.+\.(png|jpg|jpeg|gif|ico|css|js)$</filter>
                <filter class="$urlFilter"
                    onMatch="exclude">.+\?.*</filter>
            </httpURLFilters>

			<importer>
				<postParseHandlers>
						
					<tagger class="com.norconex.importer.handler.tagger.impl.KeepOnlyTagger">
						<fields>title,keywords,description,document.reference</fields>
					</tagger>
				</postParseHandlers>
			</importer>
			
			
			

			
			          
            
            <committer class="com.norconex.committer.solr.SolrCommitter">
                <solrURL>http://localhost:8983/solr/norconex/</solrURL>
				
				<sourceReferenceField keep="false">document.reference</sourceReferenceField>
				<targetReferenceField>id</targetReferenceField>
				<targetContentField>content</targetContentField>				 
				<commitBatchSize>3</commitBatchSize>
				<queueDir>./slr/optional/queue/path/</queueDir>
				<queueSize>10</queueSize>
				<maxRetries>2</maxRetries>
				<maxRetryWait>5000</maxRetryWait>
			</committer>

        </crawler>
    </crawlers>
</httpcollector>

----------------

**Comment by essiembre** [comment]
If you just want the content of the URL you provided and the content of pages referenced by that main one, change the maxDepth to 1.

As for unwanted fields, KeepOnlyTagger should do the trick. What are they?

**Comment by HappyCustomers** [comment]
Thanks I will try and get back to you
One Quick Question If I want the entire domain what is the setting Please
for example if I want all the pages of www.acmehotels.com

**Comment by HappyCustomers** [comment]
I tried with Depth 1 it is only fetching two pages, 
http://www.paihotels.com/the-president-hotel-jayanagar-bangalore/
This URL has 5 pages has 8 pages. Thanks in advance

**Comment by HappyCustomers** [comment]
<maxDepth>1</maxDepth>
<filter class="$urlFilter"
                    onMatch="include">http://www.paihotels.com/the-president-hotel-jayanagar-bangalore/.*</filter>

These are the settings for this start URL
<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
					<url>http://www.paihotels.com/the-president-hotel-jayanagar-bangalore/</url>
</startURLs>

The Crawler is fetching this URLs which are not required.
                http://www.paihotels.com/the-president-hotel-hubli/
        "http://www.paihotels.com/hotel-pai-vista-mysore/"
        "http://www.paihotels.com/promotions.html"
        :"http://www.paihotels.com/restaurants/restaurants.html"

I want The crawlers to fetch  pages under  http://www.paihotels.com/the-president-hotel-jayanagar-bangalore/ only

Please advise
Thank You

**Comment by HappyCustomers** [comment]
One More help needed. I crawl a particular website and the crawler is committing the contents to solr. However if I run another website using the same XML configuration by changing the start URL , the committer is over writing the previously stored Contents. What is the settings for adding websites to the solr?
Thanks in advance

**Comment by HappyCustomers** [comment]
How to update solr with same XML file with another website.
For Example. if Crawl ww.abc.com and then want to add using the same XML and change the start URL to www.xyz.com.
I change the start URL However solr is getting overwritten with new website
Thank you

**Comment by HappyCustomers** [comment]
<maxDepth>1</maxDepth>
<filter class="$urlFilter"
                    onMatch="include">http://www.paihotels.com/the-president-hotel-jayanagar-bangalore/.*</filter>

<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
					<url>http://www.paihotels.com/the-president-hotel-jayanagar-bangalore/</url>
</startURLs>

**Comment by HappyCustomers** [comment]
Is there any sample Java project available to call the crawler and solr committer? Thank you

**Comment by essiembre** [comment]
Have a look at the [configuration documentation](https://www.norconex.com/collectors/collector-http/configuration).  You will see you filter tag needs to be wrapped in a ``<referenceFilters>`` tag.  Also, the regex in your example has a space in it I am not sure you want.

About reusing XML: Normally, the HTTP Collector detects modifications, deletions, etc. so your Solr index can be kept up-to-date.  If you change the start URL, it will think there is a whole bunch of new URLs and all the previous ones are gone.  If you really want to share the same XML, the easiest is simply to have more than one ``<url>`` tag in your config.  Another approach is to make use of the "crawlerDefaults", and finally, you can have reusable XML fragments that you can ``#include`` in different parent ones.

**Comment by HappyCustomers** [comment]
Thanks for the quick response. I was able to filter URL using referencefilters. 
Also I am able to add new data to solr using different XML files 
Once again Thank you  for the quick  solution

**Comment by essiembre** [comment]
No problem!
