### ISSUE TITLE
com.norconex.committer.core.Committer: Cannot index document batch to Solr

### ISSUE THREAD

**Issue by joettt** [Norconex/collector-http#503]
Hi,

I am seeing this error but my context field is set as text_general.  

1) Any suggestion what I could do to fix the issue?
2) I understand the issue should be fixed but any way to ignore such errors so the rest of the batch does not fail?

I have attaced my scema file.

"possible analysis error: Document contains at least one immense term in field="content" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[66, 117, 108, 108, 101, 116, 105, 110, 32, 100, -30, -128, -103, 105, 110, 102, 111, 114, 109, 97, 116, 105, 111, 110, 32, -61, -87, 108, 101, 99]...', original message: bytes can be at most 32766 in length;"
[schema.txt](https://github.com/Norconex/collector-http/files/2182355/schema.txt)

Thanks

**Comment by essiembre** [comment]
Are you tokenizing your content in your schema field definition or storing it as one long string?  If you are tokenizing and still have this (e.g., a long string without any spaces), you can truncate the value to force it in.  To do this, I suggest you have a look at [TruncateTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/TruncateTagger.html) or [SubstringTransformer](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/impl/SubstringTransformer.html) and use the most appropriate one in your importer configuration section, as a post-parse handler.

**Comment by joettt** [comment]
I created a new core and used the same schema files and didn't have any problem indexing.  Thank you.
