### ISSUE TITLE
Error for passing arguments with PhantomJSDocumentFetcher config

### ISSUE THREAD

**Issue by wolverline** [Norconex/collector-http#505]
I'm trying to pass arguments to PhantomJs and the config is as following:
```xml
<documentFetcher class="com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher"
  detectContentType="true" detectCharset="true" screenshotEnabled="false">
  <exePath>${run-path}</exePath>
  <scriptPath>${script-path}</scriptPath>
  <resourceTimeout>5000</resourceTimeout>
  <validStatusCodes>200,302,403</validStatusCodes>
  <notFoundStatusCodes>404</notFoundStatusCodes>
  <referencePattern>^https://.*</referencePattern>
  <options>
    <opt>"arg1"</opt>
    <opt>"arg2"</opt>
    <opt>"arg3"</opt>
  </options>
  ...
</documentFetcher>
```
The above bounces an error message: `ERROR [SystemCommand] Command returned with exit value 255 (command properly escaped?).`

The command with args looks like:
`$ /path/to/phantomjs --ssl-protocol=any --ignore-ssl-errors=true --web-security=false --cookies-file=/ /path/to/phantomjs/output/mysite/files/cookies.txt --load-images=false "arg1" "arg2" "arg3" /path/to/phantom_script.js https://mysite.com/ /path/to/output/mysite/files/1532031249935000000 3000 -1 https  600.0x400.0 0.25 5000`

Later, I realized the options tags are for PhantomJS options, not for custom arguments. According the PhantomJS document (http://phantomjs.org/api/command-line.html), custom arguments should be added after the script file.
`$ /path/to/phantomjs --ssl-protocol=any --ignore-ssl-errors=true --web-security=false --cookies-file=/ /path/to/phantomjs/output/mysite/files/cookies.txt --load-images=false /path/to/phantom_script.js https://mysite.com/ /path/to/output/mysite/files/1532031249935000000 3000 -1 https  600.0x400.0 0.25 5000  "arg1" "arg2" "arg3"`

Is there any way I can pass custom arguments?

**Comment by essiembre** [comment]
The simplest way right now is to add those arguments in the PhantomJS script itself.  If you want to share the script with different crawlers, but each having different arguments, you can create a few different parent scripts which dynamically include a common script file.

I am marking this as a feature request to support custom arguments to the script file.

**Comment by wolverline** [comment]
It seems to be the only way. Thanks for your help as always.
