### ISSUE TITLE
Exclude Start URL from Committing to AWS

### ISSUE THREAD

**Issue by jerrywithaz** [Norconex/collector-http#508]
I have a start page that is sort of like a sitemap. I would like for that page to be crawled but not to be committed. The start page is not relevant to the search results and so I'd like for it to be excluded.

How would I go about doing that?

**Comment by essiembre** [comment]
Make it your start URL as you normally would, but filter it out after its download has occurred and links to follow were extracted.  One way to do this is to add the following to your crawler configuration:

```xml
<documentFilters>
  <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude">
      (put here regular expression matching your start URL)
  </filter>
</documentFilters>
```

**Comment by jerrywithaz** [comment]
Perfect! Thanks!

Also, how would I filter for the root url when the href for the link is "/" (aka the homepage).

**Comment by essiembre** [comment]
With the mentioned filter, you use a regular expression to do so.  Like this one (untested):
```
^http://www\.example\.com/?$
```

**Comment by jerrywithaz** [comment]
Ah, thanks!

You're awesome!
