### ISSUE TITLE
Running collector-http example

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#51]
I've downloaded collector-http to try it. Executing the following example:
collector-http.bat -a start -c examples/minimum/minimum-config.xml
I get the error (in spanish, so don't know the proper english message): 
"class not loaded o not found: com.norconex.collector.http.HttpCollector "
What can I do?
Thanks
Carlos

**Comment by essiembre** [comment]
I just downloaded the latest release, and ran the exact same command you did and it worked for me.    Did you change something before running that command?  Maybe a problem with your download... in the "lib" folder, can you locate this file: "norconex-collector-http-2.0.2.jar" ?

Can you try this... open the collector-http.bat file, and replace ``%~dp0`` in these two lines...
```
cd %~dp0
set ROOT_DIR=%~dp0
```
... with the full path to where the batch file is located:
```
cd C:\put\full\path\here
set ROOT_DIR=C:\put\full\path\here
```
Does that fix the issue?

**Comment by csaezl** [comment]
It wasn't such a file. But i've realized that the .zip downloaded was "norconex-collector-http-2.0.2-20150127.060813-2.zip" instead of "norconex-collector-http-2.0.2.zip". I don't remember why. Downloading it again solved the problem.
Thank you for your support.
Carlos
