### ISSUE TITLE
Multiple start URLs including sitemap.xml

### ISSUE THREAD

**Issue by wolverline** [Norconex/collector-http#510]
I have a site that has ajax pagination but I don't want to drag PhantomJS into this. Luckily the sitemap has been set up to have all the links to the articles I need to crawl. However I couldn't get sitemap.xml set up with the following config. It bounds a sitemap.xml not found error.
````xml
<sitemapResolverFactory class="$sitemapFactory" ignore="false" lenient="true">
  <tempDir>$workdir/sitemaps</tempDir>
</sitemapResolverFactory>
````

Alternatively I set up sitemapResolverFactory ignore="true" and add the sitemap as a startURL.
````xml
<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
   <url>${my-url}</url>
   <url>${my-url}/sitemap.xml</url>
</startURLs>
````
But it seems Norconex ignores the URLs in the sitemap file. So I changed it to:
````xml
<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
   <url>${my-url}</url>
   <sitemap>${my-url}/sitemap.xml</sitemap>
</startURLs>
````
Now the base URL seems to be ignored and links in the pages are not picked up. Is there any way I can make both base URL and sitemap work simultaneously?

**Comment by essiembre** [comment]
They should both be supported.  Is the base URL having the ajax pagination?  If so, that would explain why the links for that one are not picked up.  Another reason is if the URLs are the same between the sitemap and base URL, they will not be processed twice.  Can you share your full config?

**Comment by wolverline** [comment]
I was mistakenly looking into different URLs. I can confirm that it supports both urls and sitemaps; so the third config option works. Thank you as always!
