### ISSUE TITLE
How to filter image files ?

### ISSUE THREAD

**Issue by HappyCustomers** [Norconex/collector-http#513]
The http collector is indexing the JPG image files also. I have attached the configuration file along with the URL for your reference.

Example URL Indexed http://www.XXX.com/images/splash3.jpg

[sql_crawler.txt](https://github.com/Norconex/collector-http/files/2309416/sql_crawler.txt)

**Comment by essiembre** [comment]
You are overwriting the reference filters you have defined under crawlerDefaults in the crawler-specific section.  You are using regex in the later whereas the filter you chose is expecting extensions.

If you replace the reference filter defined in your crawler section with the one defined under crawler defaults, it should work.

If you only have one crawler defined, there are no benefits in using the crawler defaults.  I then recommend you do not use the crawlerDefaults section to avoid overwriting yourself accidentally.

**Comment by HappyCustomers** [comment]
Thank you very much, it is working. I am closing the issue
