### ISSUE TITLE
Code sample request

### ISSUE THREAD

**Issue by adriens** [Norconex/collector-http#515]
Hi,

in addition to [tutorials](https://www.norconex.com/collectors/collector-http/tutorials), would it possible to get some guidelines on how to generate a csv that could look like this :

```
source_url, target_url, , ...

```

where we should get a set of target_url for each source_url...in fact, all the ref found on the source_url page ?

That would be awesome.

Thank you in advance for any help.

Kind Regards,

**Comment by essiembre** [comment]
Are you able to crawl successfully?  If so, adding [URLStatusCrawlerEventListener](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/crawler/event/impl/URLStatusCrawlerEventListener.html) to your crawler configuration will provide you with what you are asking for.

**Comment by adriens** [comment]
Hello, yes, i can crowl successfully. i'll add this EventListener and let you know.

Thanks a lot for your support.
