### ISSUE TITLE
Split metadata-attribute with multiple values into multiple metadata-attributes?

### ISSUE THREAD

**Issue by SaschaHeyer** [Norconex/collector-http#516]
Hi Pascal,

it is so much fun to work with the Norconex Collector, thank you.
Well documented and easy fast results.

Is there a way to Split a metadata-attribute with multiple values into multiple metadata-attributes with single value?

I found the splitTagger, but it does not split values into multiple attributes.
https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/SplitTagger.html

**Example:**
```
<meta name="area" content="Technology,Engineering />
```
into
```
<meta name="area" content="Technology/>
<meta name="area" content="Engineering />
```

Thank you
Best regards
Sascha

**Comment by essiembre** [comment]
Thanks for the great feedback!  I am glad you like it.

The ``SplitTagger`` is meant to do what you want.   If that's not working for you, can you share your config?

I tried your above example in the importer section, using the sample configuration provided in the documentation and it worked just fine:

```xml
<importer>
  <postParseHandlers>
    <handler class="com.norconex.importer.handler.tagger.impl.SplitTagger">
      <split fromField="area" regex="true">
        <separator>\s*,\s*</separator>
      </split>
    </handler>
  </postParseHandlers>
</importer>
```
I can confirm the value was split.  The HTML does not get re-written, but the value is becoming a list of strings, instead of a single CSV string.

**Comment by SaschaHeyer** [comment]
Thank you, that's exactly the config which I also use. 

I confim that the value is splitted this way:
```
area=Technology^|~Engineering
```

as far as i understood, this is not equal with:

```
<meta name="area" content="Technology/>
<meta name="area" content="Engineering />
```

Can you confirm that?

**Comment by essiembre** [comment]
Yes, that's the same thing.  What you want is to extract the area into separate values.  What you are reporting seeing is simply the internal storage format.  Normally, you are expected to use a Committer to store extracted data.  You will then see it stored as multiple values.  What Committer are you using?  Don't you get separate values?

**Comment by SaschaHeyer** [comment]
That helped a lot.
Thank you
