### ISSUE TITLE
Unable to crawl one particular website

### ISSUE THREAD

**Issue by HappyCustomers** [Norconex/collector-http#523]
I have crazy scenario where if the start URL is http://www.xyz.com/ , the collector does not index any pages in the website. however if the start URL (http://www.xyz.com/restaurant.html) is any of the inner pages the collector indexes the entire website. please advise.  I have sent the configuration file by email

Also When I enable the log4j.logger.CrawlerEvent.URLS_EXTRACTED=TRACE , the URL_Extracted does not show any internal pages in the log when the home page is the start URL.  if any other page is the starturl then the log4j.logger.CrawlerEvent.URLS_EXTRACTED=TRACE, the log shows other internal pages in the log.

**Comment by essiembre** [comment]
If you look at the source of these two pages, you will see that the "restaurant" one has ``<a href="...">`` tags (regular links) and the home one has none.  The URLs in the home pages are ``<area ...>`` URLs.  You can enable them with [GenericLinkExtractor](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/impl/GenericLinkExtractor.html).  For example, you can add this to your crawler config.
```xml
<linkExtractors>
  <extractor class="com.norconex.collector.http.url.impl.GenericLinkExtractor">
      <tags>
          <tag name="a" attribute="href" />
          <tag name="frame" attribute="src" />
          <tag name="iframe" attribute="src" />
          <tag name="img" attribute="src" />
          <tag name="meta" attribute="http-equiv" />
          <tag name="area" attribute="href" />
      </tags>
  </extractor>
</linkExtractors>
```

**Comment by HappyCustomers** [comment]
Super, Thanks for the quick response as always, The Solution is working.
