### ISSUE TITLE
exclude filter not excluding documents

### ISSUE THREAD

**Issue by dtcyad1** [Norconex/collector-http#532]
Hi Pascal, 

I am running into an issue where the exclude filters are not working. I am including part of my config file and a snippet of the logs. I have tried various combinations of the filter, but nothing seems to work. I have tested different regex expressions in a tester and they do work. But for some reason, the documents are still being crawled and indexed. I have tried setting like "https://www.example.com/de_DE/" "https://www.example.com/de_DE/.*" "de_DE*" but nothing seems to work.
```xml
<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
	      <url>https://www.example.com</url>
      </startURLs>

      <!-- === Recommendations: ============================================ -->

      <!-- Specify a crawler default directory where to generate files. -->
      <workDir>./examples-output/minimum</workDir>

      <!-- Put a maximum depth to avoid infinite crawling (e.g. calendars). -->
      <maxDepth>-1</maxDepth>
      <!-- <maxDocuments>9</maxDocuments> -->
      <canonicalLinkDetector ignore="false" />

      <!-- We know we don't want to crawl the entire site, so ignore sitemap. -->
      <sitemapResolverFactory ignore="false" />

      <metadataChecksummer disabled="true" keep="false" targetField="collector.checksum-metadata" class="com.norconex.collector.http.checksum.impl.LastModifiedMetadataChecksummer" />

      <orphansStrategy>DELETE</orphansStrategy>

      <!-- Be as nice as you can to sites you crawl. -->
      <delay default="0" />

      

      <referenceFilters>
	<filter class="com.norconex.collector.core.filter.impl.ExtensionReferenceFilter" onMatch="exclude">jpg,gif,png,ico,css,js,svg</filter>

	
	<filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter" onMatch="exclude">de_DE</filter>
	
      </referenceFilters>
```

```
Norconex Minimum Test Page: 2018-10-29 16:00:56 INFO -          DOCUMENT_FETCHED: https://www.example.com/de_DE/
Norconex Minimum Test Page: 2018-10-29 16:00:56 INFO -     REJECTED_NONCANONICAL: https://www.example.com/de_DE/
Norconex Minimum Test Page: 2018-10-29 16:00:56 INFO -       REJECTED_REDIRECTED: https://www.example.com/de_DE (HttpFetchResponse [crawlState=REDIRECT, statusCode=301, reasonPhrase=Moved Permanently (https://www.example.com/de_DE/)])
Norconex Minimum Test Page: 2018-10-29 16:00:57 INFO -          DOCUMENT_FETCHED: https://www.example.com/de_DE/
Norconex Minimum Test Page: 2018-10-29 16:00:57 WARN - Circular reference between redirect and canonical URL detected. Will ignore canonical directive and process URL: "https://www.example.com/de_DE/". Redirect trail: [https://www.example.com/_display?p_p_id=82&p_p_lifecycle=1&p_p_state=normal&p_p_mode=view&_82_struts_action=%2Flanguage%2Fview&_82_groupId=%24page.getGroupId%28%29&_82_privateLayout=false&_82_redirect=https%3A%2F%2Fwww.example.com%2F-%2Fexplore-2016-banner&_82_languageId=en_IN, https://www.example.com/de_DE/home, https://www.example.com/de_DE]
Norconex Minimum Test Page: 2018-10-29 16:00:57 INFO -       CREATED_ROBOTS_META: https://www.example.com/de_DE/
Norconex Minimum Test Page: 2018-10-29 16:00:57 INFO -            URLS_EXTRACTED: https://www.example.com/de_DE/
Norconex Minimum Test Page: 2018-10-29 16:00:57 INFO -         DOCUMENT_IMPORTED: https://www.example.com/de_DE/
Norconex Minimum Test Page: 2018-10-29 16:00:57 INFO -    DOCUMENT_COMMITTED_ADD: https://www.example.com/de_DE/
```
Thanks

**Comment by dtcyad1** [comment]
Ok.. I was able to tweak the regex to exclude. So that seems to work now. However, for debugging, what is the best way to crawl just the one page that is in the start URL. I tried putting in the start URL of a page and setting the maxdocuments to 2. The JEF Monitor shows that 300 references were found and after processing 2 files, the crawler stops. But there is not really much info in the logs on DEBUG level and there is no crawledFiles Folder or the customary 3 files per document. I was expecting to see just the one or even 2 files. How can we prevent the 300 or so reference s from being discovered and just the one page that is in the start urls to be processed?

I also saw in the log file that the document was queued, but nothing else.

Also, while i did get the regex to work, the syntax of what works and what does not differs from any of the online testers. Do you have a couple of samples that you could paste here.
for example:
http://www.example.com/documents/meta/.. --> this should not be crawled
but
http://www.example.com/meta/...  should be crawled

I tried something like http://www.example.com/documents/meta/.* to exclude the top one, but that does not seem to work, although it does pass in a tester.

Thanks

**Comment by essiembre** [comment]
For only crawling the start URLs and nothing more, set the ``maxDepth`` to 0.  If you have many start URLs, you may want to consider using a ``<urlsFile>`` instead of a series of ``<url>``.

As for the regex not working, are you making sure to clean the workdir before each config change (like also mentioned in #531).   Another strategy is to set the ``<orphansStrategy>`` to IGNORE or DELETE.

**Comment by dtcyad1** [comment]
thanks
