### ISSUE TITLE
Typo3 v8.7 form login problems

### ISSUE THREAD

**Issue by NKDM44** [Norconex/collector-http#536]
I have a problem with the collector and the typo3 auth mechanics:

I get my okay from the server, but receive for every page inside the password protected area the login page...  
```
INFO  [GenericHttpClientFactory] Performing FORM authentication at "http://<server>/index.php?id=33"(username=<user> password=*****)
INFO  [GenericHttpClientFactory] Authentication status: HTTP/1.1 200 OK
```

Collector Client Params:
 ```
<httpClientFactory class="$httpClientFactory">
        <cookiesDisabled>false</cookiesDisabled>
        <connectionTimeout>5000</connectionTimeout>
        <expectContinueEnabled>true</expectContinueEnabled>
        <authMethod>form</authMethod>
        <authURL>http://<server>/index.php?id=33</authURL>
        <authUsernameField>user</authUsernameField>
        <authPasswordField>pass</authPasswordField>
        <authUsername>USER</authUsername>
        <authPassword>******</authPassword>
 </httpClientFactory>
```

I have no problems with this in an older version of typo3 like v4.5...

**Comment by essiembre** [comment]
I am curious, do you get OK, even with bad credentials?  I would like to rule out that auth errors are not wrongfully returned with error code 200.

Also, make sure the "authURL" is the target URL of the HTML form, not the URL of the page containing the form (unless they happen to be the same).

**Comment by essiembre** [comment]
I suspect Typo3 may require extra parameters or specific HTTP headers.  I recommend you try to find out what is sent to your server when you login.  You will know what you need to replicate.   You can use browser plugins to help you with that, such as Live HTTP Headers.

Once you know how to replicate, try to authenticate using a tool with fine-grained control on what you send.  There are browser plugins to help you there such as Postman or Restlet.  If you succeed, see if you can replicate in HTTP Collector config.

**Comment by NKDM44** [comment]
I looked into the headers and the form params and found no differences between the older and current typo3 version. But I copied the headers anyway. You never know. 

I also added the hidden form params which are pretty static like:
 
```
        <authFormParams>
           <param name="logintype">login</param>
           <param name="pid">33</param>
           <param name="redirect_url"></param>
           <param name="tx_felogin_pi1[noredirect]">0</param>
        </authFormParams>
```
But this changed anything and I got without it already Authentication status: HTTP/1.1 200 OK
I have some trouble with the last line which causes a 400 Bad Request. Even if I use backslash as an escape charakter.. 

```
400 with or without \[ 
<param name="tx_felogin_pi1[noredirect]">0</param>
```
The CMS uses an extension called RealURL for elegant urls but you can also use the internal ID like 
index.php?id=xy .. 

Still receive the login page as a response ...
