### ISSUE TITLE
sending post requests with Norconex

### ISSUE THREAD

**Issue by bibiki** [Norconex/collector-http#538]
Hi everyone,
I was wondering, is it possible to instruct norconex to send http post requests and to only retain information from the responses to those. I hope the request makes sense!
Thank you in advance for any kind of hint or information on this.

**Comment by essiembre** [comment]
It is currently not a configurable option, but it is possible via creating your own document fetcher.  Luckily, if you know your Java a bit, you can simply extend [GenericDocumentFetcher.html#createUriRequest](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/GenericDocumentFetcher.html#createUriRequest-com.norconex.collector.http.doc.HttpDocument-) to return an HttpPost instead when appropriate.

Does that answer?

**Comment by bibiki** [comment]
Hey @essiembre ,
thanks a lot for taking the time to respond. Your answer sounds promising. My concern right now is what if I want to do POST at depth level 2, but I want to do GET at levels 0 and 1. Or is this better handled with a regex matching URLs that I want a POST for? Any ideas?

**Comment by essiembre** [comment]
In that method you need to override, you receive a document instance as an argument. 

With that object, you should be able to obtain a URL/document depth with ``doc.getMetadata().getInt("collector.depth");``.

**Comment by bibiki** [comment]
hey @essiembre ,
I just wanted to let you know that extending GenericDocumentFetcher and overriding its' createUriRequest worked fine for me.
I configured my crawler with a maxDepth of 0 in order to avoid having to send both GET and POST requests inside the same crawler and because, for some reason, my crawler was unable to find the links that send POST requests.
Thanks a lot.
