### ISSUE TITLE
Alfresco Repository

### ISSUE THREAD

**Issue by Krishna210414** [Norconex/collector-http#539]
Do Norconex Provide the configuration to crawl Alfresco repository?

**Comment by Krishna210414** [comment]
It basically a content repository where people upload /maintain documents.

**Comment by essiembre** [comment]
If it can be accessed via a browser, chances are you can, provided the authentication method is supported (assuming your setup password protected). 

To have it integrate with the Alfresco API (which may be preferable given what you want to achieve), it can also be done, but you would need custom coding to adapt it.  

If you have ways to export the data to be crawled on a file system, another option would be to use the Norconex Filesystem Collector to crawl that content.

Also, I believe Alfresco can be accessed some other way, such as WebDAV or FTP.  With the Filesystem Collector, those protocols are supported.  Check the list at the bottom of the [Filesystem Collector main page](https://www.norconex.com/collectors/collector-filesystem/) for supported "file systems".

**Comment by essiembre** [comment]
FYI, the latest snapshot version of [FileSystem Collector](https://www.norconex.com/collectors/collector-filesystem/download) has CMIS support for all CMS supporting that standard, which includes Alfresco.  You can also find some documentation about in the [GenericFilesystemOptionsProvider](https://www.norconex.com/collectors/collector-filesystem/latest/apidocs/com/norconex/collector/fs/option/impl/GenericFilesystemOptionsProvider.html)

**Comment by essiembre** [comment]
Alfresco support now part of 2.9.0 FileSystem Collector release.
