### ISSUE TITLE
filling Solr "content" field

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#54]
In collector http configuration file I have the sentence:
        <targetContentField>text</targetContentField>
In Solr, "text" field is defined as: indexed="true" stored="false"
On the other hand I'd need to use Solr "content" field (indexed="false" stored="true") to store some meaningful text apart from page title, for example the text from "content" in the web page.
Does collector http provide a way of filling Solr "content" field (as it does with "text")?. Is there a conditional way of taking some text or another depending of some condition collector http could evaluate?.
Thanks,
Carlos

**Comment by csaezl** [comment]
Sorry, second line should say:
```
        <targetContentField>text</targetContentField>
```

**Comment by essiembre** [comment]
I am not sure what you mean to do here.  To have the text content both searchable and displayable, can't you simply use the same Solr field to do both? Like this:
```
<field name="text" indexed="true" stored="true" ...
```
Are you saying you want "some" text to be in field A, and different text to be in field B?  If so, you can look at the handlers offered in the importer module, like the [CopyTagger](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/CopyTagger.html).

Does that answer your question?  If not, please elaborate a bit more.  Maybe by giving a concrete example.

**Comment by csaezl** [comment]
Yes, you are right. It is not ease for me to explain what I need since I'm far from being proficient about crawler strategy and behaviour.
Anyway, i'll try again with a simple example. In order to identify or describe textually a web page, I think that tags as <title> and <content> could do the job. The crawler passes <title>'s text to solr but, afaik, it doesn't pass <content>'s text. How can I get the crawler to pass this text to solr say to "content" field (store, no index)?.
Thanks
Carlos

**Comment by essiembre** [comment]
I think you are missing text in your last post, I do not see the tags you mention.   If you answer withing Github, you should preview your answer before posting to make sure it is good.

**Comment by csaezl** [comment]
Yes, you are right. It is not ease for me to explain what I need since I'm far from being proficient about crawler strategy and behaviour.
Anyway, i'll try again with a simple example. In order to identify or describe textually a web page, I think that tags as ```<title>``` and ```<content>``` could do the job. The crawler passes ```<title>```'s text to solr but, afaik, it doesn't pass ```<content>```'s text. How can I get the crawler to pass this text to solr say to "content" field (store, no index)?.
Thanks
Carlos

**Comment by csaezl** [comment]
Sorry, instead of ```<content>``` I should say "description" or any other element with a supposed description

**Comment by essiembre** [comment]
``<title>`` is a standard HTML tag to represent the title, and that's why it is recognized by the crawler.  Not so sure about ``<description>``.  Are you saying you actually have a ``<description>`` tag in your web pages?   If so , you can use the [TextBetweenTagger](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/TextBetweenTagger.html) to extract any values found between two matching regular expression.  So the possibilities to extract exactly what you want, where you want, are practically without limits.

**Comment by csaezl** [comment]
I really mean:
```<meta name="description" content="Some text" />```

**Comment by essiembre** [comment]
HTML meta data fields are captured by default.   Make sure they are not filtered out by ``KeepOnlyTagger``. To map the HTML meta tag "description" to the Solr field "content", you can simply rename that field using the ``RenameTagger``, like this:   
```
  <tagger class="com.norconex.importer.handler.tagger.impl.RenameTagger">
      <rename fromField="description" toField="content" overwrite="true" />
  </tagger>
```
This tagger needs to go in the ``<postParseHandlers>`` section of your config.  With import handlers, you can do many text and metadata field manipulation without any coding.   I recommend you get familiar with them.  Check this page: http://www.norconex.com/collectors/importer/configuration

At the bottom you'll find a list of available "taggers" and "transformers".

**Comment by csaezl** [comment]
Thank you
Carlos

**Comment by csaezl** [comment]
Sorry for reopen this issue.
After receiving your last answer i've realized that I have Solr documents with the field "Description" that already have the content of ```<meta name="description" content="Some text" />```, so it seems not to be necessary to do any special action to get  "meta/description" text. Not via content field but via description field, generated by the crawler.
Am I right?
Carlos

**Comment by essiembre** [comment]
Yes, that should be right.  Remember if a case like that happens again, there is also the option to create a new field in Solr with whatever name you like.
