### ISSUE TITLE
Crawling Shadow Dom Elements

### ISSUE THREAD

**Issue by alex-kozlowski-maven** [Norconex/collector-http#543]
In the process of using Norconex HTTP Collector I have noticed that shadow dom elements are not being retrieved. Is this a limitation of the collector or is there a configuration option that I am missing?

Thanks

**Comment by essiembre** [comment]
Out-of-the-box HTTP Collector will only capture the static content of an HTML page.  Same content when as doing "View Source" from your browser.  If you want to access DOM elements accessible after the page is rendered, you will have to combine a technology that renders the page first.  Consider using the [PhantomJSDocumentFetcher](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/PhantomJSDocumentFetcher.html) for this purpose.

**Comment by alex-kozlowski-maven** [comment]
Thanks for pointing me in the right direction.
