### ISSUE TITLE
recrawls not following the checksum validation

### ISSUE THREAD

**Issue by dtcyad1** [Norconex/collector-http#544]
Hi,

i am running into issues where the documents are being resent even though he content has not changed. I am using a custom committer.

This is what i tried..

For debugging, i used the file committer and have this in my config:
```xml
<documentChecksummer class="com.norconex.collector.core.checksum.impl.MD5DocumentChecksummer" disabled="false" keep="true" targetField="collector.checksum-doc"/>
```
i deleted the crawledFiles folder between 2 successive runs (not the crawlstore) so that i could see the value of the collector.checksum-doc. In both the runs, the value was different, even though the content (from the .cntnt) remained unchanged. When i do a diff between the 2 files, it shows nothing has changed. How is this checksum calculated - is it based on the raw html content that includes the meta tags or is it based on what gets written to the .cntnt file?

Is the above the correct way to use it?

I also tried it this way - i have a meta data field that has a date, so it tried it this way also:
```xml
<metadataChecksummer class="com.norconex.collector.core.checksum.impl.GenericMetadataChecksummer">
	<sourceFields>article:modified_time</sourceFields>
      </metadataChecksummer>
```
but its the same result. I can see this field in the .meta file. But i still see it being committed.

In issue# 117 you mentioned "What you do with the crawl data is the job of a "Committer". You have to download one that suits your need or create one yourself."  Does this mean that the MVStore does have this date (or checksum based on this meta filed) ? does it also mean that the committer has to get that value from the MVStore and decide wether or  not to commit?

I was under the impression that the logic to check for unmodified happens before something is sent to the committer.

Sorry  - just a little bit confused!! Can we add our own fields to the mv store, like the custom date ?

Thanks

**Comment by dtcyad1** [comment]
Hi Pascal,
in my config file, I only have the document checksummer configured (line
57) - as you pointed out, all the meta  checksummers are commented out. So
why is it  using it? Do I have to explicitly have the meta checksummer and
set the disabled to true?

Thanks

Yogesh Dhavale

Cloud Search Consultant

SADA Systems

O: 813.390.4074 | SADASystems.com <http://sadasystems.com/>

Cloud Consulting | IT Services | App Development | Managed Services

<https://twitter.com/SADASystems> <https://www.facebook.com/SADASystemsinc>
<http://www.linkedin.com/company/sada-systems>

<https://sadasystems.com/blog/sada-systems-named-a-2017-google-cloud-north-america-sales-partner-of-the-year>

**Comment by essiembre** [comment]
Yes, there is a default meta checksummer for both the Filesystem Collector and the HTTP Collector.  If you do not want to use that default, the simplest way to disable is this:
```
 <metadataChecksummer disabled="true" />
```
Make sure you clean your crawl store (or workdir) as it may see it as different when comparing a cached checksum with no checksum (only on next run... then there will be nothing to compare).

**Comment by dtcyad1** [comment]
Hi Pascal,

Thanks - that does seem to work. Quick question though - I thought i saw somewhere in the documentation that by default, it first tries the last mod date and if not available, it will then do a document checksum. In my case, why is that not happening? Why do we explicitly need to turn the meta checksum off?

Thanks

**Comment by essiembre** [comment]
What your log suggested, is that you once had it, and once did not.  So that means from one run to another, the checksum was different (e.g., ``null`` vs "Jan 2nd, 2019").

You are otherwise correct: assuming you start fresh (clean cache), if you have no metadata checksummer defined, it will always consider the document is new/modified unless the document checksummer says otherwise.  If the document checksummer is disabled too, it will always reprocess each doc as if they were new/modified.
