### ISSUE TITLE
Handling of HTTP <-> HTTPS redirects

### ISSUE THREAD

**Issue by Pittiplatsch** [Norconex/collector-http#546]
From https://github.com/Norconex/collector-http/issues/144#issuecomment-446763128:

> Nowadays, with `stayOnDomain`, `stayOnPort`, and `stayOnProtocol` options in place, what is the intended way of handling HTTP <-> HTTPS directions without parsing URLs of **every** port?
> Basically, only `http://my.domain/path` and `https://my.domain/path` urls are to be allowed, whereas `http://my.domain:8080/path` and others are to be rejected.

The trivial
```
stayOnDomain="true"
stayOnPort="true"
stayOnProtocol="false"
```
doesn't seem to work, as the port differs between HTTP (80) and HTTPS (443), as already stated in https://github.com/Norconex/collector-http/issues/144#issuecomment-144621688:

> Because a change of protocol from (http vs https) also changes the port (80 vs 443), it is best to also make the "stayOnPort" false like above.

The trivial approach of
```
stayOnDomain="true"
stayOnPort="false"
stayOnProtocol="false"
```
is not intended as this would also open all other ports, e.g. `https://www.domain.com:8080` (often used for testing purposes, or for related helper services, e.g. search facilities).

**Comment by essiembre** [comment]
The ``stayOnXXX`` options are meant to be an easy setting for most generic scenarios, but can sometimes be too limited. 
If you want more flexible control, you can use one of the many filters available, such as the [RegexReferenceFilter](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/filter/impl/RegexReferenceFilter.html).

**Comment by Pittiplatsch** [comment]
I was in hope to avoid building a regex in a generic manner so that it can be used with arbitrary urls (including `:` (colons) at various - valid - positions within the URL). Such a generic regex is far from trivial.
I'll try my luck with a [ScriptFilter](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/filter/impl/ScriptFilter.html) where I have native access to URL parts without any complex regexes.

**Comment by essiembre** [comment]
You can keep ``stayOnDomain=true`` and see if the following reference filter regex helps (untested): 

```
^https?:\/\/[^:]*(:443|:80)?(\/.*|$)$
```

To see what it matches: https://regexr.com/45fgq

Let me know if that works for you, or the ScriptFilter solution, or whether you would like to turn this somehow into a feature request.
