### ISSUE TITLE
multiple meta data from ppt crawl

### ISSUE THREAD

**Issue by dtcyad1** [Norconex/collector-http#550]
Hi Pascal,

we are crawling some ppt files and we notice this in the .meta file:

dc\:title = /docProps/thumbnail.jpeg
dc\:title = Test \u2013 as of June 13, 2018
Chroma\ ColorSpaceType = RGB
collector.depth = 0
tiff\:BitsPerSample = 8 8 8 8
tiff\:BitsPerSample = 8
Caption\ Digest = 212 29 140 217 143 0 178 4 233 128 9 152 236 248 66 126
height = 197
height = 179

As you can see, there are multiple values for title, of which the first one is incorrect and the second one is correct. While there is a Tagger to get the last one only, we were wondering as to why the first one is even pulled in and from where is it coming, since we could not find it anywhere in the PPT file?
Since we cannot always guarantee that the last one will be the correct one, we are hesitant to use this tagger, since there are a lot of fields that are in multiples.

Thanks

**Comment by essiembre** [comment]
Have a look at [GenericDocumentParserFactory](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/parser/GenericDocumentParserFactory.html).

By default, that parser tries to merge all embedded documents found in a parent document.  In your example, it looks like you have images in your PPT.  If you just want to extract the content of the parent file, or extract embedded files as individual files, look at the ``<embedded>`` options from the above link to documentation.
