### ISSUE TITLE
Prefix all metadata fields with a specific value

### ISSUE THREAD

**Issue by SaschaHeyer** [Norconex/collector-http#553]
Hi Pascal,

is there an out of the box way to add a specific prefix value to each metadata field?

Best regards
Sascha

**Comment by essiembre** [comment]
Yes, if you are concerned with HTTP metadata, you can set an ``<headersPrefix>`` on [GenericMetadataFetcher](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/GenericMetadataFetcher.html).  

If you want ALL metadata to be prefixed, even those obtained after a document gets parsed, I suggest you look at [RenameTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/RenameTagger.html).  It will only do it one by one though.

If you want to do it in bulk, you can maybe write your own ``IDocumentTagger`` or maybe use the [ScriptTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ScriptTagger.html) somehow.

We can also make this a feature request to have some kind of "PrefixTagger" or modify the RenameTagger to support regular expressions.

**Comment by SaschaHeyer** [comment]
Hi Pascal,

appreciate your help thank you. 
It is indeed required for all metadata also those obtained after the document gets parsed. 

I implemented a PrefixTagger and have a additional question regarding the norconex related meta informations like **collector.referenced-urls**.

Does it in any case affect the functionality of Norconex if we rename them as well like **meta.collector.referenced-urls**?

Best regards
Sascha

**Comment by essiembre** [comment]
Renaming them should not cause any problems since important pieces of information are also stored elsewhere than document metadata.  If you notice otherwise, it is probably something to be fixed.

**Comment by SaschaHeyer** [comment]
Hi Pascal,

thank you, your support is amazing.
My solution with the PrefixTagger works well, so far no problems.

Best regards
Sascha
