### ISSUE TITLE
Orchestration of work of many crawlers?

### ISSUE THREAD

**Issue by abolotnov** [Norconex/collector-http#555]
If I wanted to crawl 50 sites (if I understand correctly, I use collector to collect the files, then extractor to extract content and committer to push content to search engine) - is JEF API intended to be used to create the jobs and control that a reasonable number of them executed at a time? 

Is there a way to do this without writing Java code? Looks like I can build 50 template-based configurations for `HTTP Collector` and have configuration for the entire pipeline defined (extract - commit) in it and would only have to figure out a way to run the jobs few at time?

If the only difference in the sites configuration-wise is their start url - is there a way to have a single configuration and a list of start urls instead? And run a single crawler with multiple threads that will eventually cover all sites?

**Comment by essiembre** [comment]
Yes, you can definitely run as many URLs you want in the same crawler.  You can either have many ``<url>`` tags defined, or you can use a ``<urlsFile>`` which contains all your URLs (one per line).  There are a few things that may force you to split them though.  For example:

* If different sites require different settings, like one requiring special authentication, or another where you want to extract content in a special way.
* Performance.  Running with too many threads may reach your server limits.  In such case, you maybe interested to split them.
* Troubleshooting/maintenance: you may prefer to group them and run the groups separately in case one fails and you want to troubleshoot just that one... you can keep running the other ones.

There is no magic formula, but you can look here for ideas: https://www.norconex.com/collectors/collector-http/faq#toc4

**Comment by abolotnov** [comment]
If I wanted to have a single crawler for many URLs, am I still going to be able to make them stay within the domains? Looks like a regex in the config, probably not a good idea to build a regex having 500 items in (aaa.com|bbb.com|ccc.com) in a single regex, right?

**Comment by essiembre** [comment]
Yes, the ``stayOn[...]="true"`` options will be respected for every URLs you have.  That will save you from having regular expressions that go on forever. :-)

**Comment by abolotnov** [comment]
This is beautiful. So far, I am genuinely impressed with the stack. 

so, if I had `http://aaa.com` in the `urlsFile` and it had links to `bbb.aaa.com` (same second-level domain), does this mean it will still get the documents from `bbb.aaa.com` with `stayOnDomain=true`?

**Comment by essiembre** [comment]
Thanks!  Subdomains are treated as unique (different) domains.  If you know what those are, your best bet is to add them as start URLs as well.  We can also make this a feature request if you like. 

In the meantime, if you know your Java, another option is to create your own [ILinkExtractor](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/ILinkExtractor.html) that only returns URLs matching the same domain as the reference URL.

**Comment by essiembre** [comment]
With the latest release if you have ``stayOnDomain="true"``, you can also set ``includeSubdomains="true"`` to treat subdomains as equivalent to the main domain.
