### ISSUE TITLE
Pure Maven Code sample for LinkChecker

### ISSUE THREAD

**Issue by adriens** [Norconex/collector-http#559]
Hi, I'd like to make run the `LinkCheckerCrawlerEventListener` from pure Maven run. I've found this java conf code :

```java
HttpCollectorConfig collectorConfig = new HttpCollectorConfig();
        collectorConfig.setId("MyHttpCollector");
        collectorConfig.setLogsDir("/tmp/logs/");
        

        HttpCrawlerConfig crawlerConfig = new HttpCrawlerConfig();
        crawlerConfig.setId("MyHttpCrawler");
        crawlerConfig.setStartURLs("https://www.myurl.com/");
        crawlerConfig.setMaxDepth(1);

        collectorConfig.setCrawlerConfigs(crawlerConfig);

        HttpCollector collector = new HttpCollector(collectorConfig);
        collector.start(true);
```

But I did not find code sample on how to provide the configuration from Code..and run from Maven.

Could you provide a dedicated Maven section to the actual one http://www.norconex.com/create-a-website-broken-links-checker/ ?

I intend to ru it all from maven. For now I can run the crawling, but could not put the code so the `LinkCheckerCrawlerEventListener` is loaded.

Thank you in advance for your help... I'm not far for having the dead link working...

**Comment by adriens** [comment]
For example, how to specifiy I want the tsv, and where ? :pray:

**Comment by essiembre** [comment]
The class from the article you reference has since be added to the HTTP Collector as [URLStatusCrawlerEventListener](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/crawler/event/impl/URLStatusCrawlerEventListener.html).  You can add it through Java code this way:
```java
        URLStatusCrawlerEventListener listener = new URLStatusCrawlerEventListener();
        listener.setOutputDir("/path/where/to/file");
        crawlerConfig.setCrawlerListeners(listener);
```

Is this what you were looking for?

**Comment by adriens** [comment]
Exactly what I was looking for :fireworks: :+1:

**Comment by adriens** [comment]
Exactly what I was looking for :fireworks: :+1:
