### ISSUE TITLE
Cyclic reference in referenced urls

### ISSUE THREAD

**Issue by SaschaHeyer** [Norconex/collector-http#562]
Hi Pascal,

I am facing some cyclic reference issues, the same Url is crawled and added to **crawledFiles** multiple times. If I search for this specific file i can find it more then 8000 times. 

Crawled URL https://www.local.development/sites/epxress/index.html
With the following link in the markup 
```<a href="../service/index.html" target=_self>```

Is it possible that the **../** in the beginning of the url cause this issue? Any way to prevent this behavior?

**1 Crawled file**
```Content-Location = https://www.local.development/sites/epxress/index.html```
```collector.referenced-urls = https://www.local.development/sites/epxress/../service/index.html```

**n. Crawled file**
```collector.referrer-reference = https://www.local.development/sites/protecciondigital/../service/../company/../service/../company/../service/../company/../service/../company/../service/index.html```

Please let me know if you need more information.
Best regards

Sascha

**Comment by essiembre** [comment]
Without a copy of your page and config it is hard to say for sure, but in any case, I suggest you try URL normalization.  See if the following can fix your issue (in your ``<crawler>`` section):

```xml
  <urlNormalizer class="com.norconex.collector.http.url.impl.GenericURLNormalizer">
    <normalizations>
        removeFragment, lowerCaseSchemeHost, upperCaseEscapeSequence,
        decodeUnreservedCharacters, removeDefaultPort, 
        encodeNonURICharacters, removeDotSegments
    </normalizations>
  </urlNormalizer>
```
The ``removeDotSegments`` entry should ideally do it for you.

**Comment by SaschaHeyer** [comment]
Hi Pascal,

indeed urlNormalizer with removeDotSegments did it. 
I appreciate your work on Norconex, so many useful features.

Thank you
Sascha
