### ISSUE TITLE
referenceFilter : How to crawl domain and sub domains for 1000 websites

### ISSUE THREAD

**Issue by HappyCustomers** [Norconex/collector-http#563]
I have around 1000 websites to be crawled. I need to crawl **any port, any protocol , domain and sub domain only.** 

My start URL configuration is like as follows. URLs will be load text file 
```
 <startURLs  stayOnDomain="false" stayOnPort="false" stayOnProtocol="false">
<urlsFile>...</urlsFile>
</startURLs>
```
My reference filter  is as follows, but it crawls external websites.

`<filter class="$filterRegexRef" onMatch="include">http.{0,1}://[a-zA-Z0-9-/.]*.*</filter>`

I have referred to the issue following issue 
https://github.com/Norconex/collector-http/issues/394
where it is mentioned for each website to have separate Filter Class which is little laborious in my case. 

The below  filter class configuration works however I have to create filter class for all the websites manually
`<filter class="$filterRegexRef" onMatch="include">http.{0,1}://[a-zA-Z0-9-/.]*xyz\.com.*</filter>`

Please advise how to have generic filter class for all the websites where the crawler crawls the domain and sub-domain only.

Thanks in advance

**Comment by essiembre** [comment]
I was convinced there was already a feature request to have ``stayOnDomain`` to optionally work with subdomains, but I could not find it so I am marking this one as such.

**Comment by essiembre** [comment]
In addition to ``stayOnDomain="true"``, the latest snapshot release now allows you to add ``includeSubdomains="true"``.  This will ensure pages on ``example.com`` will have links followed whether they point to ``example.com``, ``www.example.com`` , ``wathever.sub.example.com``, etc.

Please confirm that works for you.

**Comment by HappyCustomers** [comment]
Dear Paul, Thanks for the new feature which is very helpful to crawl the sub-domains. I tested it and is working in most scenarios tested. However in on particular scenario i am getting the following log information and this particular site is not getting crawled

> subdomain_test: 2019-02-16 16:30:47 INFO -           CRAWLER_STARTED
> subdomain_test: 2019-02-16 16:30:47 INFO - subdomain_test: Crawling references...
> subdomain_test: 2019-02-16 16:30:52 INFO -       REJECTED_REDIRECTED: http://www.xyz.com/ (HttpFetchResponse [crawlState=REDIRECT, statusCode=301, reasonPhrase=Moved Permanently (http://xyz.com/)])
> subdomain_test: 2019-02-16 16:30:52 INFO -           REJECTED_FILTER: http://xyz.com/ (URLCrawlScopeStrategy[stayOnProtocol=false,stayOnDomain=true,includeSubdomains=true,stayOnPort=false])

The configuration as  follows with no <referenceFilters> for the particular website
```
<startURLs stayOnDomain="true" stayOnPort="false" stayOnProtocol="false" includeSubdomains="true">
	<url>http://www.xyz.com/</url>
</startURLs>
```
You can recreate the scenarios ad follows.
Start URL contains **www** and the server redirects to **NON-WWW** then the site does not get crawled

Thanks once again for the great software you have produced
Regards
Balu

**Comment by HappyCustomers** [comment]
I have emailed you the sample URLs for Your testing

**Comment by essiembre** [comment]
That feature only goes one way for now.  The "parent" can optionally crawl its "children" but not the other way around.  So that somesite.com will also crawl support.somesite.com but support.somesite.com will not crawl somesite.com.

You can use the URL normalizer to enforce having www (or removing www) from every URLs.

Would you see more benefits than problems in having ``includeSubdomains`` simply allow anything on the same root domain?  That is a page located at ``sub.somesite.com`` would have all the following links followed: ``sub.sub.somesite.com``, ``somesite.com``, ``sub2.somesite.com`` and anything else ending with ``.somsite.com``.

**Comment by HappyCustomers** [comment]
Thank You Pascal. I had implemented the same solution as you have described. I had removed www from all the  start URLs and it is working fine. 
Thank you once again for the quick response and solution
Regards
Balu

**Comment by essiembre** [comment]
Thanks for the update.  What is your opinion on ``includeSubdomains`` to always accept anything below the "root" domain, no matter what the current URL is?    Meaning a page ``www.example.com`` would follow links on ``example.com``, ``support.example.com``, etc.   Basically anything on ``example.com`` even if the start URL was originally ``subdomain.example.com``.

**Comment by HappyCustomers** [comment]
my opinion for `includeSubdomains `is that when the user enters 
1. `support.example.com` it should stay in the same subdomain

2. when the user enters `example.com` it should crawl
`www.example.com` also and other subdomains `support.example.com`

3. exception is when the user enters `www.example.com` it should accept `example.com` and other subdomains if any.
 
Thank you
