### ISSUE TITLE
GenericDelayResolver - Not seeing the wait time in log nor on the screen

### ISSUE THREAD

**Issue by HappyCustomers** [Norconex/collector-http#565]
Dear Mr. Pascal,

I have configured the crawler to delay every 5 seconds as below. However I am not seeing the wait time neither on the screen in command prompt nor in the log. 
I remember seeing the wait time before. 

```
	<delay class="com.norconex.collector.http.delay.impl.GenericDelayResolver"
          default="5000" ignoreRobotsCrawlDelay="true" scope="site" >
	</delay>
```
Please advise
Thank you

**Comment by essiembre** [comment]
You can try with 1 thread and see from the logs if it pauses at every 5 seconds. I do not think it logs the delay per se.

**Comment by HappyCustomers** [comment]
I tried with one thread and the wait time in seconds is still not showing in the CLI.  

Also you are right the wait time was not getting logged in the logs per se.

**Comment by essiembre** [comment]
You see http requests made more frequently than 5 seconds?  Can you share your config?

**Comment by HappyCustomers** [comment]
I have sent the config by email.

**Comment by HappyCustomers** [comment]
> You see http requests made more frequently than 5 seconds? Can you share your config?

I have set 3 seconds , the crawler stops for few seconds , but not sure is it due to delay settings or for any other reason

**Comment by essiembre** [comment]
That would be because of the delay.  The logs won't tell you it is actually waiting.  If you see a stop for a few seconds between pages, that is an indication it is working.

**Comment by HappyCustomers** [comment]
I tried with 30 seconds delay, but the crawlers tops only for few seconds and not for 30 secs.

**Comment by HappyCustomers** [comment]
In the  log4j.properties file if I set the norconex collector Loggers settings to DEBUG then i see the wait ime in the console.

`log4j.logger.com.norconex.collector.http=DEBUG`
