### ISSUE TITLE
crawling website with Cookie and Javascript enabled as Security Service

### ISSUE THREAD

**Issue by HappyCustomers** [Norconex/collector-http#567]
Dear Mr.Pascal Essiembre,

One of the website the following content  is extracted from the webpage, instead of the actual content. 

>  StackPath Please enable cookies This website is using a security service to protect itself from online attacks. The service requires full cookie support in order to view the website. Please enable cookies on your browser and try again. Reference ID: 5492ffc2f2ddd8f55axxxxxxx StackPath Please enable JavaScript This website is using a security service to protect itself from online attacks. The service requires full JavaScript support in order to view the website. Please enable JavaScript on your browser and try again. Reference ID: 5492ffc2f2ddd8f55a34xxxx4 Loading site please wait... 

In the log I get the` DOCUMENT_IMPORTED` And `DOCUMENT_COMMITTED_ADD` .
I have also enabled ` <cookiesDisabled>false</cookiesDisabled>` in `GenericHttpClientFactory`

Please let me know how to crawl these types of websites

Thank you
Regards
Balu

**Comment by essiembre** [comment]
The HTTP Collector does not include a native Javascript renderer.  You may want to have a look at the [PhantomJSDocumentFetcher](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/PhantomJSDocumentFetcher.html).

**Comment by HappyCustomers** [comment]
Thanks Essiembre, 

PhantomJS is not in active development. There are issues using PhantomJS and no support available in the community also.  
Waiting for the new feature headless Browser in Norconex to fetch these types of websites and screenshots of the pages :)
