### ISSUE TITLE
503 REJECTED_BAD_STATUS

### ISSUE THREAD

**Issue by SaschaHeyer** [Norconex/collector-http#568]
Hi Pascal,

I get the following rejected log entry for a specific domain. The issue only occurs with Norconex. In the browser the domain response without 503.

```
REJECTED_BAD_STATUS: https://www.domain.test (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=503, reasonPhrase=Service Unavailable])
```

Any suggestions what might cause this behavior?

Best regards
Sascha

**Comment by essiembre** [comment]
Hello Sascha, I would need to know the site and your config, but is it possible your browser is configured to use a proxy? If so you would have to replicate those proxy settings on the ``GenericHttpClientFactory``.

**Comment by SaschaHeyer** [comment]
Hello Pascal,

the following configuration caused the behavior. If I remove the trustAllSSLCertificates configuration the crawler is able to index the domain. 

```
<httpClientFactory>
      <trustAllSSLCertificates>true</trustAllSSLCertificates>
</httpClientFactory>
```

Any idea how this is might related?

Best regards
Sascha

**Comment by essiembre** [comment]
I am not sure how it could be related.  I would need to be able to reproduce.  

Are you OK with the solution you found?  Else, please indicate how I can reproduce (e.g. what site).

**Comment by SaschaHeyer** [comment]
Hi Pascal,

unfortunately is a non public site which is not sharable. 
Yes I am ok with the solution. 

Best regards
Sascha
