### ISSUE TITLE
How to rotate logs in the <logsDir>, based on log-file size?

### ISSUE THREAD

**Issue by ciroppina** [Norconex/collector-http#569]
Dear Sirs

I am running a http collector configured to crawl about 20 websites
After 3-days working, it generated a log-file of about 3.6GB in the folder configured by "logsDir" tag, under the path: [collector name]/logs/latest/logs/

I tried to configure a rotate-log policy in the "log4j.properties" file, the one under the installation directory, by adding these two lines:
```
log4j.appender.CONSOLE.MaxFileSize=10240KB
log4j.appender.CONSOLE.MaxBackupIndex=10

```
but that does not work: I still get only one big .log file. How should I configure that ?
thanks

**Comment by essiembre** [comment]
The files are automatically backed up after each run, but they currently do not rotate within a running session.    The next major release (no defined date) of HTTP Collector will no longer have a hard handle on the logs, which will give more flexibility to configure it however you want.

In the meantime, you will have to rely on an external process to truncate/rotate large files, such as ``logrotate`` for Linux or a Windows equivalent.  

Alternatively, if you want to get into code, you can provide your own [ILogManager](https://github.com/Norconex/jef/blob/master/norconex-jef/src/main/java/com/norconex/jef4/log/ILogManager.java) implementation.

**Comment by ciroppina** [comment]
This sentence "_The files are automatically backed up after each run_" seems not to be always true. I configured the connector to run as a Windows Scheduled Task, running every day at "6:15PM", for max "23 hours", then the run stops and waits to restart at next "6:15PM" - but after restarted it continues to write to the same log file. When the log file size is more than 3.5GB the connector terminates because (I guess) is is no more able to manage a so huge log file.
At the next "6:15PM" the connector starts and stops immediately (after less than 1 minute) because of the size of the log file. Neither I am able to inspect a so big log file

**Comment by essiembre** [comment]
You are correct.  I should have said: after every successful completion, a back-up of the logs is made when you next start the collector.   A stop/resume will keep the same log.

You can definitely reduce greatly the logs.  Have a look at the ``log4j.properties`` file and set all log levels you find to either WARN or ERROR.

**Comment by essiembre** [comment]
You can now rely 100% on your own log4j configuration with the latest snapshot release.  Which means you can rotate your logs however you want.  Have a look at: https://github.com/Norconex/collector-http/issues/593#issuecomment-485035899
