### ISSUE TITLE
Norconex blocked as malicious bot

### ISSUE THREAD

**Issue by SaschaHeyer** [Norconex/collector-http#570]
Hello Pascal,

I am facing currently the issue that Norconex is being blocked as malicious bot.
Is there some way to log the requests which Norconex made? I would need that in order to define some excludes in our bot block logic. 

Best regards
Sascha

**Comment by essiembre** [comment]
Sure, the logs should tell you.  Make sure the log4j.properties files has the entries you are interested in set to INFO or DEBUG.

My advice to avoid being blocked is to be nice to the sites you crawl.  The default wait time between each download is 3 seconds.  Depends how big the site is, but if you don't mind that it takes a while, you can increase that delay. E.g.:
```xml
  <delay default="10 seconds"/>
```

**Comment by SaschaHeyer** [comment]
Thank you Pascal I was able to solve the behavior.
