### ISSUE TITLE
img src relative path

### ISSUE THREAD

**Issue by niozasg** [Norconex/collector-http#573]
Hi!
I am indexing images and  I would like to convert the relative url url from src attribute in image tags <img> tags to absolute url b. In most ocassions this is possible if you merge the domain home page url with the relative from the src field. For example:

`src="/system/modules/resources/img/zoo.png"` 
to be stored as
`src = "https://www.zoo.com/system/modules/resources/img/zoo.png"`
I tried to Use ReplaceTagger or MergeTagger but they only replace-merge text with text , or field-field.
Also the domains home page e.g  https://www.zoo.com/ is not in any specific field. document.embedded.parent.reference field sometimes contains it but not always.
I can pass the home page url to a variable , like :` #set($domain ="https://www.zoo.com/"),` but the how will I merge the $domain with the src field?

Thank you

**Comment by essiembre** [comment]
The crawler should resolve these for you and report images using the full URL (under ``document.reference``).  Are you experiencing something different?
