### ISSUE TITLE
Duplicate URL

### ISSUE THREAD

**Issue by HappyCustomers** [Norconex/collector-http#574]
The collector is fetching content from duplicate URLs as below. How to fetch unique URLS only?

> https://www.krinn.in/
> https://www.example.com/./
> https://www.example.com/././
> https://www.example.com/./././
> https://www.example.com/././././

I have set `<canonicalLinkDetector ignore="false" />`
Thank You

**Comment by essiembre** [comment]
Have a look at [GenericURLNormalizer](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/impl/GenericURLNormalizer.html).  Add the ``removeDotSegments`` to the default list of normalizations applied, like this:

```xml
 <urlNormalizer class="com.norconex.collector.http.url.impl.GenericURLNormalizer">
    <normalizations>
        removeFragment, lowerCaseSchemeHost, upperCaseEscapeSequence,
        decodeUnreservedCharacters, removeDefaultPort, 
        encodeNonURICharacters, removeDotSegments
    </normalizations>
  </urlNormalizer>
```

**Comment by HappyCustomers** [comment]
Thank you  will try this weekend and get back you with the results

**Comment by HappyCustomers** [comment]
it is working . Thank you
