### ISSUE TITLE
How to create a new field

### ISSUE THREAD

**Issue by coprisanu** [Norconex/collector-http#576]
Hi, 
Can you please confirm if there is a way to create a new field and set a value to it using a tagger?

Thank you

**Comment by essiembre** [comment]
You mean explicitly setting a value, not coming from the document content?  If so, [ConstantTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ConstantTagger.html) is your friend.

**Comment by coprisanu** [comment]
Hi Pascal,

Thank you for your response. It is working like you've said.

**Comment by essiembre** [comment]
Glad to hear.
