### ISSUE TITLE
Detect and avoid duplicate content

### ISSUE THREAD

**Issue by tendres1980** [Norconex/collector-http#579]
I have the situation that I need to crawl a webpage which generates duplicate content. Some documents are available on two completely different URLs - one includes the ID of the page and the other one a SEO-friendly name (e.g. "http://example.com/i-am-content" and "http://example.com/4711"). I cannot exclude one or the other because I cannot be sure which version of the URL is used for linking. Also I cannot make use of the canonical-tag because this cannot be implemented on customer-side. 

Is there any way to generate a hash on a document (excl. the URL) and check if this hash is already indexed, regardless of its URL?

**Comment by essiembre** [comment]
This is not currently supported out of the box.  This is often performed by target engines.  I would see if your search engine (or else) supports it.  It could be implemented with a custom ``IDocumentFilter`` (Importer module).  You could create a hash and store it in a fast lookup table.  If a new document comes through and shares the same hash as another URL, you reject it.

I am marking as a feature request (likely for next major release).

**Comment by tendres1980** [comment]
Thanks for the quick response and the suggestion on how this could be implemented. I will consider using a custom IDocumentFilter which creates and compares hashes for each document.

**Comment by essiembre** [comment]
The latest v3 snapshot release has two new crawler configuration options to enable deduplication:

```xml
   <metadataDeduplicate>true</metadataDeduplicate>
   <documentDeduplicate>true</documentDeduplicate>
```

Those rely on the checksum values generated by the `metadataChecksummer` and `documentChecksummer` respectively.  These new settings have no effect if their corresponding checksummer are not set.

Turning those on assumes the generated checksums produce unique values for each document.  If that is not the case, you will get false duplicate positives and you should avoid using this new feature.   Unless your have a metadata field already holding a unique value for each document, the `documentDeduplicate` is likely a better candidate.
