### ISSUE TITLE
Variables to dimension a crawler system

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#58]
We need to set up a non commercial system to search several internet sites, about un million documents to begin with. We need to make a preliminary budget and need to know the variables that influence the dimension of the system. We'd appreciate if you can give us some clue about internet sites where we could find studies or articles that can help us to value hardware, storage, people, time, that is, money, specifically on the crawler side, say, using your HTTP Collector.
Thank you very much
Carlos

**Comment by essiembre** [comment]
FYI, in case you wonder, you can use the HTTP Collector for commercial solutions as well.  It is licensed under the business-friendly Apache License 2.

I would be glad to help. I would like to ask you more questions on your project to better answer you.  I think we'd be better of using a more appropriate channel for this discussion.  Do you mind firing me an email?  You can use:

pascal.essiembre AT norconex.com

**Comment by csaezl** [comment]
You are right.

**Comment by essiembre** [comment]
Do you have trouble reaching me via email?  If you do not mind giving me yours, I will try to reach you.
