### ISSUE TITLE
Replace URL with urlNormalizer

### ISSUE THREAD

**Issue by klevismino** [Norconex/collector-http#580]
Hello guys,

Can someone give me an example on how to replace a URL with the urlNormalizer.
Example: 
Replace https://www.abc.com/sector/a?id=123
with https://www.abc.com/phase/x?id=123

Thanks!

**Comment by essiembre** [comment]
How about something like this (untested)?
```xml
  <urlNormalizer class="com.norconex.collector.http.url.impl.GenericURLNormalizer">
    <replacements>
      <replace>
         <match>/sector/a</match>
         <replacement>/phase/x</replacement>
      </replace>
    </replacements>
  </urlNormalizer>
```

**Comment by klevismino** [comment]
Hi Pascal

Thanks for your help. Can you provide an example with RegExp? e.g. remove ".page" or ".page?" at the ending of URLs
Replace https://www.abc.com/index.page and https://www.abc.com/index.page?
with https://www.abc.com/index

Regards
Klevis

**Comment by essiembre** [comment]
To help you come up with your own regular expressions, I recommend you use an online tool such as https://regex101.com/

To get you started, I have put a way to do what you are asking here: https://regex101.com/r/3U8VKI/1

**Comment by klevismino** [comment]
Hi Pascal

Thanks for suggesting that, but I already know how to use regular expressions, it is the reason why I am asking you for additional examples. In the first example you didn't escape the forward slash "/", so I suppose both replacement and match are used as strings. How would you write a regex then? How can you differentiate between the two?

Best regards
Klevis

**Comment by essiembre** [comment]
Not sure I follow.  Are you talking about cases where the forward slash is actually used as a regex delimiter?  If so, it is not the case here, so no need to escape them. So to answer your question:   
```xml
  <urlNormalizer class="com.norconex.collector.http.url.impl.GenericURLNormalizer">
    <replacements>
      <replace>
         <match>(/index)\.page\??</match>
         <replacement>$1</replacement>
      </replace>
    </replacements>
  </urlNormalizer>
```

If that is not what you meant, please let me know.
