### ISSUE TITLE
question on Tagger

### ISSUE THREAD

**Issue by dtcyad1** [Norconex/collector-http#583]
Hi Pascal,

Is it possible to have the Copy Tagger used only if the toField is null or not present or just empty string. Case in point - i have a title that is null but i have the collector.referrer-link-text with a value. I want to copy this value into the title only if the title is not there or is null or empty string.

Can this be done?

Thanks

**Comment by essiembre** [comment]
It would be nice to be able to copy only if the target is empty.  We can make this a feature request if you like.

In the meantime, you can make it work by combining the ``CopyTagger`` with overwrite being false, with the ``ForceSingleValueTagger``.  Something like this (not tested):
```xml
  <!-- This will copy the link text as an additional entry if one is already present: -->
  <tagger class="com.norconex.importer.handler.tagger.impl.CopyTagger">
      <copy fromField="collector.referrer-link-text" toField="title" overwrite="false" />
  </tagger>

  <!-- This will keep the first entry only: -->
  <tagger class="com.norconex.importer.handler.tagger.impl.ForceSingleValueTagger">
      <singleValue field="title" action="keepFirst"/>
  </tagger>
```

**Comment by dtcyad1** [comment]
Hi Pascal,

It would be great to have this as a feature request. 
Currently, I have the force single tagged on the title set to keep last because I was getting a lot of files and zip files with multiple titles and the last one seemed to be the best, especially in the case of zip files - not sure why.

Thanks for all your help!!

-yogesh

**Comment by essiembre** [comment]
Implemented in upcoming version 3.  A new "onSet" feature provides the following configurable options in most places where metadata fields can be added (and value already exists): 

* **append**: (Default) Add new values to the end of the list.
* **prepend**: Add new values to the beginning of the list.
* **replace**: Replace any existing value with new ones.
* **optional**: Only assign new values if the target field is empty.
