### ISSUE TITLE
Don't crawl external URLS

### ISSUE THREAD

**Issue by mauromi76** [Norconex/collector-http#584]
Hi Pascal
I'm sure this topic has been already solved but after searching tips on google I couldn't find the solution so I have to ask your support :)

My need is simple: I want Norconex to discard ALL external links.
so, if I'm crawling the website www.mydomain.com, who has links pointing to www.anotherdomain.com or anotherdomain2.com, I want norconex to stay and crawl only www.mydomain.com.

doing some searches I saw that the "stayOnDomain" doesn't help, and I  found tips using the tag 
`        <linkExtractors>
            <extractor ignoreExternalLinks="true" />
        </linkExtractors>`

but seems to not work as expected.

can you help me on this?

the version used is : NORCONEX 2.8.1

thanks
Mauro

**Comment by essiembre** [comment]
``stayOnDomain`` should definitely do it.  What suggests it does not?  Can you provide the relevant portion of your logs, as well are your config?

**Comment by mauromi76** [comment]
Hi Pascal
thanks for the quick feedback.
below the relevant portion. let me know if it's enough or you need the full config:

`.....
<crawlers>
    <crawler id="mywebsiteid">
        <startURLs stayOnDomain="true" stayOnPort="false" stayOnProtocol="false">
            <url>http://mydomain.com</url>
        </startURLs>
        ......
    </crawler>
</crawlers>
.....`

"mydomain.com" has external links that are indexed into Elastic Search because commited by Norconex but I don't understand why.

if it may be useful, what I noticed is that "mydomain.com" is on HTTPS while the external links are on HTTP. maybe is the `stayOnProtocol` parameter that creates the conflict for this specific case?

**Comment by mauromi76** [comment]
Hi Pascal
I think I found where "the bug" is nested.

after lot of tests, I found out that in the sitemap.xml (which is generated by the Framework we are using) there was ONE external link to another domain and I assume this was the "entry point" for the crawler to start crawling the ENTIRE external website. 

I quickly applied a patch to remove this entry and crawled again "mydomain.com" and this time it worked fine (only mydomain,com was indexed in Elastic Search)

So it appears that the paramenter "stayOnDomain" is not considered when the crawler reads the URLs from the Sitemap.xml.

can this be possible?

I let this open waiting for your comment but feel free to close it after you reply.

Mauro

**Comment by essiembre** [comment]
All start URLs are considered "onDomain". The sitemap entries are equivalent to start URLs in this case.  

If you want the crawler to only index what is in the sitemap, you can set "maxDepth" to zero.   Alternatively, you can combine the stayOnDomain with a regex filter to just eliminate that extra one.
