### ISSUE TITLE
StartURL sitemap indexing with files as url

### ISSUE THREAD

**Issue by SaschaHeyer** [Norconex/collector-http#585]
Hello Pascal,

I have configured a sitemap only crawling in Norconex, in order to index only the urls which are listed in the sitemap.xml

To archive this we set the maxDepth to zero:
```
<maxDepth>0</maxDepth>
```

We have two sitemaps defined one sitemap which contains the .html urls and the other one contains urls which are basically files like (pdf, jpg)

```
<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
<sitemap>sitemap-with-html.xml</sitemap>
<sitemap>sitemap-with-assets.xml</sitemap>
</startURLs>
```

When I start the crawler all the html pages are indexed properly. But the assets seems to be untouched. In order to investigate this behavior I removed the sitemap which contains the html urls and only left the sitemap which contains the files. 

And it seems Norconex is not identifying them as star urls.
```
INFO  [HttpCrawler] 0 start URLs identified.
```

This is a sample sitemap which contains assets in order to provide you a better understanding of the behavior
```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>http://dev-environment.test/test.pdf</loc>
      <lastmod>2018-09-21T04:27:01.192Z</lastmod>
   </url>
</urlset>
```
Any suggestions how I can force Norconex to identify them as start URLs?
If you need any further information please let me know. 

Thank you
Sascha

**Comment by essiembre** [comment]
Just to make sure, those sitemap URLs (``sitemap-with-html.xml`` and ``sitemap-with-assets.xml``) are actual URLs that you just edited, or are they meant to be pointing to the file system?  Because they have to be URLs to work in the ``<sitemap>`` tag.

If they are URLs that you just edited for posting here, are you sure those image URLs are not excluded via your filters or something else?  

Can you share your full config and maybe logs?

**Comment by SaschaHeyer** [comment]
Hi Pascal,

yes I just edited it to make it clearer, they are NOT pointing to the filesystem.

I can confirm the URLs are not excluded via filters (we have a very basic setup without any special handling).  I need a day or two in order to provide you a the full config and logs in a reproducible way.

As far as I understood from your questions I assume sitemaps with files should work the same as sitemaps with html?

Best regards
Sascha

**Comment by essiembre** [comment]
Yes, the crawler should not care what the URLs are.  If your sitemap is of standard format (and I think it is), then it should just take them.  Is the sitemap created manually or by some tools?  Have you checked that your URLs do not contain special characters that need to be XML-encoded?

Hopefully, I'll have a better idea once I can reproduce.

**Comment by SaschaHeyer** [comment]
Hi Pascal,

the following fixed the issues:
```
<sitemapResolverFactory lenient="true"
```

First I assumed it is might caused of a difference between host/domain which is used to access the sitemap and the host/domain names used in the URLs **but they are exactly the same**.

To be honest I don't see any reason why lenient solved my behavior. Can you explain how the URLs are compared without lenient="true"?

Best regards
Sascha

**Comment by essiembre** [comment]
The start of a URL in the sitemap, has to match the start URL of the sitemap itself.  In addition, from the javadoc:

> The Sitemap specification dictates that a sitemap.xml file defined
> in a sub-directory applies only to URLs found in that sub-directory and
> its children. This behavior is respected by default.  Setting lenient
> to <code>true</code> no longer honors this restriction.

Can that be your issue?

**Comment by SaschaHeyer** [comment]
Hi Pascal,

yes indeed that was the issue. 

Best regards
Sascha
