### ISSUE TITLE
HTML ISO Language Code as meta

### ISSUE THREAD

**Issue by SaschaHeyer** [Norconex/collector-http#586]
Hi Pascal,

is it possible to extract the HTML lang attribute and write it as a meta-field?
https://www.w3schools.com/tags/ref_language_codes.asp

```
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
...
</html>
```

Best regards
Sascha

**Comment by essiembre** [comment]
Sure! There are a few options, the easiest might be to use the [DomTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DOMTagger.html).   You can also use regular expressions to do so with [TextPatternTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/TextPatternTagger.html).

Both would need to be used as pre-parse handlers (on HTML files only).

**Comment by SaschaHeyer** [comment]
Great =)
confirmed, thank you Pascal
