### ISSUE TITLE
Different reference filter for first page and deeper pages  ?

### ISSUE THREAD

**Issue by sathishavpc** [Norconex/collector-http#588]
Hi Pascal,
I want to crawl only few patterns of URL's by using reference filter but that filters are needs to apply only for the deeper pages not to the index page. Even I do not want to use document filter, because if i use document filter it will hit my Apache server. I know the document filters could perform after the page download  but i want to filter before the download.  so could you help to find a way?

**Comment by essiembre** [comment]
Do you mean you want to reject deeper pages?  You can use "maxDepth".  Else, maybe you can have a regular expression that only matches the first few levels.

Can you give me concrete examples of what you want to do?
