### ISSUE TITLE
Committer-queue size and questions

### ISSUE THREAD

**Issue by SaschaHeyer** [Norconex/collector-http#590]
Hello Pascal,

to get a better understand of the committer-queue I need your knowledge.

1. The size should increase and decrease (as soon as documents are processed) over time. In other words, in the end of the crawling and committing process the queue should be empty and the folder as well?

2. Does different committer has to implement this queue cleanup on their own or is it implemented in the base class of the committer?

Best regards
Sascha

**Comment by essiembre** [comment]
As long as you do not have multiple committers pointing to the same queue directories, then yes, when the crawler ends normally, you should have no files left and if there are folders, they should be empty.  You can control how many documents get in the queue before it is flushed (i.e. committed) via configuration.

The cleanup is implemented by the base class called [AbstractFileQueueCommitter](https://www.norconex.com/collectors/committer-core/latest/apidocs/com/norconex/committer/core/AbstractFileQueueCommitter.html).

Does that answer?

**Comment by SaschaHeyer** [comment]
Morning Pascal,

thank you this answer all of my questions.

Best regards
Sascha
