### ISSUE TITLE
can you help identify the issue why urlNormalizer  removeQueryString is not working as expected

### ISSUE THREAD

**Issue by shradhatx** [Norconex/collector-http#594]
I am using 2.8.2-SNPSHOT of http crawler
```xml
    <urlNormalizer class="com.norconex.collector.http.url.impl.GenericURLNormalizer">
			<normalizations>
				removeQueryString, removeFragment,lowerCaseSchemeHost, 
                                 upperCaseEscapeSequence, decodeUnreservedCharacters, 
                                 removeDefaultPort, removeDotSegments, removeSessionIds, 
                                 upperCaseEscapeSequence
			</normalizations>
    </urlNormalizer>
```
My expectation is that I'll see only one url for the below urls-
```
    http://intranet.corp.internal.mycompany.com/about/you_helping_others.asp?credocelebration
    http://intranet.corp.internal.mycompany.com/about/you_helping_others.asp?credoweek2016
    http://intranet.corp.internal.mycompany.com/about/you_helping_others.asp?credoweek2017
    http://intranet.corp.internal.mycompany.com/about/you_helping_others.asp.asp?forourcolleagues
```

And it is showing duplicates.

**Comment by essiembre** [comment]
I cannot reproduce.  Where do you see the duplicates? In the logs? Have you tried running everything "fresh" after you added this configuration entry?  Can you share your config and your logs?

**Comment by shradhatx** [comment]
RemoveQueryString should have converted all the 3 urls I mentioned to one base url 
 http://intranet.corp.internal.mycompany.com/about/you-helping-others.asp but it is not. 
All 3 urls are seen in the log as well as in google cloud search datasource which I am using to index.

**Comment by essiembre** [comment]
Is your snapshot version recent?  The "removeQueryString" option was added less than a month ago.

If you still have the issue with the very latest version, please share your config and site so I can reproduce (if private, you can send it by email, referencing this ticket).
