### ISSUE TITLE
recrawlableResolver Not respecting the minFrequency Value of 120 days

### ISSUE THREAD

**Issue by HappyCustomers** [Norconex/collector-http#597]
Dear Mr.Pascal,

Today I was trying to rerun the crawler for one of the configuration files with around 70 websites.
These websites were crawled on `Feb 19 2019`,  I had configured the recrawlableResolver value to `120 days`.  But stlll the crawler is fetching the web pages as of` April 23 2019`. I am getting the following message for all the URLs in the input file

`Recrawl suggested according to custom directive (min frequency < elapsed time since Tue Feb 19 15:08:32 IST 2019) `

```
My Config is as follows:
<recrawlableResolver class="com.norconex.collector.http.recrawl.impl.GenericRecrawlableResolver" sitemapSupport="never" >
<minFrequency applyTo="reference" value="120 days">.*</minFrequency>
</recrawlableResolver>
```

Please advise
Thank you

**Comment by essiembre** [comment]
I was able to reproduce when entering large units. A fix was provided in the latest [snapshot release](http://www.norconex.com/collectors/collector-http/download).  I also provided more verbose debug logging. 

Please confirm.

**Comment by HappyCustomers** [comment]
Thank you Essiembre,
I will check and let you know in a day.
