### ISSUE TITLE
REJECTED_REDIRECTED

### ISSUE THREAD

**Issue by FireLizard** [Norconex/collector-http#598]
Still have the same issue as in #511 (see my comment https://github.com/Norconex/collector-http/issues/511#issuecomment-486271099).

Upgrading to v2.8.1 has no effect: [crawl.log](https://github.com/Norconex/collector-http/files/3141613/crawl.log)

**Comment by essiembre** [comment]
Please try with the latest snapshot version.

From the config you attached in #511, I cannot tell since there are missing fragments.  Do you have ``maxDocuments`` to 1 by any chance?    Please share a config that holds enough to reproduce.

**Comment by FireLizard** [comment]
The Problem was in our default settings for the url normalization. **removeDirectoryIndex** should not have been set. When removed the crawler works as expected since the **index.html**-part (redirect destination) is not removed ;)

Thank you for your efforts, @essiembre !
