### ISSUE TITLE
Read commented robots meta data from HTML head

### ISSUE THREAD

**Issue by leonardsaers** [Norconex/collector-http#60]
When using: com.norconex.collector.http.robot.impl.StandardRobotsMetaProvider

It seems like the following header will be parse as no index / no follow:

```html
<head>
...
<!-- ta bort <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"> och lägg till meta-taggarna från den motsvarande befintliga sidan när sidan ska läggas ut. -->
<META NAME="ROBOTS" CONTENT="INDEX, FOLLOW" /> 
...
</head>
```

**Comment by essiembre** [comment]
Good catch.  We'll need to fix that.

**Comment by essiembre** [comment]
That fix is now in the [latest snapshot release](http://www.norconex.com/collectors/collector-http/download).

**Comment by essiembre** [comment]
[Norconex HTTP Collector 2.1.0](http://www.norconex.com/collectors/collector-http/download) was released. Closing.
