### ISSUE TITLE
REJECTED_BAD_STATUS 400

### ISSUE THREAD

**Issue by arunakanaparthy** [Norconex/collector-http#604]
Hi,
I am trying to crawl the public site "http://www.calbar.ca.gov/" and around 7000+ documents are returning REJECTED_BAD_STATUS.  I have randomly checked these url's and seem to work fine in the browser and if used as start url as the only one to indexed do not throw the error.

Here is the part of the log towards the last the indexing where all the url access go into the error.

sbc-intranet: 2019-05-25 00:47:39 INFO -       REJECTED_BAD_STATUS: http://www.calbar.ca.gov/Public/Free-Legal-Information/FAQ (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])
sbc-intranet: 2019-05-25 00:47:39 INFO -       REJECTED_BAD_STATUS: http://www.calbar.ca.gov/Public/Free-Legal-Information/En-Espa%C3%B1ol/Servicios-de-Referencia-de-Abogados (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])
sbc-intranet: 2019-05-25 00:47:39 INFO -       REJECTED_BAD_STATUS: http://www.calbar.ca.gov/Public/Free-Legal-Information/En-Espa%C3%B1ol/Folleto-Sobre-Notarios (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])
sbc-intranet: 2019-05-25 00:47:39 INFO -       REJECTED_BAD_STATUS: http://www.calbar.ca.gov/Public/Free-Legal-Information/En-Espa%C3%B1ol/Como-Encontrar-El-Abogado-Apropiado (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])
sbc-intranet: 2019-05-25 00:47:39 INFO -       REJECTED_BAD_STATUS: http://www.calbar.ca.gov/Public/Free-Legal-Information/En-Espa%C3%B1ol/-Tiene-una-Disputa-de-Honorarios-con-su-Abogado (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])
sbc-intranet: 2019-05-25 00:47:39 INFO -       REJECTED_BAD_STATUS: http://www.calbar.ca.gov/Public/Free-Legal-Information/En-Espa%C3%B1ol/-Tiene-Alg%C3%BAn-Problema-con-su-Abogado (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])
sbc-intranet: 2019-05-25 00:47:39 INFO -       REJECTED_BAD_STATUS: http://www.calbar.ca.gov/Public/Free-Legal-Information/Legal-Guides/Living-Trust (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])
sbc-intranet: 2019-05-25 00:47:39 INFO -       REJECTED_BAD_STATUS: http://www.calbar.ca.gov/Public/Free-Legal-Information/Legal-Guides/Lawyer-Referral-Service (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])
sbc-intranet: 2019-05-25 00:47:40 INFO -       REJECTED_BAD_STATUS: http://www.calbar.ca.gov/Public/Free-Legal-Information/Legal-Guides/Lawyer-Fee-Dispute (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])
sbc-intranet: 2019-05-25 00:47:40 INFO -       REJECTED_BAD_STATUS: http://www.calbar.ca.gov/Public/Free-Legal-Information/Legal-Guides/Kids-the-Law (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])
sbc-intranet: 2019-05-25 00:47:40 INFO -       REJECTED_BAD_STATUS: http://www.calbar.ca.gov/Public/Free-Legal-Information/Legal-Guides/Finding-the-Right-Lawyer (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])
sbc-intranet: 2019-05-25 00:47:40 INFO -       REJECTED_BAD_STATUS: http://www.calbar.ca.gov/Public/Free-Legal-Information/Legal-Guides/Estate-Planning (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])
sbc-intranet: 2019-05-25 00:47:40 INFO -       REJECTED_BAD_STATUS: http://www.calbar.ca.gov/Public/Free-Legal-Information/Legal-Guides/Do-I-Need-a-Will (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])
sbc-intranet: 2019-05-25 00:47:40 INFO -       REJECTED_BAD_STATUS: http://www.calbar.ca.gov/Public/Free-Legal-Information/Legal-Guides/Client-Security-Fund (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])
sbc-intranet: 2019-05-25 00:47:40 INFO -       REJECTED_BAD_STATUS: http://www.calbar.ca.gov/Public/Free-Legal-Information/Legal-Guides/CSF-Pamphlet (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])
sbc-intranet: 2019-05-25 00:47:40 INFO -       REJECTED_BAD_STATUS: http://www.calbar.ca.gov/Public/Free-Legal-Information/Legal-Guides (HttpFetchResponse [crawlState=BAD_STATUS, statusCode=400, reasonPhrase=Bad Request])

Can you please help with this?

**Comment by essiembre** [comment]
I cannot reproduce.  I tried the first three and I am able to crawl them without issues (but the first one was redirected).  

I suspect this was an intermittent issue with the site.  If you crawl these URLs again, do you always get a 400 status code for the same URLs?   If so please share your config.

Was your crawl quite aggressive?  If you increase the delay between each page crawled, does it make a difference?  It may be the site rejecting some requests on purpose.

Else, I suggest you report this issue with the site owner.  The status code received is what the site returned, not something produced by the crawler itself.
