### ISSUE TITLE
Could N-Collector-Http behave as a client-browser, getting rendered content ?

### ISSUE THREAD

**Issue by ciroppina** [Norconex/collector-http#605]
Dear Sirs,

there are (more and more) web sites/services that generates html via-script/css or via-server-side controllers; so that if you try to download/save the result page you ONLY get a lot of scripts and styles, no-true-content

One example is Facebook (politics) Ads Library:
- https://www.facebook.com/ads/library/?active_status=active&ad_type=political_and_issue_ads&country=IT&q=[some query]

 It is a free and good service, but when I try to import query results with Norconex Collector-Http, I get:
![image](https://user-images.githubusercontent.com/15525117/58379586-cf8d8300-7fa5-11e9-9420-5b081ab6de2b.png)

that is a completely useless content. On the contrary my browser shows:
![image](https://user-images.githubusercontent.com/15525117/58379609-0bc0e380-7fa6-11e9-906e-981d1f9ab599.png)

that's a 68 "divs" page, each with its links and content. But that's the **browser rendered** result. Is it possible to catch that, and import, with the Collector-Http ?

**Comment by essiembre** [comment]
The HTTP Collector already integrates with PhantomJS to do just that.  PhantomJS is no longer supported though, so the next major release will have popular browser support.  Have a look at #461 for more details.

That being said, for [crawling Facebook](https://www.norconex.com/how-to-crawl-facebook/), you may find it more appropriate to use the Facebook Graph API.

**Comment by ciroppina** [comment]
Facebook Graph API (FG) unluckly does not fit for me, dear Pascal
FG navigates only the graph for current user (or page). Facebook Ads Library API searches every published Ad content, and it has a specific "type" of content that could be addressed: 'political and issue ads'

I would try to use the PhantomJS fetcher, awaiting for You release 'new things' with the version 3 of the Collector
