### ISSUE TITLE
Authentication with norconex also return status 403

### ISSUE THREAD

**Issue by hphuoc10101993** [Norconex/collector-http#606]
I used the methodForm is form of the class httpClientFactory. I believe that input correctly the user/pass for the page which I want to crawl data.  But, all pages also return status 403. See the below configuration and the console log

```
<httpClientFactory class="$httpClientFactory">
                <cookiesDisabled>false</cookiesDisabled>
                <connectionTimeout>5000</connectionTimeout>
                <expectContinueEnabled>true</expectContinueEnabled>
                <!--<trustAllSSLCertificates>true</trustAllSSLCertificates>-->
                <authMethod>form</authMethod>
                <trustAllSSLCertificates>true</trustAllSSLCertificates>
                <authUsername>nhtttt</authUsername>
                <authPassword>12345678</authPassword>
                <!-- These apply to FORM authentication -->
                <authUsernameField>username</authUsernameField>
                <authPasswordField>password</authPasswordField>
                <authURL>https://bulletin-dc9.herokuapp.com/admin/login/?next=/admin/</authURL>
</httpClientFactory>
```
The log on console:

INFO  - GenericHttpClientFactory   - Performing FORM authentication at "https://bulletin-dc9.herokuapp.com/admin/login/?next=/admin/" (username=nhphuoc; password=*****)
INFO  - GenericHttpClientFactory   - Authentication status: HTTP/1.1 403 Forbidden

Is there any missing for the above configuration?

Thanks

**Comment by essiembre** [comment]
What authentication mechanism is used by the site?  It is possible it is not one of the common ones currently supported by the HTTP Collector.

Also make sure the authURL you use is the URL your login form is pointing to, and not the page containing the form (unless they are the same URLs).

**Comment by hphuoc10101993** [comment]
The html for that page:
```
<form action="/admin/login/?next=/admin/" method="post" id="login-form"><input type="hidden" name="csrfmiddlewaretoken" value="uEHMjEKesW9bmJAgYmkTlfZwUFmPlzkV3xvfrxp8w9KsNDOWZGPx4iVb6EXfLv7R">
  <div class="form-row">
    
    <label class="required" for="id_username">Username:</label> <input type="text" name="username" autofocus="" maxlength="254" required="" id="id_username">
  </div>
  <div class="form-row">
    
    <label class="required" for="id_password">Password:</label> <input type="password" name="password" required="" id="id_password">
    <input type="hidden" name="next" value="/admin/">
  </div>
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="Log in">
  </div>
</form>
```
I have used the same url

```
<httpClientFactory class="$httpClientFactory">
                <cookiesDisabled>false</cookiesDisabled>
                <connectionTimeout>5000</connectionTimeout>
                <expectContinueEnabled>true</expectContinueEnabled>
                <!--<trustAllSSLCertificates>true</trustAllSSLCertificates>-->
                <authMethod>form</authMethod>
                <trustAllSSLCertificates>true</trustAllSSLCertificates>
                <authUsername>ttttt</authUsername>
                <authPassword>ttttttt</authPassword>
                <authUsernameField>username</authUsernameField>
                <authPasswordField>password</authPasswordField>
                <authURL>https://bulletin-dc9.herokuapp.com/admin/</authURL>
</httpClientFactory>

<startURLs stayOnDomain="false" stayOnPort="true" stayOnProtocol="true">
                <!--<url>https://portal.bidmc.org/Default.aspx</url>-->
                <url>https://bulletin-dc9.herokuapp.com/admin/</url>
</startURLs>
```
It still shows the same status 403

INFO  - GenericHttpClientFactory   - SSL: Trusting all certificates.
INFO  - GenericHttpClientFactory   - Performing FORM authentication at "https://bulletin-dc9.herokuapp.com/admin/" (username=nhphuoc; password=*****)
INFO  - GenericHttpClientFactory   - Authentication status: HTTP/1.1 403 Forbidden
INFO  - SitemapStore               - All Categories: Initializing sitemap store...

**Comment by essiembre** [comment]
The problem is with the hidden input field "csrfmiddlewaretoken".  It holds a dynamically generated token to make it difficult for non-humans to log in.

You could try to add the value obtained manually from that field with ``<authFormParams>``.  I would not be surprised it still not work.  Maybe cookies are also involved, timestamps, or other mechanisms.

To automate, you would need to first parse the login form, extract that value and add it to the authentication request (along with any other things required).  The simplest way to do this is by extending the ``GenericHttpClientFactory`` class and overriding its ``authenticateUsingForm`` method.

**Comment by hphuoc10101993** [comment]
Thanks for your time to support this ticket. I resolved the issue
