### ISSUE TITLE
Remove a specific parameter and its value from query string 

### ISSUE THREAD

**Issue by coprisanu** [Norconex/collector-http#607]
Hi,
 

We're using the Norconex Http Collector and the Elasticsearch committer.
We need to remove a specific parameter and its value from the query string.
We have to remove the parameters starting with "utm_" and their values.
We saw the feature called removeQueryString in GenericURLNormalizer but this one removes the whole query string.
Is there any option to remove a specific parameter like mentioned above?

Thank you

**Comment by essiembre** [comment]
The ``GenericURLNormalizer`` also allows you to use custom regular expressions.  With that, you can perform a search and replace to drop the ``utm_`` parameters.
