### ISSUE TITLE
Sitemap lastmod and changefreq behavior

### ISSUE THREAD

**Issue by SaschaHeyer** [Norconex/collector-http#616]
Hi Pascal,

assume we have the following sitemap entry and Norconex already crawled this page. 
What happens in the next crawl run if the lastmod changes?

In my opinion Norconex should should then index the page again (cause base don the lastmod it is obvious that the page changed).

Can you confirm?

```
<url>
   <loc>
      https://www.test.development/test.html
   </loc>
   <lastmod>2019-01-10T11:56:26.842+02:00</lastmod>
   <changefreq>weekly</changefreq>
   <priority>0.8</priority>
</url>
```

Best regards
Sascha

**Comment by essiembre** [comment]
The behavior you describe is the one in effect.   ``<lastmod>`` takes precedence and if specified, the crawler does not even look at the ``<changefreq>``.   If a sitemap entry does not have ``<lastmod>``, it will then rely on ``<changefreq>`` (if present).

**Comment by SaschaHeyer** [comment]
Hi Pascal,

great thank you.

Best regards
Sascha
