### ISSUE TITLE
URL not extracted

### ISSUE THREAD

**Issue by dtcyad1** [Norconex/collector-http#618]
Hi,
I have the following configuration where i am crawling 2 seperate websites:

<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
	      <url>https://www.siteA.com</url>
	      <url>https://www.siteB.com</url>
      </startURLs>

The issue is that siteA has some web pages that are not accessible from siteA itself. That is if i go to siteA and start clicking, I will never find those pages. They are almost like orphan pages.

However, those pages are linked in siteB. However, since the stayOnDomain is true, it never extracts the siteA links. If i check the .meta file for the sitB page, I never see the siteA page unless i set that parameter to false.

How can we extract the siteA page while crawling the siteB with the stayOnDomain set to true (since we dont want any other domains to be crawled and I would prefer not to add the regex filter, since I have no control over these websites.

Thanks

**Comment by essiembre** [comment]
If you want to jump from one domain to another, then the ``stayOnDomain`` is not what you want.  I recommend you set it to ``false`` and rely on ``<referenceFilters>`` set under your crawler configuration instead to include the domains you want (and the rest will be rejected).  For instance, you can use regular expressions to match your domain(s) with [RegexReferenceFilter](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/filter/impl/RegexReferenceFilter.html).
