### ISSUE TITLE
Norconex is doing a unexpected recrawl from scratch

### ISSUE THREAD

**Issue by SaschaHeyer** [Norconex/collector-http#620]
Hi Pascal,

we have a setup where Norconex is indexing based on the sitemap and the last-modification date. 

* After the very first initial crawl run is completed (which takes approximate 3 hours) ✓
* The crawler switches into the the state where it is comparing if the page was already crawled (using the crawlstore) ✓
* Then the crawler takes approximate 15 seconds for the crawl runs. ✓
* This is working for several hundreds of crawl runs (sometimes even for days)✓
* But then from time to time the crawler is doing again a recrawl from scratch which again takes a couple of hours. X

The crawler itself is running in a continuous crawling (schedule 1 minute). I also tested to increase the schedule to 15 minutes with the same effect.

Here is the unexpected crawl pattern

```
2019-07-01 14:49:59 INFO - crawler: Crawler executed in 2 hours 57 minutes 20 seconds.
.... several fast crawl runs every minute
2019-07-01 20:33:46 INFO - crawler: Crawler executed in 2 hours 52 minutes 42 seconds.
2019-07-01 22:16:35 INFO - crawler: Crawler executed in 31 seconds.
.... several fast crawl runs every minute
2019-07-01 22:17:33 INFO - crawler: Crawler executed in 29 seconds.
2019-07-02 01:41:59 INFO - crawler: Crawler executed in 2 hours 40 minutes 54 seconds.
.... several fast crawl runs every minute
2019-07-02 05:18:17 INFO - crawler: Crawler executed in 2 hours 44 minutes 14 seconds.
```

Sometimes the issues appears after several days with correct crawling. 

Any suggestions?

**Comment by essiembre** [comment]
Since this is the first time this is reported, I wonder if it is something that suddenly changes on the content you crawl, like a global site update (e.g. change of headers and footers) that would make all pages appear as new.  This can likely be confirmed if, let's say, it affects only HTML pages (PDF not being recrawled for instance since they have not changed).

Can you attach a copy of your logs when this happens?  Do you still see some "unmodified" ones?  Also, have you disabled sitemap support. If not, it could be that pages have a recrawl frequency high enough that most of the time documents are skipped until the requested recrawl delay is met.  You could disable sitemap support to test that.

If you have a copy of your config to reproduce, it would help as well.

**Comment by SaschaHeyer** [comment]
Hi Pascal,

we are doing a pure sitemap crawl, means we rely on the `<lastmod>` defined in the sitemap.
I can confirm that the `<lastmod>` values are not changed. It affects everything pages and files. 

There are no "unmodified or rejected premature or rejected unmodified" entries in the log. 

Sitemap support is enabled, can you please explain what do you mean with recrawl frequency and where is this delay defined?

Unfortunately I can't disable the sitemap crawling because we are only allowed to crawl based on the sitemap. 

I attached all configuration, I had to obfuscated some of the parts.
[configurations.zip](https://github.com/Norconex/collector-http/files/3358183/configurations.zip)

Do you think this is might be related to this issue?
https://github.com/Norconex/collector-http/issues/615

Best regards
Sascha

**Comment by essiembre** [comment]
I do not see anything standing out as problematic in your configuration files.  I may have a better idea if you attach the logs. You seem to have analyzed them quite a bit already.  Maybe lower the log4j log levels in hope to get more details when this happens?

For the recrawlable delays, have a look at [GenericRecrawlableResolver](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/recrawl/impl/GenericRecrawlableResolver.html).

**Comment by SaschaHeyer** [comment]
Hi Pascal,

thank you for your feedback. 
I set the log4j log level to INFO and will provide you the logs as soon as the issue appears again. 

Best regards
Sascha

**Comment by SaschaHeyer** [comment]
Hi Pascal,

please see attached the log files [logs.zip](https://github.com/Norconex/collector-http/files/3392258/logs.zip).

Between 2019-07-08 and 2019-07-15 the behavior occurred three times.
In between those full re-crawls there are a lot of normal runs with REJECTED_PREMATURE as expected.

```bash
./backup/2019/07/12/logs/201907121722060588__.log:obfuscated: 2019-07-12 17:22:06 INFO - obfuscated: Crawler executed in 12 hours 51 minutes 28 seconds.
./backup/2019/07/13/logs/201907130737380967__.log:obfuscated: 2019-07-13 07:37:38 INFO - obfuscated: Crawler executed in 13 hours 22 minutes 26 seconds.
./backup/2019/07/14/logs/201907140150450031__.log:obfuscated: 2019-07-14 01:50:45 INFO - obfuscated: Crawler executed in 17 hours 50 minutes 34 seconds.
```

Best regards
Sascha

**Comment by essiembre** [comment]
I checked your logs, and the same number of "start URLs" is found from parsing the sitemaps when it redoes them all or when they are all premature.  So it is not a case of the sitemap being skipped sometimes or similar. 

It rather suggests that after a while, enough time has passed and those links are now ready to be crawled.  I also see some REJECTED_PREMATURE when it is recrawling most URLs, which suggests the mechanism to find out if premature or not is still working. 

If you know this can't be the case, I am afraid I will need a way to reproduce to help you.  You can send files by email if too sensitive to share publicly.

**Comment by SaschaHeyer** [comment]
Hi Pascal,

thank you for your efforts. 
We found this entry in the logs

```
java.lang.IllegalStateException: Chunk 12626972 no longer exists [1.4.196/9]
```

After that error message Norconex started to re-crawl every document. 
Do you think this is might be related to this behavior?

Best regards
Sascha

**Comment by essiembre** [comment]
The chunk error, any context in the logs as to where it comes from (e.g., a stacktrace)?

If you get this behavior after the crawl store lock error, there is probably a direct relation.  When locked, there is no way for the crawler to read it and find out the last time a URL was crawled.  That is likely the problem.

We have to find out why you get that lock error now.  I can only think of two processing trying to read it at once.  Can you confirm 100% that all your "workdir" paths for all your crawlers are unique?  If two or more crawlers share that same crawlstore, it may be causing the lock.

**Comment by SaschaHeyer** [comment]
In some of the cases the chunk error appears after the crawl store lock error. But this does not apply to all chunk errors. 

Here is the full error message:
```
java.lang.IllegalStateException: Chunk 1408286 no longer exists [1.4.196/9] 
at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765) 
at org.h2.mvstore.MVStore.getChunkIfFound(MVStore.java:953) 
at org.h2.mvstore.MVStore.getChunk(MVStore.java:935) 
at org.h2.mvstore.MVStore.readPage(MVStore.java:1943) 
at org.h2.mvstore.MVMap.readPage(MVMap.java:741) 
at org.h2.mvstore.Page.getChildPage(Page.java:217) 
at org.h2.mvstore.Cursor.min(Cursor.java:129) 
at org.h2.mvstore.Cursor.fetchNext(Cursor.java:150) 
at org.h2.mvstore.Cursor.next(Cursor.java:50) 
at com.norconex.collector.core.data.store.impl.mvstore.MVStoreCrawlDataStore.<init>(MVStoreCrawlDataStore.java:88) 
at com.norconex.collector.core.data.store.impl.mvstore.MVStoreCrawlDataStoreFactory.createCrawlDataStore(MVStoreCrawlDataStoreFactory.java:49) 
at com.norconex.collector.core.crawler.AbstractCrawler.createCrawlDataStore(AbstractCrawler.java:243) 
at com.norconex.collector.core.crawler.AbstractCrawler.doExecute(AbstractCrawler.java:204) 
at com.norconex.collector.core.crawler.AbstractCrawler.startExecution(AbstractCrawler.java:184) 
at com.norconex.jef4.job.AbstractResumableJob.execute(AbstractResumableJob.java:49) 
at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:355) 
at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:296) 
at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:168) 
at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:149) 
com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:95) 
com.norconex.collector.http.HttpCollector.main(HttpCollector.java:74) 
```

The workdir folders are unique no crawler is sharing the folder. We also have this issue on systems with a single crawler.

**Comment by essiembre** [comment]
It turns out this problem is known to H2: https://github.com/h2database/h2database/issues/373

In that ticket, they recommend disabling ``autoCompactFillRate``.  To be able to allow for this, I added the ability to configure the underlying MVStore database.  So there are now advanced options you can use on [MVStoreCrawlDataStoreFactory](https://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/data/store/impl/mvstore/MVStoreCrawlDataStoreFactory.html).  To apply the recommended one, you can try:

```xml
  <crawlDataStoreFactory class="com.norconex.collector.core.data.store.impl.mvstore.MVStoreCrawlDataStoreFactory">
    <autoCompactFillRate>0</autoCompactFillRate>
  </crawlDataStoreFactory>
```

I have also upgraded to the latest H2 MVStore version: 1.4.199.

A new HTTP Collector snapshot was released to support the above. Pleases confirm whether it fixes your issue.

**Comment by SaschaHeyer** [comment]
We updated to the lastest snapshot and disabled autoCompactFillRate.
Update this issue with further information in a couple of days (currently running some longterm tests on our environments to see if that solved the issue).

**Comment by SaschaHeyer** [comment]
Hi Pascal,

the upgrade to snapshot and disabling autoCompactFillRate solved the behavior.
Thank you very much for your help.
 
Best regards
Sascha
