### ISSUE TITLE
Collector-Http 2.8.1 generates too many files => available disk space 0 bytes

### ISSUE THREAD

**Issue by ciroppina** [Norconex/collector-http#622]
I have three Collector-Http (2.8.1) tasks running on Windows Server 2016 Std Ed., with JRE 1.8 64bit

After 2 months running, the output folder (queue dirs, log dirs, progress dirs, crawlstore dirs) size has become so huge (more than 20 GBytes) that available disk space = 0 bytes

logs are not the true problem - log4j.properties is tuned to log few WARN, ERROR, FATAL things

queues, progress and **crawlstore** dirs are very very huge, and I cannot understand how to reduce their space, avoiding to erase the 'history' (already crawled web contents references, from about 50 websites)

Could You pls explain how to solve this problem? 
thanks

ciroppina

**Comment by essiembre** [comment]
I am assuming you are cleaning up the backups being made so they are not a cause for this?

**Progress:** It should be tiny in comparison to the rest.  Let me know if it is not the case (like a few KBs only in total).

**Queues:** Assuming you are talking about the committer queue, the documents it holds should be deleted automatically after they are committed. If not, it is possible some documents failed to be committed (e.g. rejected by your search engine), and they are retried each time, never going away.  If that looks like it is the case, you can safely delete whatever remains in the committer queue in between two crawls.  Ideally, you should fix whatever error that prevents them from being sent properly.  Maybe reducing the queue size in your Committer config may help as well.

**Crawlstore:** This one can grow quite big indeed.  It is directly tied to the volume of URLs you crawl.  Unfortunately, there are not many options that will preserve your last crawl history.  Short of getting more disk, here are some recommendations that will at least free up disk space and help you move forward:

* Delete the crawlstore folder.  This will for a fresh crawl and will consider everything as "new" and will not capture deletions.  If this is a big issue for you, you can:
  * Create a new Committer target (database, collection, etc.) for these pages and swap the old and new targets when you are ready.
  * Have a maintenance window where you wipe out your target index and recrawl from scratch.
  * If you are storing a record date, crawl date, or equivalent, you can perform your fresh crawl and manually delete all documents older than your latest crawl date. This is often a good tactic to have such date regardless.
* You can break down your sites in multiple collectors/crawlers and point each to different drives.
* You can use a different crawlstore implementation, where it is possible to scale horizontally (e.g. MongoDB).
* You can create your own crawlstore implementation.
