### ISSUE TITLE
Handle cookie expiration/refresh with form authentication

### ISSUE THREAD

**Issue by thmslprt** [Norconex/collector-http#624]
Hello,

I am currently crawling a website where some of the content is protected by a form authentication mechanism. When trying to request private content without a valid cookie, the web-server responds with a 302 redirect to the login page (https://auth.mywebsite.com).

To address that, I've setup an httpClientFactory using the GenericHttpClientFactory as followed:

	<httpClientFactory class="com.norconex.collector.http.client.impl.GenericHttpClientFactory">
		<authMethod>form</authMethod>
		<authUsername>MY_USER</authUsername>
		<authPassword>MY_PASSWORD</authPassword>
		<authUsernameField>user</authUsernameField>
		<authPasswordField>password</authPasswordField>
		<authURL>https://auth.mywebsite.com</authURL>
	</httpClientFactory>

This works well for a while as private content can be crawled successfully. However authentication seems to break after some time. It seems to be linked to some kind of expiration as the server instantly switches from responding with 200s to sending 302 redirects to the login page.

Would there be some way to automatically re-perform the form authentication, either after a fixed time or whenever a redirect to the login page is detected?

Thanks a lot,

**Comment by essiembre** [comment]
I cannot think of a way out-of-the-box to do this with form authentication. Maybe if you create your own ``IHttpDocumentFetcher`` you could intercept these redirects and force an authentication.    

You can maybe ask the site maintainer to increase the session timeout?

Also, if you know your Java and you know how long you have, you can maybe break the site crawling into multiple collector/crawler instances, each crawling only a portion of the site (with different URL filter patterns).   That way, you will luckily have time to crawl all the site before any individual crawlers session times out.

We can also make this a feature request if you like.

**Comment by davidfordaus** [comment]
Hi Pascal - we have a similar requirement though using the new headless / Chrome based crawler.  Is it possible to include this feature in an upcoming release ?

**Comment by essiembre** [comment]
@davidfordaus, upcoming version 3.0.0 will have headless browser support.

**Comment by davidfordaus** [comment]
Thanks Pascal - that's great news!

1. Do you have a sense of when 3.0 may be released?
2. Will 3.0 support the type of login that this Github issue speaks about?   We're in a situation where we'd like to login to sites and crawl using the login details we obtain by filling out a form with data.

**Comment by essiembre** [comment]
We are hoping to release this summer.  At least snapshot versions so the more adventurous can start testing.  You will be able to use your favorite browser and "script" any action you want to perform on a page once loaded.  You should be able to mimic most user interactions this way.  Certainly submitting a form.
