### ISSUE TITLE
How do I handle sitemap.xml.gz (compressed sitemap)

### ISSUE THREAD

**Issue by dkh7m** [Norconex/collector-http#626]
I'm trying to index a Plone site, and the only format I can get the sitemap in is .gz. Can Norconex somehow handle a sitemap.xml.gz file?

**Comment by essiembre** [comment]
Yes, it can.  By default, it looks for ``/sitemap.xml`` or ``/sitemap_index.xml`` for each new domains encountered.

To change that, you have a few options.  First, if you are dealing only with one site, you can define the sitemap as part of the start URLs.  Like this:
```xml
    <startURLs ... >
      <sitemap>http://www.somewhere.com/sitemap.xml.gz</sitemap>
     </startURLs>
```
If you have a mix of sites that can have their sitemaps in different locations, you can define alternate locations to check for each domains:

```xml
  <sitemapResolverFactory class="com.norconex.collector.http.sitemap.impl.StandardSitemapResolverFactory">
     <path>/sitemap.xml.gz</path>
     <path>/sitemap.xml</path>
     <path>/whatever-other-weird-name-for-sitemap.xml</path>
  </sitemapResolverFactory>
```
