### ISSUE TITLE
Limit Number of Pages Crawled for Debugging/Testing?

### ISSUE THREAD

**Issue by dhildreth** [Norconex/collector-http#627]
Is there an easy way to limit the number of pages crawled for debugging purposes?  I'd like to specify a certain URL and only crawl/process that single URL and not have to wait for the entire website to be crawled while making incremental changes to the config file.  Maybe something like:

      <maxPages>1</maxPages>

Or, maybe I can save a local copy of the webpage HTML and scan that?  I'm game for any ideas or best practices. :-)

I'm trying to make sure my preParseHandlers transformers and postParseHandlers taggers are correct.

**Comment by dhildreth** [comment]
Nevermind.  I figured I would just use the RegexReferenceFilter to specify the single page I'm interested in.  That worked quickly enough!

       <filter class="com.norconex.collector.core.filter.impl.RegexReferenceFilter"
          onMatch="include">
          .*myurl.*
        </filter>

**Comment by essiembre** [comment]
Glad you found out, but here are two other options for your consideration:
```xml
<maxDepth>0</maxDepth>
<maxDocuments>1</maxDocuments>
```

**Comment by dhildreth** [comment]
Thank you!
