### ISSUE TITLE
how can i use selector in GenericLinkExtractor?

### ISSUE THREAD

**Issue by ranheo** [Norconex/collector-http#638]
Hi

I saw 2.9.0-snapshot version can use selector in GenericLinkExtractor.

but i don`t know how can i use this. 

this is still developing the feature? 

2.9.0-SNAPSHOT Feature release
-GenericLinkExtractor now supports using "selector-syntax" to identify portions of an HTML document to include or exclude from URL extraction.

**Comment by essiembre** [comment]
All configuration options can be found from [here](https://www.norconex.com/collectors/collector-http/configuration#cfg-linkExtractors).  You can find the ``GenericLinkExtractor`` documentation [here](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/impl/GenericLinkExtractor.html). 

To answer your question, let's use an example. Let say you have a website with a table of content on the side, that has its enclosing tag identified with an HTML "id" attribute, with the value "toc".  If you want to exclude that from all HTML pages being crawled, it would look like this (inside your ``<crawler>`` section):

```xml
<linkExtractors>
    <extractor class="com.norconex.collector.http.url.impl.GenericLinkExtractor">
        <noExtractSelector>#toc</noExtractSelector>
    </extractor>
</linkExtractors>
```

You can do the opposite and have a ``extractSelector`` instead, in case you just want to consider specific elements in the page for crawling.

**Comment by ranheo** [comment]
thank you for example.

but i`m confused little bit.

i wanna get a link in href from 

<a class="title" href="something"/>

in this case, 

a.title[href]
.title
a.title 

which is right?

**Comment by essiembre** [comment]
In your example, you want to extract "something"?  If so, you have nothing to do.  The default settings will extract ``href`` URLs automatically from HTML pages.
