### ISSUE TITLE
custom 404 page content

### ISSUE THREAD

**Issue by dtcyad1** [Norconex/collector-http#640]
Hi,

we have a situation where instead of a default 404 error being returned, a custom page is rendered with a regular 200 status code. The only thing different is that the title has a 404 error in it and the content  gives a custom message. The original url still remains the same(so it is not redirected anywhere). Is there a way to regex the title value and if a match is found treat it as a 404 so a delete will be issued and it can be removed from the index?

Thanks

**Comment by essiembre** [comment]
Yes, you can use a filter in your ``<importer>`` section (probably as a pre-parse handler).

Something like this:
```xml
  <filter class="com.norconex.importer.handler.filter.impl.RegexContentFilter" onMatch="exclude" >
      <regex>.*404 error.*</regex>
  </filter>
```

**Comment by dtcyad1** [comment]
Hi Pascal,

That is the soln we implemented as well.

Thanks

--
[image: SADA Systems - Google Cloud Premier Partner]
<https://sadasystems.com/emailSignature> Yogesh Dhavale
Google Cloud Search Consultant
O:  (813) 390-4074 <+18133904074>

[image: SADA Systems is a premier cloud solutions provider specializing in
technology consulting, IT services, application development, and managed
services.] <https://sadasystems.com/?utm_source=emailSig>
[image: Twitter] <https://twitter.com/SADASystems> [image: Facebook]
<https://www.facebook.com/SADASystemsinc> [image: LinkedIn]
<https://www.linkedin.com/company/sada-systems>
