### ISSUE TITLE
Docker with website URL from environment variable

### ISSUE THREAD

**Issue by Muffinman** [Norconex/collector-http#641]
Hi,

We're looking to build an internal tool, where we can crawl and index our own websites using the Elasticsearch committer.

As some exploratory work I've got the collector running in Docker as described [here](https://www.norconex.com/how-to-run-norconex-collector-in-docker/). The next step for us is to automate the collection process and enable us to index any website by changing the parameters passed to docker.

For example:

```bash
$ docker run --net=host -e SITE_CRAWL_DEPTH=2 -e SITE_URL=https://example.com norconex-collector:2.9.0
```

I'd like these ENV variables to be made available inside the XML config, is such a thing possible?

I can see that it's possible to pass parameters into the collector using the docker `start.sh`, but I couldn't see any documentation showing how I would pass these env variables.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<httpcollector id="Norconex Complex Collector">

  #set($http = "com.norconex.collector.http")
  #set($core = "com.norconex.collector.core")
  #set($urlNormalizer   = "${http}.url.impl.GenericURLNormalizer")
  #set($filterExtension = "${core}.filter.impl.ExtensionReferenceFilter")
  #set($filterRegexRef  = "${core}.filter.impl.RegexReferenceFilter")
  #set($committerClass = "com.norconex.committer.elasticsearch.ElasticsearchCommitter")
  #set($searchUrl = "http://127.0.0.1:9200")

  <progressDir>../crawlers/norconex/progress</progressDir>
  <logsDir>../crawlers/norconex/logs</logsDir>

  <crawlerDefaults>
    <referenceFilters>
      <filter class="$filterExtension" onMatch="exclude">jpg,gif,png,ico,css,js</filter>
    </referenceFilters>
    <urlNormalizer class="$urlNormalizer">
      <normalizations>
        removeFragment, lowerCaseSchemeHost, upperCaseEscapeSequence,
        decodeUnreservedCharacters, removeDefaultPort, encodeNonURICharacters,
        removeDotSegments
      </normalizations>
    </urlNormalizer>
    <maxDepth>${SITE_CRAWL_DEPTH}</maxDepth>
    <workDir>../crawlers/norconex/workDir</workDir>
  </crawlerDefaults>
  <crawlers>
    <crawler id="Orphans Website">
      <startURLs>
        <url>${SITE_URL}</url>
      </startURLs>
      <committer class="$committerClass">
        <nodes>$searchUrl</nodes>
        <indexName>norconex</indexName>
        <typeName>web</typeName>
        <queueDir>../crawlers/norconex/committer-queue</queueDir>
        <targetContentField>body</targetContentField>
        <queueSize>100</queueSize>
        <commitBatchSize>500</commitBatchSize>
      </committer>
    </crawler>
  </crawlers>
</httpcollector>
```

My current work-around is to create a copy of the `config.xml` in `start.sh` and use `sed` to replace some placeholder strings with my env variables. Is there a better way?

**Comment by essiembre** [comment]
Unfortunately, this is currently not offered out-of-the-box the way you would like it.  

There are workarounds though.  When you specify a configuration file, the collector will automatically check for a ``.variables`` or ``.properties`` file of the same name, and treat its key-value entries as variables that can be referenced in your config.  So you can write your environment variables to such a file before launching.  Alternatively, that variable file can also be specified explicitly as an argument, as described here: http://www.norconex.com/collectors/collector-http/getting-started

You can modify the Collector launch script to add a few lines that do it.  For instance on Linux, if your config file is called ``MyConfig.xml``, maybe adding a command like this to the Collector launch script would do it:
```
env > MyConfig.variables
```
If you have too many and want to keep that variables file to the minimum, you can echo just what you need instead:

```
echo $SITE_CRAWL_DEPTH > MyConfig.variables
echo $SITE_URL >> MyConfig.variables
```
That should give you what you want.

I will nonetheless mark this as a feature request.

**Comment by essiembre** [comment]
Implemented in version 3 code.
