### ISSUE TITLE
PhantomJS script file doesn not exist or is not a valid file: Project directory\scripts\phantom.js

### ISSUE THREAD

**Issue by nancygoyal1** [Norconex/collector-http#644]
I am new to GCS and have basic coding knowledge. I want to try to crawl dynamic pages using PhantomJSDocumentFetcher with the below configurations-

```
<documentFetcher  
                    class="com.norconex.collector.http.fetch.impl.PhantomJSDocumentFetcher"
                    detectContentType="true" detectCharset="true">
                    <exePath>C:\Users\phantomjs.exe</exePath>
                    <renderWaitTime>
                          3000
                    </renderWaitTime>     
                    <referencePattern></referencePattern>  
<contentTypePattern></contentTypePattern>
                    <validStatusCodes>200</validStatusCodes>
                    <notFoundStatusCodes>404</notFoundStatusCodes>
              </documentFetcher> 
```

I have downloaded phantom.exe and is using that file. On running the application, i am getting the error **PhantomJS script file doesn not exist or is not a valid file: Project directory\scripts\phantom.js**. I am not sure if i need to install Phantomjs or i am missing something?

**Comment by essiembre** [comment]
The script file is found under your collector installation directory, under a "scripts" folder.  Add to your configuration a ``<scriptPath>`` with a path to that file and it should find it.
