### ISSUE TITLE
Instantiate new crawlers

### ISSUE THREAD

**Issue by jackpay** [Norconex/collector-http#645]
Hello this is my first post. Thanks very much for the API!
I am getting to grips with the process of Norconex now, but I was wondering if something was currently possible or could be a feature request. 
Let's say I have a Collector with N crawlers running. 
The Collector does not finish until ALL of the N crawlers have completed. 
First, is this correct behaviour?
What I was wondering was, is it possible to spawn new or restart existing crawlers inside of already running Controller instance?

My issue is that I want to incrementally crawl N sites. Meaning I want to restart crawling each domain continually. 

However, the Controller seems to be bottlenecked to take as long to complete as the longest running crawler instance. This means all completed crawlers and their threads are idle until all instances have completed. 

Is there an efficient way around this at all? I could create a Controller for each domain of course, but would this create a large hardware overhead for several hundred domains?
Thanks.

**Comment by essiembre** [comment]
Thanks for taking the time to post.  You can see having multiple crawlers defined in a single collector as a convenience (e.g., to easily share config).  There is nothing wrong with having different instances of the Collector running.  You only need different config files (as opposed to different copies of your Collector binary installation).

If you would like to share config sections, you can dynamically include config fragments if it helps (look at the "complex configuration example").  

I recommend you try to group together the domains of similar duration if you want to reduce the number of instances running.
