### ISSUE TITLE
Could not dispose of resources

### ISSUE THREAD

**Issue by SaschaHeyer** [Norconex/collector-http#651]
Hi Pascal,

we got this error message `Could not dispose of resources`. 
What does this mean and what can cause this error message?

Best regards
Sascha

**Comment by essiembre** [comment]
Hello Sascha,

Is it followed by a stack trace with more details?  

Your reported error occurs when the crawler is done with a file (likely a crawled/downloaded one) but could not get rid of it for some reason.  It could be that it is not able to close an open stream on it, but more likely, it was not able to delete the file for some reason (more frequent on Windows).  

As long as you have not observed other issues, the worst that could happen is having a downloaded file sticking around after you are done.  Even then, such files are often deleted when the JVM exits.

Maybe more info could help fix this if it is causing you trouble.
