### ISSUE TITLE
Getting started example not working

### ISSUE THREAD

**Issue by lukiant-dev** [Norconex/collector-http#653]
I wanted to evaluate Norconex's crawler. Downloaded the binary of the crawler and executed example shipped with the binary:
`sh collector-http.sh -a start -c examples/minimum/minimum-config.xml
`
Received SSL error:
`javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

Does it mean that collector-http is not supporting SSL?

Link to getting started page:
https://www.norconex.com/collectors/collector-http/getting-started

**Comment by LeMoussel** [comment]
Try :
```
<httpClientFactory>
    ...
    <!-- Be warned: trusting all certificates is usually a bad idea. -->
    <trustAllSSLCertificates>true</trustAllSSLCertificates>
</httpClientFactory>
```

**Comment by essiembre** [comment]
It does support SSL.  Often though, websites are using certificates that are not trusted by default by your Java platform.  In such case, they need to be added manually to your key store or you can try @LeMoussel  suggestion.  

From times to times also SSL uses different protocols and it may happen some are not always supported and you have to be explicit in telling which one you want to support.

There are a few tickets providing solutions to SSL problems, such as this one which was turned into a feature request to automate parts of of the solution: #592.

Please confirm if you still have the issue after trying a few suggestions.
