### ISSUE TITLE
Is it possible to make different type request depends on URL extensions?

### ISSUE THREAD

**Issue by LeMoussel** [Norconex/collector-http#654]
Is it possible to have different type request depending on the URL extension like `.jpg`, `.png`, ...?
For example for the images (jpg, png, ...) use only HEAD request to get info Header, no GET request that donwloading image.

**Comment by essiembre** [comment]
Interesting use case.  I do not think there is anything out of the box for doing this.  I am marking this as a feature request.

In the meantime, if you know your Java, I would recommend overriding ``GenericDocumentFetcher#fetchDocument(HttpClient, HttpDocument)`` to check if the supplied document is an image (or whatever check you want to do), and do nothing if so. Else, call ``super.fetchDocument(...)``.  If you give it a try, let us know if that works.

**Comment by LeMoussel** [comment]
Hello Pascal,

I know Java but I'm starting with Norconex/collector-http.
I will try and communicate my testing/JAVA code on this issue.

See you soon

**Comment by LeMoussel** [comment]
Pascal,
Ok to override [GenericDocumentFetcher.fetchDocument](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/GenericDocumentFetcher.html#fetchDocument-org.apache.http.client.HttpClient-com.norconex.collector.http.doc.HttpDocument-) for GET request 
=> `super.fetchDocument(...)`

But how can I  fetch document with HEAD request ?
Can I override [GenericMetadataFetcher.fetchHTTPHeaders](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/GenericMetadataFetcher.html#fetchHTTPHeaders-org.apache.http.client.HttpClient-java.lang.String-com.norconex.commons.lang.map.Properties-) for HEAD request
=> `super.fetchHTTPHeaders(...)` ?

**Comment by essiembre** [comment]
You can add/configure the GenericMetadataFetcher which will do a HEAD request for all documents.  In your Document fetcher, then you only invoke super if your document is not an image.  Then it will skip downloading the document. It should give you what you want.

Not sure if that's really what you meant, but you normally cannot download a document with a HEAD request.

**Comment by essiembre** [comment]
The latest v3.0.0 snapshot now supports this feature. You can define multiple HTTP "fetchers" and optionally have them process only certain URLs and/or HTTP methods.  

For instance, to only perform HTTP HEAD requests for URLs being images, you can add something along those lines under your `<crawler>` section:

```xml
<fetchHttpHead>OPTIONAL</fetchHttpHead>
<fetchHttpGet>OPTIONAL</fetchHttpGet>
<httpFetchers>
  <fetcher class="GenericHttpFetcher">
    <referenceFilters>
      <filter class="ExtensionReferenceFilter" onMatch="include">
        jpg,png,gif
      </filter>    
    </referenceFilters>
    <httpMethods>HEAD</httpMethods>
  </fetcher>
  <fetcher class="GenericHttpFetcher">
    <referenceFilters>
      <filter class="ExtensionReferenceFilter" onMatch="exclude">
        jpg,png,gif
      </filter>    
    </referenceFilters>
    <httpMethods>HEAD,GET</httpMethods>
  </fetcher>
</httpFetchers>
```

You can remove `HEAD` from the second `<httpMethods>` entry in case you do not want to make a HEAD call for non-images.
