### ISSUE TITLE
How to add specific value to metadata `collector.referenced-urls` values?

### ISSUE THREAD

**Issue by LeMoussel** [Norconex/collector-http#658]
Hi,

Is there a way to add a specific value to each metadata `collector.referenced-urls` values?

I want to retrieve the HTML `class` attribut of all referenced links from one document.
the result should be something like this:
``` html
<a class="note editorial" href="http://example.com/">
        Example.com
</a>
```
``` json
"collector.referenced-urls": [
   "http://example.com/",
    ... ,
]
```
``` json
"collector.extend-referenced-urls": [
   {
      "url": "http://example.com/",
      "class": "note editorial"
   },
   { ... },
   ....
]
```

Maybe need to write own [IDocumentTagger ](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/IDocumentTagger.html)or maybe use the [ScriptTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ScriptTagger.html) in some way.

What's the best solution?

Thanks for your time.

Best regards

**Comment by essiembre** [comment]
``ScriptTaggger`` may be flexible enough, but nothing beats creating your own tagger for something that specific.

If you want to give it a try via configuration first, I suggest you use the ``DomTagger`` to store all ``<a href="...">`` in a page in a field of your choice. Like this (untested):

```xml
  <tagger class="com.norconex.importer.handler.tagger.impl.DOMTagger">
      <dom selector="a" toField="MyPageURLs" extract="outerHtml" />
  </tagger>
```
You will end up with a multi-value field for "MyPageURLs", where each entry contains the whole block, e.g.:
``<a class="note editorial" href="http://example.com/">Example.com</a>``

Then you can manipulate each entry via a ScriptTaggger or even a ReplaceTagger, like this (untested):
```xml
  <tagger class="com.norconex.importer.handler.tagger.impl.ReplaceTagger">
      <replace fromField="MyPageURLs" regex="true">
          <fromValue>.*class="(.*?)".*href="(.*?)".*</fromValue>
          <toValue>{ "url": "$2", "class": "$1" }</toValue>
      </replace>
  </tagger>
```
The regular expression can be tricky to get right if your links are not always constent (a class, no class, class before href, after href, etc).

You can also use a MergeTagger to merge your json objects.

**Comment by LeMoussel** [comment]
Thank. 
But as you say, the use of regular expression can be tricky because I have no guarantee that it's constant.
