### ISSUE TITLE
How to intercept HttpCrawlerEvent?

### ISSUE THREAD

**Issue by LeMoussel** [Norconex/collector-http#660]
with `ICrawlerEventListener`, it's possible to intercept events of type [CrawlerEvent](https://norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/crawler/event/CrawlerEvent.html)
``` java
public class customCrawlerEventListener implements ICrawlerEventListener {
   @Override
   public void crawlerEvent(final ICrawler crawler, final CrawlerEvent event) {
       final String type = event.getEventType();
       // Do some stuff .....
   }
}
```
and set in XML config file :
``` xml
    <crawlerListeners>
      <listener class="customCrawlerEventListener">
      </listener>
    </crawlerListeners>
```
How to intercept [HttpCrawlerEvent](https://norconex.com/collectors/collector-http/latest/apidocs/index.html?com/norconex/collector/http/crawler/HttpCrawlerEvent.html) events?

Thank you for your help

**Comment by essiembre** [comment]
HttpCrawlerEvent extends CrawlerEvent.  You should be able to just cast it, but to be safer, you can do something like this:

```java
if (event instanceof HttpCrawlerEvent) {
    HttpCrawlerEvent httpEvent = (HttpCrawlerEvent) event;
    // do your magic here.
}
```

**Comment by LeMoussel** [comment]
It doesn't seem to be working.
``` java
public void crawlerEvent(final ICrawler crawler, final CrawlerEvent event) {
    if (event instanceof CrawlerEvent) {
      // OK
      final String type = event.getEventType();
      // Do some stuff for CrawlerEvent
    } else if (event instanceof HttpCrawlerEvent) {
      // KO, Never reached
      HttpCrawlerEvent httpEvent = (HttpCrawlerEvent) event;
      // Do some stuff for HttpCrawlerEvent 
    }
}
```
Isn't it because event is defined `crawlerEvent` in the [ICrawlerEventListener](https://norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/crawler/event/ICrawlerEventListener.html) interface?

**Comment by essiembre** [comment]
Your first condition will always be ``true`` so the "else if" will never be reached.  Make sure you check for HttpCrawlerEvent as your first condition.

**Comment by LeMoussel** [comment]
Hi Pascal, I do this:
``` java
public void crawlerEvent(final ICrawler crawler, final CrawlerEvent event) {
    System.out.println("DBG => " + event.getClass().getName());

    if (event instanceof HttpCrawlerEvent) {
      HttpCrawlerEvent httpEvent = (HttpCrawlerEvent) event;
      // Do some stuff for HttpCrawlerEvent
    } else if (event instanceof CrawlerEvent) {
      // Do some stuff for CrawlerEvent 
    }
}
```

With http://cocon.se/concret/logs-bea, I got this log:

> INFO  - REJECTED_NONCANONICAL      -     REJECTED_NONCANONICAL: http://cocon.se/concret/logs-bea
> DBG => com.norconex.collector.core.crawler.event.CrawlerEvent

[REJECTED_NONCANONICA](https://norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/crawler/HttpCrawlerEvent.html)L  is an HttpCrawlerEvent, but the  name of event object is always `com.norconex.collector.core.crawler.event.CrawlerEvent`.

There's something I don't understand...

**Comment by essiembre** [comment]
What is it you are trying to do exactly?  CrawlerEvent (or its subclasses) is only a shell containing more useful info.  Its type is not really useful and regardless of actual implementation, you can get what matters this way:

```java
public void crawlerEvent(final ICrawler crawler, final CrawlerEvent event) {
    
    // Source of the event, which varies:
    Object subject = event.getSubject();

    // Contextual info about your URL:
    HttpCrawlData crawlData = (HttpCrawlData) event.getCrawlData(); 

    // The type of event (what shows in your logs):
    String eventType = event.getEventType();

    // Let's say you want to react on a non-canonical rejection event,
    // you could do something like this:
    if (HttpCrawlerEvent.REJECTED_NONCANONICAL.equals(eventType)) {
        // do something
    }
}
```

**Comment by LeMoussel** [comment]
I want to write to a warning file for certain types of events and write to an error file for others. 
Your answer is perfect.. Thank you so much for your help.
