### ISSUE TITLE
How to reduces specified consecutive characters  in `collector.referrer-link-text`?

### ISSUE THREAD

**Issue by LeMoussel** [Norconex/collector-http#663]
Sometimes I have `collector.referrer-link-text=\r\n\r\n\t\t\t\r\n            Some text ....\r\n            \r\n\r\n\r\n\t\t\tSome text ....`

How to reduces specified consecutive characters or strings to only one instance in `collector.referrer-link-text`?

**Comment by LeMoussel** [comment]
My solution with `ScriptTagger` in JavaScript:
``` xml
  <tagger class="com.norconex.importer.handler.tagger.impl.ScriptTagger">
    <script><![CDATA[
		var referrerLinkText = metadata.getString('collector.referrer-link-text');
		if (referrerLinkText != null) {
			var result = referrerLinkText.replace(/\s+/gi, ' ').trim();
			metadata.addString('referrer-link-text', result);
		}
    ]]></script>
  </tagger>
```
But I'm not sure it's the most efficient one.

**Comment by essiembre** [comment]
What you have looks fine to me.  You could also use the ``ReplaceTagger``, like this (untested):
```xml
<tagger class="com.norconex.importer.handler.tagger.impl.ReplaceTagger">
  <replace fromField="collector.referrer-link-text" regex="true" replaceAll="true">
    <fromValue>\s+</fromValue>
    <toValue xml:space="preserve"> </toValue>
  </replace>
</tagger>   
```

**Comment by LeMoussel** [comment]
Thanks for your help. The solution you're proposing also works very well.
