### ISSUE TITLE
Warning: Nashorn engine is planned to be removed from a future JDK release

### ISSUE THREAD

**Issue by LeMoussel** [Norconex/collector-http#664]
It seems likely that Norconex/collector-http uses (directly or indirectly) the Nashorn engine. This leads to the warning message given in the log of this issue. 

 It's by using

> tagger class="com.norconex.importer.handler.tagger.impl.ScriptTagger">

that I get this warning.

Is there a way to stop using Nashorn and adopt an alternative instead?

**Comment by essiembre** [comment]
I would not worry as there is no tight-coupling.  Nashorn is not referenced explicitly.  The tagger refers to the JavaScript engine by the engine name "JavaScript", which is by default the one shipped with your JVM.  Ideally, "JavaScript" will remain available under that engine name in future JVM releases, even if the actual implementation changes. Worst case you just have to specify the new name, but keep your script. In the end, if you stick to ECMAScript basics, you should be fine with any implementation.  

You can also add your own scripting engine.  A quick tip: if you put an invalid engine name, like ``engineName="IamBad"``, then you will get an error and the tagger should list available engines in your JVM.  That is a way to know what you have installed or available to you.

**Comment by LeMoussel** [comment]
To silence these warnings, add:

> -Dnashorn.args=--no-deprecation-warning
