### ISSUE TITLE
How to modify document content with Javascript?

### ISSUE THREAD

**Issue by LeMoussel** [Norconex/collector-http#665]
I want to modify the content of the document with Javascript code.
For this I use [ScriptTagge](https://norconex.com/collectors/importer/latest/apidocs/index.html?com/norconex/importer/handler/tagger/impl/ScriptTagger.html)r and do this:
``` xml
<tagger class="com.norconex.importer.handler.tagger.impl.ScriptTagger">
   <script><![CDATA[
      // Document content
      var Contenttype = metadata.getString('document.contentType');
      if (Contenttype != null && Contenttype == 'text/html') {
         if (content != null) {
            // Test
            content = '=> TEST: ' + content;
         }
      }
   ]]></script>
</tagger>
```
In the output file (I use [JSONFileCommitter](https://norconex.com/collectors/committer-core/latest/apidocs/com/norconex/committer/core/impl/JSONFileCommitter.html)) the content value has not changed. '=> TEST: ' is not present in `content`.
``` json
{"doc-add": {
     "reference": "document reference, e.g., URL",
     "metadata": { ... },
     "content": "Initial Document Content without '=> TEST: '"
}}
```

**Comment by essiembre** [comment]
I tried your script with sample data and it works fine for me.  I suspect the content-type is not what your code expect.  You can find out by assigning it to your content just for testing:
```JavaScript
var Contenttype = metadata.getString('document.contentType');
content += ' Contenttype: ' + Contenttype;
...
```

**Comment by LeMoussel** [comment]
Strange ....  it's not working for me.
Here's my config test: [testConfigHttpCollector.xml.txt](https://github.com/Norconex/collector-http/files/4179487/testConfigHttpCollector.xml.txt)
Running under windows with `testCollector-http.bat`: [testCollector-http.bat.txt](https://github.com/Norconex/collector-http/files/4179495/testCollector-http.bat.txt)

in the JSON file under `.\output-test\crawledFilesJSON` for the variable `content` we have as a result:
``` xml
[
  {
  "doc-add": {
    "reference": "http://httpbin.org/forms/post",
    "metadata": {
      "collector.referrer-link-text": [
        "HTML form"
      ],
      "collector.referrer-reference": [
        "http://httpbin.org/"
      ],
      "collector.depth": [
        "1"
      ]
    },
    "content": "Customer name: Telephone: E-mail address: Pizza Size Small Medium Large Pizza Toppings Bacon Extra Cheese Onion Mushroom Preferred delivery time: Delivery instructions: Submit order"
  }
},
  {
  "doc-add": {
    "reference": "http://httpbin.org/",
    "metadata": {
      "title": [
        "httpbin.org"
      ],
      "collector.depth": [
        "0"
      ],
      "collector.referenced-urls": [
        "http://httpbin.org/forms/post"
      ]
    },
    "content": "httpbin.org 0.9.2 [ Base URL: httpbin.org/ ] A simple HTTP Request & Response Service. Run locally: $ docker run -p 80:80 kennethreitz/httpbin the developer - Website Send email to the developer [Powered by Flasgger] Other Utilities HTML form that posts to /post /forms/post"
  }
}
]

```

According to the attached configuration file it should be :

> "content": "Contenttype: [value of metadata document.contentType]Customer name: Telephone: E-mail ....
> "content": "Contenttype: [value of metadata document.contentType]httpbin.org 0.9.2 [ Base URL: httpbin.org/ ] .....

**Comment by essiembre** [comment]
Taggers cannot modify the content, only metadata.  Modifying content is done using Transformers. This works:

```xml
<transformer class="com.norconex.importer.handler.transformer.impl.ScriptTransformer">
    <script><![CDATA[
        var Contenttype = metadata.getString('document.contentType');
        content = 'Contenttype: [' + Contenttype + ']' + content;
    ]]></script>
</transformer>		
```

**Comment by LeMoussel** [comment]
Thank you!
