### ISSUE TITLE
How to set/get HTTP Status code in metadata?

### ISSUE THREAD

**Issue by LeMoussel** [Norconex/collector-http#666]
I want to keep all HTTP response code (HTTP StatusCode).
In config file, I set `DebugTagger` like this
`<tagger class="com.norconex.importer.handler.tagger.impl.DebugTagger" logLevel="INFO"/>`

In the list of all fields, I found nothing about HTTP StatusCode.

How cans I set HTTP StatusCode in metadata?

**Comment by essiembre** [comment]
Right now the status code is not kept.  You would have to modify the GenericDocumentFetcher to do so.  That said unless you changed the default document fetch settings, that will be little value to you.  The status will always be 200 (docs with other statuses are rejected).

If you want to have an overview of what statuses are encountered while crawling for analysis/reporting (like finding broken links), I recommend you have a look at [URLStatusCrawlerEventListener](
https://norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/crawler/event/impl/URLStatusCrawlerEventListener.html) instead.

**Comment by LeMoussel** [comment]
In config file, I change the default document fetch settings like this
``` xml
    <documentFetcher class="com.norconex.collector.http.fetch.impl.GenericDocumentFetcher">
      <validStatusCodes>200,301,302,404,500</validStatusCodes>
      <!-- <notFoundStatusCodes>404</notFoundStatusCodes> -->
    </documentFetcher>
```
To modify the GenericDocumentFetcher, I have to do this :
``` java
// http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/GenericDocumentFetcher.html
public class CustomFetcher extends GenericDocumentFetcher {
  private static final Logger LOG = LoggerFactory.getLogger(CustomFetcher.class);

  @Override
  public HttpFetchResponse fetchDocument(HttpClient httpClient, HttpDocument doc) {
     // TODO some stuff to get hhtp status code 
     // ...
  }
}
```
But I don't find out how to retrieve the HTTP satus code in this method.  What's your advice?

**Comment by LeMoussel** [comment]
In Config file, I set :
``` xml
    <!-- <documentFetcher class="com.norconex.collector.http.fetch.impl.GenericDocumentFetcher"> -->
    <documentFetcher class="CustomFetcher">
      <validStatusCodes>200,301,302,404,500</validStatusCodes>
    </documentFetcher>
```
I modify  the [GenericDocumentFetcher ](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/GenericDocumentFetcher.html) like this :

``` java
public class CustomFetcher extends GenericDocumentFetcher {
  @Override
  public HttpFetchResponse fetchDocument(HttpClient httpClient, HttpDocument doc) {
    final HttpFetchResponse response  = super.fetchDocument(httpClient, doc);
    int statusCode = response.getStatusCode();
    HttpMetadata metadata = doc.getMetadata();

    metadata.addInt("StatusCode", statusCode);

    return response;
  }
}
```

But in other methods, When I check metada, the `StatusCode` key in metadta is missing. 
What am I missing?

**Comment by essiembre** [comment]
That looks like a good way to do it.  Does it work for you?

**Comment by LeMoussel** [comment]
Yes. Thank you for your advice.

**Rem:**  Don't forget to add, in the configuration file, `StatusCode` in KeepOnlyTagger tag fields.
