### ISSUE TITLE
Why redirected URL has REJECTED state?

### ISSUE THREAD

**Issue by LeMoussel** [Norconex/collector-http#678]
I use `JDBCCrawlDataStoreFactory`. In INVALID table, there are urls with REJECTED state.
![image](https://user-images.githubusercontent.com/1816573/75801086-dc33d880-5d7a-11ea-9ed7-25d9f4e1e9a1.png)

In Debug mode,
``` xml
log4j.logger.com.norconex.collector.core.crawler=DEBUG
log4j.logger.com.norconex.collector.http=DEBUG
```

For http://f4b1.com/seo-tester-si-son-site-est-mobile-friendly-avec-outil-de-google, In the log there is :
> f4b1.com: 2020-03-03 18:10:36 DEBUG - f4b1.com: Processing reference: http://f4b1.com/seo-tester-si-son-site-est-mobile-friendly-avec-outil-de-google
> f4b1.com: 2020-03-03 18:10:36 DEBUG - Fetching document: http://f4b1.com/seo-tester-si-son-site-est-mobile-friendly-avec-outil-de-google
> f4b1.com: 2020-03-03 18:10:36 DEBUG - Encoded URI: http://f4b1.com/seo-tester-si-son-site-est-mobile-friendly-avec-outil-de-google
> f4b1.com: 2020-03-03 18:10:37 DEBUG - URL redirect: http://f4b1.com/seo-tester-si-son-site-est-mobile-friendly-avec-outil-de-google -> http://f4b1.com/referencement/seo-tester-si-son-site-est-mobile-friendly-avec-outil-de-google
> f4b1.com: 2020-03-03 18:10:37 DEBUG - Unsupported HTTP Response: HTTP/1.1 301 Moved Permanently
> f4b1.com: 2020-03-03 18:10:37 DEBUG - Redirect target URL is already queued: http://f4b1.com/referencement/seo-tester-si-son-site-est-mobile-friendly-avec-outil-de-google (from: http://f4b1.com/seo-tester-si-son-site-est-mobile-friendly-avec-outil-de-google).
> 

`Redirect target URL is already queued` means that the url is already known in the queue (this is the case because the url is present in the start url http://f4b1.com) 

But wouldn't it be more meaningful to position the state `REJECTED_REDIRECTED: http://f4b1.com/seo-tester-si-son-site-est-mobile-friendly-avec-outil-de-google`?

The complete log: [f4b1.com.log](https://github.com/Norconex/collector-http/files/4282678/f4b1.com.log)

**Comment by essiembre** [comment]
You are correct.  The source URL was being dropped (rejected) but when the target URL was already encountered, it did not fire the rejection event.

Please try the latest 2.9.1-SNAPSHOT and confirm whether you see this behavior again.

**Comment by LeMoussel** [comment]
Yep !It' OK with the latest 2.9.1-SNAPSHOT.  Great job!

![image](https://user-images.githubusercontent.com/1816573/76342387-d1d78880-62fe-11ea-82ff-5a8163153079.png)

![image](https://user-images.githubusercontent.com/1816573/76342572-1d8a3200-62ff-11ea-9d0a-5faa6df0dd5a.png)

Shall I close this issue?

**Comment by essiembre** [comment]
Thanks for confirming. Yes, let's close.
