### ISSUE TITLE
crawlDataStoreFactory with Postgres?

### ISSUE THREAD

**Issue by bkisselbach** [Norconex/collector-http#681]
Is it possible to use a non-H2 database with the JDBCCrawlDataStoreFactory? The documentation at https://norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/data/store/impl/jdbc/JDBCCrawlDataStoreFactory.html doesn't seem to indicate any configuration options

**Comment by bkisselbach** [comment]
We are trying to get a better handle on the content flowing through to a SQL committer and were curious if we could push the norconex logs into the same database so we can get a better insight into what had been crawled, status etc

**Comment by essiembre** [comment]
I suggest you have a look at using a [URLStatusCrawlerEventListener](https://norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/crawler/event/impl/URLStatusCrawlerEventListener.html).  

You could also use the ``MultiCommitter`` and specify a JSONFileCommitter or XMLFileCommiter in addition to your SQL one.  Those keep an ongoing copy of additions and deletions.  They do not overwrite previously written files, so it it can keep a full history of what you have committed if you like.

Can one of these work for you?
