### ISSUE TITLE
Stripping content based on class or id tags

### ISSUE THREAD

**Issue by onixterry** [Norconex/collector-http#682]
I am trying to figure out how to strip out content based upon a "class" or "id" tag.

I'm finding that if you use Strip Between you can end up with some HTML artifacts being left behind because invalid HTML markup remains and that is not automatically removed.

Is there a way to strip between a structure like this:

```
<div class="header" id="headarea">
... some other HTML markup ...
</div>
```
Such that it is smart enough to know that you mean to strip everything between the start and end of that particular "div" structure?  

I've got an example set of pages where the header area is being stripped out but most pages end up with some extraneous HTML markup.  One of them is an incomplete HTML element that has a class name and the "c" in "class" is removed but not the rest of it so I end up with a document that contains a word I'd rather not have in it.  :)

Example page:
https://garden.org/about/dmca/

[plants_example.zip](https://github.com/Norconex/collector-http/files/4439360/plants_example.zip)

**Comment by essiembre** [comment]
It is difficult to do via regular expression alone.  A DOMTransformer would be required (currently does not exist).  I am making this a feature request. In the meantime, short of creating your own transformer, the following could work:

1. User a [DOMTagger](https://norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DOMTagger.html) to extract the portions you are interested in, and store those into a new field, and ignore the content for that document.
2. If you want to make sure content is ignored, you can use [SubstringTransformer.](https://norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/transformer/impl/SubstringTransformer.html) to eliminate it.

Could this work for you?

**Comment by onixterry** [comment]
Thanks.  I think the DOMTagger should work since we can target a field sections of HTML that we actually want to keep.

**Comment by onixterry** [comment]
I can extract the data I want and put it into a field.  What I am not clear about is how to replace the main content field that is submitted to the committer.  My DOMTagger is in my preparsehandler if that makes a difference.

**Comment by essiembre** [comment]
Which committer are you using?  You should have the option to specify which field to grab the content from (default is not a field but the content stream).  Like this:

```xml
<sourceContentField>MyFieldNameContainingContent</sourceContentField>
```

**Comment by onixterry** [comment]
I am using the Google Cloud Search committer.

I tried adding that item (not mentioned in Google's documentation) and it did not appear to do anything.

**Comment by essiembre** [comment]
I checked [GoogleCloudSearchCommitter](https://github.com/google-cloudsearch/norconex-committer-plugin/blob/master/src/main/java/com/norconex/committer/googlecloudsearch/GoogleCloudSearchCommitter.java) class documentation. There is a note that says to use that option, you need to set "uploadFormat" to "text".

**Comment by onixterry** [comment]
Ah, ok.  That's not ideal.  Looks like we might need to wait for the DOMTransformer or build one.  Seems like "stripping" elements works fine for the Google Cloud Search Committer - the stripped content is removed from the original 'content' field.

**Comment by essiembre** [comment]
The feature request has been implemented in version 3 with the new [DOMDeleteTransformer](https://opensource.norconex.com/importer/v3/apidocs/com/norconex/importer/handler/transformer/impl/DOMDeleteTransformer.html) class.

You can now use selector-syntax to delete parts of a document DOM.  Example for your initial post:

```xml
 <handler class="DOMDeleteTransformer">
   <dom selector="#headarea" />
 </handler>
```
