### ISSUE TITLE
ReplaceTransformer matching issue? 

### ISSUE THREAD

**Issue by svanschalkwyk** [Norconex/collector-http#686]
Input line is:
```
<meta name="p_similar_products">/ip/Organic-Carrots-2-lb-bag/44391103?athcpid=4
```
Expecting "/ip/" to be replaced. 
Configuration is this:

```
<transformer class="com.norconex.importer.handler.transformer.impl.ReplaceTransformer">
	<restrictTo caseSensitive="false"
              field="p_similar_products">
          		.*
  	   </restrictTo>
	   <replace>
    	      <fromValue>^\/ip\/.*</fromValue>
        	  <toValue>https://grocery.walmart.com/ip/</toValue>
      	     </replace>
</transformer>
  
```

**Comment by essiembre** [comment]
Transformers are dealing with the content/body of your document.   The "restrictTo" is to limit which documents are affected by your config, not fields.  You seem to want to do this on a field.  In which case, try using the [ReplaceTagger](https://norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/ReplaceTagger.html) and make sure to specify the "fromField".
