### ISSUE TITLE
Overly restrictive sitemap.xml gzip content-type 

### ISSUE THREAD

**Issue by simonwibberley** [Norconex/collector-http#687]
A site might simply put "gzip" as the content type in sitemap response headers, this causes the collector to bork at compressed streams. More permissive logic on the content-type test could allow for this kind of variation.

**Comment by essiembre** [comment]
Good idea.  I don't believe having just "gzip" could mean anything other than gzip compression in this context so it is pretty safe.  Thanks for the suggestion.  Will do.

**Comment by essiembre** [comment]
PR merged and a new snapshot was just made.  Please confirm.

**Comment by simonwibberley** [comment]
Confirmed!
