### ISSUE TITLE
Crawl PDF content and metadata from a JSON file

### ISSUE THREAD

**Issue by ai-amit** [Norconex/collector-http#690]
Hi, we have a JSON file which has data from our AEM DAM repository.

The files stored in AEM DAM are mostly PDF files. We need to read PDF content and index them.

We have exported the metadata as well as PDF URL in the json file and want to read this JSON. The process will read metadata as well as read the PDF content and then index it into Elastic Search.

Do you think we can use HTTP collector for this use case. If yes can you please guide.

Thanks,
Amit

**Comment by ai-amit** [comment]
So I tried testing the HTTP collector for the JSON content. The JSON is located on a different server. When I try crawling the JSON it indexed the complete JSON as one record. It did not crawl the URLs embedded in the JSON fields.

Should I be using link extractors so that those PDF URLs are crawled?

**Comment by ai-amit** [comment]
Ok I made some more progress. I was able to use RegexLinkExtractor to get the PDF link from the JSON file. So far so good.

But when I looked at my index - seems the PDF isnt parsed completely. I only see some partial text being crawled. It missed lot of the text from the initial page and also did index few paragraphs from the second page...thats it...

Any idea what could be wrong?

**Comment by essiembre** [comment]
Hello! First, congrats on your progress.   It looks like you are quite close.  

Just like that, I can't tell you the cause of getting a partial content. It could be that some pages are images of text instead of the actual text.  If so, it is normal you do not get the text, but you can use the OCR support the collector has.

It is hard to tell without reproducing it.  Can you share a sample PDF causing this issue, along with your config?

**Comment by ai-amit** [comment]
First of all - I am impressed with the way crawler works! 

You are absolutely right....I looked at the PDF and it seems the PDF has images with the text. My bad. I will attach the sample PDF in this comment.

Overall I want some guidance on the way I am trying to use the HTTP Collector. Like I mentioned earlier - we are having a huge JSON which has metadata including the PDF URL for all assets (~30K PDFs) in our AEM DAM . We need to index both metadata as well as PDF content in Elastic Search. The metadata fields in the JSON should be indexed as separate fields in Elastic Search and not the complete json record in one field.

The JSON is in this flat format:

{
  "CRAWLABLE": "true",
  "COUNTRIES": "US",
  "CREATED_DATE": "2009-03-27T17:44:55.000Z",
  "ASSET_PATH": "https://example.com/pdf/testing.pdf",
  "CONTENT_TYPE_NAME": "training-materials",
  "CONTENT_TYPE_TITLE": "Training Materials",
  "ABSTRACT": "",
  "DOC_TYPE": "Asset",
  "LANGUAGE_TITLE": "English",
}

The above represents one record.

One option is to index the metadata using a separate process and use HTTP collector to fetch PDF URLs and then crawl them to get the content for indexing. This is not what we want to follow since it would mean first creating ES record with just the metadata and then using Elastic Search Committer to update the same record with PDF content.

Preference is to be able to read the entire JSON record. Pick each field and crawl the PDF URL and index in one shot. The ES record would look like exactly the way JSON is but with an additional field "CONTENT" which will have PDF crawled content.

Is this something we can do? Mainly how do I read the JSON fields individually.

**Comment by ai-amit** [comment]
[Testing.pdf](https://github.com/Norconex/collector-http/files/4598031/Testing.pdf)

PDF file which had text in images

**Comment by ai-amit** [comment]
Pascal, were you able to look the files I attached in my previous comments.

**Comment by essiembre** [comment]
Just to confirm, are you saying you want to store the PDF in its original binary format or its text?  

If you want to search through it and want its text, I recommend you have a look at [Tesserac OCR](https://github.com/tesseract-ocr/).  You can configure the Importer module to use it via the [GenericDocumentParserFactory](https://norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/parser/GenericDocumentParserFactory.html).

OCR is not always 100% accurate, but it can get you quite far if your document images are of decent quality.

With Tesseract, you will have both the metadata AND content extracted during the same pass.  Is it what you are after?
