### ISSUE TITLE
How to check outside domain to depth of one

### ISSUE THREAD

**Issue by dkichline** [Norconex/collector-http#691]
I want to check an infinite depth of links for those that stay on the start url's domain.  However, if the url directs the crawler off of the start url's domain, can I restrict that check to a depth of one?

**Comment by dkichline** [comment]
OK, I thought I had found a way to do this.

`        crawlerConfig.setMetadataFilters(new IMetadataFilter() {
            private Logger logger = Logger.getLogger(IMetadataFilter.class);
            @Override
            public boolean acceptMetadata(String s, Properties properties) {

                String collectorReferrerReference = properties.getString("collector.referrer-reference");

                boolean accept = collectorReferrerReference.startsWith("https://hmc-bsa.org");

                return accept;
            }
        });`

However, it still looks like the document is being downloaded despite my filter.

`INFO  - DOCUMENT_FETCHED           -          DOCUMENT_FETCHED: https://2qwrf62rjqi54de8ue3tjeoe-wpengine.netdna-ssl.com/wp-content/themes/beascout/assets/images/icon-sm-03.png
INFO  - CREATED_ROBOTS_META        -       CREATED_ROBOTS_META: https://2qwrf62rjqi54de8ue3tjeoe-wpengine.netdna-ssl.com/wp-content/themes/beascout/assets/images/icon-sm-03.png
INFO  - IMetadataFilter            - collector.content-type : image/png
INFO  - IMetadataFilter            - collector.referrer-link-tag : img.src
INFO  - IMetadataFilter            - collector.referrer-reference : https://beascout.scouting.org/
INFO  - IMetadataFilter            - collector.is-crawl-new : true
INFO  - IMetadataFilter            - collector.depth : 2
INFO  - REJECTED_FILTER            -           REJECTED_FILTER: https://2qwrf62rjqi54de8ue3tjeoe-wpengine.netdna-ssl.com/wp-content/themes/beascout/assets/images/icon-sm-03.png`


Running my app, it still seems to be going down the rabbit hole and processing every single link found.

**Comment by dkichline** [comment]
I also tried

` crawlerConfig.setMetadataFilters(new RegexMetadataFilter("collector.referrer-reference", "^https:\\/\\/hmc-bsa.org.*", OnMatch.INCLUDE, false));`

Same thing keeps happening, it continues processing links with different referrers.

**Comment by dkichline** [comment]
OK, I am going to close this.  As it turns out, it was just a case of my not understanding how the various filters work.  

The first thing that finally got me on the right track was the [Collector Flow](https://norconex.com/collectors/collector-http/flow).  

What I was not understanding is that unless the metadata is downloaded, by specifying a MetadataFetcher, in my case the GenericMetadataFetcher sufficed, the metadata filter filter did not kick in till after the links were extracted and placed on the queue.

So I added the GenericMetadataFetcher, added my custom MetadataFilter, and everything started working the way I expected.

**Comment by essiembre** [comment]
Glad to hear, thanks for taking the time to report your solution.
