### ISSUE TITLE
Making committer failure a fatal error?

### ISSUE THREAD

**Issue by ronjakoi** [Norconex/collector-http#692]
I have my collector set up to commit to Apache Solr. It builds a queue and when it fills it it sends the documents to Solr.

If I have an error such as Solr rejects a document because of a mismatch between the collector's config and the Solr schema, I almost always would prefer that the collector abort immediately because it's usually an indication of a big problem. That's not what the collector does though, it keeps going and tries to commit all subsequent documents.

Is there a way to configure the collector to immediately drop everything and abort crawling if committing to Solr fails?

**Comment by dkichline** [comment]
Did you try using the [StopOnException](https://norconex.com/collectors/collector-http/configuration#cfg-stopOnExceptions) configuration?
