### ISSUE TITLE
Client Certificates with the GenericHttpClientFactory 

### ISSUE THREAD

**Issue by ahaw021** [Norconex/collector-http#693]
We have a requirement to send client certificates as part of the crawl

I don't see a setting for this in GenericHttpClientFactory

What would be the easiest way of achieving this ?

**Comment by essiembre** [comment]
What do you mean by "send"?  Do you mean you want to save a copy somewhere?   Certificates are saved in the Java KeyStore and can be exported.

This site gives you a list of keystore-related command that can help you:
https://www.sslshopper.com/article-most-common-java-keytool-keystore-commands.html

Let me know if you if you mean something different.

**Comment by ahaw021** [comment]
Hi Pascal

https://dzone.com/articles/use-client-certificate-authentication-with-java-an 

This is a better explanation of what we are trying to achieve.

**Comment by essiembre** [comment]
To use your own Keystore and/or Truststore, you can specify them as system properties.  You can modify the collector-http.sh (or .bat) script to add the following arguments to the java command:
```
-Djavax.net.ssl.keyStore=/path/to/your/keyStore.ks
-Djavax.net.ssl.keyStorePassword=YourKeyStorePassword
-Djavax.net.ssl.trustStore=/path/to/your/trustStore.ts
-Djavax.net.ssl.trustStorePassword=YourTrustStorePassword
```

If you would rather do it programmatically, you can override the ``createSSLContext()`` method found in ``GenericHttpClientFactory``.

There is currently no way to do this via XML configuration alone.  We can make it a feature request if you like.

**Comment by essiembre** [comment]
Marked it as a feature request.

**Comment by ahaw021** [comment]
Thanks Pascal -- overwriting the GenericHttpClientFactory will work for us.

Having this as a configuration option would be great as Client Certificates / MTLS is becoming a more common requirement.
