### ISSUE TITLE
HSTS support

### ISSUE THREAD

**Issue by jetnet** [Norconex/collector-http#694]
any plans for [HTTP Strict Transport Security](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) support?
Some web-servers do not redirect properly (via `Location` header), but rather sending a `Strict-Transport-Security` response header expecting the client to internally convert the scheme from HTTP to HTTPS.
Thanks!

**Comment by essiembre** [comment]
Marking this as a feature request.  In the meantime, you can make sure https is always used with ``secureScheme`` of the ``GenericURLNormalizer`` class.
