### ISSUE TITLE
GenericMetadataFetcher & Connection: close

### ISSUE THREAD

**Issue by jetnet** [Norconex/collector-http#696]
one more issue with the `GenericMetadataFetcher`: it seems, if a webserver is replying `Connection: close`, then the collector cannot proceed:
```
www.bochum.de: 2020-05-22 21:41:55 INFO -       REJECTED_REDIRECTED: http://www.bochum.de/ (HttpFetchResponse [crawlState=REDIRECT, statusCode=302, reasonPhrase=Found (https://www.bochum.de/)])
www.bochum.de: 2020-05-22 21:41:56 ERROR - Cannot fetch metadata: https://www.bochum.de/ (www.bochum.de:443 failed to respond)
www.bochum.de: 2020-05-22 21:41:56 INFO -            REJECTED_ERROR: https://www.bochum.de/ (com.norconex.collector.core.CollectorException: org.apache.http.NoHttpResponseException: www.bochum.de:443 failed to respond)
```
I found a hint for a similar issue at [stackoverflow](https://stackoverflow.com/a/29024369/10390714)

my metadata fetcher config:
``` xml
<metadataFetcher
        class="com.norconex.collector.http.fetch.impl.GenericMetadataFetcher"
                skipOnBadStatus="true" >
        <!-- trick to make the crawler continue w/o metadata.
             It is required as some sites reply 'NOT FOUND' for a HEAD request -->
        <notFoundStatusCodes>444</notFoundStatusCodes>
</metadataFetcher>
```
The mentioned above site can be crawled when this section is commented out.

**Comment by essiembre** [comment]
What do you mean by "could not proceed"?  Does it hang forever, or do you mean that document gets rejected while you want it to be skipped? (possible duplicate of #695)

**Comment by jetnet** [comment]
I install the latest maintenance release `2020-05-25` and still getting this error.
I believe, it is not related to #695, since the error reason is different: the crawler is getting `REJECTED_ERROR` when trying to fetch metadata and stops. It happens only when `metadataFetcher` is active. Most probably, it happens, because Apache HTTP Client is closing the active connection improperly.
```
INFO  [CrawlerEventManager]           CRAWLER_STARTED
INFO  [AbstractCrawler] www.bochum.de: Crawling references...
WARN  [MetadataFetcherStage] Bad HTTP response when fetching metadata: HttpFetchResponse [crawlState=BAD_STATUS, statusCode=302, reasonPhrase=Found]
INFO  [CrawlerEventManager]       REJECTED_REDIRECTED: http://www.bochum.de/ (HttpFetchResponse [crawlState=REDIRECT, statusCode=302, reasonPhrase=Found (https://www.bochum.de/)])
ERROR [GenericMetadataFetcher] Cannot fetch metadata: https://www.bochum.de/ (www.bochum.de:443 failed to respond)
INFO  [CrawlerEventManager]            REJECTED_ERROR: https://www.bochum.de/ (com.norconex.collector.core.CollectorException: org.apache.http.NoHttpResponseException: www.bochum.de:443 failed to respond)
INFO  [AbstractCrawler] www.bochum.de: Could not process document: https://www.bochum.de/ (org.apache.http.NoHttpResponseException: www.bochum.de:443 failed to respond)
INFO  [CrawlerEventManager] DOCUMENT_COMMITTED_REMOVE: https://www.bochum.de/
INFO  [AbstractCrawler] www.bochum.de: Deleting orphan references (if any)...
INFO  [AbstractCrawler] www.bochum.de: Deleted 0 orphan references...
INFO  [AbstractCrawler] www.bochum.de: Crawler finishing: committing documents.
```

**Comment by essiembre** [comment]
The error suggests the host is not responding. If you feel it is tied to HTTP Client, there are timeout and other settings you can set on the HTTPClient with [GenericHttpClientFactory](https://norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/client/impl/GenericHttpClientFactory.html).

Can you share a config that reproduces the issue?

**Comment by jetnet** [comment]
yes, please: `0x0.st/iObe.xml`
please note, the site can be crawled only when the section `metadataFetcher` is commented out.
Thanks!

**Comment by essiembre** [comment]
I was able to reproduce thanks to your config.  Metadata fetching was "skipped" only on bad HTTP _status_.  In this case, were dealing with a network _exception_.  Now ``skipOnBadStatus="true"`` will log exceptions and skip as if a bad status.  

You can change the Log4J log levels if you do not like to see the warnings.  If you see many ``RetryExec`` log entries and they annoy you, you can add this to your log4j.properties:
```
log4j.logger.org.apache.http.impl.execchain.RetryExec=WARN
```
Please try the latest snapshot and confirm.

**Comment by jetnet** [comment]
Fantastic support again! Thank you, it is working now!
FYI: to get rid off the warnings:
```
www.site.com: 2020-06-09 11:46:38 WARN - Cannot fetch metadata: https://www.site.com/path (www.site.com:443 failed to respond)
```
I had to add the following into `log4j.properties`:
```
log4j.logger.com.norconex.collector.http.fetch.impl.GenericMetadataFetcher=ERROR
```
