### ISSUE TITLE
Wrongful dependency on Java 8.

### ISSUE THREAD

**Issue by essiembre** [Norconex/collector-http#70]
From @leonardsaers, java 8 was required to make the latest shanshot work.  See ticket https://github.com/Norconex/collector-http/issues/66#issuecomment-85087299

Java 7 should be supported.

**Comment by essiembre** [comment]
@leonardsaers, did you compile with Java 8 before running on Java 7? Did you get that error at compile time or runtime?  It turns out with Java 8, you have to be explicit and tell your Java you are compiling for Java 7 as a target.  This issue and solution are described here:

https://gist.github.com/AlainODea/1375759b8720a3f9f094

**Comment by leonardsaers** [comment]
I downloaded the snapshot: http://www.norconex.com/collectors/collector-http/download , so I did not compile it.

**Comment by essiembre** [comment]
OK, I updated the code to use a different approach that does not conflict between Java 7 and 8.   I created a new snapshot version of ``committer-core`` available for download [here](http://www.norconex.com/collectors/committer-core/download).  

If you prefer, I also created a new snapshot version of Norconex HTTP Collector you can download [here](http://www.norconex.com/collectors/collector-http/download).

Are you using one of [Norconex Committers](http://www.norconex.com/collectors/#committers) or you created your own?  There is recent code in Github for some of them.  You may need me to generate a snapshot release if you run into issues.  Let me know.

**Comment by leonardsaers** [comment]
Thanks, It works with open jdk 7 and the new snapshot. We are using a custom commiter.

**Comment by essiembre** [comment]
[Norconex HTTP Collector 2.1.0](http://www.norconex.com/collectors/collector-http/download) was released, which includes the version of ``committer-core`` with the fix. Closing.
