### ISSUE TITLE
Norconex HTTP crawler crawling/committing pages from another domain.

### ISSUE THREAD

**Issue by traghu123** [Norconex/collector-http#701]
Hello,

    We ran into a very strange issue this weekend (on 6/6/2020). The norconex crawler, which runs nightly in our setup and whose configs have been the same for more than a year, started crawling and committing pages from another site (theconversation.com web site). The start URL is https://health.ucdavis.edu and the start URL config is as below, 

startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="false"

metadataFetcher element is commented.

No other domains/sites are crawled and this is the first time we have experienced this issue, any help to troubleshoot or identify what may have happened will be of great help. Please let me know if I can provide additional information to clarify my question.

Thank you. 
Raghavendar Thirumala

**Comment by traghu123** [comment]
The one anomaly I have noticed with the site that should not be crawled is that the site does not have two dots in its domain name, e.g. all the site URLs have the pattern like https://theconversation.com/us or https://theconversation.com/heres-how-to-stay-safe-while-buying-groceries-amid-the-coronavirus-pandemic-138683, no www. in front of the domain name, wondering if that is playing a role? Thanks for looking into it and your thoughts

**Comment by essiembre** [comment]
This should obviously not happen. Can you share a config that reproduces the issue?
