### ISSUE TITLE
Question - Retain html tags while indexing

### ISSUE THREAD

**Issue by 4rsood** [Norconex/collector-http#702]
Hello, wondering if there is a way I can retain all the html formatting while indexing the body contents of a web page.

**Comment by essiembre** [comment]
One one approach is to copy the HTML to a field before the HTML gets parsed (i.e. as a pre-parse handler).  Something like this could do it (not tested):

```
  <tagger class="com.norconex.importer.handler.tagger.impl.TextPatternTagger">
      <restrictTo field="document.contentType">text/html</restrictTo>
      <pattern field="doc_html">.*</pattern>
  </tagger>
```

**Comment by 4rsood** [comment]
Thank you Pascal.  It worked - I am able to copy the entire HTML contents of the document to a field.  What if I want to copy the contents in seaparate fields based on certain div tags.  For example, I want to copy the entire HTML contents of 
<div class="findings"><h2>Findings</h2>Findings contents with html tags go here...</div> in a separate field.

**Comment by essiembre** [comment]
For this, ``DOMTagger`` is your friend.  It will give you a lot of options.

**Comment by 4rsood** [comment]
I have been able to use DOMTagger and extract contents but they all come out as raw text.

**Comment by essiembre** [comment]
This is expected behavior by default.  Have a look a the [class documentation](https://norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DOMTagger.html) for your "extract" options.  To keep the HTML, you probably want to use `html` or `outerHtml`.

**Comment by 4rsood** [comment]
It worked with the following configuration:
. ´<tagger class="com.norconex.importer.handler.tagger.impl.DOMTagger">     
      <dom selector="div.evaluationfindings"
              toField="evaluationfindingshtml"
              extract="html"
               />     
  </tagger>

Thanks again!
