### ISSUE TITLE
crawling mediawiki

### ISSUE THREAD

**Issue by ceiche59** [Norconex/collector-http#703]
I'm trying to crawl a MediaWiki but it only crawl the Start URl and then finishes without any error.

any idea?

**Comment by essiembre** [comment]
Is the page content javascript-driven? 

Please share a configuration file that reproduces the problem.

**Comment by ceiche59** [comment]
no, it's not - it's a mediawiki site (mainly PHP). I can see many redirects

Here are a snippet from the logs:
DEBUG [AbstractCrawler] XXXX Wiki Intranet: Crawler thread #1 started.
DEBUG [AbstractCrawler] XXXX Wiki Intranet: Processing reference: https://wiki.XXXX.net/index.php
DEBUG [GenericDocumentFetcher] Fetching document: https://wiki.XXXX.net/index.php
DEBUG [GenericDocumentFetcher] Encoded URI: https://wiki.XXXX.net/index.php
DEBUG [GenericRedirectURLProvider] URL redirect: https://wiki.XXXX.net/index.php -> https://wiki.XXXX.net/index.php
DEBUG [GenericDocumentFetcher] Unsupported HTTP Response: HTTP/1.1 302 Found
DEBUG [HttpImporterPipelineUtil] **Redirect target URL is already being processed:** https://wiki.XXXX.net/index.php (from: https://wiki.XXXX.net/index.php).

Here my Config-File
[mediawiki-config.zip](https://github.com/Norconex/collector-http/files/4817626/mediawiki-config.zip)

**Comment by essiembre** [comment]
I had a look at your config, and nothing jumps at me as the cause for stopping after the first URL.  I cannot reproduce without the site URL.  Is it possible for you to share it?

Else, it may help if you set your log level to DEBUG everywhere in your log4j.properties file and share the full log.  Being able to reproduce would be best though.

**Comment by ceiche59** [comment]
Unfortunately I cannot share the full URL - and you wouldn't be able to access it anyhow; it's on a internal network.

I used a simple test program with Apache HTTP-Client and it reports : Caused by: org.apache.http.client.CircularRedirectException: **Circular redirect to** 

So seems to be an configuration issue with the MediaWiki configuration.

**Comment by essiembre** [comment]
Glad you found the cause.  That would explain why it aborts.  If you get into a redirect loop, the crawler never gets to an actual page.
