### ISSUE TITLE
Forcing array Like Structure for Fields

### ISSUE THREAD

**Issue by ahaw022** [Norconex/collector-http#709]
We have a requirement to use the Azure Search Committer for H1 -> H3 Fields

The challenge is that depending on the page we may get one or more H1 -> H3 Fields. 

If we get one the committer treats it a single value and the commit process doesn't work. 

I see there is a SingleValue Tagger. What is the opposite of that?

Is it the MergeTagger with single value turned to no? 

I would like those fields to always be arrays even if there is only one entrance.

**Comment by essiembre** [comment]
I just created a new [snapshot release](https://norconex.com/collectors/committer-azuresearch/download) with a new option for this.   You can force specific fields to always be sent as an array with this new config snippet:
```xml
      <arrayFields regex="[false|true]">
          (Optional fields to be forcefully sent as array, even if single
           value. Unless "regex" is true, expects a CSV list of field names.)
      </arrayFields>
```

So for the H1, H2, and H3, you should be able to use something like this (not tested):

```xml
      <arrayFields regex="true">(?i)H\d</arrayFields>
```
or
```xml
      <arrayFields regex="false">H1, h1, H2, h2, H3, h3</arrayFields>
```

Please give it a try and confirm.

**Comment by ahaw022** [comment]
Awesome Thanks Pascal!
