### ISSUE TITLE
How to put reference back to queue after extract links from it?

### ISSUE THREAD

**Issue by lianghanzhen** [Norconex/collector-http#710]
Hi, I tried to put reference back to queue after extract links from it, but `QueueReferenceStage` will check if the reference is `active`, `queued` or `processed`. Obviously the reference is `active` after extracted links, which it will not be queued.

Due to the fact the pipelines are not configurable, I can not add another stage to put the reference in queue.

Do you have any ideas? Thanks in advance.

**Comment by essiembre** [comment]
Extracted links are automatically queued for further processing unless they are filtered out by some of your filtering rules. 

The flow is a bit different than what you describe. It is:

```
queued -> active -> processed
```

Once extracted, eligible URLs not already encountered are first `queued`. Then crawler threads periodically pull URLs from the queue to process them. While they are being processed, they are marked as `active`.  When done with a URL (e.g., rejected it, committed it, ...), it is marked as `processed`.

Are you observing URLs not being processed when they should?  Maybe change the log level in log4j.properties check your logs for more insight on what happens to those URLs.

**Comment by lianghanzhen** [comment]
What I tried to achieve was keep the crawler running forever, so I put the
urls being processed back to the queue, but if urls are being processed,
they can not be queued.

Is there a listener that can tell me the urls are processed?

**Comment by essiembre** [comment]
The crawler is designed to start, run, and die.  You would typically schedule it to run at specific interval (e.g., cronjob).

You can chain executions if you like, in a loop, to simulate running forever, but the concept of a crawl "session" is important to find out what changed from the last session, if there are orphans, etc.

For processed documents, you can create your own `ICrawlerEventListener` and look for events like `DOCUMENT_COMMITTED_ADD`, `DOCUMENT_COMMITTED_REMOVE` or any of the `REJECTED_*` events.
