### ISSUE TITLE
Authenticated site crawling issue with multiple URLs

### ISSUE THREAD

**Issue by onixterry** [Norconex/collector-http#711]
I am trying to crawl a web site protected with NTLM on IIS 10 / Windows Server 2016 Standard.  Using "DNN".

There is a "startURL" page that is public/anonymous.

On that page just two A HREF links.

```
<a href="http://<host>/link1/">link1</a>
<a href="http://<host>/link2/">link2</a>
```

Obviously this is simplified.

The startURL is fetched and the logs show that both links are extracted.

When the links are followed you see REJECTED_REDIRECTED to

```
http://<host>/link1/login?returnurl=%2flink1%2f
http://<host>/link2/login?returnurl=%2flink2%2f
```

You then see a further REJECTED_REDIRECTED

`http://<host>/desktopmodules/authenticationservices/dnnpro_activedirectory/windowssignin.aspx?portalid=1`

where "portalid=1" refers to the same directory as "link1".

You then see REJECTED_REDIRECTED again for

`http://<host>/link1/login?returnurl=%2flink1%2f`

At this point we see DOCUMENT_FETCHED for:
`http://<host>/link1/login?returnurl=%2flink1%2f`

There is never any REJECTED REDIRECTED for the second link.  i.e. there is no mention of `http://<host>/desktopmodules/authenticationservices/dnnpro_activedirectory/windowssignin.aspx?portalid=2`

If we log in as the "crawler" user, in a browser, and manually click on the links, we can see that the IIS server does, indeed serve up both 
`http://<host>/desktopmodules/authenticationservices/dnnpro_activedirectory/windowssignin.aspx?portalid=1`
AND
`http://<host>/desktopmodules/authenticationservices/dnnpro_activedirectory/windowssignin.aspx?portalid=2`

If we monitor the logs while the Norconex collector is running, the server never serves up 
`http://<host>/desktopmodules/authenticationservices/dnnpro_activedirectory/windowssignin.aspx?portalid=2`

To further complicate things - if we put `<a href="http://<host>/link2/">link2</a>` as a link on `http://<host>/link1/` then "link2" is successfully crawled.  There does not appear to be any redirection to the "authenticationservices" page in that case (although I could be wrong because this is coming from memory).

I feel as though it is a server configuration issue but the server admin disagrees.

We tried disabling cookies in the "auth" setup and then nothing would crawl correctly.  We tried "basic" auth instead of NTLM and nothing worked.

Any thoughts?  Is this sufficient information?

Thanks
Terry

**Comment by essiembre** [comment]
Can you please share your config?  Ideally, if your URL is public, can you share it as well so it is possible to reproduce?

**Comment by onixterry** [comment]
[norconex-config.txt](https://github.com/Norconex/collector-http/files/5118145/norconex-config.txt)

The config file is attached.  We are using some Velocity templates so excuse that coding.  :)

Unfortunately, the site being crawled is an Intranet site so not possible to share.

**Comment by essiembre** [comment]
Without a way to reproduce it is hard to help you.  Can you also attach your logs?

On the surface, it looks like the redirects are pointing to a login page. Is that so?  If you access the `login` or `windowssignin.aspx` page directly using a private session in your browser (so cache is clean), do you get a login form?

If you get a login form it may suggest an authentication mechanism other than NTLM needs to be used.  Can you ask the website administrator to confirm what type of authentication is in place?

If it is form-based, use the form authentication method, making sure you configure the `authURL` for the login form **target**.  Keep in mind It not rare for form-based authentication to add some tricks in their form to prevent bot-based authentication.

If it is using BASIC auth (browser-based popup login), then you can try setting `authPreemptive` to `true` in case your servers expect that.

**Comment by onixterry** [comment]
I'm attaching the collector logs as well as IIS logs.

In the IIS logs you'll see the two different attempts we tried.  The first attempt is our crawler (which matches up to the collector logs, attached).  The second attempt was a user, in Incognito, logged in as the same user.  When we were browsing in Incognito we were only ever challenged once for a login, regardless of where on the site we went.  In the first log, you'll notice very little because nothing appears to be being served up to the crawler.

We did try that authPreemptive setting, I'm fairly sure, because I recall searching around for NTLM issues with the Norconex crawler and seeing that in another post.

What I feel like is happening is that the web server is serving up a blank page on the second URL but since I cannot see the HTML that is being served to the crawler, I cannot prove it.  I suspect the issue is on the web server but I cannot prove it.

According to the Admins they are using NTLM and not HTTP Basic.  In fact, we did try using the BASIC auth setting and I believe nothing worked then.

It really seems as though a cookie is generated correctly when the crawler visits the first page but then when the crawler goes to visit the second URL the server is either not getting a cookie that it expects or it does not like the cookie it is seeing.

Is there any way to have Norconex output the actual HTML that it gets back from the page and/or print out information about the cookies that are being passed back and forth?

[Collector.log](https://github.com/Norconex/collector-http/files/5138205/Collector.log)
[u_ex200814-trimmed.log](https://github.com/Norconex/collector-http/files/5138206/u_ex200814-trimmed.log)

**Comment by essiembre** [comment]
I could not find the exact cause from your attached files but I got a few pointers.

First, not sure if you changed your config since you first shared it, but I can see your start URL resolves to this:
```
http://webdev.site.xx.ct
```

You have `stayOnDomain="false"` but you are forcing it to stay on domain with a reference filter that resolves to this:
```xml
<filter class="$filterRegexRef" onMatch="include">http://webdev.site.xx.ct.*\/.*</filter>
```
But in your log, you have URLs starting with `http://corpwebdev.corp.on.ca`.  

To help troubleshoot, I suggest you try the following to focus on the authentication only and nothing else (backup or copy your existing files first).

In your XML config add new tags or modify existing to match these:

```xml
<startURLs stayOnDomain="false" stayOnPort="false" stayOnProtocol="false">
...
</startURLs>
<numThreads>1</numThreads>
<maxDocuments>3</maxDocuments><!-- something low so the logs are kept short -->
<robotsTxt ignore="true"/>
<sitemapResolverFactory ignore="true"/>
<canonicalLinkDetector ignore="true"/>
<robotsMeta ignore="true"/>
```

Also, do this:
* Remove your reference filters.
* Modify your `userAgent` to add something that uniquely identifies your crawler instance (to isolate your crawl request from other requests in your IIS logs).
* Modify the log4j.properties to have everything in it set to TRACE.  That one will produce super-verbose logs, which hopefully will have the HTTP response headers from the server.

See if from the above you can find the cause.  If not, attach your new config and new logs.
