### ISSUE TITLE
Issue with relative links

### ISSUE THREAD

**Issue by bennrx** [Norconex/collector-http#719]
Hello,

I'm facing a problem with relative links during a crawl.

I've got 2 types of links on my site : 

- navigation links with complete url
- links to attachments which are relatives to root

Everything is working well for complete links but the crawler ignore relative links like this one : 
`<a class="btn btn-success" href="/upload/pdf/test.pdf" target="_blank"> Télécharger</a>`

I've made a try by changing this link for : 
`<a class="btn btn-success" href="http://ROOT/upload/pdf/test.pdf" target="_blank"> Télécharger</a>`

and the file is well indexing.

Do you have any idea how I can manage that ?

Thanks

**Comment by essiembre** [comment]
It should be picked up.  Can you share a link to a page with the problem and a configuration that reproduces the issue?
