### ISSUE TITLE
Parameter -a resume not working

### ISSUE THREAD

**Issue by martinfou** [Norconex/collector-http#72]
While trying to reproduce the bug described in #69 I have noticed that the -a resume command does not seem to work properly.  

Here are the steps to follow to reproduce the problem. 

1) collector-http.bat -a start -c c:\Users\fournierm\home\norconex\norconex-collector-http-2.1.0-SNAPSHOT\examples\minimum\minimum-config.xml

2) Stop the application by issuing the following command while the crawler is working. C:\Users\fournierm\home\norconex\norconex-collector-http-2.1.0-SNAPSHOT>collector-http.bat -a stop -c c:\Users\fournierm\home\norconex\norconex-collector-http-2.1.0-SNAPSHOT\examples\minimum\minimum-config.xml

3) Resume the crawling using the following command collector-http.bat -a resume -c c:\Users\fournierm\home\norconex\norconex-collector-http-2.1.0-SNAPSHOT\examples\minimum\minimum-config.xml

4) Take a look a the solr log files and you will see that the same pages were submitted the second time around.

**Comment by essiembre** [comment]
Several fixes were recently made and a [snapshot release](http://www.norconex.com/collectors/collector-http/download) has been made (2015-04-06).  Please try it and let me know.   Make sure to install it in a clean location to prevent having the same Jars with different versions.

**Comment by martinfou** [comment]
I have tested it and it is now working. If I stopped the job at 42 % completed ... it really restart at 42% and it no longer sends pages that were already crawled.

**Comment by csaezl** [comment]
So, I suppose I have to use ```-a resume```. Am I right?

**Comment by essiembre** [comment]
You are correct, ``-a start`` will always re-crawl from the beginning, ignoring the progress of the previous run.   ``-a resume`` will try to recover exactly where it left off.  If you have nothing to recover (the previous job ran until completion), then resuming won't do anything special.   

In either cases, the HTTP Collector performs "incremental" runs, and keeps track of what changed from one run to the next (to detect modified/deleted documents).

**Comment by csaezl** [comment]
Almost last question before testing. Related to issue #69 from which this one was derived, since HTTP Collector was interrupted, directory ```queue\path\add``` contains 3.837 files (that is, 1.279 documents). What will ```-a resume``` do with this information before crawling again?. Some URLs exist in my Solr repository and some don't. Should I do anything in advance or the  ```-a resume``` process will take care of everything?.

**Comment by essiembre** [comment]
If you have not deleted any of the progress files or anything else generated by the collector.  The resume won't do anything "explicitly" with those.  Which means, the next time the Committer will scan the queue for files to send, those will be picked up normally as if the process never stopped. 

If you suspect some are wrong, you can delete your queue, and delete all generated files (workdir, progress dir, log dir, etc) and issue a -start again to start fresh.

**Comment by csaezl** [comment]
collector-http-2.1.0-20150407.033412-6.zip | committer-solr-2.0.2-20150408.044504-1.zip
------------------------------------------------------- | ---------------------------------------------------------
httpclient-4.4.jar (02/04/2015) | httpclient-4.4.1.jar (01/04/2015)
httpcore-4.4.jar (02/04/2015) | httpcore-4.4.1.jar (01/04/2015)
commons-codec-1.9.jar (02/04/2015) | commons-codec-1.10.jar (28/03/2015)

Which version/s should I use?

**Comment by essiembre** [comment]
Whenever I encounter that, I always keep the highest version.  So I recommend you keep those in your right column.

**Comment by csaezl** [comment]
![08-04-2015 21-59-12](https://cloud.githubusercontent.com/assets/10865115/7054178/17a01970-de3b-11e4-9aef-bcd4237b4666.jpg)
Error running HTTP Collector. Perhaps deleting old versions I deleted too much.

**Comment by essiembre** [comment]
Yes, you probably did.  But this is a mistake easy to make, because Apache Commons Collections has two different libraries that are both required:  "commons-collection" and "commons-collections4".   They are not the same thing (the classes have different package structure).   It looks like you deleted the first one, which probably was: ``commons-collections-3.2.1.jar``.

**Comment by csaezl** [comment]
![08-04-2015 22-19-08](https://cloud.githubusercontent.com/assets/10865115/7054526/64bf4148-de3d-11e4-8846-3fb65e4f545e.jpg)

Sorry for sending one more. If a get a third error I'd try mixing collector and commiter jars again.

**Comment by essiembre** [comment]
Same deal.  Apache has two streams that are distinct libraries (one can't replace the other):  Apache Commons Lang and Apache Commons Lang 3.  Both are required, and it looks like you deleted the "Lang" one (as opposed to Lang 3).   If you check carefully, the digit "3" in this case, or "4" in the above case, are actually part of the library names, (in addition to the version sometimes).

**Comment by essiembre** [comment]
[Norconex HTTP Collector 2.1.0](http://www.norconex.com/collectors/collector-http/download) was released. Closing.
