### ISSUE TITLE
Norconex - Class GenericHttpClientFactory

### ISSUE THREAD

**Issue by Krystian780** [Norconex/collector-http#721]
Hi, 

I am trying to crawl a site which require 2 step authentication. 
Firstly, a small window appears which requires filling out with login and password, then I am redirected to a site which also requires providing login and password. I am able to run the crawler which requires only one step authentication but when I have to crawl the site with 2 authentications I am not sure which extension / options from this site I should use: https://opensource.norconex.com/collectors/http/v2/apidocs/com/norconex/collector/http/client/impl/GenericHttpClientFactory.html 
Any hints ?

**Comment by essiembre** [comment]
What type of authentication is it? BASIC?  To be clear, are you encountering two different sites asking to authenticate, or the same site required two-factor authentication just to get in?   

If the first, the best approach would be to create two different crawlers in your collector config.  One for each site.  Then you can have different authentication for each.

If the second, I would have to see it.  If really two-factor authentication, they usually involve a random piece, like a code sent to you for confirmation that you have to provide back.  Those are to ensure unique access, which excludes crawlers.

Can you share your site maybe?  Or can you provide more details on the authentication mechanisms?

**Comment by Krystian780** [comment]
Hi, 

I would like to crawl only one site: https://sites.google.com/roche.com/biissearchsquad 
This site asks for my email and if the given email is correct I am directed to the other site which also require authorization: **https://wamqa.roche.com/**

If there is only one step authorization - **https://wamqa.roche.com/** I am able to run the crawler but if there is two steps authorization - first email, then wamq - I don't know how to do that.

**Comment by essiembre** [comment]
If I understand you well, each site can be accessed via one step authorization?  It is only when the crawler navigates from one site to the other that it becomes an issue, right?  If so, I would try my earlier advice and have a different crawler for each site, each having their own authentication mechanisms.  Make sure they do not crawl each other by using reference filters, or `stayOnSite` being `true`.

If my understanding is wrong, please clarify.  Without being able to experience it for myself, it is difficult to give you sound advice.

**Comment by Krystian780** [comment]
https://sites.google.com/roche.com/biissearchsquad - site can be accessed via two step authorization.
First you need to give correct email then you are directed to other site which also requires from you credentials.

**Comment by essiembre** [comment]
There is currently no built-in support for multiple authentications for the same crawl.  Unless the content of the site you are interested in can be accessed some other way, I am afraid you will have to use a custom solution. You may have to create your own  `IHttpClientFactory` implementation or extend `GenericHttpClientFactory`.  Basically, you will have to code the flow yourself.  Not knowing the inner workings of your authentication mechanisms, I am not sure how hard/feasible you will find it.

There is also the possibility of simulating user interaction with a browser-based crawl, but I am not sure it would be any simpler.  Version 2 supports PhantomJS for this, but it is a bit outdated.  Version 3 (only available as snapshot) allows you to use any popular browser.

**Comment by Krystian780** [comment]
Hi, 

So, Norconex can not crawl a site that has two steps authentication unless I extend  GenericHttpClientFactory? 
Have you extented GenericHttpClientFactory to crawl such a site ? If yes, do you have an example how to do that ?

**Comment by essiembre** [comment]
Sorry, I do not have a code example specific to your use case.  

If you want to consider alternatives to extending GenericHttpClientFactory, you can investigate using browser-based crawling, mimicking user interaction.  Version 2 offers an HTTP client based on PhantomJs, but PhantomJs is no longer supported so I am not sure how far you will get.  HTTP Collector Version 3 supports popular browsers if you are comfortable dealing with code still in development (snapshot version). 

Can the site you are crawling be adapted to accept requests from a specific "user-agent" or IP?  This could be a way to facilitate crawling.
