### ISSUE TITLE
Fetch all (really all) Urls and import/commit them nowhere 

### ISSUE THREAD

**Issue by petrich** [Norconex/collector-http#723]
Hi There, 

is it possible to fetch all kinds of urls from a website (no matter of the Content-Type) ... and  not commit/import them anywhere.

I need it for checking of any broken/death urls.

 Thank you in advance.

**Comment by essiembre** [comment]
Sure, have a look at [URLStatusCrawlerEventListener](https://opensource.norconex.com/collectors/http/v2/apidocs/com/norconex/collector/http/crawler/event/impl/URLStatusCrawlerEventListener.html).  It can report on all statuses, or just 404.

If you do not provide a committer, it will not be sent anywhere.  

Works for you?

**Comment by petrich** [comment]
Works perfectly now. Thank you very much.

**Comment by MWcompeff** [comment]
Happy new year! Greetings from Bürgstadt/Germany. Meld Dich mal!
