### ISSUE TITLE
Is it possible to access environment variables in the configuration?

### ISSUE THREAD

**Issue by ronjakoi** [Norconex/collector-http#724]
The configuration XML supports Velocity templates. I have been trying to find out if you can access environment variables with Velocity. This would make it simple to for example set different crawl depths for different cronjobs or different commit targets in test and production environments.

**Comment by essiembre** [comment]
It can be done.  In version 2.x, which I presume you are using, you have to use a little trick.  You can modify the launch script to add a few lines echoing the environment variables you are interested in, into a `xyz.variables` file just before the launch command. You will then be able to use those variables in your config file.  

For example, if you are on a linux system, you would modify the `collector-http.sh` script to add this before the `java ...` command:

```sh
echo "myvar1=$MY_ENV_VARIABLE" > ./myfile.variables
echo "myvar2=$ANOTHER_ENV_VARIABLE" >> ./myfile.variables
```

You then have to add this variable file to your command-line execution with the `-v` flag.  Unless the base name of your `.variables` file is the same as your configuration file name (in which case it will be automatically detected).

In your configuration file, you will then be able to use `${myvar1}` and ${myvar2} as you see fit.

FYI, there is already native support for environment variables/system properties in the version 3.x codebase.  The original request for it is tracked in #641.  You can refer to the V3 [usage documentation](https://opensource.norconex.com/docs/collectors/http/configuration.html#environment-variables).  There is no plan to implement this new feature in V2, so hopefully the above trick will work for you in the meantime.

Please confirm.

**Comment by ronjakoi** [comment]
Thank you for your reply. I have other issues on my hands at the moment but I will try your solution soon and report back.

**Comment by ronjakoi** [comment]
I am closing this because due to some other desired features, I am planning to migrate to 3.0 which supports environment variables out of the box.
