### ISSUE TITLE
crawler commits web page that already exist when it receives a stop command.

### ISSUE THREAD

**Issue by martinfou** [Norconex/collector-http#73]
While trying to reproduce bug #69, I noticed that the collector-http was submitting pages that were already crawled and present in Solr before shutting down when it receives a stop command.

**Comment by essiembre** [comment]
Several fixes were recently made and a [snapshot release](http://www.norconex.com/collectors/collector-http/download) has been made (2015-04-06).  Please try it and let me know.   Make sure to install it in a clean location to prevent having the same Jars with different versions.

**Comment by martinfou** [comment]
I have tested and I can confirm that it is working properly.

**Comment by essiembre** [comment]
[Norconex HTTP Collector 2.1.0](http://www.norconex.com/collectors/collector-http/download) was released. Closing.
