### ISSUE TITLE
Importer 3.0 whitespace behavior in matchers StripBetweenTransformer

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#734]
The whitespace in the startMatcher and endMatcher are seen as actual whitespace. So `<startMatcher method="basic"> body </startMatcher>` won't match on "<body>". Not sure if this is on purpose. Just something to be aware of.

In the example of the documentation  inclusive="true" is part of `handler `instead of `stripBetween`.

**Comment by essiembre** [comment]
Yes, starting with this version, whitespaces are preserved. See: https://opensource.norconex.com/docs/collectors/http/configuration.html#white-spaces

Thanks for reporting the Javadoc error. It is now fixed.

**Comment by essiembre** [comment]
It turns out you were not the only one having issues with this change of behavior.  It was reverted to default white-space handling behavior in the latest snapshot.  If you want to preserve them, you now have to be explicit. E.g.:

```
<value xml:space="preserve">    blah    </value>
```

The online manual will be updated.
