### ISSUE TITLE
steps for incremental crawl

### ISSUE THREAD

**Issue by Akhilabala** [Norconex/collector-http#736]
Please provide the steps for incremental crawl

**Comment by essiembre** [comment]
Hello @Akhilabala, incremental is active by default.  On subsequent crawl, it will only send to your committer documents that have been modified/added/deleted.

It uses checksums to find out if a document has changed or not, which you can configure to behave in different ways.  Look for `metadataChecksummer` and `documentChecksummer` configuration options.
