### ISSUE TITLE
Regex and backreferences in StripBetweenTransformer

### ISSUE THREAD

**Issue by gallbrook** [Norconex/collector-http#737]
Hi,

I'm attempting to use regex and a backreference in the StripBetweenTransformer but it doesn't seem to be working.

I'm wanting to strip any html content contained within a tag that has a class containing visually-hidden 
E.g. `
  <a href="#main-content" class="visually-hidden focusable skip-link">
    Skip to main content
  </a>
`

The relavent part of my config is:

```<preParseHandlers>
<transformer class="com.norconex.importer.handler.transformer.impl.StripBetweenTransformer" inclusive="true" caseSensitive="false">
<stripBetween>
<start><![CDATA[<(\w+)[\s\w"=\-#]+?visually-hidden[\s\w"=\-#]+?>]]></start>
<end><![CDATA[</]]>$1<![CDATA[>]]></end>
</stripBetween>
<restrictTo field="document.contentType">text/html</restrictTo>
</transformer>
</preParseHandlers>```

However this doesn't seem to be working.  Is this even possible?

Georgina.

**Comment by essiembre** [comment]
You cannot use back-references with `StripBetweenTransformer` since the "start" and "end" are executed separately from each other.

To do what you want, you have to perform a "search and replace" in one swoop.   For this, you can use the `ReplaceTransformer`, like this:

```xml
    <transformer class="com.norconex.importer.handler.transformer.impl.ReplaceTransformer">
      <replace>
        <fromValue><![CDATA[<(\w+)[\s\w"=\-#]+?visually-hidden[\s\w"=\-#]+?>.*?</\1>]]></fromValue>
        <toValue></toValue>
      </replace>
    </transformer>
```

**Comment by gallbrook** [comment]
Hi @essiembre,

Thanks for your response, I have tried what your code and it works beautifully.

Performing a "search and replace" in one swoop using the ReplaceTransformer is a neat trick.

Georgina
