### ISSUE TITLE
Cannot extract nested sitemap from sitemap.xml

### ISSUE THREAD

**Issue by peter-chan-hkmci** [Norconex/collector-http#738]
I have a sitemap.xml which contains the following information:
```
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>(url to sub-sitemap-1.xml)</loc>
    <lastmod>2021-02-02T18:16:47+00:00</lastmod>
  </sitemap>
  <sitemap>
    <loc>(url to sub-sitemap-2.xml)</loc>
    <lastmod>2021-02-02T18:16:47+00:00</lastmod>
  </sitemap>
</sitemapindex>
```

And I added this sitemap.xml to `startURLs` tag, like:
```
<startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
  <sitemap>(url to sitemap.xml)</sitemap>
</startURLs>
```

However, the crawler logged the following error:
```
ERROR [StandardSitemapResolver] Cannot fetch sitemap: <url of the sitemap.xml> (java.lang.NullPointerException)
```

So you have any idea?

**Comment by essiembre** [comment]
There was a similar issue fixed a couple of months ago.  Assuming you are using 2.9.0, please try the latest snapshot version (2.9.1-SNAPSHOT).

**Comment by jetnet** [comment]
the latest snapshot still has this issue, unfortunately.

**Comment by essiembre** [comment]
I was finally able to reproduce and provided a fix.  Please try the latest HTTP Collector snapshot and confirm.

**Comment by jetnet** [comment]
Thank you! Nested sitemaps work now. But the PREMATURE-feature stopped working, see #741
