### ISSUE TITLE
Identifying document language by content (LangDetectLanguageIdentifierUpdateProcessorFactory)

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#74]
Almost all documents crawled by HTTP Collector have information about its language, but some PDF, DOC, etc may not have metadata because the authors don't register such type of information.
In this case, the document content has to be analyse in order to determine its language.
Does HTTP Collector supports this type of activity?.
Since I use Solr to store the documents, is there a way of instructing HTTP Collector to make the call to Solr ```/update``` with this parameter: ```http://localhost:8983/solr/update?update.chain=langid```, so ```LangDetectLanguageIdentifierUpdateProcessorFactory``` (in my ```solrconfig.xml```) could identify the document language?. I've tried ```<solrUpdateURLParams>```  (```SolrCommiter``` section) with not much success.
Thank you

**Comment by essiembre** [comment]
Norconex HTTP Collector has built-in language detection with its [LanguageTagger](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/LanguageTagger.html), which is part of the Importer module (goes inside your ``<importer>`` tags).

**Comment by csaezl** [comment]
Thank you very much. It works great!.
Two more related questions:
- Talking again about ```/update ``` parameters, is a way of passing ```update.chain=langid ``` to Solr in HTTP Collector call?.
- And about importers, I've read that they have a function/capacity named ```title generator```. What is it about?.

Thanks,
Carlos

**Comment by essiembre** [comment]
About titles, this is a new feature of the Importer module 2.1.0.  It will be shipped with the next release of HTTP Collector but until then, you will have to update it manually.  Look for [TitleGeneratorTagger](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/TitleGeneratorTagger.html).

It's not a magic solution, but hopefully it can give you something better than no title or a file name.

For the /update feature, that's a question for the Solr Committer project.  I've moved it [here](https://github.com/Norconex/committer-solr/issues).

**Comment by csaezl** [comment]
Thank you very much for your support.
Carlos
