### ISSUE TITLE
Norconex - cookies

### ISSUE THREAD

**Issue by Krystian780** [Norconex/collector-http#744]
Hi, 

Is it  possible to put 10 sites in a configuration file and set cookies to every site ? 

For example:

`<url>www.firstsite.com</url>`
`<url>www.secondsite.com</url>`
`<url>www.thirdsite.com</url>`

`<httpClientFactory>`
    `<headers>`
        `<header name="Cookie">name1=COOKIE FOR THE FIRST SITE ; name2=COOKIE FOR THE SECOND SITE; name2=COOKIE FOR THE THIRD SITE;</header>`
    `</headers>`
  `</httpClientFactory>`

Norconex wants to access a first site which require cookie in the header, 
then Norconex wants to access a second site which require a different cookie in the header 

is it possible to do that in one configuration file ?

**Comment by essiembre** [comment]
Hello @Krystian780. It is possible, but not on one line as you suggest.  Short of writing your own `IHttpClientFactory`, you would have to create multiple `<crawler>` sections in the same configuration file.  Rest assured, you do not have to duplicate your entire crawler config in each.   You can use <crawlerDefaults> for all your settings, except what is unique to each `<crawler>`.  

You can also have a look at dynamic includes of configuration fragments if that helps when dealing with multiple crawlers.

**Comment by Krystian780** [comment]
Have you got the link to the dynamics that includes configuration fragments similar to my problem ?

**Comment by essiembre** [comment]
When you download the HTTP Collector, there is a ["complex" sample](https://raw.githubusercontent.com/Norconex/collector-http/2.x-branch/norconex-collector-http/src/site/resources/examples/complex/complex-config.xml) that comes with it.  It shows how to perform fragment inclusion.  As for your case specifically, there are a few ways you can go about it. If you want to keep everything in the same config, here are a couple options:

**Option 1: Crawler defaults**

The simplest is to define everything in crawler default, except for the start URL and the `HttpClientFactory` in each crawler. E.g.:

```xml
<httpcollector id="My Collector">
  ...
  <crawlerDefaults>
    ... (your configuration)  ...
  </crawlerDefaults>
  <crawlers>
    <crawler id="Crawler 1">
      <startURLs><url>https://site1.com/index.html</url></startURLs>
      <httpClientFactory>
        <headers><header name="Cookie">name1=COOKIE FOR SITE 1</header></headers>
      </httpClientFactory>
    </crawler>
    <crawler id="Crawler 2">
      <startURLs><url>https://site2.com/index.html</url></startURLs>
      <httpClientFactory>
        <headers><header name="Cookie">name2=COOKIE FOR SITE 2</header></headers>
      </httpClientFactory>
    </crawler>
    <crawler id="Crawler 3">
      <startURLs><url>https://site1.com/index.html</url></startURLs>
      <httpClientFactory>
        <headers><header name="Cookie">name3=COOKIE FOR SITE 3</header></headers>
      </httpClientFactory>
    </crawler>
  </crawlers>
</httpcollector>
```

While it should work just fine, it could lead to big config files if you have a lot of URLs.

**Option 2: macros**

You can simplify the above example by taking advantage of Apache Velocity, the template engine used to parsed the HTTP Collector configurations.  You can configure the bulk of your crawler under the `<crawlerDefaults>` section like above but you have the `<crawler>` section in a Velocity macro that you invoke with arguments.  Example:

```xml
<httpcollector id="My Collector">
  ...
  <crawlerDefaults>
    ... (your configuration)  ...
  </crawlerDefaults>
  
#macro( crawler $id $url $cookie )
    <crawler id="$id">
      <startURLs><url>$url</url></startURLs>
      <httpClientFactory>
        <headers><header name="Cookie">$cookie</header></headers>
      </httpClientFactory>
    </crawler>
#end
  
  <crawlers>
    #crawler("Crawler 1", "https://site1.com/index.html", "COOKIE FOR SITE 1")
    #crawler("Crawler 2", "https://site2.com/index.html", "COOKIE FOR SITE 2")
    #crawler("Crawler 3", "https://site3.com/index.html", "COOKIE FOR SITE 3")
  </crawlers>
</httpcollector>
```

You can decide to move your macro to a fragment that you can reuse in multiple collectors in case you want to reduce the number of crawlers per collector.

**Other ideas**

* You could dynamically generate your config files using your own external process.
* You could create your own `IHttpClientFactory` implementation that extends the default one. You could make it so it accepts a mapping between a URL pattern and a cookie value.  That way you only have one crawler defined.
