### ISSUE TITLE
Using splitter

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#75]
For my use case I need to store the title of a parent with the child document  The references and titles of multiple items are in XML file, so it needs to be split.

```
<channel>
<item>
<title>Test</title>
<guid>http://www.test.com/test.pdf</guid>
</item>
<item>
<title>Test2</title>
<guid>http://www.test.com/test2.pdf</guid>
</item>
</channel>
```
So if the pdf has another title in its meta, the title in the XML overwrites that value (or stores it in another field).

Could you point me to an example on how to do this?

**Comment by essiembre** [comment]
I'd like to make sure I understand your use case properly.   

Your starting point is a single (or many?) XML file like your example, holding titles and URLs to fetch.  Is that correct?   

And for every URL in that XML file, you want to fetch the document, along with its metadata... but overwrite the title metadata found in the PDF (if any) with the one defined in your XML (if any).

Am I understanding your objective correctly?

**Comment by OkkeKlein** [comment]
Yes, the starting point is a XML holding URLs to many XMLs holding titles and URLs to fetch. I got a link extractor working so all the XMLs with the meta data are found. But I need to split those XMLs and then use the meta data for the fetched PDFs.

**Comment by essiembre** [comment]
You seem well started!   There are different ways ways to do this.  

For splitting documents in general, you may want to look at creating your own [IDocumentSplitter](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/splitter/IDocumentSplitter.html) (or extend [AbstractDocumentSplitter](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/splitter/AbstractDocumentSplitter.html)). 

In your case though, you can probably continue the way you started with your custom link extractor.  I suggest you enhance it  to add the title to each [Link](http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/url/Link.html) you extract (via the ``setTitle(String)`` method).  This should add a metadata property called ``collector.referrer-link-title`` to your child documents.  

Then, to overwrite the PDF title, you can use an existing tagger for this.  I suggest you look at the existing [CopyTagger](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/CopyTagger.html) or [RenameTagger](http://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/RenameTagger.html) for this.

**Comment by OkkeKlein** [comment]
Using linkextractor is probably easier approach. Thanx for the tip.

**Comment by OkkeKlein** [comment]
Everything is working fine when I start crawling in the XML holding the URLs to the PDFs. But as soon as i start at lower depth (XML holding the links to the paginated XMLs) I see it finds the links to the PDFs but they never get crawled or added to references table. Not with maxDepth increased or maxdocuments set to -1. What am I missing?

**Comment by essiembre** [comment]
I am assuming you got the info you needed.  Feel free to open another issue if you have more questions.
