### ISSUE TITLE
Running on AWS within a Docker image

### ISSUE THREAD

**Issue by jettro** [Norconex/collector-http#750]
HI,
we are executing an experiment with Norconex running in a Docker container on the AWS platform. I want to have an implementation IDataStoreEngine that works with AWS. Was thinking about using MVStore on S3, but that does not feel like the best solution. Other idea was to use a jdbc connection, but having problems running it against for instance MySQL. 

My question, is such a setup on your agenda? I don't mind helping out, but do not want to do something that is already there. Please let me know you thoughts.

**Comment by essiembre** [comment]
As you may know, the datastore is keeping track of URLs crawled and a minimum amount of metadata to be able to perform "incremental" crawls efficiently.  As such, it does not help you with the content it crawled.   For this, you normally use Committers.  There are quite a few already, including an SQL one.  They are also easier to extend if you want to create your own. 

Can you maybe describe what you are after?  Is it so you have a way to persist/reuse the datastore on a volatile Docker container?  If so, you can use a persistent volume that you re-attach when you launch your container. Else, MySQL should now work with the latest snapshot as described in #749.

For relatively small crawls (less than 1 million pages) the default MVStore implementation is quite efficient. Especially if have fast local disks and/or lots of RAM.  For larger ones, then you may have to use multiple crawler instances and/or distribute the datastore to get something more scalable.  Is this rather what you are after? In such a case, a relational SQL database, MongoDB, or your own implementation would do.

**Comment by jettro** [comment]
Our usecase is starting and stopping a Docker container on AWS Fargate. Therefore I want to keep the information about the crawls for the next time. I have written a first experiment using DynamoDB. GOing to test it, if it works, I'll make it available somehow.

**Comment by essiembre** [comment]
If you are looking for something that may be simpler, you should be able to mount volumes with AWS Fargate.  

If you proceed with DynamoDB, please do share your progress.
