### ISSUE TITLE
Stopping HttpCollector using stop method produce threads leak - programatic configuration 

### ISSUE THREAD

**Issue by SiwyDym** [Norconex/collector-http#754]
Hi 
I noticed that, when I start `HttpCollector `and wait to the end, then everything works well, but when I try to stop them, then I got a lot of exceptions in logs. Collector are stopped, but there are always 3 zombii threads left(exactly the same number of threads as `numThreads `for `HttpCrawlerConfig`). In [link ](https://postimg.cc/QH5KN1y5)there is visualization behavioral of threads . I had problem to upload directly to github. 

In example I use programatic option to configure `HttpCollector`. 

Example errors:

> 2021-05-12 12:20:38,726 [pool-44-thread-1] [ ERROR ] c.n.c.h.f.i.GenericDocumentFetcher:265 : Cannot fetch document: https://www.google.pl/images/branding/googlelogo/1x/googlelogo_white_background_color_272x92dp.png (Socket closed)
> 2021-05-12 12:20:38,726 [pool-44-thread-3] [ ERROR ] c.n.c.h.f.i.GenericDocumentFetcher:265 : Cannot fetch document: https://www.google.pl/history/optout?hl=pl (Socket closed)
> 2021-05-12 12:20:38,727 [pool-44-thread-2] [ ERROR ] c.n.c.h.f.i.GenericDocumentFetcher:265 : Cannot fetch document: https://www.google.pl/advanced_search?hl=pl&authuser=0 (Software caused connection abort: recv failed)
> 2021-05-12 12:20:38,727 [pool-44-thread-1] [ ERROR ] c.n.c.c.c.AbstractCrawler:566 : 8c5790f7-e5ed-4578-a395-02962abe3eeb: Could not process document: https://www.google.pl/images/branding/googlelogo/1x/googlelogo_white_background_color_272x92dp.png (javax.net.ssl.SSLException: Socket closed)
> com.norconex.collector.core.CollectorException: javax.net.ssl.SSLException: Socket closed
> 	at com.norconex.collector.http.fetch.impl.GenericDocumentFetcher.fetchDocument(GenericDocumentFetcher.java:268)
> 	at com.norconex.collector.http.pipeline.importer.DocumentFetcherStage.executeStage(DocumentFetcherStage.java:42)
> 	at com.norconex.collector.http.pipeline.importer.AbstractImporterStage.execute(AbstractImporterStage.java:31)
> 	at com.norconex.collector.http.pipeline.importer.AbstractImporterStage.execute(AbstractImporterStage.java:24)
> 	at com.norconex.commons.lang.pipeline.Pipeline.execute(Pipeline.java:91)
> 	at com.norconex.collector.http.crawler.HttpCrawler.executeImporterPipeline(HttpCrawler.java:360)
> 	at com.norconex.collector.core.crawler.AbstractCrawler.processNextQueuedCrawlData(AbstractCrawler.java:538)
> 	at com.norconex.collector.core.crawler.AbstractCrawler.processNextReference(AbstractCrawler.java:419)
> 	at com.norconex.collector.core.crawler.AbstractCrawler$ProcessReferencesRunnable.run(AbstractCrawler.java:812)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: javax.net.ssl.SSLException: Socket closed
> 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
> 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:352)
> 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:295)
> 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:290)
> 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:144)
> 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1359)
> 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1268)
> 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401)
> 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373)
> 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
> 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
> 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
> 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
> 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
> 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
> 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
> 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
> 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
> 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
> 	at com.norconex.collector.http.fetch.impl.GenericDocumentFetcher.fetchDocument(GenericDocumentFetcher.java:205)
> 	... 11 common frames omitted
> 	Suppressed: java.net.SocketException: Socket closed
> 		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
> 		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
> 		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:83)
> 		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:383)
> 		... 32 common frames omitted
> Caused by: java.net.SocketException: Socket closed
> 	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
> 	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
> 	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
> 	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
> 	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
> 	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
> 	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
> 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
> (...)
> 2021-05-12 12:20:38,728 [pool-44-thread-2] [ ERROR ] c.n.c.c.c.AbstractCrawler:693 : 8c5790f7-e5ed-4578-a395-02962abe3eeb: Could not finalize processing of https://www.google.pl/advanced_search?hl=pl&authuser=0 (This store is closed [1.4.200/4])
> java.lang.IllegalStateException: This store is closed [1.4.200/4]
> 	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
> 	at org.h2.mvstore.MVStore.checkOpen(MVStore.java:2657)
> 	at org.h2.mvstore.MVStore.getChunk(MVStore.java:1227)
> 	at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1214)
> 	at org.h2.mvstore.MVStore.readPage(MVStore.java:2209)
> 	at org.h2.mvstore.MVMap.readPage(MVMap.java:672)
> 	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1043)
> 	at org.h2.mvstore.Page.get(Page.java:222)
> 	at org.h2.mvstore.MVMap.get(MVMap.java:472)
> 	at org.h2.mvstore.MVMap.get(MVMap.java:459)
> 	at org.h2.mvstore.MVMap.containsKey(MVMap.java:477)
> 	at com.norconex.collector.core.data.store.impl.mvstore.MVStoreCrawlDataStore.isQueued(MVStoreCrawlDataStore.java:114)
> 	at com.norconex.collector.core.pipeline.queue.QueueReferenceStage.execute(QueueReferenceStage.java:52)
> 	at com.norconex.collector.core.pipeline.queue.QueueReferenceStage.execute(QueueReferenceStage.java:29)
> 	at com.norconex.commons.lang.pipeline.Pipeline.execute(Pipeline.java:91)
> 	at com.norconex.collector.http.crawler.HttpCrawler.executeQueuePipeline(HttpCrawler.java:280)
> 	at com.norconex.collector.http.crawler.HttpCrawler.beforeFinalizeDocumentProcessing(HttpCrawler.java:432)
> 	at com.norconex.collector.core.crawler.AbstractCrawler.finalizeDocumentProcessing(AbstractCrawler.java:632)
> 	at com.norconex.collector.core.crawler.AbstractCrawler.processNextQueuedCrawlData(AbstractCrawler.java:568)
> 	at com.norconex.collector.core.crawler.AbstractCrawler.processNextReference(AbstractCrawler.java:419)
> 	at com.norconex.collector.core.crawler.AbstractCrawler$ProcessReferencesRunnable.run(AbstractCrawler.java:812)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)

I use `norconex-collector-http` in `2.8.0` 

It's something releated [with this comment](https://github.com/Norconex/collector-core/blob/norconex-collector-core-1.8.2/norconex-collector-core/src/main/java/com/norconex/collector/core/AbstractCollector.java#L170) ?

**Comment by essiembre** [comment]
I am not sure what is causing it in your case.  When you stop it using the stop command, it does not stop right away, as per the code you referenced. It tries to shut down gracefully, which maybe in your case is not possible for some reason.

It looks like the crawl store gets closed while the process tries to write to it again.  Maybe you have different collectors pointing to the same workdir?  Maybe you are trying to restart it before it is entirely done?   Maybe something else in your program is keeping those threads alive?  Does this also happen when you run it from the command line?   There might be cleaning actions occurring at JVM shutdown and if it does not get shut down, those are not triggered, causing errors eventually.

In any case, a workaround can be to kill the parent process (and its children).

You can also try with the latest stable release (2.9.0) in case this was indirectly fixed.
