### ISSUE TITLE
Forms with div tags and ajax posts

### ISSUE THREAD

**Issue by arunakanaparthy** [Norconex/collector-http#755]
Hi,
I have a site which triggers an ajax post from a button for authentication. Does form based auth work for this or do we need to implement custom authentication? Can you please provide a direction on how to tackle the issue?
![Screen Shot 2021-05-28 at 12 49 59 PM](https://user-images.githubusercontent.com/48925007/120023686-c9c34180-bfb3-11eb-9789-0d844042759f.png)

**Comment by essiembre** [comment]
Without knowing the inner workings of your site, I can think of two things to try.

First, if you know the target URL that is invoked when that button is pressed, you can try the form-based authentication, passing all expected values to that.

If there is no way to make that work, you may have to try the milestone release of HTTP Collector 3.0.0 and try doing it using a browser (see [WebDriverHttpFetcher](https://opensource.norconex.com/collectors/http/v3/apidocs/com/norconex/collector/http/fetch/impl/webdriver/WebDriverHttpFetcher.html)).   You may try to simulate user behavior with the `<latePageScript>` configuration option.  This can get quite complex though, especially if the site is designed to make it difficult.

**Comment by arunakanaparthy** [comment]
Thank you Pascal! Will try your suggestions
