### ISSUE TITLE
Error building 4.0.0

### ISSUE THREAD

**Issue by svanschalkwyk** [Norconex/collector-http#757]
```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.norconex.collectors:norconex-collector-http:3.0.0-SNAPSHOT: Could not find artifact com.norconex.commons:norconex-commons-maven-parent:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 11
```

**Comment by essiembre** [comment]
The parent POM is [published](https://oss.sonatype.org/service/local/repositories/snapshots/content/com/norconex/commons/norconex-commons-maven-parent/1.0.0-SNAPSHOT/norconex-commons-maven-parent-1.0.0-20210329.055621-10.pom) so it should normally load just fine.  I suspect it is linked to not having the Sonatype Nexus repo configured.  

You are in a catch-22.  The Sonatype repo is required for snapshots and is configured in the said parent project, but unless you have the parent installed relative to the child, it simply won't find it and won't know about the Sonatype snapshot repo. 

You have a few options.  

1. Install that dependency manually to your local maven repo.
2. You can add the Sonatype repo to your `pom.xml`:
```xml
<repository>
  <id>sonatype.oss.snapshots</id>
  <name>Sonatype OSS Snapshot Repository</name>
  <url>http://oss.sonatype.org/content/repositories/snapshots</url>
  <releases>
    <enabled>false</enabled>
  </releases>
  <snapshots>
    <enabled>true</enabled>
  </snapshots>
</repository> 
```
3. You can clone/fork the parent project so the HTTP Collector can reference it locally.
4. You can create yourself a new Maven profile in your Maven settings with the Sonatype repo configured.

Please confirm if any of these work for you.
