### ISSUE TITLE
How does "setMaxDocuments()" feature work?

### ISSUE THREAD

**Issue by naoxide95** [Norconex/collector-http#765]
good evening!
I need to ask about "getMaxDocument()" for crawlerConfig objects
- does it control max documents crawled by every single crawler, or by all crawlers as a whole?
- does it include all documents collected from a single website, or from all websites  of a crawler as a whole?
thanks in advance

**Comment by essiembre** [comment]
* Each crawler individually, where it is set. All settings set to `<crawler...>` or `HttpCrawlerConfig` in Java apply only to the associated crawler. 

* It applies to all websites defined for a single crawler. More explanation on `maxDocuments` from the configuration documentation:
> Stop crawling after that many references were processed. A processed reference is one that was read from the crawler queue in an attempt to fetch its corresponding document, whether that attempt was successful or not. For additional control on stopping the crawler after a certain number of events, have a look at com.norconex.collector.core.crawler.event.impl.StopCrawlerOnMaxEventListener

**Comment by naoxide95** [comment]
thank you
