### ISSUE TITLE
Crawl data storage in mongodb with http-collector v3 issue

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#766]
```
<dataStoreEngine
      class="com.norconex.collector.core.store.impl.mongodb.MongoDataStoreEngine">
      <connectionString>mongodb://127.0.0.1:27017</connectionString>
</dataStoreEngine>
```
 INFO  connection - Opened connection [connectionId{localValue:4, serverValue:57}] to 127.0.0.1:27017

Then crawler hangs on that. 1 document stored in queued table.

**Comment by essiembre** [comment]
I was able to reproduce.  Working on a fix.

**Comment by essiembre** [comment]
I made a new snapshot release that fixes this issue and a few other data store glitches discovered along the way.  Try it and please confirm.

**Comment by OkkeKlein** [comment]
Tested and MongoDB now has rows of references. Thank you and feel free to close issue
