### ISSUE TITLE
Forms Authentication v3.x

### ISSUE THREAD

**Issue by dtcyad1** [Norconex/collector-http#768]
Hi Pascal,

This is more a question than an issue.

How do we do forms authentication in version 3.x? Do you have any config samples you can share? Is it possible to extend the httpfetcher to do custom authentication?

Thanks

**Comment by essiembre** [comment]
Have a look at [GenericHttpFetcher](https://opensource.norconex.com/collectors/http/v3/apidocs/com/norconex/collector/http/fetch/impl/GenericHttpFetcher.html#nx-xml-usage-heading) which contains a usage sample.

You can extend it if you need more options (even create a PR!).  If your authentication requires several interactions, you can also have a look at the [WebDriverHttpFetcher](https://opensource.norconex.com/collectors/http/v3/apidocs/com/norconex/collector/http/fetch/impl/WebDriverHttpFetcher.html#nx-xml-usage-heading) for something closer to a real browser-based login.
