### ISSUE TITLE
[http-collector 3.0.0-RC1] [MongoDataStoreEngine] Collection name for storetypes is too long

### ISSUE THREAD

**Issue by sylvainroussy** [Norconex/collector-http#769]
Hi!
After overriding class _CrawlDocInfoService_ to customize the collections names with UUID suffix (we have one database per tenant and many differents cralers for each database), the _MongoDataStoreEngine_ throws the following Exception:

```
Command failed with error 73 (InvalidNamespace): 'fully qualified namespace 6d1e7e9a-853f-4c3c-9f4d-a9b93ee49454_95_4_95_1.com.norconex.collector.core.store.impl.mongodb.MongoDataStoreEngine--storetypes is too long (max is 120 bytes)' on server 10.10.30.13:27017.
```

Facing to this issue, I have to override MongoDataStoreEngine but here again my custom MongoDataStoreEngine needs to put on package _com.norconex.collector.core.store.impl.mongodb_ because MongoDataStore has no public methods (idFilter() for example) and it isn't a good way for me (because my custom classes are a part of my project, not norconex project).

This is an info, because I can place workarounds, but I think it's not a good way to deal with future Norconex updates...

**Comment by essiembre** [comment]
Hello Sylvain!

I am not sure I understand the problem you are trying to solve. 

With v3, the MongoDataStoreEngine already creates one 1 Mongo database for each crawler using the collector id and crawler id.  So, as long as your collector ids and crawler ids are unique (as they should), there won't be any overlap and you do not need the UUID prefix.  

Or are you saying you do NOT want 1 db-per crawler, but rather all crawlers sharing the same DB for a tenant? If this is what you're doing, the "--storetypes" collection should be sharable as it only contains a mapping between collection names and the java class they represent (i.e., no need to prefix).

**Comment by essiembre** [comment]
You may want to try the latest snapshot release that was just made.  The MongoDataStoreEngine collection used to store the types is now `MongoDataStoreEngine--storetypes` (significantly shorter).

**Comment by sylvainroussy** [comment]
Hello Pascal!
It is OK for me for storetypes collection.
Thanks.
