### ISSUE TITLE
Recrawling and checksums

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#77]
Does the crawler only look at HttpMetadataChecksummer or also the documentChecksummer to decide whether to redownload pages?

A combination of content and modified date would give better indication whether redownload is needed in my use case.

**Comment by essiembre** [comment]
It does both.  It checks the Last-Modified date in the HTTP header before downloading the document.   If the doc has changed or if no Last-Modified was present, it downloads it and at a later point, will performs a content checksum.

**Comment by OkkeKlein** [comment]
I am using a lot of titles and other meta data from referrers. If those change, the link that is being referred to is not redownloaded, because it's Last-Modified didn't change. A checksum (MD5) built from multiple tag values would change that.

**Comment by essiembre** [comment]
I am marking this issue as a feature request for this: **being able to specify multiple fields at once for checksum creation**.  
In the meantime you can accomplish the same behavior by relying on the document checkummer, after merging the fields you want yourself.  An example:

```xml
<crawler id="MyCrawler">
...
<importer>
  <postParseHandlers>
    <tagger class="com.norconex.importer.handler.tagger.impl.CopyTagger">
      <copy fromField="Last-Modified" toField="combinedValues" overwrite="false" />
      <copy fromField="AnotherField" toField="combinedValues" overwrite="false" />
    </tagger>
    <tagger class="com.norconex.importer.handler.tagger.impl.ForceSingleValueTagger">
      <singleValue field="combinedValues" />
    </tagger>
  </postParseHandlers>
</importer>
<documentChecksummer class="com.norconex.collector.core.checksum.impl.MD5DocumentChecksummer"
    sourceField="combinedValues" />
...
</crawler>
```

As an alternative, you can create your own Metadata Checksummer by extending [AbstractMetadataChecksummer](http://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/checksum/AbstractMetadataChecksummer.html).

**Comment by OkkeKlein** [comment]
Nice flexible solution. 

Now my next issue:
Just finished crawl. DId a recrawl and because the starting urls had not changed it ended after processing these 2 urls. It didn't process the 4000 urls in the MongoDB. Starting crawl again with same result and all URL info dropped from the DB cache.

Or should I have used -resume option?

**Comment by OkkeKlein** [comment]
Nice solution.

Trying to recrawl, the starting URL is rejected because of not modified, which is fine, but all the other links in the MongoDB are not checked if they were modified. The crawler just ends.

Tested both with -start and -resume in http collector  2.1.0

**Comment by essiembre** [comment]
Is this happening for you only with the Mongo implementation?   Looks like a bug to me.  Since this mongo issue is not related to your original question, can you respond by opening a new issue?  Thanks.

**Comment by OkkeKlein** [comment]
Can not reproduce, so closing the issue.

**Comment by essiembre** [comment]
Let's keep it open until the feature-request gets implemented (i.e. "specify multiple fields at once for checksum creation").

**Comment by essiembre** [comment]
**metadataChecksummer:**
There is now a new class for specifying multiple fields for a meta data checksum: [GenericMetadataChecksummer](http://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/checksum/impl/GenericMetadataChecksummer.html).

**documentChecksummer:**
[MD5DocumentChecksummer](http://www.norconex.com/collectors/collector-core/latest/apidocs/com/norconex/collector/core/checksum/impl/MD5DocumentChecksummer.html) was modified to accept multiple fields for a checksum.

Those are in the [2.2.0](http://www.norconex.com/collectors/collector-http/download) official release.
