### ISSUE TITLE
Where can I find the documentation on how to replace logging with a different implementation?

### ISSUE THREAD

**Issue by essiembre** [Norconex/collector-http#775]
> The upcoming version 3 of the HTTP Collector uses Log4j 2 by default but it uses the patched release. Also, you can replace logging with a different implementation.

Hi! Where can I find the documentation on how to replace logging with a different implementation?
Thanks!

_Originally posted by @stfnwp in https://github.com/Norconex/collector-http/issues/771#issuecomment-1016261887_

**Comment by essiembre** [comment]
@stfnwp, version 3 uses [SLF4J](https://www.slf4j.org) which is an abstraction over your favoring logging framework.  The logging implementation used id bound at runtime, which allows you to swap them.   To use a different logging implementation, go in your installation `lib` directory and replace all log4j jars files with the jars for the logging implementation you want.

Here are the steps involved:

1. Remove/backup the `log4j2.xml` file.
2. Remove/backup the following files from the `lib` folder (replace * with the version you currently have, likely `2.17.1`):
    * log4j-api-*.jar
    * log4j-core-*.jar
    * log4j-slf4j-impl-*.jar
3. Add the logging libraries (the required jars published by the logging implementation of choice) to the `lib` folder.
4. Add the SLF4J binding jar matching your new logging implementation, those are described in [SLF4J user manual](https://www.slf4j.org/manual.html#swapping).
5. Refer to your logging implementation documentation for how you configure the logging.  You will likely need a file equivalent to the `log4j2.xml` but specific to your logging implementation.

If you are a coder and want to change them at build time, you would have to change the bindings in the project `pom.xml`.

**Comment by stfnwp** [comment]
Thank you for this detailed explanation. Finally I managed to get logging to work. Issue solved.

**Comment by essiembre** [comment]
Glad to hear!
