### ISSUE TITLE
How to preserve the hash symbol in the URL while indexing a document

### ISSUE THREAD

**Issue by caoyang1211** [Norconex/collector-http#780]
I am trying to index the URL https://www.cancer.gov/types/ovarian/patient/ovarian-germ-cell-treatment-pdq#_106. It ends up indexing the whole page, and the string "#_106" is removed from the URL in the search results. Is there any way I can preserve the hash tag so that users can be linked to the specific section of the page when they click the search result? I tried setting `<canonicalLinkDetector ignore="true" />` but it doesn't help. Thanks!

**Comment by essiembre** [comment]
The `#` are removed by default by the [GenericURLNormalizer](https://opensource.norconex.com/crawlers/web/v3/apidocs/com/norconex/collector/http/url/impl/GenericURLNormalizer.html#nx-xml-usage-heading).  Here is an example to put in under the crawler section that will apply the same URL normalization defaults, except for no longer removing the hashtag:

```xml
<urlNormalizer class="GenericURLNormalizer">
  <normalizations>
    lowerCaseSchemeHost, upperCaseEscapeSequence,
    decodeUnreservedCharacters, removeDefaultPort,
    encodeNonURICharacters
  </normalizations>
</urlNormalizer>
```

**Comment by caoyang1211** [comment]
Got it . Thanks a lot Pascal!
