### ISSUE TITLE
[Collector] Sometimes ConcurrentModificationException in collector execution

### ISSUE THREAD

**Issue by sylvainroussy** [Norconex/collector-http#781]
No urgency for right now,
Sometimes (when finishing it seems) an exception occured:
```

java.util.ConcurrentModificationException: null

 at java.base/java.util.ArrayList.forEach(ArrayList.java:1543)

 at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)

 at com.norconex.collector.core.Collector.start(Collector.java:193)
```
Line 193 in the collector class (but the execution works well!)

```
if (crawlers.size() == 1) {
                // no concurrent crawlers, just start
                crawlers.forEach(Crawler::start); //=> line 193
 }
```

**Comment by essiembre** [comment]
Strange. I have not experienced this yet.  Did you figure out a way to reproduce consistently?

**Comment by essiembre** [comment]
@sylvainroussy, I made a 3.0.1-SNAPSHOT release that attempts to fix this concurrency issue when the crawler ends.  Let me know if it fixes it for you.

**Comment by sylvainroussy** [comment]
Hi Pascal! An thank you for the snapshot. I will try it. But no, no way to repreduce it. It produces sometimes, I looked for the cause, but I found nothing (a bit of time of investigation only). Weird. 
I'm closing this issue for now.
