### ISSUE TITLE
Relative URLs Not being correctly resolved

### ISSUE THREAD

**Issue by sylvainroussy** [Norconex/collector-http#788]
Hello!

From this start URL :
https://eur-lex.europa.eu/search.html?textScope0=ti&lang=en&SUBDOM_INIT=ALL_ALL&DTS_DOM=ALL&type=advanced&DTS_SUBDOM=ALL_ALL&qid=1653030108454&andText0=plastic%3F&sortOne=DD&sortOneOrder=desc

We are not be able to download relatives URLs like (for PDF docs) : 
CrawlerEvent.REJECTED_FILTER - ./legal-content/EN/TXT/HTML/?uri=CELEX:32021D1752 - No "include" reference filters matched.  

With this pattern filter pattern : https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=.*

Of course removeDotSegments normalizer is used.

Something is bad here ?
Thanks.

**Comment by UtsavVanodiya7** [comment]
Make sure regex is correct and regex characters like '?' are escaped. 
^https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/**\?**uri=.*

**Comment by essiembre** [comment]
Bonjour Sylvain,

Have you resolved your issue?  Else can you share a config to reproduce?  

Maybe: make sure your start URL is not excluded from your filter rule.

**Comment by sylvainroussy** [comment]
Hi Pascal,

The real pattern is : **https://eur-lex\.europa\.eu/legal-content/EN/TXT/PDF/\?uri=.***
(we have a simplified form for users, transformed to real regex expression)
And this pattern match the following url : **https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:52022M10723**
(checked on https://www.freeformatter.com/java-regex-tester.html)

What is strange it seems not all the urls are rebuilt in complete form, some examples :

1) ./legal-content/AUTO/?uri=CELEX:72019L0904IRL_202202086&qid=1653030108454&rid=2
2) https://eur-lex.europa.eu/./images/n/eurlex-logo.jpg
3)  https://eur-lex.europa.eu/./browse/institutions/auditors.html

Source code for the point 1:
<a id="cellar_e00cf74f-b3f8-11ec-9d96-01aa75ed71a1" href="./legal-content/AUTO/?uri=CELEX:72019L0904IRL_202202086&amp;qid=1653030108454&amp;rid=2" class="title" name="https://eur-lex.europa.eu/legal-content/AUTO/?uri=CELEX:72019L0904IRL_202202086">European Union (Single Use Plastics) (Amendment) Regulations 2022</a>

Source code for the point 3:
<img class="pdf-logo-img" src="./images/n/eurlex-logo.jpg" alt="Back to EUR-Lex homepage" />

Source code for the point 4:
 <li class=""><a href="./browse/institutions/auditors.html" id="Court-of-Auditors" title="European Court of Auditors">European Court of Auditors</a></li>

Strange beahviour, isn't it?

As you know it's difficult to provide you a complete configuration because the configuration is directly Java coded.

**Comment by essiembre** [comment]
I was able to reproduce and I'll investigate the issue.

FYI, you can share your config using code as well:

```java
XML xml = new XML("collector");
myCollectorInstance.getCollectorConfig().saveToXML(xml);
String printOrSaveThisString= xml.toString(2);
```

It is the equivalent of generating it on the command line with the command `configrender`.

**Comment by essiembre** [comment]
The issue was a mishandling of the colon in your URL.  I made a new snapshot release with a fix.  Please confirm.

**Comment by sylvainroussy** [comment]
It works ! Thank you very much. Closing.
