### ISSUE TITLE
Web Crawler 3.0: how to programmatically add a ConstantHandler to ImporterConfig

### ISSUE THREAD

**Issue by ciroppina** [Norconex/collector-http#793]
Hi, in my Collector-Http 2.9.0 Java code I used to add a new Constant tag this way:
```
ImporterConfig importerConfig = crawlerCfg.getImporterConfig();
List<IImporterHandler> handlers = importerConfig.getPostParseHandlers();
for (IImporterHandler tagger : handlers) {
	if (tagger.getClass().getName().equals(ConstantTagger.class.getName())) {
		ConstantTagger cTagger= (ConstantTagger)tagger;
		cTagger.addConstant("Authorization", 
			"HCP "+ t.getUsr().trim()+":" +t.getPwd().trim()
		);
	}
}

```
But now method **getPostParseHandlers()** is Deprecated in favour of the new **getPostParseConsumer()**. How to use this new method return type to add a constant tag (name/value)?
thank You

**Comment by essiembre** [comment]
With version 3, handlers are no longer restricted to just a list. They can be part of a "flow" hierarchy or be any implementation of `Consumer<HandlerContext>`.  While it adds configuration possibilities, it does make it a bit trickier to get your tagger the way you want.  Luckily, there are a few ways to do so.

If you are modifying an entry initially loaded from a simple XML (e.g., not using XML flow conditions), then we know what we are dealing with (a `List` of known types), and this would be one way to do it:

```java
        ((List<?>) importerConfig.getPostParseConsumer()).stream()
            .map(HandlerConsumer.class::cast)
            .map(HandlerConsumer::getHandler)
            .filter(ConstantTagger.class::isInstance)
            .map(ConstantTagger.class::cast)
            .findFirst()
            .ifPresent(tagger -> tagger.addConstant("Authorization", "..."));
```

Another approach that will work with more complex configurations is to use reflection this way:

```java
        Consumer<?> handlers = importerConfig.getPostParseConsumer();
        BeanUtil
            .find(new MutableObject<>(handlers), ConstantTagger.class)
            .stream()
            .findFirst()
            .ifPresent(tagger -> tagger.addConstant("Authorization", "..."));
```

Precision on some imports: 

```java
import com.norconex.commons.lang.bean.BeanUtil;
import org.apache.commons.lang3.mutable.MutableObject;
```


Let me know if that works for you.
