### ISSUE TITLE
Web Crawler 3.0: LinkExtractor respects only the first attribute per tag

### ISSUE THREAD

**Issue by adesso-thomas-lippitsch** [Norconex/collector-http#798]
Hi,

the linkExtractor seems to respect only the first attribute of a tag:
```XML
<linkExtractors>
    <extractor class="HtmlLinkExtractor">
        <tags>
            <tag name="a" attribute="data-href" />
            <tag name="a" attribute="href" />
        </tags>
    </extractor>
</linkExtractors>
```
In the example above it extracts URLs in data-href only. If there is an href in the same tag as well, it is ignored.

Is this the expected behavior?
I would have expected that it looks in both attributes for URLs.

Sincerely,
Tom

**Comment by essiembre** [comment]
I cannot reproduce.  Can you share both your config and a sample document?

I ran a test on a sample HTML with these two links:

```html
 <a data-href="data-href1.html" href="just-href1.html">two hrefs #1</a>
 <a href="just-href2.html" data-href="data-href2.html">two hrefs #2</a>
```

Then, printing the links + attributes obtained for each using the HtmlLinkExtractor, I got this:

```
http://www.example.com/just-href1.html
    attr.data-href --> [data-href1.html]
    tag --> [a]
    text --> [two hrefs #1]
    attr --> [href]
```

```
http://www.example.com/just-href2.html
    attr.data-href --> [data-href2.html]
    tag --> [a]
    text --> [two hrefs #2]
    attr --> [href]
```

It picked only the `href`, as expected.
