### ISSUE TITLE
Use xpdf to parse PDFs

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#80]
Xpdf parses PDF content better then PDFBox or other parsers (at least in my experience). Might be nice to add this as an option.

**Comment by essiembre** [comment]
Have you experienced PDF parsing issues with HTTP Collector 2.1.0?

Lots of testing was done on PDFs in that version.  The PDFBox library was upgraded to 2.0.0, a version still in development but already significantly better than their previous version.  Also, custom code was added to enhance the PDF parsing to also include XFA (dynamic forms) and support for embedded JBIG2 and jpeg2000 images.  It has also been tested to work fine with OCR of embedded images of supported formats.

If you experience PDF parsing issues, please report them [here](https://github.com/Norconex/importer/issues) and we'll certainly consider an alternative parser if we can't provide easy fixes.

**Comment by OkkeKlein** [comment]
Last extensive test was a few years ago, so maybe PDFbox has caught up in the mean time. If I run into issues I will report them in the importer issue tracker.

**Comment by essiembre** [comment]
Thanks!
