### ISSUE TITLE
stoping problem

### ISSUE THREAD

**Issue by andres-182** [Norconex/collector-http#805]
Hi!
I’m a user of Norconex V2…. but when I try to use Norconex V3 it has a problem trying to stop a configuration, the error displayed was…
![imagen](https://user-images.githubusercontent.com/115369457/208708462-289636f8-fa10-4542-99f6-61d80e057f64.png)

And the command that I was using was 'sh collector-http.sh stop -config=examples/config_example.xml', when I use this command with 'start' works.
Can you help me with this problem?
Thanks a lot for your time,
Regards.

**Comment by essiembre** [comment]
In case it is related, can you replace the deprecated class with the new one?  If you still have the issue after this, can you share your config?
