### ISSUE TITLE
Feature request for MapDB/ crawled data

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#81]
One of the database systems that HTTP Collector uses to store information about crawled documents is MapDB. It seems that when HTTP Collector upgrades MapDB to a new version, the existing crawled data is not longer accessible, getting the error: `storage has invalid header`. So, suddenly, HTTP Collector can't access its crawled data so the crawling system doesn't work anymore.

The first feature request for HTTP Collector is to implement a function that upgrades the existing crawled data to the new MapDB version, so HTTP Collector can keep working with its crawled data.

Furthermore, since it is expected that the crawling system based on HTTP Collector will evolve and need more resources, presumably will need to use any of the other databases systems that HTTP Collector supports.

The second feature request  for HTTP Collector is to implement a function that migrates the existing crawled data from one database system to another (among the database systems supported by HTTP Collector) so HTTP Collector can keep working with its crawled data.

**Comment by essiembre** [comment]
This has been implemented in version 3.  While MapDB is no longer used, you can now export the storage engine content in a neutral format and re-import it in the same or another storage engine (e.g., from MVStore to MongoDB, or to JDBC database).

Sample usage (Linux):

```
collector-http.sh storeexport -config=/path/to/collector-config.xml
```
