### ISSUE TITLE
Drop documents after parsing

### ISSUE THREAD

**Issue by giannisni** [Norconex/collector-http#811]
Hello, I would like to drop and dont commit documents that after the parsing and processing, do not contain one specific field.
My case is that Im scraping news websites and I want to drop documents that do not contain a date field in the end, after my handlers.

**Comment by giannisni** [comment]
Thank you for your answer.
as I understand this is deprecated?

But also I need this filter to be applied after my post parse handlers. 
I think that is not possible

**Comment by essiembre** [comment]
Why deprecated? I do not see any deprecation notice in the JavaDoc link shared by @ohtwadi. 

You can do it in post-parse, yes.   If all you care about is whether a value is there or not, there is also [EmptyFilter](https://opensource.norconex.com/importer/v3/apidocs/com/norconex/importer/handler/filter/impl/EmptyFilter.html):

```xml
<handler class="EmptyFilter" onMatch="include">
  <fieldMatcher method="regex">
    YOUR_EXPRESSION_HERE
  </fieldMatcher>
</handler>
```
