### ISSUE TITLE
Norconex v3.0.1 and Selenium

### ISSUE THREAD

**Issue by cjurewicz** [Norconex/collector-http#813]
Hello! I am somewhat new to Norconex v3. We have been using version 2.9 for the last year or so. We decided that we should upgrade to version 3 so that we can take advantage of the WebDriver facility provided by Selenium. I have successfully accomplished the migration, and now  I would like to take advantage of this new feature. The websites that we are crawling are on our intranet and are increasingly relying on json driven data tables, and the ability to render the javascript pages for crawling is exactly what we need. 

I have been looking all over the web trying to find an implementation example.  We are running the Norconex crawling software on a Linux box, and ideally we would like to use Microsoft Edge as our headless browser.

Any assistance with this matter would be greatly appreciated. I'm sorry if this is the wrong place for this question.

**Comment by ohtwadi** [comment]
Have you seen the docs for WebDriverHttpFetcher?
https://opensource.norconex.com/crawlers/web/v3/apidocs/com/norconex/collector/http/fetch/impl/webdriver/WebDriverHttpFetcher.html

**Comment by cjurewicz** [comment]
Thank you @ohtwadi! I should have been more explicit. I had seen this page, but I got lost in the weeds of this page and the Selenium site. On this page, there are a number of XML tags that go no further with any sort of documentation. When I look at pages like this I often go to the "XML configuration usage" example section to see an example of how to use the class. The example on this page indicated that I required a "Driver path" that is more than likely provided by Selenium.

This is where things really got sticky. On the Selenium website, there are so many different machine configurations and so many different configuration options and so many different downloadables (mostly Windows). I suspect that Selenium does not exist solely for Norconex.

So what I was hoping for was that someone had setup a Norconex V3 unix crawl using a Selenium web driver that could emulate the Wave browser, and that they could share which pieces from Selenium to download and how they had setup their Norconex configuration.

**Comment by cjurewicz** [comment]
Further to my previous comment, I have tried this. In my Norconex xml file in the <httpfetchers> section, I have coded the following <fetcher>:

	<fetcher class="com.norconex.collector.http.fetch.impl.webdriver.WebDriverHttpFetcher">
		<browser>edge</browser>
		<driverPath>/client/home/webpub/norconex-collector-http-3.0.1/edgedriver_linux64/msedgedriver</driverPath>
	</fetcher>	

The <driverPath> I have identified comes from the Selenium web site at the following URL:
https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/

I downloaded and the Edge driver from the "Quick Reference" section, and placed the unziped file onto the Linux box.

I ran the "collector-http.sh" with my Norconex xml file with the output written to a log.txt. When I did this, the following was written to the terminal:

> Starting Microsoft Edge WebDriver 114.0.1788.0 (dcfd4dcad6f7dc8d2ea38fd039ac4448f9fac805) on port 1761
> To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver
> 
> Only local connections are allowed.
> Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.
> 
> Microsoft Edge WebDriver was started successfully.
> Starting Microsoft Edge WebDriver 114.0.1788.0 (dcfd4dcad6f7dc8d2ea38fd039ac4448f9fac805) on port 7022
> To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver
> 

This was repeated 10 times probably once for each thread.

Early in the log.txt file the following line was written:

> 06:54:07.870 [PSPC crawler#1] INFO  Browser - Creating local "EdgeDriver" web driver.

Shortly after on the first thread the following large block is written to the log file:

> 06:54:08.181 [PSPC crawler#1] ERROR Crawler - Problem in thread execution.
> com.norconex.collector.core.CollectorException: Could not build web driver
>         at com.norconex.collector.http.fetch.impl.webdriver.Browser$WebDriverBuilder.build(Browser.java:237) ~[norconex-collector-http-3.0.1.jar:3.0.1]
>         at com.norconex.collector.http.fetch.impl.webdriver.Browser$WebDriverSupplier.get(Browser.java:181) ~[norconex-collector-http-3.0.1.jar:3.0.1]
>         at com.norconex.collector.http.fetch.impl.webdriver.WebDriverHolder.getDriver(WebDriverHolder.java:74) ~[norconex-collector-http-3.0.1.jar:3.0.1]
>         at com.norconex.collector.http.fetch.impl.webdriver.WebDriverHttpFetcher.fetcherThreadBegin(WebDriverHttpFetcher.java:247) ~[norconex-collector-http-3.0.1.jar:3.0.1]
>         at com.norconex.collector.http.fetch.AbstractHttpFetcher.accept(AbstractHttpFetcher.java:148) ~[norconex-collector-http-3.0.1.jar:3.0.1]
>         at com.norconex.collector.http.fetch.AbstractHttpFetcher.accept(AbstractHttpFetcher.java:82) ~[norconex-collector-http-3.0.1.jar:3.0.1]
>         at com.norconex.commons.lang.event.EventManager.doFire(EventManager.java:144) ~[norconex-commons-lang-2.0.1.jar:2.0.1]
>         at com.norconex.commons.lang.event.EventManager.fire(EventManager.java:125) ~[norconex-commons-lang-2.0.1.jar:2.0.1]
>         at com.norconex.commons.lang.event.EventManager.fire(EventManager.java:119) ~[norconex-commons-lang-2.0.1.jar:2.0.1]
>         at com.norconex.collector.core.crawler.Crawler$ProcessReferencesRunnable.run(Crawler.java:917) [norconex-collector-core-2.0.1.jar:2.0.1]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_362]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_362]
>         at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
> Caused by: java.lang.reflect.InvocationTargetException
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_362]
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_362]
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_362]
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_362]
>         at org.apache.commons.lang3.reflect.ConstructorUtils.invokeExactConstructor(ConstructorUtils.java:181) ~[commons-lang3-3.12.0.jar:3.12.0]
>         at org.apache.commons.lang3.reflect.ConstructorUtils.invokeExactConstructor(ConstructorUtils.java:148) ~[commons-lang3-3.12.0.jar:3.12.0]
>         at com.norconex.collector.http.fetch.impl.webdriver.Browser$WebDriverBuilder.lambda$build$0(Browser.java:232) ~[norconex-collector-http-3.0.1.jar:3.0.1]
>         at com.norconex.commons.lang.SystemUtil.callWithProperty(SystemUtil.java:118) ~[norconex-commons-lang-2.0.1.jar:2.0.1]
>         at com.norconex.collector.http.fetch.impl.webdriver.Browser$WebDriverBuilder.build(Browser.java:222) ~[norconex-collector-http-3.0.1.jar:3.0.1]
>         ... 12 more
> Caused by: org.openqa.selenium.WebDriverException: unknown error: cannot find msedge binary
> Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
> System info: host: 'vapl-tamely', ip: '10.2.4.105', os.name: 'Linux', os.arch: 'amd64', os.version: '4.18.0-425.19.2.el8_7.x86_64', java.version: '1.8.0_362'
> Driver info: driver.version: EdgeDriver
> remote stacktrace: #0 0x560fea0c7003 <unknown>
> #1 0x560fe9dd05f1 <unknown>
> #2 0x560fe9dfa6ed <unknown>
> 

Any thoughts?

**Comment by essiembre** [comment]
Hello @cjurewicz.  

A WebDriver has two external dependencies: a browser and a driver for that browser.

The WebDriver you are using may attempt to detect these two dependencies if they are in the locations it expects (see web driver documentation).  To make sure it has what it needs without relying on detection, you can specify them both with:

```xml
  <browserPath>(in your case, the full path to Edge, including file extension)</browserPath>
  <driverPath>(the full path to webdriver exe, including file extension)</driverPath>
```

By being explicit on those paths should get rid of the error.  

That being said, I find the Edge one is the one that had the most issues matching all desired features last time I tried. Your mileage can vary, but if you run into several issues that seem Edge-specific, I would recommend you try with Chrome or Firefox.

**Comment by cjurewicz** [comment]
Thanks @essiembre for your feedback. I will try connecting to the Firefox browser.

**Comment by cjurewicz** [comment]
So I now have a Firefox browser on my Linux box. If I run the following command "firefox -v" I get

Mozilla Firefox 102.9.0esr

I have the xml file setup with the following "fetcher"

> 
> <fetcher class="com.norconex.collector.http.fetch.impl.webdriver.WebDriverHttpFetcher">
> 		<browser>firefox</browser>
> 		<browserPath>/usr/bin/firefox</browserPath>
> 		<driverPath>/client/home/webpub/norconex-collector-http-3.0.1/firefoxdriver_linux64/geckodriver</driverPath>
> </fetcher>
> 

When I run the following command: "collector-http.sh start -config=pspc.xml"
 I get the following output on my terminal (repeats 10 times for each thread):

> 1683220858956   geckodriver     INFO    Listening on 127.0.0.1:27082
> 1683220859155   mozrunner::runner       INFO    Running command: MOZ_CRASHREPORTER="1" MOZ_CRASHREPORTER_NO_REPORT="1" MOZ_CRASHREPORTER_SHUTDOWN="1" MOZ_NO_REMOTE="1" "/usr/bin/firefox" "--marionette" "-headless" "-no-remote" "-profile" "/tmp/rust_mozprofileZNJbZp"
> *** You are running in headless mode.
> Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.689617) [GFX1-]: glxtest: Unable to open a connection to the X server
> Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.689617) |[1][GFX1-]: glxtest: libEGL initialize failed (t=0.689653) [GFX1-]: glxtest: libEGL initialize failed
> 1683220859868   Marionette      INFO    Marionette enabled
> 1683220859872   Marionette      INFO    Listening on port 36785
> Read port: 36785
> 1683220860065   RemoteAgent     WARN    TLS certificate errors will be ignored for this session
> Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.689617) |[1][GFX1-]: glxtest: libEGL initialize failed (t=0.689653) |[2][GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt (t=1.37896) [GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
> console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /tmp/rust_mozprofileZNJbZp/search.json.mozlz4", (void 0)))
> Missing chrome or resource URL: resource://gre/modules/UpdateListener.jsm
> Missing chrome or resource URL: resource://gre/modules/UpdateListener.sys.mjs
> May 04, 2023 1:21:01 PM org.openqa.selenium.remote.ProtocolHandshake createSession
> INFO: Detected dialect: W3C

Which is sort of good because Firefox acknowledges that it is running in headless mode. Unfortunately, it's having trouble talking to an "X server". This seems to be some sort of graphics server. My system admin does not seem to know what that means (need new system admin?)

Also if I run the following command outside of the collector, I get a similar issue. "firefox -headless"

> *** You are running in headless mode.
> Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.242981) [GFX1-]: glxtest: Unable to open a connection to the X server
> Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.242981) |[1][GFX1-]: glxtest: libEGL initialize failed (t=0.243011) [GFX1-]: glxtest: libEGL initialize failed
> Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.242981) |[1][GFX1-]: glxtest: libEGL initialize failed (t=0.243011) |[2][GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt (t=0.844225) [GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
> Missing chrome or resource URL: resource://gre/modules/UpdateListener.jsm
> Missing chrome or resource URL: resource://gre/modules/UpdateListener.sys.mjs
> Exiting due to channel error.
> 

So I'm thinking this is a Firefox headless configuration issue. Does anyone know how I can advise my sys admin?
