### ISSUE TITLE
collector v.3: Any way to get a list of all extractet Urls? 

### ISSUE THREAD

**Issue by phpsyscoder** [Norconex/collector-http#817]
Hi there,
is there any way to get a list of all extractet Urls (`URLS_EXTRACTED`) after crawling finished?  
Even URLs that have been filtered out or disallowed to crawl.

Thank you very much

**Comment by essiembre** [comment]
Hello @petrich, There are a few ways depending on what you'd like to achieve and how "hands-on" you want to get.

The easiest is to use [URLStatusCrawlerEventListener](https://opensource.norconex.com/crawlers/web/v3/apidocs/com/norconex/collector/http/crawler/event/impl/URLStatusCrawlerEventListener.html) under the `<eventListeners>` section of your crawler config. You will get a report of all URLs the crawler attempted to fetch, optionally filtered by HTTP status codes.

That won't give you those filtered out before a fetch attempt, though.  If you are interested in those as well, have a look at the `<keepReferencedLinks>` option of [HttpCrawlerConfig](https://opensource.norconex.com/crawlers/web/v3/apidocs/com/norconex/collector/http/crawler/HttpCrawlerConfig.html).  That will store with each document all URLs that were extracted.  It should do exactly what you are after, keeping the relation between URLs and documents containing them as a bonus.

However, the latter solution will not create a list of all unique URLs encountered as a file report.  To get such a list, you'll have to query your target repository to build it, or create a crawler event listener (Java) and listen for the `URLS_EXTRACTED` event. The event object will contain somewhere all URLs for the corresponding document.  You can do what you want with those at that point.
