### ISSUE TITLE
elasticsearch commiter queue

### ISSUE THREAD

**Issue by giannisni** [Norconex/collector-http#818]
Hello, I am crawling news websites and indexing them to elasticsearch with the commiter. I noticed that there are a lot stuck in the commiter queue and the directory is almost 30 gbs for one month of crawling. Why this happens? Elasticsearch is indexing succesfuly many documents, my index has almost 1.5 million documents. 
How can I know if those documents in the queue are dumped or just failed to commit and stuck there? Can I configure the commiter so that this doesnt happen so often?

Thank you

**Comment by essiembre** [comment]
Which version of the HTTP Collector and the Elasticsearch committer are you using?   Do you have errors in the HTTP Collector logs and/or Elasticsearch logs?  

With HTTP Collector V3.x, it should store documents or document batches in an error folder.  If you use an older version, faulty documents/batches may remain there and fail every time they are retried.

One thing you can do is confirm what type of errors you get.  If you know your data reaches the search engine and things are good on that front, you can manually delete the queue between runs, if anything remains.

**Comment by giannisni** [comment]
I am using http collection 3.0.1 and elasticsearch commiter 5.0.0. There are 2 folders error,queue.  The error folder holds most of the documents in zip files but i dont know which error exactly causes the problem. The zip files contain only content,metadata and reference files.
Also I just realized I cant find any logs or progress folder. My http collector configurations have:

    <logsDir>./logs</logsDir>
    <progressDir>./progress</progressDir>
    
Thank you

**Comment by essiembre** [comment]
You should definitely get logs.  By default, they are sent to STDOUT if not mistaken.  You can change the log4j2.xml file to send to a file, or even simpler maybe, you can redirect the output to a file. E.g.:

```
collector-http.sh > somefile.log
```
