### ISSUE TITLE
referrerLinkTag is the same as referrerLinkText

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#82]
In MongoDB these 2 values are always the same. Both in custom extractor as with HtmlLinkExtractor.

```
"referrerLinkTag": "a.href",
"referrerLinkText": "a.href",
```

**Comment by essiembre** [comment]
Fixed in code.  Will be in next (snapshot) release.

**Comment by OkkeKlein** [comment]
Can confirm that it works.

**Comment by essiembre** [comment]
Fix can be found in latest [2.2.0 snapshot release](http://www.norconex.com/collectors/collector-http/download).

**Comment by essiembre** [comment]
Norconex HTTP Collector 2.2.0 official release is out. It includes this fix. You can download it [here](http://www.norconex.com/collectors/collector-http/download).
