### ISSUE TITLE
Migration guide from version 2.9.1 to 3.0.1

### ISSUE THREAD

**Issue by du-it** [Norconex/collector-http#823]
I wonder if there is any other migration guide unless [Migrate to version 3](https://opensource.norconex.com/crawlers/web/v3/migration)? I couldn't figure out how to migrate this from version 2.9.1 to version 3.0.1:

```
HttpCollectorConfig
    .setLogsUnmanaged(true);
    .setProgressDir(COLLECTOR_PROGRESS_DIR);
```

```
HttpCrawlerConfig
    .setUserAgent(USER_AGENT);
    .setWorkDir(new File(getPath(CRAWLER_WORK_DIR, website)));
    .setMetadataFetcher(DEFAULT_METADATA_FETCHER);
    .setSitemapResolverFactory(aGenericSitemapResolver);
    .setHttpClientFactory(basicAuth(auth.getUsername(), auth.getPassword()));
```

**Comment by ohtwadi** [comment]
This might help. 
https://opensource.norconex.com/docs/crawlers/web/getting-started.html#java-usage

**Comment by essiembre** [comment]
Most of the items on your list are covered in the migration guide you mentionned. In any case, let me dive into each with a bit more details:

* `HttpCollectorConfig`
  * `.setLogsUnmanaged(true);`
    Gone. Logs are no longer managed by the HTTP Collector. Out-of-the-box, it now ships with Log4j 2 and outputs to STDOUT. You can change the Log4j logging options by modifying the `log4j2.xml`. Checkout [Log4j configuration options](https://logging.apache.org/log4j/2.x/manual/configuration.html).
  * `.setProgressDir(COLLECTOR_PROGRESS_DIR);`
    Gone. Progess is no longer kept in files. If it is important for you to monitor progress, the crawler exposes a lot of statistical data via [JMX](https://docs.oracle.com/javase/8/docs/technotes/guides/jmx/index.html).  You can use a tool such as [Prometheus](https://prometheus.io) and its [JMX Exporter](https://github.com/prometheus/jmx_exporter) to process crawl data in real time and present the information the best way you see fit.
* `HttpCrawlerConfig`
  * `.setUserAgent(USER_AGENT);`
    This is now specific to each HTTP Fetcher implementation.  You can set it via  [GenericHttpFetcher](https://opensource.norconex.com/crawlers/web/v3/apidocs/com/norconex/collector/http/fetch/impl/GenericHttpFetcher.html).
  * `.setWorkDir(new File(getPath(CRAWLER_WORK_DIR, website)));`
    Setting the working directory is now done at the collector level. See `HttpCollectorConfig#setWorkDir`. A subdirectory for each crawler defined will automatically be created using the crawler id you created.
  * `.setMetadataFetcher(DEFAULT_METADATA_FETCHER);`
    The same configured fetchers are now used for metadata and document fetching (HTTP HEAD vs GET). You can configure when you want those fetched by with the <a href="https://opensource.norconex.com/crawlers/web/v3/apidocs/com/norconex/collector/http/crawler/HttpCrawlerConfig.html" title="Link to HttpCrawlerConfig class documentation">HttpCrawlerConfig</a>. Look for the `setFetchHttpGet` and `setFetchHttpGet` methods and class documentation for available options.
  * `.setSitemapResolverFactory(aGenericSitemapResolver);`
    This one is still there, renamed to `setSitemapResolver`.
  * `.setHttpClientFactory(basicAuth(auth.getUsername(), auth.getPassword()));`
    The `HttpClientFactory` has been merged with fetchers.  So configuratation options are available there, for instance on `GenericHttpFetcher`.

Hopefully, this will get you further.

**Comment by du-it** [comment]
Thank you for providing me with those details. 
The last things I currently struggle with are: 

```
ElasticSearchCommitter committer = new ElasticSearchCommitter();
committer.setQueueDir(queueDir); 
```

and 

```
ImporterConfig importerConfig = new ImporterConfig();
        importerConfig.setPreParseHandlers(getPreParseHandlers(website));
        importerConfig.setPostParseHandlers(getPostParseHandlers());
```

Viewing the setXxxParseHandlers(...) methods I can see that they are marked as deprecated, but the @Deprecated annotation seems not to be used as recommended to by [How and When to Deprecate APIs](https://docs.oracle.com/javase/8/docs/technotes/guides/javadoc/deprecation/deprecation.html#how) since there is no information about what class/method to use instead.

**Comment by essiembre** [comment]
The working directories are now derived from the main one specified at the collector level and committers are now "numbered" folders.  They are no longer manually set.  This avoids path collisions when having multiple crawlers.

For adding handlers programmatically, you are correct it is the `setPreParseConsumer(...)` (or postParse).  Refer to the [setPreParseConsumer JavaDoc](https://opensource.norconex.com/importer/v3/apidocs/com/norconex/importer/ImporterConfig.html#setPreParseConsumer-java.util.function.Consumer-) for tips to add handlers one by one instead of writing a "consumer" yourself.  E.g.: 

```java
LanguageTagger langTagger = ...
SometingElseTagger otherTagger = ...

importerConfig.setPreParseConsumer(HandlerConsumer.fromHandlers(
    langTagger,
    otherTagger
));
```

For language I am not sure what you are trying to do, but using LanguageTagger seems indeed like a good option.

**Comment by du-it** [comment]
I think the idea with the automatically numbered folders seems to be a good idea. 

I just try to update Maven dependencies in the POM, hence have to migrate existing code from 2.9.0 to 3.0.1 and I am yet not much deep in the intention of the code. The javadoc of the method says: 
```
    /**
     * Adds the content language of the HTML document to the provided field.
     */
``` 
...while `HttpHeaders.CONTENT_LANGUAGE` is "Content-language". 

Maybe it's enough to simply return a new LanguageTagger!?

A more important issue is that I thought I could simply change from 

```
    private final List<ISuiteLifeCycleListener> suiteLifeCycleListeners = new ArrayList<>();

    public void start(boolean resumeNonComplete) {
     
   collector.getCollectorConfig().setSuiteLifeCycleListeners(suiteLifeCycleListeners.toArray(ISuiteLifeCycleListener[]::new));
        collector.start(resumeNonComplete);
    }
```
to 

```
    public void start(/*boolean resumeNonComplete*/) {
        collector.getCollectorConfig().setEventListeners(
            (IEventListener[]) suiteLifeCycleListeners.toArray(ISuiteLifeCycleListener[]::new));
        collector.start(/*resumeNonComplete*/);
    }
```
    
but this results in a ClassCastException.

**Comment by essiembre** [comment]
Version 3 is a major upgrade and is, unfortunately, not a drop-in replacement.  Please read the migration guide.  It mentions `ISuiteLifeCycleListener` is deprecated, replaced with a simplified `IEventListener`.  The JEF dependency is no longer used (so no more concept of "job suites".  You can listen for events programmatically with the following instead:

```java
myCollectorConfig.addEventListeners(event -> {
    // do something with the event. E.g.:
    if ("DOCUMENT_COMMITTED_UPSERT".equals(event.getName()) {
        // ...
    }
});
```

The `HttpHeaders.CONTENT_LANGUAGE` constant is likely coming from Apache HTTP Client library and represents the language as provided in the HTTP response under its standard location for it.  All HTTP response header values are available to you, and you decide what to keep.  It is up to you whether to trust and use the language value from the response headers or use `LanguageTagger` to detect the language instead.
