### ISSUE TITLE
ExternalTransformer

### ISSUE THREAD

**Issue by giannisni** [Norconex/collector-http#845]
Hello!
I want to extract the text from news articles. Originally norconex does this and puts it to content field, but it also takes other html tags like categories, time or relative news.
My thought was to use an external library like newspaper3k using it from a python script that i call it from ExternalTransformer which then stores the text in a new field.
Is that a good practice? Please help me with configurations of ExternalTransformer as I am really confused.
I already implemented the python script that takes as input from arguments a url and extracts the text.

**Comment by ohtwadi** [comment]
You don't need to use an external library for this. The built in [KeepOnlyTagger](https://opensource.norconex.com/importer/v3/apidocs/com/norconex/importer/handler/tagger/impl/KeepOnlyTagger.html#nx-xml-usage-heading) will allow you to only keep the metadata you want, discarding everything else.

**Comment by giannisni** [comment]
Τhank you, but i meant strictly the "content" field. I need to extract only the text of an article. Content thought contains multiple more elements. For example newspaper3k or boilerpipe extract solely the article text.

**Comment by giannisni** [comment]
can you please help me how to use ExternalTransformer instead? 
I want the crawler to run a python script everytime with newspaper library in it. Norconex will pass just the document reference and the script will extract the correct content from the article. 
Then it will return the content to the crawler so to be indexed
I am really confused by the documentation
