### ISSUE TITLE
SharePoint 2016 webscraping help or example 

### ISSUE THREAD

**Issue by leonardoobay** [Norconex/collector-http#846]
I keep getting the  following error No Strict-Transport-Security (HSTS) support detected for domain "Internal Website GOES HERE ".
Im trying to scrape thru a internal sharepoint site that uses NTLM authentication and goes through a proxy is there an example on how to do this  with java?

**Comment by essiembre** [comment]
The message you refer to should show as `INFO` and not an error.  The crawler informs you the site you are crawling does not support HSTS. HSTS is an optional directive for web clients, not a requirement.

I don't have an example, but if you get errors, can you share what you've tried and the results? Attaching relevant portions of your logs with a copy of your configuration could also help.

If you are only wondering where to configure authentication, have a look at the [GenericHttpFetcher](https://opensource.norconex.com/crawlers/web/v3/apidocs/com/norconex/collector/http/fetch/impl/GenericHttpFetcher.html#nx-xml-usage-heading).  All configuration options for authentication and proxy settings are detailed there.

**Comment by leonardoobay** [comment]
here is the config file im using with blanked out url and credentials

**Comment by leonardoobay** [comment]
![crawlconfig1](https://github.com/Norconex/collector-http/assets/25556069/89a67dbe-aaf8-434d-8717-3dc70fca1043)

**Comment by leonardoobay** [comment]
![crawlconfig3](https://github.com/Norconex/collector-http/assets/25556069/58783494-5bd7-4383-b692-1b278317e573)

**Comment by leonardoobay** [comment]
![crawlconfig4](https://github.com/Norconex/collector-http/assets/25556069/8b7ed4c2-e029-445a-8e48-b9c925a7f44f)
