### ISSUE TITLE
Need to install Norconex latest using browser gcloud cli or ssh

### ISSUE THREAD

**Issue by EGWYI** [Norconex/collector-http#850]
In My project, Norconex 2.8 is used. I want to update to latest version, How can I install latest version of norconex through ssh or browser cli of gcloud.

**Comment by ohtwadi** [comment]
The Web Crawler is distributed as a self-contained zip package. It does not require any installation per se. You simply [download](https://opensource.norconex.com/crawlers/web/download), extract, and use the provided `collector-http.bat` or `collector-http.sh` scripts to launch it. To download the latest version in Linux, you may use the `scp` command.

You will be upgrading from version 2.8 to 3.0.2. Version 3 was a major release and there were breaking changes. Please take a look at the [Change Log](https://opensource.norconex.com/crawlers/web/v3/changes#v3.0.2) and upgrade your configuration(s) accordingly.

**Comment by EGWYI** [comment]
Thanks for reply @ohtwadi 
In project, I am using Norconex 2.8, need to upgrade to 3.0.2, for that I need to simply download and extract the new package from norconex officila site or is there any command which I run will do that.

If I will download and extract, then what will happen to the old version. As I am using in production, so I need clear picture of impact and cons

**Comment by ohtwadi** [comment]
>If I will download and extract, then what will happen to the old version. As I am using in production, so I need clear picture of impact and cons

I **strongly** recommend you do some testing in a non-prod environment first to understand what a fiesable upgrade process would be with in **your** environment.

The [installation page](https://opensource.norconex.com/docs/crawlers/web/installation.html) from Crawler manual may prove useful.
