### ISSUE TITLE
Processing order checksum headers

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#86]
Looking at the log file a document is processed in following order, 

Processing URL
Fetching document
ReferenceFiltersStage
URLS_EXTRACTED
Headers checksum
REJECTED metadata checkum (unmodified)
REJECTED_UNMODIFIED

Should the headers checksum not be determined  before fetching a document?

**Comment by OkkeKlein** [comment]
Did some digging in code and found that metadataFetcher is being used instead of httpHeadersFetcher as mentioned in the example on http://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/GenericMetadataFetcher.html

When using metadataFetcher the correct order of processing is followed.

**Comment by essiembre** [comment]
Good catch.  Fixed in code.  I will try to update the online javadoc soon.  ``<metadataFetcher ...>`` it is... and I found the document fetcher was also badly documented in the Javadoc.  It should be ``<documentFetcher ...>``.

**Comment by essiembre** [comment]
Online documentation fixed.
