### ISSUE TITLE
utf-8 incoding 

### ISSUE THREAD

**Issue by haditabealhojeh** [Norconex/collector-http#860]
Hi everybody.

I am new to Norconex. I am writing a web crowler that commit the results in elasticsearch as [link](https://github.com/haditabealhojeh/example/blob/main/config). but i am getting non utf-8 characters in the [result](https://github.com/haditabealhojeh/example/blob/main/results). my text is in Persian.

**Comment by ohtwadi** [comment]
Do you see the same behaviour if you use [JSONFileCommitter](https://opensource.norconex.com/committers/core/v3/apidocs/com/norconex/committer/core3/fs/impl/JSONFileCommitter.html) ?

**Comment by ohtwadi** [comment]
Closing as a duplicate of ES Committer issue [44](https://github.com/Norconex/committer-elasticsearch/issues/44)
