### ISSUE TITLE
Empty href's are still matched

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#87]
The regex in HtmlLinkExtractor matches empty href ```<a href="" class="logo" title="homepage">```

**Comment by OkkeKlein** [comment]
Changing regex to ``` "(^|\\s)(" + attribs + ")\\s*=\\s*([\"'])([^\\<\\>]*?)\\3"``` fixes this.

**Comment by essiembre** [comment]
Fix can be found in latest [2.2.0 snapshot release](http://www.norconex.com/collectors/collector-http/download).

**Comment by essiembre** [comment]
Norconex HTTP Collector 2.2.0 official release is out. It includes this fix. You can download it [here](http://www.norconex.com/collectors/collector-http/download).
