### ISSUE TITLE
Restricting ReplaceTransformer

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#89]
The regex in ``` <restrictTo caseSensitive="false"	field="document.reference">.*test.*</restrictTo>``` is never passed to the importerhandler. Only field value.

**Comment by essiembre** [comment]
For which class are you using the ``<restrictTo...>``?  Can you provide the complete XML for that class configuration?

**Comment by essiembre** [comment]
Since this is an issue with the importer module, I moved this issue to the Norconex Importer project: https://github.com/Norconex/importer/issues/7
