### ISSUE TITLE
Expected behaviour crawling a website according to machine resources

### ISSUE THREAD

**Issue by csaezl** [Norconex/collector-http#91]
This issue is related to issue #69. I'm trying to get better crawling performance via decreasing ```delay``` parameter and increasing ```threads``` parameter. Combined with the need of resuming a crawling run, have leaded me to a confusing situation and need some advice related to the expected behaviour of the crawler.

I'm doing crawling testing on a Dell, model PER210II, Intel Xeon E31220@3.10GHz, 8 GB, 64 bits, Windows Server 2008 R2. I set ```delay``` to 50ms and tried several values for ```threads```: 12, 10, 7, 5, 4. For all of them the proccess java.exe for HTTP Collector always reaches 99% of CPU usage after hours of crawling. Only HTTP Collector and Solr, apart from other services, are running.

Since at 99% the performace is very very slow (if not frozen) I had to ```-a stop``` the crawler although not all the times it responded to the request. Resuming with ```-a resume``` seems to work.
What behaviour (or performance) can I expect from the crawler on this type of machine?. At this time I don't see any way of making it work apart from not expecifying the ```threads``` parameter, what is very slow.

There are other situations where the crawling gets frozen without reaching 99% CPU. It's on the DOCUMENT_FETCHED event. With ```-a resume``` the proccess continues in the DOCUMENT_FETCHED with the same document.

Finnally, I have about 3000+ documents on  ```<queueDir>```. What is expected to happen to those documents in the crawling proccess?. Will they be sent to Solr?.

**Comment by OkkeKlein** [comment]
To answer your last question first. Depending on the queueSize setting in committer, the documents are sent to Solr. Default value is 1000, which may be a bit much when testing. Lower it to see if documents are sent to Solr.

As to the other issue, it seems to be content related. You might want to find out what document the thread is stuck on. Add custom logging to collector if needed.

Looking at the linked related issue, you might want to grab the latest snapshot from devel branch from GitHub and try a crawl with MongoDb as linkDB. See if that works better.

**Comment by csaezl** [comment]
As for setting ```threads```, I've increased ```delay``` from 50ms to 100ms and don't get 99% of CPU values anymore. The values are from 1% to 5%. Does it make sense?. Is there a correlation between  ```threads``` and ```delay```.

**Comment by essiembre** [comment]
Yes there is one, but up to a point. You were likely asking you machine to chew on too much at once.  The delay scope you define will also influence, but with the default scope ("crawler"), we can usually make this generic assumption:

At 50 ms, you were asking to potentially download, parse, do whatever other operations, etc, on up to 20 documents **per second**.  That can be quite a bit.  If your number of threads is equals or greater than your number of CPUs (4 cores I think in your case) and they are all busy all the time processing documents, they will be super-busy (99%), which can bring your machine to its knees . Normally, the bigger your documents the more this is true. Crawling tiny HTML pages only vs plenty of large PDFs will make a big difference. The HTTP Collector will use as much CPU has is available if it needs it.

At 100 ms, that's up to 10 documents per seconds, which is likely more reasonable in your case.

With a very aggressive delay, I recommend you specify a number of threads that is one less than your number of cores/CPUs, just so one remains available to your other OS operations and avoid freezes to CPUs being maxed out.  You can also put a CPU quota on your user/process if your OS allows for it.

Files are sometimes cached in memory by the Importer module for faster processing.  A max pool of memory is defined for this.  That pool is shared between threads.  The more threads you have the lesser the amount of memory each threads will use.  At some point, larger files will be swapped to disk to preserve memory.  This can cause extra IO and possibly CPU usage.  When using many threads, you can also try to increase the following values under ``<importer>`` (shown with defaults below):

```xml 
<!-- max memory used for a single file. 10MB by default -->
<maxFileCacheSize>10000000</maxFileCacheSize>
<!-- max memory for the sum of all files.  100MB by default -->
<maxFilePoolCacheSize>100000000</maxFilePoolCacheSize>  
```

You can also look at increasing the Java heap size in the startup script, in case that helps.

**Comment by csaezl** [comment]
Thank you very much

**Comment by pascaldimassimo** [comment]
Please ignore my latest commit. It was linked to the wrong issue.
