### ISSUE TITLE
Adding engine with JavaScript runtime like Selenium or HtmlUnit

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#95]
+1 

Would be a nice feature. Check https://github.com/momer/nutch-selenium for inspiration :)

**Comment by essiembre** [comment]
Since you are "plussing" this, it means you saw this in the application [TODO.txt](https://github.com/Norconex/collector-http/blob/master/norconex-collector-http/TODO.txt) file.  Now that you've exposed it, I am making this a formal feature-request.  :-)

**Comment by bruce-genhot** [comment]
hi @essiembre , is this feature relased ?

**Comment by essiembre** [comment]
It is not implemented but this is not for lack of trying. :-)  I experimented quite a bit with this one already.  The main issue I have is finding a Java-based HTML interpreter (e.g. browser) that supports JavaScript/Ajax properly.

I tried with HtmlUnit and unfortunately, I had too many failures. An alternative would be to use existing java wrappers around popular browsers and grab the generated browser content (like Selenium offers for instance). This has important disadvantages for a generic crawler.  First, relying on an external browser causes portability concerns (support for each browsers may vary and not every organizations support the same browser). Second, using a browser requires a graphical environment (real or virtual) which is not always available/practical.  Last, there are many HTTP Collector configuration settings that impacts how exactly documents are fetched, and HTTP connections handled (e.g. trusting all certificates, socket timeouts, custom handling of redirects, etc.).  Using a browser would completely bypass these options and introduce limitations.

I aslo tried the WebEngine offered by JavaFX, which offers a WebKit implementation, but it does not work headless and does not appear to let developers provide their own document-fetching mechanism (for best integration).

My hope is to see the Java API or find a Java library supporting WebKit headless, or for HTMLUnit to get better Javascript/Ajax support.  

If you know your way around Java pretty well and want to experiment, I think the best place to start is to provide a new implementation of [IHttpDocumentFetcher](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/IHttpDocumentFetcher.html).

Suggestions are welcomed. These are the requirements I'd like to see in whatever solution proposed for a JavaScript/Ajax interpreter: 
 * Java-based
 * Open-source (compatible with Apache License)
 * Portable
 * Headless
 * The way documents are fetched can be customized/overwritten.

**Comment by essiembre** [comment]
Experimental support is now available in the [latest snapshot](https://www.norconex.com/collectors/collector-http/download) for integrating PhantomJS to crawl web pages relying heavily on JavaScript to generate their content.  PhantomJS is a headless browser available to several platforms.  First download [PhantomJS](http://phantomjs.org/) and then use [PhantomJSDocumentFetcher](https://www.norconex.com/collectors/collector-http/latest/apidocs/com/norconex/collector/http/fetch/impl/PhantomJSDocumentFetcher.html).  Refer to that last link for documentation and usage sample.  Feedback is welcome!

**Comment by ebbesson** [comment]
Hi
Great work!
I've tried it out, it runs on Windows, but POSIX systems it PhanomJS complains that it can't open "extras/phantom.js". It appears that the extra quote on the command line argument for the script file makes Phantom interpret it as a string. I experimented by removing the "addQuotes" for that and then got it running on my RedHat environment. I never got around to commit the fix for code to my fork and create pull request, but it was quite minor change.

Also the javadoc for example configuration says points to a _PhatomDocumentFetcher_ an obvious typo :)

**Comment by essiembre** [comment]
I made a fix and tested it on both Windows and Linux and they now both work OK.  The fix is in the latest snapshot release.  I also fixed the javadoc.  Thanks for reporting this!

**Comment by sylvainroussy** [comment]
Hi!
I saw this in `PhantomJSDocumentFetcher` documentation :

```
<scriptPath>
          (Optional path to a PhantomJS script. Defaults to scripts/phantom.js)
</scriptPath>
```

But when starting an execution, the validation failed because of that:
```
if (!new File(scriptPath).isFile()) {
            throw new CollectorException(
                    "PhantomJS script file does not exist or is not a "
                  + "valid file: " + new File(scriptPath).getAbsolutePath());
}
```

What is the `phantom.js` script file ? I've none.

**Comment by essiembre** [comment]
If you are using a recent version, the zip file for the HTTP collector has a "scripts" directory in it.  That directory contains a "phantom.js" file.

**Comment by sylvainroussy** [comment]
Got it! Thanks.
