### ISSUE TITLE
MongoDB is having issues

### ISSUE THREAD

**Issue by OkkeKlein** [Norconex/collector-http#97]
From the Gigs of logs generated by MongoDB:

```Sat Apr 25 12:10:47.702 [conn3] warning: ClientCursor::yield can't unlock b/c of recursive lock ns: assets.references top: { opid: 43, active: true, secs_running: 0, op: "query", ns: "assets", query: { findandmodify: "references", query: { stage: "QUEUED" }, sort: { depth: 1 }, update: { $set: { stage: "ACTIVE" } } }, client: "127.0.0.1:54206", desc: "conn3", threadId: "0x7fd3299d8700", connectionId: 3, locks: { ^: "w", ^assets: "W" }, waitingForLock: false, numYields: 0, lockStats: { timeLockedMicros: {}, timeAcquiringMicros: { r: 0, w: 5556 } } }
Sat Apr 25 12:10:47.702 [conn3] warning: ClientCursor::yield can't unlock b/c of recursive lock ns: assets.references top: { opid: 43, active: true, secs_running: 0, op: "query", ns: "assets", query: { findandmodify: "references", query: { stage: "QUEUED" }, sort: { depth: 1 }, update: { $set: { stage: "ACTIVE" } } }, client: "127.0.0.1:54206", desc: "conn3", threadId: "0x7fd3299d8700", connectionId: 3, locks: { ^: "w", ^assets: "W" }, waitingForLock: false, numYields: 0, lockStats: { timeLockedMicros: {}, timeAcquiringMicros: { r: 0, w: 5556 } } }```

**Comment by OkkeKlein** [comment]
Tue Apr 28 09:52:06.221 [conn3] info DFM::findAll(): extent 0:5000 was empty, skipping ahead. ns:assets.references
Tue Apr 28 09:52:06.247 [conn3] info DFM::findAll(): extent 0:5000 was empty, skipping ahead. ns:assets.references

**Comment by OkkeKlein** [comment]
Apparently the errors from first log come from querying an unindexed field. There is an index called depth_1_crawlState_1, which seems as a concatenation.

**Comment by OkkeKlein** [comment]
To fix this issue you need to create a compounded index with stage as first field and depth as second field. I created the index manually and exceptions were no longer showing up.

**Comment by essiembre** [comment]
Thanks for reporting your findings. We should be able to add that fix.

**Comment by essiembre** [comment]
Re-opening until official release.  Marked as fixed/done until then.

Thanks @OkkeKlein and @pascaldimassimo  for reporting and fixing this!

**Comment by essiembre** [comment]
A new [snapshot release](http://www.norconex.com/collectors/collector-http/download) is available with this fix.

**Comment by OkkeKlein** [comment]
Wrong fix :) 

The stage needs to be indexed in combination with depth, not the crawlState.(unless another query uses it, then stage,depth needs to be added).

**Comment by pascaldimassimo** [comment]
Oups, sorry about that! Got mixed up between state and stage... Thanks for spotting this.

Well commit a new fix soon.

**Comment by pascaldimassimo** [comment]
Here is the fix:
https://github.com/Norconex/collector-core/commit/b952779dcb8402f61cb1f60d4ad7e85b1b9cabbe

Sorry, I've linked it to the wrong issue (#91 instead of #97)

**Comment by essiembre** [comment]
FYI, just made a new snapshot release with this new fix in it.

**Comment by essiembre** [comment]
Norconex HTTP Collector 2.2.0 official release is out. It includes this fix. You can download it [here](http://www.norconex.com/collectors/collector-http/download).
